src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Most_Recent_Billing_Period_End_Date__c</fullName>
        <label>Most Recent Billing Period End Date</label>
        <summarizedField>Invoice__c.Billing_Period_End_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Invoice__c.Type__c</field>
            <operation>equals</operation>
            <value>Actual</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Invoice__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>10K Services Invoice</value>
        </summaryFilterItems>
        <summaryForeignKey>Invoice__c.Account__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <globalPicklist>Assignment_Type</globalPicklist>
        <label>Assignment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Expert</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <recordTypes>
        <fullName>Assignment</fullName>
        <active>true</active>
        <label>Assignment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Require_Stories_on_Time_Entries__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Require Stories on Time Entries</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Story_Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story_Name__c</fullName>
        <label>Story Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Story</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Task_Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story__c</fullName>
        <label>Story</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Task_Name__c</fullName>
        <label>Task Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>Assignment__r.End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Assignment__r.Project__r.Name</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <formula>TEXT(Assignment__r.Role__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <formula>Assignment__r.Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Story</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimecardGridController.cls
public without sharing class TimecardGridController {    
    
    
    @AuraEnabled
    public static Date getToDayDate(){
        date d = System.today();
        return d;//return today date
    }
   
    @AuraEnabled
    public static Date generateWeekStartDate(Date selDate){
          
          Integer numberOfDays ; 
          Date startDate;
          Date weekStart = selDate.toStartofWeek();
          numberOfDays = 0;
          Datetime dt = datetime.newInstance(weekStart.year(), weekStart.month(),weekStart.day());
          
          
          if(dt.format('EEE').tolowercase() == 'sun'){      
              if(selDate == selDate.toStartofWeek()){
                  numberOfDays  = -6;
              }else{     
                  numberOfDays = 1;
              }     
          }else if(dt.format('EEE').tolowercase() == 'sat'){
              if(selDate == selDate.toStartofWeek()){
                  numberOfDays  = -5;
              }else{     
                  numberOfDays = 2;
              }  
              
          }          
          startDate  = weekStart.addDays(numberOfDays);
          return startDate;         
    }
    
    @AuraEnabled
    public static List<Assignment__c> getActiveAssignment(Date selDate) {
        Date startDate = generateWeekStartDate(selDate);
        Date endDate = startDate.addDays(6);
          
        //get current user
        List<User> UserList = new List<User>([SELECT Id, ContactId FROM User WHERE Id = : UserInfo.getUserId() LIMIT 1]);
        
        
        //return all active assignments
        return [SELECT id, Start_Date__c, End_Date__c, Project__c, Project__r.Require_Stories_on_Time_Entries__c, Project__r.Name,  Role__c, Assignment_Type__c, Project__r.Account__r.Most_Recent_Billing_Period_End_Date__c,
                Resource__c, (SELECT id, Assignment__c, Date__c,  Description__c, Hours__c, Story__c, Task__c 
                            FROM Time_Entries__r WHERE Date__c >=: startdate and Date__c <=: enddate)
                FROM Assignment__c WHERE Status__c = 'Active' And Resource__c = :UserList[0].ContactId ORDER BY NAME];
    }
    
    @AuraEnabled
    public static List<AssigAndTimeWrapper> getwrapp (String day, String month, String year) {
        Date selDate = datetime.newInstance(Integer.valueOf(year), Integer.valueOf(month), Integer.valueOf(day)).date();
        //get all active assignment
        

        List<Assignment__c> ActiveAssignmentsList = getActiveAssignment(selDate);        
        
        //lst of current week                                                       
        List<weekWrapper> WeekWrapperList = getCurrentWeek (String.valueOf(selDate.day()), String.valueOf(selDate.month()), String.valueOf(selDate.year())) ;
           
        //temp current week lst
        List<TimeEntryWrapper> tempTimeEntryList ;
        
        //lst wrapper time entry
        List<AssigAndTimeWrapper> wrappTimeList = new List<AssigAndTimeWrapper>();
        
       
        //Boolean
        Boolean isEdit ;
        
        //temp time entry map
        Map<String, List<Time_Entry__c>> tempmap;
        for(Assignment__c ass : ActiveAssignmentsList){            
            tempmap = new Map<String, List<Time_Entry__c>>();
            tempTimeEntryList = new List<TimeEntryWrapper>();

            
            for(Time_Entry__c te:ass.Time_Entries__r){                
                List<Time_Entry__c> relTimeList = new List<Time_Entry__c>();
                String dteString = te.Date__c.format(); 
                if(tempmap.containsKey(dteString))
                    relTimeList.addAll(tempmap.get(dteString));
                
                relTimeList.add(te);                
                tempmap.put(dteString,relTimeList);
            }
            Date toDayDate = selDate;
            //Sunday Date
           // Date weekStart = toDayDate.toStartofWeek();
            
            Date weekStart = generateWeekStartDate(selDate);
            weekStart = weekStart.addDays(-1);
            
            
            
            for(Integer i=1;i<8;i++){
                //isEdit
                if( ass.Project__r.Account__r.Most_Recent_Billing_Period_End_Date__c != null){
                    isEdit = (ass.Project__r.Account__r.Most_Recent_Billing_Period_End_Date__c <  Date.parse(WeekWrapperList[i].Date1) &&  ass.Start_Date__c <= Date.parse(WeekWrapperList[i].Date1) && ass.End_Date__c >= Date.parse(WeekWrapperList[i].Date1));
                }
                else{
                    isEdit = (ass.Start_Date__c <= Date.parse(WeekWrapperList[i].Date1) && ass.End_Date__c >= Date.parse(WeekWrapperList[i].Date1));
                }
                
                Date theDay = Date.parse(WeekWrapperList[i].Date1);
                if(tempmap.containsKey(WeekWrapperList[i].Date1)){
                    
                    tempTimeEntryList.add(new TimeEntryWrapper(tempmap.get(WeekWrapperList[i].Date1),theDay,WeekWrapperList[i].Name,ass.id, isEdit));        
                }
                else{
                    Time_Entry__c  te = new Time_Entry__c(Assignment__c=ass.id,date__c= weekStart.addDays(i));
                    tempTimeEntryList.add(new TimeEntryWrapper(new List<Time_Entry__c>{te},theDay,WeekWrapperList[i].Name,ass.id, isEdit));        
                }
            }
            wrappTimeList.add(new AssigAndTimeWrapper(ass,tempTimeEntryList));
            
        }
            List<AssigAndTimeWrapper> tmpWrapperList = new List<AssigAndTimeWrapper>(wrappTimeList);
            wrappTimeList = filterAssignAndTimeProjectRoleWise(wrappTimeList);
        return wrappTimeList;
    }

    public static List<AssigAndTimeWrapper> filterAssignAndTimeProjectRoleWise(List<AssigAndTimeWrapper> wrappAssignTimeList ){
        List<AssigAndTimeWrapper> tmpWrapperList = new List<AssigAndTimeWrapper>();
        
        Map<String,AssigAndTimeWrapper> tmpWrappermap = new Map<String,AssigAndTimeWrapper>();
        for(AssigAndTimeWrapper wrapper : wrappAssignTimeList) {
            String ckey = wrapper.ass.Project__c + '_' + wrapper.ass.Role__c ;
            List<TimeEntryWrapper> tmp = wrapper.TimeEntryList ;
            if(tmpWrappermap.containsKey(ckey)){
                List<TimeEntryWrapper> timeEntryWrapper = new List<TimeEntryWrapper>();
                List<TimeEntryWrapper> timeEntryList = tmpWrappermap.get(ckey).TimeEntryList ;
                for(Integer i = 0; i < 7; i++){
                    if((timeEntryList[i].isEdit != tmp[i].isEdit) && (tmp[i].isEdit)) { 
                        timeEntryList[i] = tmp[i];
                    }
                    timeEntryWrapper.add(timeEntryList[i]);
                }
                wrapper.TimeEntryList = new List<TimeEntryWrapper>(timeEntryWrapper) ; 
            }
                
            tmpWrappermap.put(ckey,wrapper);        
        }
        for(String s : tmpWrappermap.keySet()) {
            tmpWrapperList.add(tmpWrappermap.get(s));
        }
        return tmpWrapperList ;
    }
    
    @AuraEnabled
    public static List<weekWrapper> getCurrentWeek (String day, String month, String year){
        Date selDate = datetime.newInstance(Integer.valueOf(year), Integer.valueOf(month), Integer.valueOf(day)).date();
        //getting date for monday as starting date
        Date weekStart = generateWeekStartDate(selDate);
        
        List<String> weekDaysList = new List<String>{'Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'};
        LIst<String> monthList = new List<String>{'Jan','Feb','Mar','April','May','June','July','Aug'
                      ,'Sept','Oct','Nov','Dec'};
        List<weekWrapper> WeekWrapperList = new List<weekWrapper>();
        WeekWrapperList.add(new weekWrapper('ACTIVE ASSIGNMENTS','',''));
        
        for(Integer i=0 ; i<7 ; i++){
            String thedate = weekStart.addDays(i).format(); 
            String formatedDate= monthList[ weekStart.addDays(i).month() - 1] +', '+weekStart.addDays(i).day();
            WeekWrapperList.add(new weekWrapper(weekDaysList[i],thedate,formatedDate));            
        }
        return WeekWrapperList;
    }
    @AuraEnabled
    public static List<StoryTaskWrapper> getUserStories(String projectId)
    {
        String currentUserId = UserInfo.getUserId();
        List<StoryWrapper> storyWrapperList = new List<StoryWrapper>();
        List<TaskWrapper> taskWrapperList = new List<TaskWrapper>();
        List<StoryTaskWrapper> storyTaskWrapperList = new List<StoryTaskWrapper>();
        Map<String, List<TaskWrapper>> storyToTaskMap = new Map<String, List<TaskWrapper>>();
        String storyName;
        String taskName;
        List<Story__c> storyList = [SELECT Id, Name, Story_Name__c, 
                                        (SELECT Id, Name, Task_Name__c FROM Tasks__r) 
                                    FROM Story__c 
                                    WHERE Project__c =: projectId 
                                    ORDER BY LastViewedDate DESC];
        for(Story__c storyRec : storyList)
        {
            if((storyRec.Story_Name__c).length() > 40)
            {
                storyName = storyRec.Name+' - '+(storyRec.Story_Name__c).substring(0, 40);
                storyWrapperList.add(new StoryWrapper(storyRec.Id, storyName));
            }
            else
            {
                storyName = storyRec.Name+' - '+storyRec.Story_Name__c;
                storyWrapperList.add(new StoryWrapper(storyRec.Id, storyName));
            }
            taskWrapperList = new List<TaskWrapper>();
            for(Task__c taskRec : storyRec.Tasks__r)
            {
                if((taskRec.Task_Name__c).length() > 40)
                {
                    taskName = taskRec.Name+' - '+(taskRec.Task_Name__c).substring(0, 40);
                    taskWrapperList.add(new TaskWrapper(taskRec.Id, taskName));
                }
                else
                {
                    taskName = taskRec.Name+' - '+taskRec.Task_Name__c;
                    taskWrapperList.add(new TaskWrapper(taskRec.Id, taskName));
                }
            }
            storyToTaskMap.put(storyRec.Id, taskWrapperList);
        }
        storyTaskWrapperList.add(new StoryTaskWrapper(storyWrapperList, storyToTaskMap));
        return storyTaskWrapperList;
    }
    @AuraEnabled
    public static List<TaskWrapper> getStoryTasks(String storyId)
    {
        String selectedStoryId = storyId;
        String taskName;
        List<TaskWrapper> taskWrapperList = new List<TaskWrapper>();
        List<Task__c> taskList = [SELECT Id, Name, Task_Name__c FROM Task__c WHERE Story__c =: selectedStoryId];
        for(Task__c taskRec : taskList)
        {
            if((taskRec.Task_Name__c).length() > 40)
            {
                taskName = taskRec.Name+' - '+(taskRec.Task_Name__c).substring(0, 40);
                taskWrapperList.add(new TaskWrapper(taskRec.Id, taskName));
            }
            else
            {
                taskName = taskRec.Name+' - '+taskRec.Task_Name__c;
                taskWrapperList.add(new TaskWrapper(taskRec.Id, taskName));
            }
        }
        return taskWrapperList;
    }
    //Task Wrapper
    public class TaskWrapper
    {
        @AuraEnabled public String recId {get; set;}
        @AuraEnabled public String recName {get; set;}

        public TaskWrapper(String recId, String recName)
        {
            this.recId = recId;
            this.recName = recName;
        }
    }
    //Stories Wrapper
    public class StoryWrapper
    {
        @AuraEnabled public String recId {get; set;}
        @AuraEnabled public String recName {get; set;}

        public StoryWrapper(String recId, String recName)
        {
            this.recId = recId;
            this.recName = recName;
        }
    }
    //Stories-Task Wrapper
    public class StoryTaskWrapper
    {
        @AuraEnabled public List<StoryWrapper> storyWrapperList {get; set;}
        @AuraEnabled public Map<String, List<TaskWrapper>> storyToTaskMap {get; set;}
        public StoryTaskWrapper(List<StoryWrapper> storyWrapperList, Map<String, List<TaskWrapper>> storyToTaskMap)
        {
            this.storyWrapperList = storyWrapperList;
            this.storyToTaskMap = storyToTaskMap;
        }
    }
    //wrapper current week date and day
    public class weekWrapper {
        @AuraEnabled
        public String Name;
        @AuraEnabled
        public String Date1;
        @AuraEnabled
        public String formatedDate;
        public weekWrapper (String n, String d,String f){
            Name=n;
            Date1=d;
            formatedDate= f;
        }
    }
    //wrapper active assignmet and related time entry
    public class AssigAndTimeWrapper{
        @AuraEnabled
        public Assignment__c ass ;
        @AuraEnabled
        public List<TimeEntryWrapper> TimeEntryList;
        public AssigAndTimeWrapper(Assignment__c a, List<TimeEntryWrapper> l){
            ass = a ;
            TimeEntryList = l ;           
        }
    }
    //wrapper time entry 
    public class TimeEntryWrapper{
        @AuraEnabled
        public List<Time_Entry__c> tymEnry;
        @AuraEnabled
        public Date RelDate;
        @AuraEnabled
        public ID assID;
        @AuraEnabled
        public String dayName ;    
        @AuraEnabled
        public Decimal totOfTimeEnries;
        @AuraEnabled
        public Boolean isEdit ;
        public TimeEntryWrapper(List<Time_Entry__c> t,Date d,String name,ID i,Boolean is){
            isEdit = is;
            tymEnry = t;
            RelDate = d;
            assID = i;
            dayName = name;       
            totOfTimeEnries= 0;
            for(Time_Entry__c tym :tymEnry){
                if(tym.Hours__c != null ){
                    totOfTimeEnries += tym.Hours__c ;
                }
            }
                
        }
    }
    @AuraEnabled 
    public static Time_Entry__c[]  submitSave(Time_Entry__c[]  TimeEntry){    
        List<Time_Entry__c> tymList = new List<Time_Entry__c>();
        for(object sobj :TimeEntry){
            tymList.add((Time_Entry__c)sobj);
        }
        
        upsert tymList ;
        return tymList ;
    }
    
}