src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Code__c</fullName>
        <inlineHelpText>Unique 6 digit code assigned to Customers that is used when generating Invoices</inlineHelpText>
        <label>Billing Code</label>
        <length>6</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <picklist>
            <picklistValues>
                <fullName>Net 15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 30</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Net 45</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <picklist>
            <picklistValues>
                <fullName>Net 15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 45</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate_Structure__c</fullName>
        <label>Rate Structure</label>
        <picklist>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_Through__c</fullName>
        <label>Valid Through</label>
        <type>Date</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Billable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billable Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Expert</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <recordTypes>
        <fullName>Assignment</fullName>
        <active>true</active>
        <label>Assignment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Billing_Code__c</fullName>
        <label>Project Billing Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Agreement</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>PA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <formula>IF(
  ISBLANK(Rate_Specific_Effective_Date__c),
  Agreement__r.Effective_Date__c,
  Rate_Specific_Effective_Date__c
)</formula>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours_Per_Month__c</fullName>
        <label>Hours Per Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours_Per_Week__c</fullName>
        <label>Hours Per Week</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Rate__c</fullName>
        <label>Monthly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_Weeks__c</fullName>
        <label>Number of Weeks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_Through__c</fullName>
        <formula>IF(
  ISBLANK(Rate_Specific_Valid_Through__c),
  Agreement__r.Valid_Through__c,
  Rate_Specific_Valid_Through__c
)</formula>
        <label>Valid Through</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Weekly_Rate__c</fullName>
        <label>Weekly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <formula>Assignment__r.Rate__r.Hourly_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hourly Billable Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Billing_Code__c</fullName>
        <formula>Assignment__r.Project__r.Project_Billing_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Billing Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Assignment__r.Project__r.Name</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <formula>TEXT(Assignment__r.Role__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GenerateInvoicesController_Test.cls
@isTest
private class GenerateInvoicesController_Test {

   @IsTest static void test_method_one() {
        // Implement test code
        
         TestDataFactory factory = new TestDataFactory ();
         List<Account> accList = factory.generateAccounts(1);
         insert accList;
         
         List<agreement__C> agreementList = factory.generateRetainerAgreementsForAccounts(accList, 1);
         agreementList[0].Rate_Structure__c = 'Monthly';
         insert agreementList;
         
         system.debug('AGREEMENT !!!! : ' + agreementList);

         pagereference pg=Page.GenerateInvoices;
         Test.setCurrentPageReference(pg);
         apexpages.currentpage().getparameters().put('agreementId',agreementList[0].id);
        
         GenerateInvoicesController cntrlr =new GenerateInvoicesController();

         accList[0].Billing_Code__c = 'Test-6';
         update accList;
         
         cntrlr =new GenerateInvoicesController();
         
         accList[0].Payment_Terms__c = 'Null';
         update accList;
         
         //generating projects
         List<Project__C> prjList = factory.generateProjects(accList[0].id,1);
         prjList[0].name ='Test Prj';
         insert prjList;
         
         //generating project agreement
         Project_agreement__c prjAgreement = factory.generateProjectAgreements(prjList[0].id,agreementList[0].id);
         insert prjAgreement;
         
         agreementList[0].Payment_Terms__c = 'Net 15';
         update agreementList;
         
         List<Rate__c> ratelist = factory.generateRateForAgreement(agreementList[0].id,Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS,Constants.ROLE_CONSULTANT,1);
         rateList[0].Hours_Per_Month__c = 2;
         insert ratelist;
        
         //generating assignments
         List<Assignment__c> assignmentList = factory.generateAssignment(prjList[0].id,Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS ,1);
         assignmentList[0].Billable__c = true;
         assignmentList[0].Rate__c = rateList[0].Id;
         assignmentList[0].Role__c = Constants.ROLE_CONSULTANT ; 
         insert assignmentList;

         system.debug('ASSIGNMENT !!!! : ' + assignmentList);
         
         List<time_entry__c> timeEntryList = factory.generateTimeEntry(assignmentList[0].id ,'test',system.today(),2,1);
         insert timeEntryList;
        
         cntrlr = new GenerateInvoicesController();
         
         cntrlr.selectedMonth = timeEntryList[0].Date__c.Year() + '-' + timeEntryList[0].Date__c.Month();
         cntrlr.selectedPeriodEndDate = timeEntryList[0].Date__c.Year() + '-' + timeEntryList[0].Date__c.Month() + '-' + timeEntryList[0].Date__c.Day();
         cntrlr.fetchProjects();
         cntrlr.selectedProject = prjList[0].id;
         cntrlr.getProjectOptions();        
         cntrlr.fetchTimeEntryData();
         cntrlr.getMonthOptions();
       
    }
    
    @isTest static void test_method_two() {
        // Implement test code
        
         TestDataFactory factory = new TestDataFactory ();
         List<Account> accList = factory.generateAccounts(1);
         insert accList;
         
         List<Contact> contList = factory.generateContactsForAccounts(accList, 1);
         insert contList;
         
         List<agreement__C> agreementList = factory.generateRetainerAgreementsForAccounts(accList, 1); 
         agreementList[0].Effective_Date__c = Date.newInstance(System.today().Year(), System.today().Month(), 1);
         agreementList[0].Valid_Through__c  = Date.newInstance(System.today().Year(), System.today().Month()+1, 1) - 1;
         agreementList[0].Rate_Structure__c = 'Weekly';
         insert agreementList;
         
         pagereference pg=Page.GenerateInvoices;
         Test.setCurrentPageReference(pg);
         apexpages.currentpage().getparameters().put('agreementId',agreementList[0].id);
        
         GenerateInvoicesController cntrlr = new GenerateInvoicesController();

         accList[0].Billing_Code__c = 'Test-6';
         update accList;
         
         cntrlr =new GenerateInvoicesController();
         
         accList[0].Payment_Terms__c = 'Null';
         update accList;
         
         //generating projects
         List<Project__C> prjList = factory.generateProjects(accList[0].id,1);
         prjList[0].Project_Billing_Code__c ='ABCG12';
         insert prjList;
         
         //generating project agreement
         Project_agreement__c prjAgreement = factory.generateProjectAgreements(prjList[0].id,agreementList[0].id);
         insert prjAgreement ;
         
         agreementList[0].Payment_Terms__c = 'Net 15';
         update agreementList;
         
         List<Rate__c> ratelist = factory.generateRateForAgreement(agreementList[0].id,Constants.ASSIGNMENTTYPE_NAMEDRESOURCE,Constants.ROLE_CONSULTANT,1);
         rateList[0].Hours_Per_Week__c = 40;
         rateList[0].Number_of_Weeks__c = 4;
         rateList[0].Weekly_Rate__c = 1000;
         insert ratelist;

         List<Rate__c> ratelist1 = factory.generateRateForAgreement(agreementList[0].id,Constants.ASSIGNMENTTYPE_NAMEDRESOURCE,Constants.ROLE_CONSULTANT,1);
         rateList1[0].Hours_Per_Week__c = 40;
         rateList1[0].Number_of_Weeks__c = 4;
         rateList1[0].Weekly_Rate__c = 1000;
         insert ratelist1 ;
         List<Rate__c> ratelist2 = factory.generateRateForAgreement(agreementList[0].id,Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS,Constants.ROLE_CONSULTANT,1);
         rateList2[0].Hours_Per_Week__c = 40;
         rateList2[0].Number_of_Weeks__c = 4;
         rateList2[0].Weekly_Rate__c = 1000;
         insert ratelist2 ;
             
         List<Assignment__c> assignmentList = factory.generateAssignment(prjList[0].id,Constants.ASSIGNMENTTYPE_NAMEDRESOURCE,1);
         assignmentList[0].Billable__c = true;
         assignmentList[0].role__c = Constants.ROLE_CONSULTANT ; 
         assignmentList[0].Resource__c = contList[0].id;
         assignmentList[0].Rate__c = rateList[0].Id;
         insert assignmentList ;
         List<Assignment__c> assignmentList1 = factory.generateAssignment(prjList[0].id,Constants.ASSIGNMENTTYPE_NAMEDRESOURCE,1);
         assignmentList1[0].Billable__c = true;
         assignmentList1[0].role__c = Constants.ROLE_CONSULTANT ; 
         assignmentList1[0].Resource__c = contList[0].id;
         assignmentList1[0].Rate__c = rateList2[0].Id;
         insert assignmentList1 ;
         List<Assignment__c> assignmentList2 = factory.generateAssignment(prjList[0].id,Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS,1);
         assignmentList2[0].Billable__c = true;
         assignmentList2[0].role__c = Constants.ROLE_CONSULTANT ; 
         assignmentList2[0].Rate__c = rateList2[0].Id;
         assignmentList2[0].Resource__c = contList[0].id;
         insert assignmentList2 ;
         
         List<time_entry__c> timeEntryList  = factory.generateTimeEntry(assignmentList[0].id ,'test',system.today(),3,1);
         insert timeEntryList ;
        
        
         cntrlr = new GenerateInvoicesController();
         
         //setting selected month value in controller
         cntrlr.selectedMonth = timeEntryList[0].Date__c.Year() + '-' + timeEntryList[0].Date__c.Month();
         cntrlr.selectedPeriodEndDate = timeEntryList[0].Date__c.Year() + '-' + timeEntryList[0].Date__c.Month() + '-' + timeEntryList[0].Date__c.Day();
         cntrlr.fetchProjects();
         //cntrlr.selectedMonth = timeEntryList[0].Date__c.Year() + '-' + timeEntryList[0].Date__c.Month();
         cntrlr.selectedProject = prjList[0].id;
         cntrlr.getProjectOptions();  
         
         cntrlr.fetchTimeEntryData();
         //cntrlr.saveInvoiceAndLineItems();
           
    }
    @isTest static void test_method_three() {
        // Implement test code
        
         TestDataFactory factory = new TestDataFactory ();
         List<Account> accList = factory.generateAccounts(1);
         insert accList;
         
         List<Contact> contList = factory.generateContactsForAccounts(accList, 1);
         insert contList;
         
         List<agreement__C> agreementList = factory.generateRetainerAgreementsForAccounts(accList, 1); 
         agreementList[0].Effective_Date__c = Date.newInstance(System.today().Year(), System.today().Month(), 1);
         agreementList[0].Valid_Through__c  = Date.newInstance(System.today().Year(), System.today().Month()+1, 1) - 1;
         insert agreementList;
         
         pagereference pg=Page.GenerateInvoices;
         Test.setCurrentPageReference(pg);
         apexpages.currentpage().getparameters().put('agreementId',agreementList[0].id);
        
         GenerateInvoicesController cntrlr = new GenerateInvoicesController();

         accList[0].Billing_Code__c = 'Test-6';
         update accList;
         
         cntrlr =new GenerateInvoicesController();
         
         accList[0].Payment_Terms__c = 'Null';
         update accList;
         
         //generating projects
         List<Project__C> prjList = factory.generateProjects(accList[0].id,1);
         prjList[0].Project_Billing_Code__c ='ABCG12';
         insert prjList;
         
         //generating project agreement
         Project_agreement__c prjAgreement = factory.generateProjectAgreements(prjList[0].id,agreementList[0].id);
         insert prjAgreement ;
         
         agreementList[0].Payment_Terms__c = 'Net 15';
         update agreementList;
         
         List<Rate__c> ratelist = factory.generateRateForAgreement(agreementList[0].id,Constants.ASSIGNMENTTYPE_NAMEDRESOURCE,Constants.ROLE_CONSULTANT,1);
         rateList[0].Hours_Per_Month__c = 2;
         rateList[0].Hourly_Rate__c = 4;
         rateList[0].Monthly_Rate__c = 200;
         insert ratelist;

         List<Rate__c> ratelist1 = factory.generateRateForAgreement(agreementList[0].id,Constants.ASSIGNMENTTYPE_RETAINEDCAPACITY,Constants.ROLE_CONSULTANT,1);
         rateList1[0].Hours_Per_Month__c = 2;
         rateList1[0].Hourly_Rate__c = 2;
         rateList1[0].Monthly_Rate__c = 200;
         insert ratelist1;

         List<Rate__c> ratelist2 = factory.generateRateForAgreement(agreementList[0].id,Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS,Constants.ROLE_CONSULTANT,1);
         rateList2[0].Hours_Per_Month__c = 2;
         rateList2[0].Hourly_Rate__c = 2;
         insert ratelist2;
             
         List<Assignment__c> assignmentList = factory.generateAssignment(prjList[0].id,Constants.ASSIGNMENTTYPE_NAMEDRESOURCE,1);
         assignmentList[0].Billable__c = true;
         assignmentList[0].role__c = Constants.ROLE_CONSULTANT ; 
         assignmentList[0].Rate__c = rateList[0].Id; 
         assignmentList[0].Resource__c = contList[0].Id;
         insert assignmentList;
         List<Assignment__c> assignmentList1 = factory.generateAssignment(prjList[0].id,Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS,1);
         assignmentList1[0].Billable__c = true;
         assignmentList1[0].role__c = Constants.ROLE_CONSULTANT;
         assignmentList1[0].Rate__c = rateList2[0].Id;
         assignmentList1[0].Resource__c = contList[0].id;
         insert assignmentList1 ;
         List<Assignment__c> assignmentList2 = factory.generateAssignment(prjList[0].id,Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS,1);
         assignmentList2[0].Billable__c = true;
         assignmentList2[0].role__c = Constants.ROLE_CONSULTANT; 
         assignmentList2[0].Resource__c = contList[0].id;
         assignmentList2[0].Rate__c = rateList2[0].Id;
         insert assignmentList2 ;
         
         List<time_entry__c> timeEntryList  = factory.generateTimeEntry(assignmentList[0].id ,'test',system.today(),3,1);
         insert timeEntryList ;
        
        
         cntrlr = new GenerateInvoicesController();
         
         //setting selected month value in controller
         cntrlr.selectedMonth = timeEntryList[0].Date__c.Year() + '-' + timeEntryList[0].Date__c.Month();
         cntrlr.fetchProjects();
         //cntrlr.selectedMonth = timeEntryList[0].Date__c.Year() + '-' + timeEntryList[0].Date__c.Month();
         cntrlr.selectedProject = prjList[0].id;
         cntrlr.getProjectOptions();  
         
         cntrlr.fetchTimeEntryData();
         //cntrlr.saveInvoiceAndLineItems();
           
    }
    @isTest static void test_method_four() {
        // Implement test code
        
         TestDataFactory factory = new TestDataFactory ();
         List<Account> accList = factory.generateAccounts(1);
         insert accList;
         
         List<Contact> contList = factory.generateContactsForAccounts(accList, 1);
         insert contList;
         
         List<agreement__C> agreementList = factory.generateRetainerAgreementsForAccounts(accList, 1); 
         agreementList[0].Effective_Date__c = Date.newInstance(System.today().Year(), System.today().Month(), 1);
         agreementList[0].Valid_Through__c  = Date.newInstance(System.today().Year(), System.today().Month()+1, 1) - 1;
         insert agreementList;
         
         pagereference pg=Page.GenerateInvoices;
         Test.setCurrentPageReference(pg);
         apexpages.currentpage().getparameters().put('agreementId',agreementList[0].id);
        
         GenerateInvoicesController cntrlr = new GenerateInvoicesController();

         accList[0].Billing_Code__c = 'Test-6';
         update accList;
         
         cntrlr =new GenerateInvoicesController();
         
         accList[0].Payment_Terms__c = 'Null';
         update accList;
         
         //generating projects
         List<Project__C> prjList = factory.generateProjects(accList[0].id,1);
         prjList[0].Project_Billing_Code__c ='ABCG12';
         insert prjList;
         
         //generating project agreement
         Project_agreement__c prjAgreement = factory.generateProjectAgreements(prjList[0].id,agreementList[0].id);
         insert prjAgreement ;
         
         agreementList[0].Payment_Terms__c = 'Net 15';
         update agreementList;
         
         List<Rate__c> ratelist = factory.generateRateForAgreement(agreementList[0].id,Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS,Constants.ROLE_CONSULTANT,1);
         rateList[0].Hours_Per_Month__c = 2;
         rateList[0].Hourly_Rate__c = 2;
         insert ratelist ;
         List<Rate__c> ratelist1 = factory.generateRateForAgreement(agreementList[0].id,Constants.ASSIGNMENTTYPE_NAMEDRESOURCE,Constants.ROLE_CONSULTANT,1);
         rateList1[0].Hours_Per_Month__c = 2;
         rateList1[0].Hourly_Rate__c = 2;
         rateList1[0].Monthly_Rate__c = 200;
         insert ratelist1 ;
         List<Rate__c> ratelist2 = factory.generateRateForAgreement(agreementList[0].id,Constants.ASSIGNMENTTYPE_NAMEDRESOURCE,Constants.ROLE_CONSULTANT,1);
         rateList2[0].Hours_Per_Month__c = 2;
         rateList2[0].Hourly_Rate__c = 2;
         rateList2[0].Monthly_Rate__c = 200;
         insert ratelist2 ;
             
         List<Assignment__c> assignmentList = factory.generateAssignment(prjList[0].id,Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS,1);
         assignmentList[0].Billable__c = true;
         assignmentList[0].role__c = Constants.ROLE_CONSULTANT;
         assignmentList[0].Rate__c = rateList[0].Id;
         assignmentList[0].Resource__c = contList[0].id;
         insert assignmentList ;
         List<Assignment__c> assignmentList1 = factory.generateAssignment(prjList[0].id,Constants.ASSIGNMENTTYPE_NAMEDRESOURCE,1);
         assignmentList1[0].Billable__c = true;
         assignmentList1[0].Rate__c = rateList2[0].Id;
         assignmentList1[0].role__c = Constants.ROLE_CONSULTANT ; 
         assignmentList1[0].Resource__c = contList[0].id;
         insert assignmentList1 ;
         List<Assignment__c> assignmentList2 = factory.generateAssignment(prjList[0].id,Constants.ASSIGNMENTTYPE_NAMEDRESOURCE,1);
         assignmentList2[0].Billable__c = true;
         assignmentList2[0].role__c = Constants.ROLE_CONSULTANT;
         assignmentList2[0].Rate__c = rateList2[0].Id;
         assignmentList2[0].Resource__c = contList[0].id;
         insert assignmentList2 ;
         
         List<time_entry__c> timeEntryList  = factory.generateTimeEntry(assignmentList[0].id ,'test',system.today(),3,1);
         insert timeEntryList;
        
        
         cntrlr = new GenerateInvoicesController();
         
         //setting selected month value in controller
         cntrlr.selectedMonth = timeEntryList[0].Date__c.Year() + '-' + timeEntryList[0].Date__c.Month();
         cntrlr.fetchProjects();
         //cntrlr.selectedMonth = timeEntryList[0].Date__c.Year() + '-' + timeEntryList[0].Date__c.Month();
         cntrlr.selectedProject = prjList[0].id;
         cntrlr.getProjectOptions();  
         
         cntrlr.fetchTimeEntryData();
         //cntrlr.saveInvoiceAndLineItems();
           
    }
    
}