src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DoubleClick_Status__c</fullName>
        <label>DoubleClick Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not A Subscriber</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Current Subscriber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Subscriber</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Services_Status__c</fullName>
        <label>Services Status</label>
        <picklist>
            <picklistValues>
                <fullName>No Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotalOutstandingInvoices0_30DaysOverdue__c</fullName>
        <label>Outstanding Invoices 0-30 Days Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalOutstandingInvoices31_60DaysOverdue__c</fullName>
        <label>Outstanding Invoices 31-60 Days Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalOutstandingInvoices61_90DaysOverdue__c</fullName>
        <label>Outstanding Invoices 61-90 Days Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalOutstandingInvoices_90DaysOverdue__c</fullName>
        <label>Outstanding Invoices &gt;90 Days Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Goodwill_Last_Year__c</fullName>
        <label>Total Goodwill Last Year</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Goodwill_This_Year__c</fullName>
        <label>Total Goodwill This Year</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Invoiced_Previous_Year__c</fullName>
        <label>Total Invoiced Previous Year</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Invoiced_This_Year__c</fullName>
        <label>Total Invoiced This Year</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Paid_Previous_Year__c</fullName>
        <label>Total Paid Previous Year</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Paid_This_Year__c</fullName>
        <label>Total Paid This Year</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Invoiced_Total__c</fullName>
        <label>Annual Invoiced Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Annual_Margin__c</fullName>
        <label>Annual Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Annual_Paid_Total__c</fullName>
        <label>Annual Paid Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billable Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Agreement you selected is not associated with the Account that is selected on this Invoice.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Agreement__c.Account__c</valueField>
            </filterItems>
            <infoMessage>These results have been filtered to show only Agreements for the Account selected on this Invoice.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Period_End_Date__c</fullName>
        <label>Billing Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Period_Start_Date__c</fullName>
        <label>Billing Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Generated_On__c</fullName>
        <label>Billing Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Project you selected is not associated with the Account that is selected on this Invoice.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Project__c.Account__c</valueField>
            </filterItems>
            <infoMessage>These results have been filtered to show only Projects for the Account selected on this Invoice.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Actual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Goodwill_Amount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Goodwill Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Rate__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Assignment__r.Project__r.Name</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountInvoiceRollups_Test.cls
@isTest(SeeAllData = false)
private class AccountInvoiceRollups_Test {
    
    static testMethod void test_usecase_one() {
        
		Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
        List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
    														'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
    														'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
    														null, 'Net 30', 'test@test.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
    														1);
        insert accList;
        
        List<Contact> contactList = TestDataFactory_Contacts.generatecontacts(accList, 'Test contact', 'lastName', '', '', 1);
        insert contactList;
        
        List<Opportunity> oppList = TestDataFactory_Opportunity.generateOpportunities(accList[0].Id,Constants.RECORDTYPEID_OPPORTUNITY_PRODUCT, 'Closed Won', system.today().addDays(2),system.today().addDays(-30),system.today().addDays(-2), 1);
        insert oppList;
        
        List<Account_Plan__c> accountPlanningsList = TestDataFactory_AccountPlannings.generateAccountPlannings('Test', accList[0].Id, String.valueOf(Date.today().year()),1);
        accountPlanningsList.addAll(TestDataFactory_AccountPlannings.generateAccountPlannings('Test2', accList[0].Id, String.valueOf(Date.today().year()),1));
        insert accountPlanningsList;
        
        List<Project__c> projectList = TestDataFactory_Projects.generateProjects(accList[0].Id, 'Test Project', 1);
        insert projectList;
        
        List<Agreement__c> agreementList = TestDataFactory_Agreements.generateAgreements('Test Agreement 1', accList[0].Id, Constants.RECORDTYPEID_AGREEMENT_RETAINER, 'Active', Date.newInstance(System.Today().Year(), System.Today().Month() - 1, 1), Date.newInstance(System.Today().Year() + 1, System.Today().Month() - 1, 1) , 1);
        insert agreementList;
        
        List<Rate__c> rateList = TestDataFactory_Rates.generateRateForAgreement(agreementList[0].id, Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS, Constants.ROLE_CONSULTANT, 100, 1);
        insert rateList;
        List<Assignment__c> assignmentList = TestDataFactory_Assignments.generateAssignments(projectList[0].Id, contactList[0].Id, rateList[0].Id, 'Active', 'Developer', 'Named Resource', true, 250, 1);
        insert assignmentList;
        
        List<Invoice__c> invoiceList = TestDataFactory_Invoices.generateInvoices(accList[0].Id, system.today(),system.today().addDays(-2), system.today(), 2, 1);
        invoiceList.addAll(TestDataFactory_Invoices.generateInvoices(accList[0].Id, system.today().addDays(-32), system.today(), system.today(), 2, 1));
        invoiceList.addAll(TestDataFactory_Invoices.generateInvoices(accList[0].Id, system.today().addDays(-62), system.today(), system.today(), 2, 1));
        invoiceList.addAll(TestDataFactory_Invoices.generateInvoices(accList[0].Id, system.today().addDays(-92), system.today(), system.today(), 2, 1));
        invoiceList[0].Type__c = 'Actual';
        invoiceList[1].Type__c = 'Actual';
        invoiceList[2].Type__c = 'Actual';
        invoiceList[3].Type__c = 'Actual';
        insert invoiceList;
        
        List<Invoice_Line_Item__c> InvoiceLineItemsList = TestDataFactory_InvoiceLineItems.generateInvoiceLineItems(invoiceList[0].Id, Constants.RECORDTYPEID_INVOICE_10KPRODUCTNVOICELINEITEM, null, 2, 30, 1);
        InvoiceLineItemsList.addAll(TestDataFactory_InvoiceLineItems.generateInvoiceLineItems(invoiceList[1].Id, Constants.RECORDTYPEID_INVOICE_10KPRODUCTNVOICELINEITEM, null, 2, 30, 1));
        InvoiceLineItemsList.addAll(TestDataFactory_InvoiceLineItems.generateInvoiceLineItems(invoiceList[2].Id, Constants.RECORDTYPEID_INVOICE_10KPRODUCTNVOICELINEITEM, null, 2, 30, 1));
        InvoiceLineItemsList.addAll(TestDataFactory_InvoiceLineItems.generateInvoiceLineItems(invoiceList[3].Id, Constants.RECORDTYPEID_INVOICE_10KPRODUCTNVOICELINEITEM, null, 2, 30, 1));
        insert InvoiceLineItemsList;
        
        Test.startTest();
            Id idCron = System.schedule('Account Invoice Rollups Scheduler TEST', '0 0 0 * * ?' , new AccountInvoiceRollupsSchedule());
            List<Account_Plan__c> accountPlanResultList = [SELECT Id, Annual_Invoiced_Total__c, Annual_Paid_Total__c, Annual_Margin__c  FROM Account_Plan__c WHERE Id=:accountPlanningsList[0].Id];
            List<Account> accountResultList = [SELECT Id,TotalOutstandingInvoices0_30DaysOverdue__c, TotalOutstandingInvoices31_60DaysOverdue__c, TotalOutstandingInvoices61_90DaysOverdue__c, 
            									TotalOutstandingInvoices_90DaysOverdue__c, Total_paid_previous_year__c, Total_paid_this_year__c,
            									Total_invoiced_this_year__c, Total_invoiced_previous_year__c  FROM Account WHERE Id=:accList[0].Id];
            
            System.assertEquals(28,accountResultList[0].TotalOutstandingInvoices0_30DaysOverdue__c);
            System.assertEquals(28,accountResultList[0].TotalOutstandingInvoices31_60DaysOverdue__c);
            System.assertEquals(28,accountResultList[0].TotalOutstandingInvoices61_90DaysOverdue__c);
            System.assertEquals(28,accountResultList[0].TotalOutstandingInvoices_90DaysOverdue__c);

            System.assertEquals(112, accountResultList[0].Total_invoiced_this_year__c);
            System.assertEquals(0, accountResultList[0].Total_invoiced_previous_year__c);
            
            System.assertEquals(0, accountResultList[0].Total_paid_this_year__c);
            System.assertEquals(0, accountResultList[0].Total_paid_previous_year__c);
            
            System.assertEquals(8, accountPlanResultList[0].Annual_Margin__c);
            System.assertEquals(112, accountPlanResultList[0].Annual_Invoiced_Total__c);
            System.assertEquals(0, accountPlanResultList[0].Annual_Paid_Total__c);
            
            
        Test.stopTest();
    }
    
    static testMethod void test_usecase_two() {
    	
    	Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
        List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
    														'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
    														'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
    														null, 'Net 30', 'test@test.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
    														1);
        insert accList;
        
        List<Contact> contactList = TestDataFactory_Contacts.generatecontacts(accList, 'Test contact', 'lastName', '', '', 1);
        insert contactList;
        
        List<Opportunity> oppList = TestDataFactory_Opportunity.generateOpportunities(accList[0].Id,Constants.RECORDTYPEID_OPPORTUNITY_PRODUCT, 'Closed Won', system.today().addDays(2),system.today().addDays(-30),system.today().addDays(-2), 1);
        insert oppList;
        
        List<Account_Plan__c> accountPlanningsList = TestDataFactory_AccountPlannings.generateAccountPlannings('Test', accList[0].Id, String.valueOf(Date.today().year()),1);
        accountPlanningsList.addAll(TestDataFactory_AccountPlannings.generateAccountPlannings('Test2', accList[0].Id, String.valueOf(Date.today().year())
            ,1));
        insert accountPlanningsList;
        
        List<Project__c> projectList = TestDataFactory_Projects.generateProjects(accList[0].Id, 'Test Project', 1);
        insert projectList;
        
        List<Agreement__c> agreementList = TestDataFactory_Agreements.generateAgreements('Test Agreement 1', accList[0].Id, Constants.RECORDTYPEID_AGREEMENT_RETAINER, 'Active', Date.newInstance(System.Today().Year(), System.Today().Month() - 1, 1), Date.newInstance(System.Today().Year() + 1, System.Today().Month() - 1, 1) , 1);
        insert agreementList;
        
        List<Rate__c> rateList = TestDataFactory_Rates.generateRateForAgreement(agreementList[0].id, Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS, Constants.ROLE_CONSULTANT, 100, 1);
        insert rateList;
        
        List<Assignment__c> assignmentList = TestDataFactory_Assignments.generateAssignments(projectList[0].Id, contactList[0].Id, rateList[0].Id, 'Active', 'Developer', 'Named Resource', true, 250, 1);
        insert assignmentList;
        
        List<Invoice__c> invoiceList = TestDataFactory_Invoices.generateInvoices(accList[0].Id, system.today(),system.today().addDays(-2), system.today(), 2, 1);
        invoiceList.addAll(TestDataFactory_Invoices.generateInvoices(accList[0].Id, system.today().addDays(-32), system.today(), system.today(), 2, 1));
        invoiceList.addAll(TestDataFactory_Invoices.generateInvoices(accList[0].Id, system.today().addDays(-62), system.today(), system.today(), 2, 1));
        invoiceList.addAll(TestDataFactory_Invoices.generateInvoices(accList[0].Id, system.today().addDays(-92), system.today(), system.today(), 2, 1));
        invoiceList[0].Type__c = 'Actual';
        invoiceList[1].Type__c = 'Actual';
        invoiceList[2].Type__c = 'Actual';
        invoiceList[3].Type__c = 'Actual';
        insert invoiceList;
        
        List<Invoice_Line_Item__c> InvoiceLineItemsList = TestDataFactory_InvoiceLineItems.generateInvoiceLineItems(invoiceList[0].Id, Constants.RECORDTYPEID_INVOICE_10KPRODUCTNVOICELINEITEM, null, 2, 30, 1);
        InvoiceLineItemsList.addAll(TestDataFactory_InvoiceLineItems.generateInvoiceLineItems(invoiceList[1].Id, Constants.RECORDTYPEID_INVOICE_10KPRODUCTNVOICELINEITEM, null, 2, 30, 1));
        InvoiceLineItemsList.addAll(TestDataFactory_InvoiceLineItems.generateInvoiceLineItems(invoiceList[2].Id, Constants.RECORDTYPEID_INVOICE_10KPRODUCTNVOICELINEITEM, null, 2, 30, 1));
        InvoiceLineItemsList.addAll(TestDataFactory_InvoiceLineItems.generateInvoiceLineItems(invoiceList[3].Id, Constants.RECORDTYPEID_INVOICE_10KPRODUCTNVOICELINEITEM, null, 2, 30, 1));
        insert InvoiceLineItemsList;
        
        List<Payment__c> paymentList = TestDataFactory_Payments.generatePayments(invoiceList[0].Id, 10, Date.today(), 1);
        paymentList.addAll(TestDataFactory_Payments.generatePayments(invoiceList[1].Id, 20, Date.today(), 1));
        paymentList.addAll(TestDataFactory_Payments.generatePayments(invoiceList[2].Id, 30, Date.today(), 1));
        paymentList.addAll(TestDataFactory_Payments.generatePayments(invoiceList[3].Id, 10, Date.today(), 1));
        insert paymentList;
        
        Test.startTest();
            Id idCron = System.schedule('Account Invoice Rollups Scheduler TEST', '0 0 0 * * ?' , new AccountInvoiceRollupsSchedule());
            List<Account_Plan__c> accountPlanResultList = [SELECT Id, Annual_Invoiced_Total__c, Annual_Paid_Total__c, Annual_Margin__c  FROM Account_Plan__c WHERE Id=:accountPlanningsList[0].Id];
            List<Account> accountResultList = [SELECT Id,TotalOutstandingInvoices0_30DaysOverdue__c, TotalOutstandingInvoices31_60DaysOverdue__c, TotalOutstandingInvoices61_90DaysOverdue__c, 
            									TotalOutstandingInvoices_90DaysOverdue__c, Total_paid_previous_year__c, Total_paid_this_year__c,
            									Total_invoiced_this_year__c, Total_invoiced_previous_year__c  FROM Account WHERE Id=:accList[0].Id];
            
            System.assertEquals(1, accountPlanResultList.size());
            System.assertEquals(1, accountResultList.size());
            
            System.assertEquals(18,accountResultList[0].TotalOutstandingInvoices0_30DaysOverdue__c);
            System.assertEquals(8,accountResultList[0].TotalOutstandingInvoices31_60DaysOverdue__c);
            System.assertEquals(-2,accountResultList[0].TotalOutstandingInvoices61_90DaysOverdue__c);
            System.assertEquals(18,accountResultList[0].TotalOutstandingInvoices_90DaysOverdue__c);
            
            System.assertEquals(112, accountResultList[0].Total_invoiced_this_year__c);
            System.assertEquals(0, accountResultList[0].Total_invoiced_previous_year__c);
            
            System.assertEquals(70, accountResultList[0].Total_paid_this_year__c);
            System.assertEquals(0, accountResultList[0].Total_paid_previous_year__c);
            
            System.assertEquals(8, accountPlanResultList[0].Annual_Margin__c);
            System.assertEquals(112, accountPlanResultList[0].Annual_Invoiced_Total__c);
            System.assertEquals(70, accountPlanResultList[0].Annual_Paid_Total__c);
            
            
        Test.stopTest();
    }
    
    static testMethod void test_usecase_three() {
    	
    	Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
        List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
    														'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
    														'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
    														null, 'Net 30', 'test@test.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
    														1);
        insert accList;
        
        List<Contact> contactList = TestDataFactory_Contacts.generatecontacts(accList, 'Test contact', 'lastName', '', '', 1);
        insert contactList;
        
        List<Opportunity> oppList = TestDataFactory_Opportunity.generateOpportunities(accList[0].Id,Constants.RECORDTYPEID_OPPORTUNITY_PRODUCT, 'Closed Won', system.today().addDays(2),system.today().addDays(-30),system.today().addDays(-2), 1);
        insert oppList;
        
        List<Account_Plan__c> accountPlanningsList = TestDataFactory_AccountPlannings.generateAccountPlannings('Test', accList[0].Id, String.valueOf(Date.today().year()),1);
        accountPlanningsList.addAll(TestDataFactory_AccountPlannings.generateAccountPlannings('Test2', accList[0].Id, String.valueOf(Date.today().year()),1));
        insert accountPlanningsList;
        
        List<Project__c> projectList = TestDataFactory_Projects.generateProjects(accList[0].Id, 'Test Project', 1);
        insert projectList;
        
        List<Agreement__c> agreementList = TestDataFactory_Agreements.generateAgreements('Test Agreement 1', accList[0].Id, Constants.RECORDTYPEID_AGREEMENT_RETAINER, 'Active', Date.newInstance(System.Today().Year(), System.Today().Month() - 1, 1), Date.newInstance(System.Today().Year() + 1, System.Today().Month() - 1, 1) , 1);
        insert agreementList;
        
        List<Rate__c> rateList = TestDataFactory_Rates.generateRateForAgreement(agreementList[0].id, Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS, Constants.ROLE_CONSULTANT, 100, 1);
        insert rateList;
        
        List<Assignment__c> assignmentList = TestDataFactory_Assignments.generateAssignments(projectList[0].Id, contactList[0].Id, rateList[0].Id, 'Active', 'Developer', 'Named Resource', true, 250, 1);
        insert assignmentList;
        
        List<Invoice__c> invoiceList = TestDataFactory_Invoices.generateInvoices(accList[0].Id, system.today(),system.today().addDays(-2), system.today(), 2, 1);
        invoiceList.addAll(TestDataFactory_Invoices.generateInvoices(accList[0].Id, system.today().addDays(-32), system.today(), system.today(), 2, 1));
        invoiceList.addAll(TestDataFactory_Invoices.generateInvoices(accList[0].Id, system.today().addDays(-62), system.today(), system.today(), 2, 1));
        invoiceList.addAll(TestDataFactory_Invoices.generateInvoices(accList[0].Id, system.today().addDays(-92), system.today(), system.today(), 2, 1));
        invoiceList.addAll(TestDataFactory_Invoices.generateInvoices(accList[0].Id, system.today(), system.today().addYears(-1), system.today(), 2, 1));
        invoiceList[0].Type__c = 'Actual';
        invoiceList[1].Type__c = 'Actual';
        invoiceList[2].Type__c = 'Actual';
        invoiceList[3].Type__c = 'Actual';
        invoiceList[4].Type__c = 'Actual';
        insert invoiceList;
        
        List<Invoice_Line_Item__c> InvoiceLineItemsList = TestDataFactory_InvoiceLineItems.generateInvoiceLineItems(invoiceList[0].Id, Constants.RECORDTYPEID_INVOICE_10KPRODUCTNVOICELINEITEM, null, 2, 30, 1);
        InvoiceLineItemsList.addAll(TestDataFactory_InvoiceLineItems.generateInvoiceLineItems(invoiceList[1].Id, Constants.RECORDTYPEID_INVOICE_10KPRODUCTNVOICELINEITEM, null, 2, 30, 1));
        InvoiceLineItemsList.addAll(TestDataFactory_InvoiceLineItems.generateInvoiceLineItems(invoiceList[2].Id, Constants.RECORDTYPEID_INVOICE_10KPRODUCTNVOICELINEITEM, null, 2, 30, 1));
        InvoiceLineItemsList.addAll(TestDataFactory_InvoiceLineItems.generateInvoiceLineItems(invoiceList[3].Id, Constants.RECORDTYPEID_INVOICE_10KPRODUCTNVOICELINEITEM, null, 2, 30, 1));
        InvoiceLineItemsList.addAll(TestDataFactory_InvoiceLineItems.generateInvoiceLineItems(invoiceList[4].Id, Constants.RECORDTYPEID_INVOICE_10KPRODUCTNVOICELINEITEM, null, 3, 20, 1));
        insert InvoiceLineItemsList;
        
        List<Payment__c> paymentList = TestDataFactory_Payments.generatePayments(invoiceList[0].Id, 10, Date.today(), 1);
        paymentList.addAll(TestDataFactory_Payments.generatePayments(invoiceList[1].Id, 20, Date.today(), 1));
        paymentList.addAll(TestDataFactory_Payments.generatePayments(invoiceList[2].Id, 30, Date.today(), 1));
        paymentList.addAll(TestDataFactory_Payments.generatePayments(invoiceList[3].Id, 10, Date.today(), 1));
        insert paymentList;
        
        Test.startTest();
            Id idCron = System.schedule('Account Invoice Rollups Scheduler TEST', '0 0 0 * * ?' , new AccountInvoiceRollupsSchedule());
            List<Account_Plan__c> accountPlanResultList = [SELECT Id, Annual_Invoiced_Total__c, Annual_Paid_Total__c, Annual_Margin__c  FROM Account_Plan__c WHERE Id=:accountPlanningsList[0].Id];
            List<Account> accountResultList = [SELECT Id,TotalOutstandingInvoices0_30DaysOverdue__c, TotalOutstandingInvoices31_60DaysOverdue__c, TotalOutstandingInvoices61_90DaysOverdue__c, 
            									TotalOutstandingInvoices_90DaysOverdue__c, Total_paid_previous_year__c, Total_paid_this_year__c,
            									Total_invoiced_this_year__c, Total_invoiced_previous_year__c  FROM Account WHERE Id=:accList[0].Id];
            System.debug(accountResultList[0]);
            System.debug(accountPlanResultList[0]);
            
            System.assertEquals(1, accountPlanResultList.size());
            System.assertEquals(1, accountResultList.size());
            
            System.assertEquals(35,accountResultList[0].TotalOutstandingInvoices0_30DaysOverdue__c);
            System.assertEquals(8,accountResultList[0].TotalOutstandingInvoices31_60DaysOverdue__c);
            System.assertEquals(-2,accountResultList[0].TotalOutstandingInvoices61_90DaysOverdue__c);
            System.assertEquals(18,accountResultList[0].TotalOutstandingInvoices_90DaysOverdue__c);
            
            System.assertEquals(112, accountResultList[0].Total_invoiced_this_year__c);
            System.assertEquals(17, accountResultList[0].Total_invoiced_previous_year__c);
            
            System.assertEquals(70, accountResultList[0].Total_paid_this_year__c);
            System.assertEquals(0, accountResultList[0].Total_paid_previous_year__c);
            
            System.assertEquals(10, accountPlanResultList[0].Annual_Margin__c);
            System.assertEquals(112, accountPlanResultList[0].Annual_Invoiced_Total__c);
            System.assertEquals(70, accountPlanResultList[0].Annual_Paid_Total__c);
            
            
        Test.stopTest();
    }
    
    static testMethod void test_usecase_four() {
    	
    	Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
        List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
    														'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
    														'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
    														null, 'Net 30', 'test@test.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
    														1);
        insert accList;
        
        List<Contact> contactList = TestDataFactory_Contacts.generatecontacts(accList, 'Test contact', 'lastName', '', '', 1);
        insert contactList;
        
        List<Account_Plan__c> accountPlanningsList = TestDataFactory_AccountPlannings.generateAccountPlannings('Test', accList[0].Id, String.valueOf(Date.today().year()),1);
        accountPlanningsList.addAll(TestDataFactory_AccountPlannings.generateAccountPlannings('Test2', accList[0].Id, String.valueOf(Date.today().year()),1));
        insert accountPlanningsList;
        
        List<Project__c> projectList = TestDataFactory_Projects.generateProjects(accList[0].Id, 'Test Project', 1);
        insert projectList;
        
        List<Agreement__c> agreementList = TestDataFactory_Agreements.generateAgreements('Test Agreement 1', accList[0].Id, Constants.RECORDTYPEID_AGREEMENT_RETAINER, 'Active', Date.newInstance(System.Today().Year(), System.Today().Month() - 1, 1), Date.newInstance(System.Today().Year() + 1, System.Today().Month() - 1, 1) , 1);
        insert agreementList;
        
        List<Rate__c> rateList = TestDataFactory_Rates.generateRateForAgreement(agreementList[0].id, Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS, Constants.ROLE_CONSULTANT, 100, 1);
        insert rateList;
        
        List<Assignment__c> assignmentList = TestDataFactory_Assignments.generateAssignments(projectList[0].Id, contactList[0].Id, rateList[0].Id, 'Active', 'Developer', 'Named Resource', true, 250, 1);
        insert assignmentList;
        
        List<Time_Entry__c> timeEntriesList = TestDataFactory_TimeEntries.generateTimeEntries(assignmentList[0].Id, 'Test', system.today().addMonths(1), 8, 1);
        insert timeEntriesList;
        	
    	Test.startTest();
        	//Id idCron = System.schedule('Account Invoice Rollups Scheduler TEST', '0 0 0 * * ?' , new AccountInvoiceRollupsSchedule());
        	List<Id> lstAccountIds = new List<Id>{accList[0].Id};
        	AccountInvoiceRollupsUtility.updateAccountServiceStatus(lstAccountIds);
            List<Account_Plan__c> accountPlanResultList = [SELECT Id, Annual_Invoiced_Total__c, Annual_Paid_Total__c, Annual_Margin__c  FROM Account_Plan__c WHERE Id=:accountPlanningsList[0].Id];
            List<Account> accountResultList = [SELECT Id,Services_Status__c FROM Account WHERE Id=:accList[0].Id];
            System.debug(accountResultList[0]);
            
            System.assertEquals(1, accountResultList.size());
            System.assertEquals('Prospect',accountResultList[0].Services_Status__c);
        Test.stopTest();
    }
    
	static testMethod void test_usecase_five() {
    	
    	Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
        List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
    														'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
    														'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
    														null, 'Net 30', 'test@test.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
    														1);
        insert accList;
        
        List<Contact> contactList = TestDataFactory_Contacts.generatecontacts(accList, 'Test contact', 'lastName', '', '', 1);
        insert contactList;
        
        List<Account_Plan__c> accountPlanningsList = TestDataFactory_AccountPlannings.generateAccountPlannings('Test', accList[0].Id, String.valueOf(Date.today().year()),1);
        accountPlanningsList.addAll(TestDataFactory_AccountPlannings.generateAccountPlannings('Test2', accList[0].Id, String.valueOf(Date.today().year()),1));
        insert accountPlanningsList;
        
        List<Project__c> projectList = TestDataFactory_Projects.generateProjects(accList[0].Id, 'Test Project', 1);
        insert projectList;
        
        List<Agreement__c> agreementList = TestDataFactory_Agreements.generateAgreements('Test Agreement 1', accList[0].Id, Constants.RECORDTYPEID_AGREEMENT_RETAINER, 'Active', Date.newInstance(System.Today().Year(), System.Today().Month() - 1, 1), Date.newInstance(System.Today().Year() + 1, System.Today().Month() - 1, 1) , 1);
        insert agreementList;
        
        List<Rate__c> rateList = TestDataFactory_Rates.generateRateForAgreement(agreementList[0].id, Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS, Constants.ROLE_CONSULTANT, 100, 1);
        insert rateList;
        
        List<Assignment__c> assignmentList = TestDataFactory_Assignments.generateAssignments(projectList[0].Id, contactList[0].Id, rateList[0].Id, 'Active', 'Developer', 'Named Resource', true, 250, 1);
        insert assignmentList;
        
        List<Time_Entry__c> timeEntriesList = TestDataFactory_TimeEntries.generateTimeEntries(assignmentList[0].Id, 'Test', system.today().addMonths(7), 8, 1);
        insert timeEntriesList;
        	
    	Test.startTest();
        	//Id idCron = System.schedule('Account Invoice Rollups Scheduler TEST', '0 0 0 * * ?' , new AccountInvoiceRollupsSchedule());
        	List<Id> lstAccountIds = new List<Id>{accList[0].Id};
        	AccountInvoiceRollupsUtility.updateAccountServiceStatus(lstAccountIds);
        	
            List<Account_Plan__c> accountPlanResultList = [SELECT Id, Annual_Invoiced_Total__c, Annual_Paid_Total__c, Annual_Margin__c  FROM Account_Plan__c WHERE Id=:accountPlanningsList[0].Id];
            List<Account> accountResultList = [SELECT Id,Services_Status__c FROM Account WHERE Id=:accList[0].Id];
            System.debug(accountResultList[0]);
            
            System.assertEquals(1, accountResultList.size());
            //System.assertEquals('Former',accountResultList[0].Services_Status__c);
        Test.stopTest();
    }
    
    static testMethod void test_usecase_six() {
    	
    	Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
        List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
    														'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
    														'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
    														null, 'Net 30', 'test@test.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
    														1);
        insert accList;
        
        List<Contact> contactList = TestDataFactory_Contacts.generatecontacts(accList, 'Test contact', 'lastName', '', '', 1);
        insert contactList;
        
        List<Account_Plan__c> accountPlanningsList = TestDataFactory_AccountPlannings.generateAccountPlannings('Test', accList[0].Id, String.valueOf(Date.today().year()),1);
        accountPlanningsList.addAll(TestDataFactory_AccountPlannings.generateAccountPlannings('Test2', accList[0].Id, String.valueOf(Date.today().year()),1));
        insert accountPlanningsList;
        
        List<Project__c> projectList = TestDataFactory_Projects.generateProjects(accList[0].Id, 'Test Project', 1);
        insert projectList;
        
        List<Agreement__c> agreementList = TestDataFactory_Agreements.generateAgreements('Test Agreement 1', accList[0].Id, Constants.RECORDTYPEID_AGREEMENT_RETAINER, 'Active', Date.newInstance(System.Today().Year(), System.Today().Month() - 1, 1), Date.newInstance(System.Today().Year() + 1, System.Today().Month() - 1, 1) , 1);
        insert agreementList;
        
        List<Rate__c> rateList = TestDataFactory_Rates.generateRateForAgreement(agreementList[0].id, Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS, Constants.ROLE_CONSULTANT, 100, 1);
        insert rateList;
        
        List<Assignment__c> assignmentList = TestDataFactory_Assignments.generateAssignments(projectList[0].Id, contactList[0].Id, rateList[0].Id, 'Active', 'Developer', 'Named Resource', true, 250, 1);
        insert assignmentList;
        	
    	Test.startTest();
        	//Id idCron = System.schedule('Account Invoice Rollups Scheduler TEST', '0 0 0 * * ?' , new AccountInvoiceRollupsSchedule());
        	List<Id> lstAccountIds = new List<Id>{accList[0].Id};
        	AccountInvoiceRollupsUtility.updateAccountServiceStatus(lstAccountIds);
        	
            List<Account_Plan__c> accountPlanResultList = [SELECT Id, Annual_Invoiced_Total__c, Annual_Paid_Total__c, Annual_Margin__c  FROM Account_Plan__c WHERE Id=:accountPlanningsList[0].Id];
            List<Account> accountResultList = [SELECT Id,Services_Status__c FROM Account WHERE Id=:accList[0].Id];
            System.debug(accountResultList[0]);
			
            System.assertEquals(1, accountResultList.size());
            System.assertEquals('Prospect',accountResultList[0].Services_Status__c);
        Test.stopTest();
    }
    
    static testMethod void test_usecase_seven() {
    	
    	Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
        List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
    														'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
    														'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
    														null, 'Net 30', 'test@test.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
    														1);
        insert accList;
        
        List<Contact> contactList = TestDataFactory_Contacts.generatecontacts(accList, 'Test contact', 'lastName', '', '', 1);
        insert contactList;
        
        List<Opportunity> oppList = TestDataFactory_Opportunity.generateOpportunities(accList[0].Id,Constants.RECORDTYPEID_OPPORTUNITY_PRODUCT, 'Closed Won', system.today().addDays(2),system.today().addDays(-50),system.today().addDays(-20), 1);
        insert oppList;
        
        List<Account_Plan__c> accountPlanningsList = TestDataFactory_AccountPlannings.generateAccountPlannings('Test', accList[0].Id, String.valueOf(Date.today().year()),1);
        accountPlanningsList.addAll(TestDataFactory_AccountPlannings.generateAccountPlannings('Test2', accList[0].Id, String.valueOf(Date.today().year()),1));
        insert accountPlanningsList;
        
        List<Project__c> projectList = TestDataFactory_Projects.generateProjects(accList[0].Id, 'Test Project', 1);
        insert projectList;
        
        List<Agreement__c> agreementList = TestDataFactory_Agreements.generateAgreements('Test Agreement 1', accList[0].Id, Constants.RECORDTYPEID_AGREEMENT_RETAINER, 'Active', Date.newInstance(System.Today().Year(), System.Today().Month() - 1, 1), Date.newInstance(System.Today().Year() + 1, System.Today().Month() - 1, 1) , 1);
        insert agreementList;
        
        List<Rate__c> rateList = TestDataFactory_Rates.generateRateForAgreement(agreementList[0].id, Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS, Constants.ROLE_CONSULTANT, 100, 1);
        insert rateList;
        
        List<Assignment__c> assignmentList = TestDataFactory_Assignments.generateAssignments(projectList[0].Id, contactList[0].Id, rateList[0].Id, 'Active', 'Developer', 'Named Resource', true, 250, 1);
        insert assignmentList;
        
        List<Time_Entry__c> timeEntriesList = TestDataFactory_TimeEntries.generateTimeEntries(assignmentList[0].Id, 'Test', system.today().addMonths(1), 8, 1);
        insert timeEntriesList;
        	
    	Test.startTest();
        	//Id idCron = System.schedule('Account Invoice Rollups Scheduler TEST', '0 0 0 * * ?' , new AccountInvoiceRollupsSchedule());
        	List<Id> lstAccountIds = new List<Id>{accList[0].Id};
        	AccountInvoiceRollupsUtility.updateAccountServiceStatus(lstAccountIds);
        	
            List<Account> accountResultList = [SELECT Id, DoubleClick_Status__c, Services_Status__c FROM Account WHERE Id=:accList[0].Id];
            System.debug(accountResultList[0]);
            
            System.assertEquals(1, accountResultList.size());
            //System.assertEquals('Current Subscriber',accountResultList[0].DoubleClick_Status__c);
        Test.stopTest();
    }
    
    static testMethod void test_usecase_eight() {
    	
    	Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
        List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
    														'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
    														'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
    														null, 'Net 30', 'test@test.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
    														1);
        insert accList;
        
        List<Contact> contactList = TestDataFactory_Contacts.generatecontacts(accList, 'Test contact', 'lastName', '', '', 1);
        insert contactList;
        
        List<Opportunity> oppList = TestDataFactory_Opportunity.generateOpportunities(accList[0].Id,Constants.RECORDTYPEID_OPPORTUNITY_PRODUCT, 'Closed Won', system.today().addDays(2),system.today().addDays(-150),system.today().addDays(-130), 1);
        insert oppList;
        
        List<Account_Plan__c> accountPlanningsList = TestDataFactory_AccountPlannings.generateAccountPlannings('Test', accList[0].Id, String.valueOf(Date.today().year()),1);
        accountPlanningsList.addAll(TestDataFactory_AccountPlannings.generateAccountPlannings('Test2', accList[0].Id, String.valueOf(Date.today().year()),1));
        insert accountPlanningsList;
        
        List<Project__c> projectList = TestDataFactory_Projects.generateProjects(accList[0].Id, 'Test Project', 1);
        insert projectList;
        
        List<Agreement__c> agreementList = TestDataFactory_Agreements.generateAgreements('Test Agreement 1', accList[0].Id, Constants.RECORDTYPEID_AGREEMENT_RETAINER, 'Active', Date.newInstance(System.Today().Year(), System.Today().Month() - 1, 1), Date.newInstance(System.Today().Year() + 1, System.Today().Month() - 1, 1) , 1);
        insert agreementList;
        
        List<Rate__c> rateList = TestDataFactory_Rates.generateRateForAgreement(agreementList[0].id, Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS, Constants.ROLE_CONSULTANT, 100, 1);
        insert rateList;
        
        List<Assignment__c> assignmentList = TestDataFactory_Assignments.generateAssignments(projectList[0].Id, contactList[0].Id, rateList[0].Id, 'Active', 'Developer', 'Named Resource', true, 250, 1);
        insert assignmentList;
        
        List<Time_Entry__c> timeEntriesList = TestDataFactory_TimeEntries.generateTimeEntries(assignmentList[0].Id, 'Test', system.today().addMonths(1), 8, 1);
        insert timeEntriesList;
        	
    	Test.startTest();
        	//Id idCron = System.schedule('Account Invoice Rollups Scheduler TEST', '0 0 0 * * ?' , new AccountInvoiceRollupsSchedule());
        	List<Id> lstAccountIds = new List<Id>{accList[0].Id};
        	AccountInvoiceRollupsUtility.updateAccountServiceStatus(lstAccountIds);
        	
            List<Account> accountResultList = [SELECT Id, DoubleClick_Status__c, Services_Status__c FROM Account WHERE Id=:accList[0].Id];
            System.debug(accountResultList[0]);
            
            System.assertEquals(1, accountResultList.size());
            //System.assertEquals('Former Subscriber',accountResultList[0].DoubleClick_Status__c);
        Test.stopTest();
    }
    
    static testMethod void test_usecase_nine() {
    	
    	Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
        List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
    														'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
    														'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
    														null, 'Net 30', 'test@test.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
    														1);
        insert accList;
        
        List<Contact> contactList = TestDataFactory_Contacts.generatecontacts(accList, 'Test contact', 'lastName', '', '', 1);
        insert contactList;
        
        List<Account_Plan__c> accountPlanningsList = TestDataFactory_AccountPlannings.generateAccountPlannings('Test', accList[0].Id, String.valueOf(Date.today().year()),1);
        accountPlanningsList.addAll(TestDataFactory_AccountPlannings.generateAccountPlannings('Test2', accList[0].Id, String.valueOf(Date.today().year()),1));
        insert accountPlanningsList;
        
        List<Project__c> projectList = TestDataFactory_Projects.generateProjects(accList[0].Id, 'Test Project', 1);
        insert projectList;
        
        List<Agreement__c> agreementList = TestDataFactory_Agreements.generateAgreements('Test Agreement 1', accList[0].Id, Constants.RECORDTYPEID_AGREEMENT_RETAINER, 'Active', Date.newInstance(System.Today().Year(), System.Today().Month() - 1, 1), Date.newInstance(System.Today().Year() + 1, System.Today().Month() - 1, 1) , 1);
        insert agreementList;
        
        List<Rate__c> rateList = TestDataFactory_Rates.generateRateForAgreement(agreementList[0].id, Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS, Constants.ROLE_CONSULTANT, 100, 1);
        insert rateList;
        
        List<Assignment__c> assignmentList = TestDataFactory_Assignments.generateAssignments(projectList[0].Id, contactList[0].Id, rateList[0].Id, 'Active', 'Developer', 'Named Resource', true, 250, 1);
        insert assignmentList;
        	
    	Test.startTest();
        	//Id idCron = System.schedule('Account Invoice Rollups Scheduler TEST', '0 0 0 * * ?' , new AccountInvoiceRollupsSchedule());
        	List<Id> lstAccountIds = new List<Id>{accList[0].Id};
        	AccountInvoiceRollupsUtility.updateAccountServiceStatus(lstAccountIds);
        	
            List<Account> accountResultList = [SELECT Id, DoubleClick_Status__c, Services_Status__c FROM Account WHERE Id=:accList[0].Id];
            System.debug(accountResultList[0]);
            
            System.assertEquals(1, accountResultList.size());
            System.assertEquals('Not A Subscriber',accountResultList[0].DoubleClick_Status__c);
        Test.stopTest();
    }


    static testMethod void test_usecase_ten() {
        
        
        Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
        List<Account> accList    = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test Account', 'Prospect', 15, 
                                                                                'code coverage', 'internal', 'App Cloud;Sales Cloud', 'Enterprise', 
                                                                                'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
                                                                                'code quality with code coverage above 75%', 'NDA aggrement', 'United States', 
                                                                                '501 test street', 'test city', 'Florida', '90001', null, null, 'Net 30', 
                                                                                'acc@testemail.com', 'TestA', 'HELLO WORLD', 'invoicingNotes', 
                                                                                'Partner Client', 1);
        insert accList;
        
        List<Contact> contactList = TestDataFactory_Contacts.generatecontacts(accList, 'Test contact', 'lastName', '', '', 1);
        insert contactList;
        
        List<Opportunity> oppList = TestDataFactory_Opportunity.generateOpportunities(accList[0].Id,Constants.RECORDTYPEID_OPPORTUNITY_PRODUCT, 'Closed Won', system.today().addDays(2),system.today().addDays(-30),system.today().addDays(-2), 1);
        insert oppList;
        
        List<Account_Plan__c> accountPlanningsList = TestDataFactory_AccountPlannings.generateAccountPlannings('Test', accList[0].Id, String.valueOf(Date.today().year()),1);
        accountPlanningsList.addAll(TestDataFactory_AccountPlannings.generateAccountPlannings('Test2', accList[0].Id, String.valueOf(Date.today().year()),1));
        insert accountPlanningsList;
        
        List<Project__c> projectList = TestDataFactory_Projects.generateProjects(accList[0].Id, 'Test Project', 1);
        insert projectList;
        
        List<Agreement__c> agreementList = TestDataFactory_Agreements.generateAgreements('Test Agreement 1', accList[0].Id, Constants.RECORDTYPEID_AGREEMENT_RETAINER, 'Active', Date.newInstance(System.Today().Year(), System.Today().Month() - 1, 1), Date.newInstance(System.Today().Year() + 1, System.Today().Month() - 1, 1) , 1);
        insert agreementList;
        
        List<Rate__c> rateList = TestDataFactory_Rates.generateRateForAgreement(agreementList[0].id, Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS, Constants.ROLE_CONSULTANT, 100, 1);
        insert rateList;
        List<Assignment__c> assignmentList = TestDataFactory_Assignments.generateAssignments(projectList[0].Id, contactList[0].Id, rateList[0].Id, 'Active', 'Developer', 'Named Resource', true, 250, 1);
        insert assignmentList;
        

        List<Invoice__c> invoiceList =TestDataFactory_Invoices.generateInvoices(accList[0].id, Date.today(), Date.today().addDays(2), Date.today().addDays(6), 1.2, 2);
        invoiceList[0].Due_Date__c = Date.today().addDays(-99);
        invoiceList[1].Due_Date__c = Date.today().addDays(-2);
        invoiceList[0].Billing_Period_Start_Date__c = Date.today().addDays(-20);
        invoiceList[0].Billing_Period_End_Date__c = Date.today().addDays(-10);
        invoiceList[1].Billing_Period_Start_Date__c = Date.today().addDays(-100);
        invoiceList[1].Billing_Period_End_Date__c = Date.today().addDays(-110);
        invoiceList[1].Invoice_Generated_On__c = Date.today().addDays(-80);
        invoiceList[0].RecordTypeId = Constants.RECORDTYPEID_INVOICE_10KSERVICESINVOICE;
        invoiceList[1].RecordTypeId = Constants.RECORDTYPEID_INVOICE_10KSERVICESINVOICE;
        invoiceList[0].Type__c = 'Actual';
        invoiceList[1].Type__c = 'Actual';
        insert invoiceList;
        
        List<Invoice_Line_Item__c> invoiceLineItemList = TestDataFactory_InvoiceLineItems.generateInvoiceLineItems(invoiceList[0].Id, 
                                                                                                                   Constants.RECORDTYPEID_INVOICE_10KSERVICESINVOICELINEITEM, 
                                                                                                                   rateList[0].Id, 10, 1000, 2);
        
        invoiceLineItemList[1].invoice__c = invoiceList[1].Id;
        invoiceLineItemList[0].Hours__c = 5;
        invoiceLineItemList[0].Goodwill_Amount__c = 5;
        invoiceLineItemList[1].Goodwill_Amount__c = 10;
        invoiceLineItemList[1].Hours__c = 10;
        insert invoiceLineItemList;
        
        Test.startTest();
            Id idCron = System.schedule('Account Invoice Rollups Scheduler TEST', '0 0 0 * * ?' , new AccountInvoiceRollupsSchedule());
            List<Account_Plan__c> accountPlanResultList = [SELECT Id, Annual_Invoiced_Total__c, Annual_Paid_Total__c, Annual_Margin__c  FROM Account_Plan__c WHERE Id=:accountPlanningsList[0].Id];
            List<Account> accountResultList = [SELECT Id,Total_Goodwill_Last_Year__c,Total_Goodwill_This_Year__c,TotalOutstandingInvoices0_30DaysOverdue__c, TotalOutstandingInvoices31_60DaysOverdue__c, TotalOutstandingInvoices61_90DaysOverdue__c, 
                                                TotalOutstandingInvoices_90DaysOverdue__c, Total_paid_previous_year__c, Total_paid_this_year__c,
                                                Total_invoiced_this_year__c, Total_invoiced_previous_year__c  FROM Account WHERE Id=:accList[0].Id];
            
            System.assertEquals(5,accountResultList[0].Total_Goodwill_This_Year__c);
            System.assertEquals(10,accountResultList[0].Total_Goodwill_Last_Year__c);
        Test.stopTest();
    }
}