src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Code__c</fullName>
        <inlineHelpText>Unique 6 digit code assigned to Customers that is used when generating Invoices</inlineHelpText>
        <label>Billing Code</label>
        <length>6</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Most_Recent_Billing_Period_End_Date__c</fullName>
        <label>Most Recent Billing Period End Date</label>
        <summarizedField>Invoice__c.Billing_Period_End_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Invoice__c.Type__c</field>
            <operation>equals</operation>
            <value>Actual</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Invoice__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>10K Services Invoice</value>
        </summaryFilterItems>
        <summaryForeignKey>Invoice__c.Account__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <picklist>
            <picklistValues>
                <fullName>Net 15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 30</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Net 45</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <picklist>
            <picklistValues>
                <fullName>Net 15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 45</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate_Structure__c</fullName>
        <label>Rate Structure</label>
        <picklist>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Retainer_Overage_Behavior__c</fullName>
        <label>Retainer Overage Behavior</label>
        <picklist>
            <picklistValues>
                <fullName>No Extra Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time &amp; Materials</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_Through__c</fullName>
        <label>Valid Through</label>
        <type>Date</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <globalPicklist>Assignment_Type</globalPicklist>
        <label>Assignment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billable Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Agreement you selected is not associated with the Account that is selected on this Invoice.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Agreement__c.Account__c</valueField>
            </filterItems>
            <infoMessage>These results have been filtered to show only Agreements for the Account selected on this Invoice.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Period_End_Date__c</fullName>
        <label>Billing Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Project you selected is not associated with the Account that is selected on this Invoice.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Project__c.Account__c</valueField>
            </filterItems>
            <infoMessage>These results have been filtered to show only Projects for the Account selected on this Invoice.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Actual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Internal?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoiced_Separately__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoiced Separately</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Billing_Code__c</fullName>
        <label>Project Billing Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Agreement</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>PA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <globalPicklist>Assignment_Type</globalPicklist>
        <label>Assignment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <formula>IF(
  ISBLANK(Rate_Specific_Effective_Date__c),
  Agreement__r.Effective_Date__c,
  Rate_Specific_Effective_Date__c
)</formula>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Monthly_Rate__c</fullName>
        <label>Monthly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_Months__c</fullName>
        <label>Number of Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_Through__c</fullName>
        <formula>IF(
  ISBLANK(Rate_Specific_Valid_Through__c),
  Agreement__r.Valid_Through__c,
  Rate_Specific_Valid_Through__c
)</formula>
        <label>Valid Through</label>
        <type>Date</type>
    </fields>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Project_Billing_Code__c</fullName>
        <formula>Assignment__r.Project__r.Project_Billing_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Billing Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Assignment__r.Project__r.Name</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GenerateProjectInvoicesBatch.cls
global class GenerateProjectInvoicesBatch implements Database.Batchable<sObject> {
    
    public Boolean lastMonth = false;

    String query = 'SELECT Id FROM Project__c WHERE Invoiced_Separately__c = true AND Internal__c = false';

    global GenerateProjectInvoicesBatch() {
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Project__c> startingProjectList) {
        
        Set<Id> projectScopeIdSet = new Set<Id>();
        for(Project__c project : startingProjectList) {
            projectScopeIdSet.add(project.Id);
        }

        List<Project__c> scope = new List<Project__c>();
        for(Project__c project : [SELECT Id, Name, Account__c, Project_Billing_Code__c,
                                         (SELECT Id, Agreement__c, Project__c
                                          FROM Project_Agreements__r
                                          WHERE Agreement__r.RecordTypeId !=: Constants.RECORDTYPEID_AGREEMENT_DELIVERYPARTER)
                                  FROM Project__c 
                                  WHERE Id IN: projectScopeIdSet]) {
            scope.add(project);
        }

        if(scope.size() == 1 && scope[0].Project_Agreements__r.size() > 0){
            Set<Id> childAgreementIdSet = new Set<Id>();
            for(Project_Agreement__c projectAgreement:(List<Project_Agreement__c>) scope[0].Project_Agreements__r){
                childAgreementIdSet.add(projectAgreement.Agreement__c);
            }
            List<String> resultList = new List<String>();
            String selectedDateTimeDisplay;
            Integer numberOfWeeks;
            Date periodStartDate;
            Date periodEndDate;
            Date invoiceGeneratedOn;
            //Date dueDate;
            List<Invoice_Line_Item__c> invoiceLineItemList      = new List<Invoice_Line_Item__c>();
            List<Time_Entry__c> timeEntryList                   = new List<Time_Entry__c>();
            for(Agreement__c agreement : [SELECT Id, Name, Account__c, Account__r.Name, RecordTypeId, Payment_Terms__c, Rate_Structure__c,
                                            Account__r.Billing_Code__c, Effective_Date__c, Valid_Through__c, Retainer_Overage_Behavior__c,
                                            Account__r.Most_Recent_Billing_Period_End_Date__c,
                                            (SELECT Id, Agreement__c, Assignment_Type__c, Monthly_Rate__c, Number_of_Months__c, Role__c, Region__c, 
                                                Hourly_Rate__c, Hours_Per_Month__c, Number_of_Weeks__c, Hours_Per_Week__c, Weekly_Rate__c 
                                            FROM Rates__r)
                                        FROM Agreement__c WHERE Id IN: childAgreementIdSet AND RecordTypeId !=: Constants.RECORDTYPEID_AGREEMENT_DELIVERYPARTER ]){
                Boolean chargeForOverages;
                Id selectedAgreementId;
                Boolean isMonthly                                   = false;
                Map<String, Rate__c> agreementRateMap               = new Map<String, Rate__c>();
                Set<Id> projectIdSet                                = new Set<Id>();
                
                List<Assignment__c> assignmentsWithoutValidRates    = new List<Assignment__c>();
                String selectedProject                              = 'All';
                Boolean validRecordType                             = true;
                String mapKey                                       = '';
                String recordTypeId                                 = Constants.RECORDTYPEID_AGREEMENT_RETAINER;
                //Agreement__c agreement                                = agreementList[0];

                selectedAgreementId = agreement.Id;
                chargeForOverages = (agreement.Retainer_Overage_Behavior__c == 'No Extra Charge') ? false : true;
                if(agreement.Account__r.Billing_Code__c == null || agreement.Account__r.Billing_Code__c == '') {
                    validRecordType = false;
                }
                if(agreement.Payment_Terms__c == null || agreement.Payment_Terms__c == '') {
                    validRecordType = false;
                }
                if(agreement.Rate_Structure__c == 'Monthly') {
                    isMonthly = true;
                }
                if(validRecordType) {
                        projectIdSet.add(scope[0].Id);
            
                    //Build up a map of all the Rates that are tied to this Agreement, keyed with AssignmentType+Role+RecordId
                    //@TODO - Will need to update this for date-bound Capacity records
                    for(Rate__c rate : agreement.Rates__r) {
                        mapKey = rate.Assignment_Type__c + '@' + rate.Region__c + '@' + rate.Role__c;
                        if(rate.Assignment_Type__c == Constants.ASSIGNMENTTYPE_NAMEDRESOURCE) {
                            mapKey += '@' + rate.Id;
                        }

                        agreementRateMap.put(mapKey, rate);
                    }

                    if((agreement.Rate_Structure__c == 'Monthly' && agreement.RecordTypeId == recordTypeId) || agreement.RecordTypeId != recordTypeId) {
                        Date currentDate    = lastMonth ? Date.today().addMonths(-1) : Date.today();
                        periodStartDate     = Date.newInstance(currentDate.year(), currentDate.month(), 1);
                        periodEndDate       = Date.newInstance(currentDate.year(), currentDate.month()+1, 1)-1;

                        invoiceGeneratedOn = lastMonth ? Date.newInstance(Date.today().year(), Date.today().month(), 1) : Date.newInstance(Date.today().year(), Date.today().month() + 1, 1);

                        Datetime selectedDateTime   = Datetime.newInstance(currentDate.year(), currentDate.month(), 1);
                        selectedDateTimeDisplay     = selectedDateTime.format('MMyyyy');
                    }
                    else if(agreement.Rate_Structure__c == 'Weekly' && agreement.RecordTypeId == recordTypeId){
                        Date currentDate    = lastMonth ? agreement.Account__r.Most_Recent_Billing_Period_End_Date__c.addDays(-27) : agreement.Account__r.Most_Recent_Billing_Period_End_Date__c.addDays(1);
                        periodStartDate     = currentDate;
                        periodEndDate       = currentDate.addDays(27);

                        invoiceGeneratedOn = Date.newInstance(periodEndDate.year(), periodEndDate.month(), 1);

                        Datetime selectedDateTime   = Datetime.newInstance(periodStartDate.year(),periodStartDate.month(),periodStartDate.day());
                        selectedDateTimeDisplay     = selectedDateTime.format('MMddyyyy');

                        numberOfWeeks = (periodStartDate.daysBetween(periodEndDate) / 7) + 1;
                    }

                    Set<Id> agreementIdSet = new Set<Id>{selectedAgreementId};

                    String result = InvoiceCreationUtility.generateServicesInvoice( chargeForOverages, 
                                                                                    isMonthly, 
                                                                                    agreementRateMap, 
                                                                                    numberOfWeeks,  
                                                                                    invoiceLineItemList,
                                                                                    periodStartDate,
                                                                                    periodEndDate,
                                                                                    projectIdSet,
                                                                                    agreementIdSet,
                                                                                    timeEntryList,
                                                                                    assignmentsWithoutValidRates,
                                                                                    selectedProject,
                                                                                    false);
                    if(invoiceLineItemList.size() > 0 && result != null )
                    {
                        resultList.add(result);
                    }
                }

                //dueDate = invoiceGeneratedOn.addDays(Integer.valueOf(agreement.Payment_Terms__c.split(' ')[1]));
            }
            if(invoiceLineItemList.size() > 0)
            {
                //Initialize the Invoice header
                Invoice__c invoice                      = new Invoice__c();
                invoice.RecordTypeId                    = Constants.RECORDTYPEID_INVOICE_10KSERVICESINVOICE;
                invoice.Name                            = '10K-';
                invoice.Name                            += scope[0].Project_Billing_Code__c + '-';
                invoice.Name                            += selectedDateTimeDisplay;
                invoice.Account__c                      = scope[0].Account__c;
                invoice.Project__c                      =  scope[0].Id;
                if(scope[0].Project_Agreements__r.size() == 1)
                    invoice.Agreement__c                = scope[0].Project_Agreements__r[0].Agreement__c;
                invoice.Billing_Period_Start_Date__c    = periodStartDate;
                invoice.Billing_Period_End_Date__c      = periodEndDate;
                invoice.Type__c                         = 'Draft';
                invoice.Invoice_Generated_On__c         = invoiceGeneratedOn;
                //invoice.Due_Date__c                     = dueDate;

                //Set the names of all Resources who billed hours for this Invoice into the Expert_Names__c field on the Invoice
                Decimal invoiceAmount = 0.0;
                for(String result : resultList){
                    if(invoice.Expert_Names__c == null){
                        if(result.split('@').size() > 1)
                            invoice.Expert_Names__c = result.split('@')[1].split('##')[0] ;
                    }
                    else {
                        if(result.split('@').size() > 1){
                            for(String expertName : result.split('@')[1].split('##')[0].split(', ')){
                                
                                if(!invoice.Expert_Names__c.contains(expertName))
                                    invoice.Expert_Names__c += ', ' + expertName;
                            }
                        }
                    } 
                    try{
                        invoiceAmount += Decimal.valueOf(result.split('##')[1]);
                    }
                    catch(Exception ex){
                        //invoiceAmount = 0.0;
                    }
                }
                    
                List<Invoice__c> invoiceList = [SELECT Id , Name FROM Invoice__c WHERE Name =: invoice.Name AND Type__c = 'Draft' LIMIT 1];
                if(invoiceList.size() > 0 ){
                    invoice.Id = invoiceList[0].Id;
                }
                if(lastMonth && invoiceList.size() > 0){
                    PageReference newInvoice = InvoiceCreationUtility.saveInvoiceAndLineItems(invoice,invoiceLineItemList,timeEntryList,false);
                }
                else if (!lastMonth) {
                    PageReference newInvoice = InvoiceCreationUtility.saveInvoiceAndLineItems(invoice,invoiceLineItemList,timeEntryList,false);
                }
            }
            
            
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
        //Automatically start the next job in the series of Invoicing jobs
        GenerateInvoicesBatch invoiceBatch = new GenerateInvoicesBatch();

        //If this job was run with lastMonth = TRUE, the next step is to run the regular Invoice Batch for the prior month
        if(lastMonth) {
            invoiceBatch.lastMonth = true;
            ChainedBatchId__c batchIds = ChainedBatchId__c.getOrgDefaults();
            if(!Test.isRunningTest())
                batchIds.SecondBatch_Id__c = Database.executeBatch(invoiceBatch, 1);
            upsert batchIds;
        }
        //If however the job was run for the current month, there next steps is to run the regular Invoice Batch for the current month
        else {
            invoiceBatch.lastMonth = false;
            ChainedBatchId__c batchIds = ChainedBatchId__c.getOrgDefaults();
            if(!Test.isRunningTest())
                batchIds.FifthBatch_Id__c = Database.executeBatch(invoiceBatch, 1);
            upsert batchIds;
        }
    }
}