src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>25</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Account_Record_Type__c</fullName>
        <label>Account Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Additional_Invoice_Recipients__c</fullName>
        <label>Additional Invoice Recipients</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Appirio_DSM_Expiration_Date__c</fullName>
        <label>Appirio DSM Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Appirio_DSM_Status__c</fullName>
        <label>Appirio DSM Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Support / Free User</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Code__c</fullName>
        <inlineHelpText>Unique 6 digit code assigned to Customers that is used when generating Invoices</inlineHelpText>
        <label>Billing Code</label>
        <length>6</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Current_Use_of_3rd_Party_SFDC_Resources__c</fullName>
        <label>Current Use of 3rd-Party SFDC Resources</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Custom_Invoice_Email_Template__c</fullName>
        <label>Custom Invoice Email Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Standards__c</fullName>
        <label>Delivery Standards</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Documentation_Provided__c</fullName>
        <label>Documentation Provided</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>If_How_To_Log_Time_In_Their_System__c</fullName>
        <label>If/How To Log Time In Their System</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Invoicing_Notes__c</fullName>
        <label>Invoicing Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Migration_Id__c</fullName>
        <externalId>true</externalId>
        <label>Migration Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Num_of_Employees_Focused_on_Salesforce__c</fullName>
        <label>Num of Employees Focused on Salesforce</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partner_Tier__c</fullName>
        <label>Partner Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Global Strategic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Platinum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <picklist>
            <picklistValues>
                <fullName>SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <picklist>
            <picklistValues>
                <fullName>Net 15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 30</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Net 45</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_Meeting_Tool__c</fullName>
        <label>Preferred Meeting Tool</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Primary_Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Contact that is associated to this Account</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <infoMessage>Only Contacts that belong to this Account are shown</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_And_Requirement_Management_Tools__c</fullName>
        <label>Project And Requirement Management Tools</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>QuickBooks_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Set automatically when the Account is created in QuickBooks</inlineHelpText>
        <label>QuickBooks Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Received_W9__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Received W9</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region_Picklist__c</fullName>
        <globalPicklist>Region</globalPicklist>
        <label>Region</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Required_Security_Personnel_Information__c</fullName>
        <label>Required Security/Personnel Information</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Routing_Number__c</fullName>
        <label>Routing Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Edition__c</fullName>
        <label>Salesforce Edition</label>
        <picklist>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlimited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Sure</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Salesforce_Products_Used__c</fullName>
        <label>Salesforce Products Used</label>
        <picklist>
            <picklistValues>
                <fullName>Sales Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wave Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SalesforceIQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SteelBrick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pardot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desk.com</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Signed_NDA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Signed NDA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Taxpayer_Identification_Number_TIN__c</fullName>
        <label>Taxpayer Identification Number (TIN)</label>
        <length>11</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>TotalOutstandingInvoices0_30DaysOverdue__c</fullName>
        <label>Outstanding Invoices 0-30 Days Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalOutstandingInvoices31_60DaysOverdue__c</fullName>
        <label>Outstanding Invoices 31-60 Days Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalOutstandingInvoices61_90DaysOverdue__c</fullName>
        <label>Outstanding Invoices 61-90 Days Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalOutstandingInvoices_90DaysOverdue__c</fullName>
        <label>Outstanding Invoices &gt;90 Days Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>What_type_of_help_are_you_looking_for__c</fullName>
        <label>What type of help are you looking for?</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>X10K_DSM_Status__c</fullName>
        <label>10K DSM Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Yet Introduced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Introduced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Has 10K Paperwork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Converted - DSM Subscriber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Converted - Migrating Off DSM</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory_Accounts.cls
public with sharing class TestDataFactory_Accounts {
    
    public static List<Account> generateAccounts(Id recordTypeId, String name, String accountType, Integer numOfEmpFocusOnSF, String whatTypeHelpLookingFor, String currentUseOf3rdPartyRes,
    														String sfProductUsed, String sfEdition, String partnerType, String requiredSecurityPI, String projectAndRequirementMgmtTool, String preferedMeetingTool, String ifHowtoLogTimeInTheirSystem, 
    														String deliveryStandards, String documentsProvided, String BillingCountry, String BillingStreet, String BillingCity, String BillingState, String BillingPostalCode, String Region,
    														Id primaryBillingContactID, String paymentTerms, String additionalInvoiceRecipients, String billingCode, String customInvoiceEmailTemplate, String invoicingNotes, String accountRecordType,
    														Integer numOfRecords) {
		return generateAccountsInternal(recordTypeId, name, accountType, numOfEmpFocusOnSF, whatTypeHelpLookingFor, currentUseOf3rdPartyRes,
    														sfProductUsed, sfEdition, partnerType, requiredSecurityPI, projectAndRequirementMgmtTool, preferedMeetingTool, ifHowtoLogTimeInTheirSystem, 
    														deliveryStandards, documentsProvided, BillingCountry, BillingStreet, BillingCity, BillingState, BillingPostalCode, Region,
    														primaryBillingContactID, paymentTerms, additionalInvoiceRecipients, billingCode, customInvoiceEmailTemplate, invoicingNotes, accountRecordType,
    														numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Account> generateAccountsInternal(Id recordTypeId, String name, String accountType, Integer numOfEmpFocusOnSF, String whatTypeHelpLookingFor, String currentUseOf3rdPartyRes,
    														String sfProductUsed, String sfEdition, String partnerType, String requiredSecurityPI, String projectAndRequirementMgmtTool, String preferedMeetingTool, String ifHowtoLogTimeInTheirSystem, 
    														String deliveryStandards, String documentsProvided, String BillingCountry, String BillingStreet, String BillingCity, String BillingState, String BillingPostalCode, String Region,
    														Id primaryBillingContactID, String paymentTerms, String additionalInvoiceRecipients, String billingCode, String customInvoiceEmailTemplate, String invoicingNotes, String accountRecordType,
    														Integer numOfRecords) {
    	List<Account> accountList = new List<Account>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
			Account acc = new Account();
            acc.Name = name;
            acc.RecordTypeId = recordTypeId;
            acc.Type = accountType;
            acc.Salesforce_Products_Used__c = sfProductUsed;//App Cloud;Sales Cloud
            acc.Salesforce_Edition__c = sfEdition;
            acc.Partner_Type__c = partnerType;
            acc.Num_of_Employees_Focused_on_Salesforce__c = numOfEmpFocusOnSF;
            acc.What_type_of_help_are_you_looking_for__c = whatTypeHelpLookingFor;
            acc.Current_Use_of_3rd_Party_SFDC_Resources__c = currentUseOf3rdPartyRes;
            acc.Required_Security_Personnel_Information__c = requiredSecurityPI;
            acc.Project_And_Requirement_Management_Tools__c = projectAndRequirementMgmtTool;
            acc.Preferred_Meeting_Tool__c = preferedMeetingTool;
            acc.If_How_To_Log_Time_In_Their_System__c = ifHowtoLogTimeInTheirSystem;
            acc.Delivery_Standards__c = deliveryStandards;
            acc.Documentation_Provided__c = documentsProvided;
            acc.BillingCountry = BillingCountry;
            acc.BillingStreet = BillingStreet;
            acc.BillingCity = BillingCity;
            acc.BillingState = BillingState;
            acc.BillingPostalCode = BillingPostalCode;
            //acc.Region__c = Region;
            acc.Region_Picklist__c = Region;
            acc.Primary_Billing_Contact__c = primaryBillingContactID;
            acc.Payment_Terms__c = paymentTerms;
            acc.Additional_Invoice_Recipients__c = additionalInvoiceRecipients;
            acc.Billing_Code__c = billingCode;
            acc.Custom_Invoice_Email_Template__c = customInvoiceEmailTemplate;
            acc.Invoicing_Notes__c = invoicingNotes;
            acc.Account_Record_Type__c = accountRecordType;
            
            /*
            //Other fields 
            acc.Phone = phone;
            acc.Fax = Fax;
            acc.Website = website;
            acc.ParentID = '';
            acc.Account_Status__c
            acc.Industry
            acc.AccountSource
            acc.Signed_NDA__c = false;
            acc.Received_W9__c = false;
            acc.Routing_Number__c
            acc.Taxpayer_Identification_Number_TIN__c
            acc.Account_Number__c
            acc.Bank_Name__c
            acc.Partner_Tier__c
            acc.Description
            acc.Appirio_DSM_Status__c
            acc.X10K_DSM_Status__c
            acc.Appirio_DSM_Expiration_Date__c
            acc.ShippingStreet
            acc.ShippingCountry
            acc.ShippingCity
            acc.ShippingState
            acc.ShippingPostalCode
            acc.TotalOutstandingInvoices0_30DaysOverdue__c
            acc.TotalOutstandingInvoices31_60DaysOverdue__c
            acc.TotalOutstandingInvoices61_90DaysOverdue__c
            acc.TotalOutstandingInvoices_90DaysOverdue__c
            acc.Billing_Frequency__c
            acc.List_Experts_On_Invoices__c
            acc.Include_Timesheet_Summary_on_Invoices__c
            acc.Migration_Id__c
            acc.QuickBooks_Id__c
            */
            accountList.add(acc); 
        }
        
        return AccountList;
    }
}