src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Code__c</fullName>
        <inlineHelpText>Unique 6 digit code assigned to Customers that is used when generating Invoices</inlineHelpText>
        <label>Billing Code</label>
        <length>6</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Most_Recent_Billing_Period_End_Date__c</fullName>
        <label>Most Recent Billing Period End Date</label>
        <summarizedField>Invoice__c.Billing_Period_End_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Invoice__c.Type__c</field>
            <operation>equals</operation>
            <value>Actual</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Invoice__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>10K Services Invoice</value>
        </summaryFilterItems>
        <summaryForeignKey>Invoice__c.Account__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <picklist>
            <picklistValues>
                <fullName>Net 15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 30</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Net 45</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <picklist>
            <picklistValues>
                <fullName>Net 15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 45</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate_Structure__c</fullName>
        <label>Rate Structure</label>
        <picklist>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Retainer_Overage_Behavior__c</fullName>
        <label>Retainer Overage Behavior</label>
        <picklist>
            <picklistValues>
                <fullName>No Extra Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time &amp; Materials</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_Through__c</fullName>
        <label>Valid Through</label>
        <type>Date</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <globalPicklist>Assignment_Type</globalPicklist>
        <label>Assignment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billable Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region used from global value set &apos;Region&apos;</description>
        <globalPicklist>Region</globalPicklist>
        <label>Region</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Agreement you selected is not associated with the Account that is selected on this Invoice.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Agreement__c.Account__c</valueField>
            </filterItems>
            <infoMessage>These results have been filtered to show only Agreements for the Account selected on this Invoice.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Period_End_Date__c</fullName>
        <label>Billing Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Actual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Weeks__c</fullName>
        <label>Number of Weeks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Agreement</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>PA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <globalPicklist>Assignment_Type</globalPicklist>
        <label>Assignment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <formula>IF(
  ISBLANK(Rate_Specific_Effective_Date__c),
  Agreement__r.Effective_Date__c,
  Rate_Specific_Effective_Date__c
)</formula>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours_Per_Month__c</fullName>
        <label>Hours Per Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours_Per_Week__c</fullName>
        <label>Hours Per Week</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Rate__c</fullName>
        <label>Monthly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_Months__c</fullName>
        <label>Number of Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Weeks__c</fullName>
        <label>Number of Weeks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <globalPicklist>Region</globalPicklist>
        <label>Region</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_Through__c</fullName>
        <formula>IF(
  ISBLANK(Rate_Specific_Valid_Through__c),
  Agreement__r.Valid_Through__c,
  Rate_Specific_Valid_Through__c
)</formula>
        <label>Valid Through</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Weekly_Rate__c</fullName>
        <label>Weekly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <formula>Assignment__r.Rate__r.Hourly_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hourly Billable Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <formula>TEXT(Assignment__r.Role__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GenerateInvoicesBatch.cls
global class GenerateInvoicesBatch implements Database.Batchable<sObject> {

    String query = 'SELECT Id FROM Agreement__c WHERE RecordTypeId != \'' + Constants.RECORDTYPEID_AGREEMENT_DELIVERYPARTER + '\'';
    
    public Boolean lastMonth = false;                   
    
    global GenerateInvoicesBatch() {}
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Agreement__c> startingAgreementList) {
        
        Set<Id> startingAgreementIdSet = new Set<Id>();
        for(Agreement__c agreement : startingAgreementList) {
            startingAgreementIdSet.add(agreement.Id);
        }

        List<Agreement__c> agreementList = new List<Agreement__c>();
        for(Agreement__c agreement : [SELECT Id, Name, Account__c, Account__r.Name, RecordTypeId, Payment_Terms__c, Rate_Structure__c, 
                                             Account__r.Billing_Code__c, Effective_Date__c, Valid_Through__c, Retainer_Overage_Behavior__c,
                                             Account__r.Most_Recent_Billing_Period_End_Date__c,
                                             (SELECT Id, Agreement__c, Assignment_Type__c, Monthly_Rate__c, Number_of_Months__c, Role__c, Region__c, 
                                                     Hourly_Rate__c, Hours_Per_Month__c, Number_of_Weeks__c, Hours_Per_Week__c, Weekly_Rate__c 
                                              FROM Rates__r)
                                      FROM Agreement__c 
                                      WHERE Id IN: startingAgreementIdSet]) {
            agreementList.add(agreement);
        }
        Map<Id,List<Project_Agreement__c>> projectAgreementMap = new Map<Id,List<Project_Agreement__c>>();
        for(Project_Agreement__c projectAgreement : [SELECT Id, Agreement__c, Project__c 
                                                    FROM Project_Agreement__c 
                                                    WHERE Agreement__c IN: startingAgreementIdSet
                                                        AND Project__r.Invoiced_Separately__c = false
                                                        AND Project__r.Internal__c = false]) {
            if(!projectAgreementMap.containsKey(projectAgreement.Agreement__c))
                projectAgreementMap.put(projectAgreement.Agreement__c,new List<Project_Agreement__c>());
            projectAgreementMap.get(projectAgreement.Agreement__c).add(projectAgreement);
        }

        if(!agreementList.isEmpty()) {
            Boolean chargeForOverages;
            String selectedDateTimeDisplay;
            Integer numberOfWeeks;
            Date periodStartDate;
            Date periodEndDate;
            Date invoiceGeneratedOn;
            //Date dueDate;
            Id selectedAgreementId;
            Boolean isMonthly                                   = false;
            Map<String, Rate__c> agreementRateMap               = new Map<String, Rate__c>();
            List<Invoice_Line_Item__c> invoiceLineItemList      = new List<Invoice_Line_Item__c>();
            Set<Id> projectIdSet                                = new Set<Id>();
            List<Time_Entry__c> timeEntryList                   = new List<Time_Entry__c>();
            List<Assignment__c> assignmentsWithoutValidRates    = new List<Assignment__c>();
            String selectedProject                              = 'All';
            Boolean validRecordType                             = true;
            String mapKey                                       = '';
            String recordTypeId                                 = Constants.RECORDTYPEID_AGREEMENT_RETAINER;
            Agreement__c agreement                              = agreementList[0];

            selectedAgreementId = agreement.Id;
            chargeForOverages = (agreement.Retainer_Overage_Behavior__c == 'No Extra Charge') ? false : true;
            if(projectAgreementMap.keySet().size() == 0) {
                validRecordType = false;
            }
            if(agreement.Account__r.Billing_Code__c == null || agreement.Account__r.Billing_Code__c == '') {
                validRecordType = false;
            }
            if(agreement.Payment_Terms__c == null || agreement.Payment_Terms__c == '') {
                validRecordType = false;
            }
            if(agreement.Rate_Structure__c == 'Monthly') {
                isMonthly = true;
            }
            if(validRecordType) {
                //Build up a set of Ids of all the Projects that are tied to this Agreement
                for(Project_Agreement__c projAgree : projectAgreementMap.get(agreement.Id)) {
                    projectIdSet.add(projAgree.Project__c);
                }
        
                //Build up a map of all the Rates that are tied to this Agreement, keyed with AssignmentType+Role+RecordId
                //@TODO - Will need to update this for date-bound Capacity records
                for(Rate__c rate : agreement.Rates__r) {
                    mapKey = rate.Assignment_Type__c + '@' + rate.Region__c + '@' + rate.Role__c;
                    if(rate.Assignment_Type__c == Constants.ASSIGNMENTTYPE_NAMEDRESOURCE) {
                        mapKey += '@' + rate.Id;
                    }

                    agreementRateMap.put(mapKey, rate);
                }

                if((agreement.Rate_Structure__c == 'Monthly' && agreement.RecordTypeId == recordTypeId) || agreement.RecordTypeId != recordTypeId) {
                    Date currentDate    = lastMonth ? Date.today().addMonths(-1) : Date.today();
                    periodStartDate     = Date.newInstance(currentDate.year(), currentDate.month(), 1);
                    periodEndDate       = Date.newInstance(currentDate.year(), currentDate.month()+1, 1)-1;

                    invoiceGeneratedOn = lastMonth ? Date.newInstance(Date.today().year(), Date.today().month(), 1) : Date.newInstance(Date.today().year(), Date.today().month() + 1, 1);

                    Datetime selectedDateTime   = Datetime.newInstance(currentDate.year(), currentDate.month(), 1);
                    selectedDateTimeDisplay     = selectedDateTime.format('MMyyyy');
                }
                else if(agreement.Rate_Structure__c == 'Weekly' && agreement.RecordTypeId == recordTypeId){
                    Date currentDate    = lastMonth ? agreement.Account__r.Most_Recent_Billing_Period_End_Date__c.addDays(-27) : agreement.Account__r.Most_Recent_Billing_Period_End_Date__c.addDays(1);
                    periodStartDate     = currentDate;
                    periodEndDate       = currentDate.addDays(27);

                    invoiceGeneratedOn = Date.newInstance(periodEndDate.year(), periodEndDate.month(), 1);

                    Datetime selectedDateTime   = Datetime.newInstance(periodStartDate.year(),periodStartDate.month(),periodStartDate.day());
                    selectedDateTimeDisplay     = selectedDateTime.format('MMddyyyy');

                    numberOfWeeks = (periodStartDate.daysBetween(periodEndDate) / 7) + 1;
                }

                Set<Id> agreementIdSet = new Set<Id>{selectedAgreementId};
                String result = InvoiceCreationUtility.generateServicesInvoice( chargeForOverages, 
                                                                                isMonthly, 
                                                                                agreementRateMap, 
                                                                                numberOfWeeks,  
                                                                                invoiceLineItemList,
                                                                                periodStartDate,
                                                                                periodEndDate,
                                                                                projectIdSet,
                                                                                agreementIdSet,
                                                                                timeEntryList,
                                                                                assignmentsWithoutValidRates,
                                                                                selectedProject,
                                                                                false);
                
                //dueDate = invoiceGeneratedOn.addDays(Integer.valueOf(agreement.Payment_Terms__c.split(' ')[1]));

                if(invoiceLineItemList.size() > 0)
                {
                  //Initialize the Invoice header
                    Invoice__c invoice                      = new Invoice__c();
                    invoice.RecordTypeId                    = Constants.RECORDTYPEID_INVOICE_10KSERVICESINVOICE;
                    invoice.Name                            = '10K-';
                    invoice.Name                            += agreement.Account__r.Billing_Code__c + '-';
                    invoice.Name                            += selectedDateTimeDisplay;
                    invoice.Account__c                      = agreement.Account__c;
                    invoice.Agreement__c                    = agreement.Id;
                    invoice.Billing_Period_Start_Date__c    = periodStartDate;
                    invoice.Billing_Period_End_Date__c      = periodEndDate;
                    invoice.Type__c                         = 'Draft';
                    invoice.Invoice_Generated_On__c         = invoiceGeneratedOn;
                    //invoice.Due_Date__c                     = dueDate;

                    //Set the names of all Resources who billed hours for this Invoice into the Expert_Names__c field on the Invoice
                    if(result.split('@').size() > 1)
                    invoice.Expert_Names__c = result.split('@')[1].split('##')[0];
                    Decimal invoiceAmount;
                    try{
                        invoiceAmount = Decimal.valueOf(result.split('##')[1]);
                    }
                    catch(Exception ex){
                        invoiceAmount = 0.0;
                    }
                    List<Invoice__c> invoiceList = [SELECT Id , Name FROM Invoice__c WHERE Name =: invoice.Name AND Type__c = 'Draft' LIMIT 1];
                    if(invoiceList.size() > 0 ){
                        invoice.Id = invoiceList[0].Id;
                    }
                    if(lastMonth && invoiceList.size() > 0){
                        PageReference newInvoice = InvoiceCreationUtility.saveInvoiceAndLineItems(invoice,invoiceLineItemList,timeEntryList,false);
                    }
                    else if (!lastMonth) {
                        PageReference newInvoice = InvoiceCreationUtility.saveInvoiceAndLineItems(invoice,invoiceLineItemList,timeEntryList,false);
                    }
                }
            }
        }
    }
    
    global void finish(Database.BatchableContext BC) {

        //Automatically start the next job in the series of Invoicing jobs
        GenerateDeliveryPartnerInvoicesBatch deliveryPartnerInvoiceBatch = new GenerateDeliveryPartnerInvoicesBatch();

        //If this job was run with lastMonth = TRUE, the next step is to run the regular Invoice Batch for the prior month
        if(lastMonth) {
            deliveryPartnerInvoiceBatch.lastMonth = true;
            ChainedBatchId__c batchIds = ChainedBatchId__c.getOrgDefaults();
            if(!Test.isRunningTest())
                batchIds.ThirdBatch_Id__c = Database.executeBatch(deliveryPartnerInvoiceBatch, 1);
            upsert batchIds;
        }
        //If however the job was run for the current month, there next steps is to run the regular Invoice Batch for the current month
        else {
            deliveryPartnerInvoiceBatch.lastMonth = false;
            ChainedBatchId__c batchIds = ChainedBatchId__c.getOrgDefaults();
            if(!Test.isRunningTest())
                batchIds.SixthBatch_Id__c = Database.executeBatch(deliveryPartnerInvoiceBatch, 1);
            upsert batchIds;
        }
    }
}