src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Additional_Invoice_Recipients__c</fullName>
        <label>Additional Invoice Recipients</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Contact that is associated to this Account</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <infoMessage>Only Contacts that belong to this Account are shown</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Additional_Invoice_Recipients__c</fullName>
        <inlineHelpText>Defaults from the Account. A list of email addresses to include in CC on each Invoice that is sent out.</inlineHelpText>
        <label>Additional Invoice Recipients</label>
        <type>TextArea</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Currency_Code_With_Symbols__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Currency_Symbol__c</fullName>
        <label>Currency Symbol</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Currency Code With Symbols</label>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Agreement you selected is not associated with the Account that is selected on this Invoice.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Agreement__c.Account__c</valueField>
            </filterItems>
            <infoMessage>These results have been filtered to show only Agreements for the Account selected on this Invoice.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PastDueInvoiceNotificationBatch_Test.cls
@isTest
private class PastDueInvoiceNotificationBatch_Test
{
    //Covering batch
    static testMethod void test_method_one() {
        
        TestDataFactory objTestDataFactory = new TestDataFactory();   
        Currency_Code_With_Symbols__c currencySymbol = new Currency_Code_With_Symbols__c(Name = 'USD', Currency_Symbol__c = '$');
        insert currencySymbol;
        List<Account> lstAccounts = objTestDataFactory.generateAccounts(1);
        insert lstAccounts;
        List<Contact> lstContacts = objTestDataFactory.generateContactsForAccounts(lstAccounts,2);
        insert lstContacts;
        lstContacts[0].email = 'Test@test.com';
        update lstContacts;
        lstAccounts[0].Primary_Billing_Contact__c = lstContacts[0].id;
        update lstAccounts;
        List<Agreement__c> lstAgreement = objTestDataFactory.generateRetainerAgreementsForAccounts(lstAccounts, 1);
        insert lstAgreement;
        lstAgreement[0].Additional_Invoice_Recipients__c = 'test1@test.com';
        update lstAgreement;
        List<Rate__c> rateList = objTestDataFactory.generateRateForAgreement(lstAgreement[0].Id, Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS, Constants.ROLE_DEVELOPER, 1);
        insert rateList;
        List<Invoice__c > invoiceList = new List<Invoice__c >();
        for(Integer i=0; i < 2 ; i++){
            Invoice__c  invoice = new Invoice__c  ();
            invoice.account__c = lstAccounts[0].id;
            invoice.name = 'Test' + i;
            invoiceList.add(invoice );
        }    
        insert invoiceList; 
        invoiceList[0].RecordTypeId = Constants.RECORDTYPEID_INVOICE_10KPRODUCTINVOICE;
        invoiceList[1].RecordTypeId = Constants.RECORDTYPEID_INVOICE_10KPRODUCTINVOICE;
        invoiceList[0].Due_Date__c  = system.today() - 5;
        invoiceList[1].Due_Date__c  = system.today() - 5;
        invoiceList[0].Agreement__c  = lstAgreement[0].Id;
        update invoiceList;

        List<Invoice_Line_Item__c> invoiceLineItem = objTestDataFactory.generateInvoiceLineItems(invoiceList[0].Id, rateList[0].Id, 1);
        insert invoiceLineItem;

        Payment__c paymentList = new Payment__c();
        paymentList.Invoice__c = invoiceList[0].Id;
        paymentList.Amount__c = -100.00;
        insert paymentList;

        Document document;
        document = new Document();
        document.ContentType = 'image/png';
        document.DeveloperName = 'logo_2_png';
        document.IsPublic = true;
        document.Name = 'logo (1).png';
        List<Folder> folderLst = [select id from folder where name = '10K Logos'];
        if(folderLst.size() > 0)
        {
            document.FolderId = folderLst[0].Id;
            insert document;
        }
        

        Test.StartTest();
            PastDueInvoiceNotificationSchedule objBatch = new PastDueInvoiceNotificationSchedule();
            String sch = '0 0 23 * * ?';
            system.schedule('Test status Check', sch, objBatch);
            System.assertNotEquals(invoiceList[0].RecordTypeId, Constants.RECORDTYPEID_INVOICE_DELIVERYPARTNERINVOICE);
        Test.stopTest();
    }
}