src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Current_Tier__c</fullName>
        <label>Current Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Everest</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ascent_Metrics__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Ascent_Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount_Invoiced_YTD__c</fullName>
        <label>Amount Invoiced YTD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Tier__c</fullName>
        <label>Current Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hours_Invoiced_YTD__c</fullName>
        <label>Hours Invoiced YTD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_End_Date__c</fullName>
        <label>Month End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Month_Start_Date__c</fullName>
        <label>Month Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Tier__c</fullName>
        <label>Next Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ascent Metric</label>
    <nameField>
        <label>Ascent Metrics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ascent Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Period_End_Date__c</fullName>
        <label>Billing Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Period_Start_Date__c</fullName>
        <label>Billing Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Hours_Invoiced__c</fullName>
        <formula>Total_Hours__c  -  Total_Goodwill_Hours__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Hours Invoiced</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Invoice_Amount__c</fullName>
        <label>Total Invoice Amount</label>
        <summarizedField>Invoice_Line_Item__c.Line_Item_Total_Text__c</summarizedField>
        <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AscentMetricsBatch.cls
/* 
    @Description    AscentMetricsBatch Class When new Invoice generates then creation / updation of Ascent Metrics (Author :- Akshat)
    @createdate     08 Jan 2018
 */
 
global class AscentMetricsBatch implements Database.Batchable<sObject> {

    String query = 'SELECT Id,Name,RecordTypeId FROM Account WHERE RecordTypeId = \'' + Constants.RECORDTYPEID_Account_DirectClient  + '\' OR RecordTypeId = \'' + Constants.RECORDTYPEID_Account_PartnerClient + '\' OR RecordTypeId = \'' + Constants.RECORDTYPEID_Account_PartnerClientDeliveryPartner + '\'';
    
    global AscentMetricsBatch() {}
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Account> accountList) {
        
        // Picklist value of Currrent tier field of Accounts
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = Account.Current_Tier__c.getDescribe();
        for( Schema.PicklistEntry pickListVal : fieldResult.getPicklistValues()){
            pickListValuesList.add(pickListVal.getLabel());
        }
        
        // with existing values with as well New of AscMetrics related to Accounts
        Map<Account,List<Ascent_Metrics__c>> existingNewAscMetricAccountMap = new Map<Account,List<Ascent_Metrics__c>>();
        Integer currentMonthNumber = date.Today().Month();
        
        for(Account acc : [Select Id,Name,Current_Tier__c, (Select Id,Name,Amount_Invoiced_YTD__c,Hours_Invoiced_YTD__c,Month_End_Date__c,Month_Start_Date__c,Current_Tier__c,Next_Tier__c From Ascent_Metrics__r Where Month_End_Date__c = THIS_year) from Account Where Id IN : accountList])
        {
            List<Ascent_Metrics__c > tempAscList = new List<Ascent_Metrics__c >();
                
            for(Integer i=1 ; i <= currentMonthNumber ; i++){
                Date monthStartDate = Date.newInstance(date.today().year(), i, 1);
                Date monthEndDate = Date.newInstance(date.today().year(), i+1, 1)-1;
                boolean ascendMetricThisMonth  = false;
                        
                for( Ascent_Metrics__c existingAscMetric : acc.Ascent_Metrics__r ){
                    If(existingAscMetric.Month_Start_Date__c == monthStartDate && existingAscMetric.Month_End_Date__c == monthEndDate ){
                        tempAscList.add(existingAscMetric); 
                        ascendMetricThisMonth = true;
                    }
                }
                If(!ascendMetricThisMonth){
                    Ascent_Metrics__c ascMetric = new Ascent_Metrics__c();
                    ascMetric.Account__c = acc.Id;
                    ascMetric.Month_Start_Date__c  = monthStartDate ;
                    ascMetric.Month_End_Date__c = monthEndDate ;
                    tempAscList.add(ascMetric);
                }
            }
            existingNewAscMetricAccountMap.put(acc,tempAscList);
        }
        
        // New Records With Invoice List inner query with Account
        Map<Id,List<Invoice__c>> accountWithInvoiceMap = new Map<Id,List<Invoice__c>>();
        for(Account acc : [Select Id,Name,Current_Tier__c,(SELECT Id,Name,Billing_Period_Start_Date__c,Billing_Period_End_Date__c,Total_Hours_Invoiced__c,Total_Invoice_Amount__c FROM Invoices__r Where Billing_Period_Start_Date__c = THIS_year) From Account WHERE Id IN : accountList]){
            If(acc.Invoices__r.isEmpty()){
                accountWithInvoiceMap.put(acc.Id,new List<Invoice__c>{});
            }
            else{
                accountWithInvoiceMap.put(acc.Id,acc.Invoices__r);
            }
        }
        
        // Main Process of Metric record based on Account with invoice based calculation
        Date yearFirstDate = Date.newInstance(date.today().year(),1,1);
        List<Ascent_Metrics__c> mainUpsertingAscMetricList = new List<Ascent_Metrics__c>();
            
        for(Account acc : existingNewAscMetricAccountMap.keyset()){
            // First Part calculating tier value of Account
            String currentTier = acc.Current_Tier__c;
            string nextTier = nextTierPickListCalc(currentTier,pickListValuesList);
            If(nextTier == null || nextTier == '')
                nextTier = currentTier ;
            
            List<Ascent_Metrics__c> tempAscmetricList = existingNewAscMetricAccountMap.get(acc);
            List<Invoice__c> invList = accountWithInvoiceMap.get(acc.Id);
            
            // Processing the Metric List based invoice List
            
            for(Ascent_Metrics__c tempAscMetric : tempAscmetricList )
            {
                Decimal totalAmount = 0;
                Decimal totalHour = 0;
                for(Invoice__c inv : invList ){
                    If(inv.Billing_Period_Start_Date__c >= yearFirstDate && inv.Billing_Period_End_Date__c <= tempAscMetric.Month_End_Date__c){
                        totalAmount += inv.Total_Invoice_Amount__c;
                        totalHour += inv.Total_Hours_Invoiced__c;
                    }
                }
                tempAscMetric.Current_Tier__c = currentTier;
                tempAscMetric.Next_Tier__c = nextTier;
                tempAscMetric.Amount_Invoiced_YTD__c = totalAmount ;
                tempAscMetric.Hours_Invoiced_YTD__c = totalHour ;
                tempAscMetric.Name = convertMonthNumberToName(tempAscMetric.Month_Start_Date__c.month())+' '+tempAscMetric.Month_Start_Date__c.day()+' - '+convertMonthNumberToName(tempAscMetric.Month_End_Date__c.month())+ ' '+tempAscMetric.Month_End_Date__c.Day() +' for $'+totalAmount ;
                mainUpsertingAscMetricList.add(tempAscMetric);
            }
        }
        
        If(mainUpsertingAscMetricList.size() > 0)
            upsert mainUpsertingAscMetricList;   
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
    
    private static String nextTierPickListCalc(String currentTier,List<String> pickListValuesList){
        String nextTier = '';
        boolean CounterNext = false;
        If(currentTier == null || currentTier == '')
            CounterNext = true;
        for(String picklistVal : pickListValuesList){
            If(CounterNext){
               nextTier =  picklistVal;
               break;
            }    
            If(currentTier != null && currentTier != '' && currentTier.trim() == picklistVal.trim())
                CounterNext = true;
        }
        return nextTier ;
    }
           
    private static String convertMonthNumberToName(Integer matrixMonth){
        Map<Integer, String> monthMap = new Map<Integer, String>{1 => 'Jan',2 =>'Feb',3 => 'Mar',4 => 'Apr',5 => 'May', 6 => 'June', 7=> 'July', 8 => 'Aug', 9=> 'Sept', 10 => 'Oct', 11 => 'Nov', 12 => 'Dec'};
        return monthMap.get(matrixMonth);
    }
}