src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Current_Tier__c</fullName>
        <label>Current Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Everest</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Outstanding_Invoices__c</fullName>
        <label>Total Outstanding Invoices</label>
        <summarizedField>Invoice__c.Outstanding_Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Invoice__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>10K Product Invoice, 10K Services Invoice</value>
        </summaryFilterItems>
        <summaryForeignKey>Invoice__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Outstanding_Overdue_Invoices__c</fullName>
        <formula>TotalOutstandingInvoices_90DaysOverdue__c  +  TotalOutstandingInvoices0_30DaysOverdue__c  +  TotalOutstandingInvoices31_60DaysOverdue__c  +  TotalOutstandingInvoices61_90DaysOverdue__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Outstanding Overdue Invoices</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ascent_Metrics__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Ascent_Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount_Invoiced_YTD__c</fullName>
        <label>Amount Invoiced YTD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Tier__c</fullName>
        <label>Current Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hours_Invoiced_YTD__c</fullName>
        <label>Hours Invoiced YTD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_End_Date__c</fullName>
        <label>Month End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Month_Start_Date__c</fullName>
        <label>Month Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Tier__c</fullName>
        <label>Next Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ascent Metric</label>
    <nameField>
        <label>Ascent Metrics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ascent Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/GenerateAscentMonthlyReportPdfController.cls
public class GenerateAscentMonthlyReportPdfController{
	public Ascent_Metrics__c ascendMetricRec {get;Set;}
	public Map<Id,List<String>> accIdWithSetContactMap {get;set;}
	public String allContactName {get;set;}
	public GenerateAscentMonthlyReportPdfController(){
		Id ascendMetricId = apexpages.currentpage().getparameters().get('id');
		Set<Id> oppMSAIds   = new Set<Id>();
		ascendMetricRec = [SELECT Id, Account__c, Account__r.Current_Tier__c, Account__r.Owner.Name, Account__r.RecordTypeId, Account__r.Name, 
                                                    Account__r.Total_Outstanding_Invoices__c, Account__r.Total_Outstanding_Overdue_Invoices__c, 
                                                    IsDeleted, Name, Amount_Invoiced_YTD__c, Current_Tier__c, Hours_Invoiced_YTD__c, Month_End_Date__c, 
                                                    Month_Start_Date__c, Next_Tier__c 
                                                FROM Ascent_Metrics__c WHERE Id = :ascendMetricId];
		for(Opportunity oppMSAtype : [SELECT Id, Name, AccountId 
                                        FROM Opportunity 
                                        WHERE RecordTypeId =: Constants.RECORDTYPEID_OPPORTUNITY_MSA 
                                        AND AccountId =: ascendMetricRec.Account__c 
                                        AND Start_Date__c <=: ascendMetricRec.Month_Start_Date__c AND End_Date__c >=: ascendMetricRec.Month_End_Date__c]) {
            oppMSAIds.add(oppMSAtype.Id);
        }
        // Processing metric List to create wrapper in every contains key condition with contact roles
        accIdWithSetContactMap = new Map<Id,List<String>>();
        
        Set<String> contactIDSet = new Set<String>();
        for(OpportunityContactRole oppConRole : [SELECT Id, OpportunityId, Opportunity.AccountId, ContactId, Contact.FirstName, Role 
                                                    FROM OpportunityContactRole WHERE OpportunityId =: oppMSAIds]) {
            if(!contactIDSet.contains(oppConRole.Opportunity.AccountId+'#'+oppConRole.ContactId)) {
                if(accIdWithSetContactMap.containsKey(oppConRole.Opportunity.AccountId)) {
                    accIdWithSetContactMap.get(oppConRole.Opportunity.AccountId).add(oppConRole.Contact.FirstName);
                } else {
                    accIdWithSetContactMap.put(oppConRole.Opportunity.AccountId, new List<String>{(oppConRole.Contact.FirstName)});
                }
                contactIDSet.add(oppConRole.Opportunity.AccountId+'#'+oppConRole.ContactId);
            }
        }

        allContactName = '';
        if(accIdWithSetContactMap.containsKey(ascendMetricRec.Account__c) && accIdWithSetContactMap.get(ascendMetricRec.Account__c).size() > 0){
        	if(accIdWithSetContactMap.get(ascendMetricRec.Account__c).size() > 1){
        		for(String contactName : accIdWithSetContactMap.get(ascendMetricRec.Account__c)){
        			allContactName += contactName+',';
        		}	
        	}
        	else{
        		allContactName = accIdWithSetContactMap.get(ascendMetricRec.Account__c)[0] + ',';
        	}
        }
        
	}



}