src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Additional_Invoice_Recipients__c</fullName>
        <label>Additional Invoice Recipients</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Invoice_Recipients__c</fullName>
        <inlineHelpText>Defaults from the Account. A list of email addresses to include in CC on each Invoice that is sent out.</inlineHelpText>
        <label>Additional Invoice Recipients</label>
        <type>TextArea</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Other_Email__c</fullName>
        <label>Other Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SandboxRefreshUtility.cls
global with sharing class SandboxRefreshUtility implements SandboxPostCopy
{
	global void runApexClass(SandboxContext context) 
	{
		List<Lead> leadList = new List<Lead>();
		for(Lead l : [SELECT Id, Email FROM Lead WHERE Email != null]) 
		{
		    l.Email = 'matt@10kview.com';
		    leadList.add(l);
		}
		update leadList;

		List<Contact> contactList = new List<Contact>();
		for(Contact con : [SELECT Id, Email, Other_Email__c FROM Contact WHERE Email != null OR Other_Email__c != null]) 
		{
		    if(con.Email != null) {
		        con.Email = 'matt@10kview.com';
		    }
		    if(con.Other_Email__c != null) {
		        con.Other_Email__c = 'matt@10kview.com';
		    }
		    contactList.add(con);
		}
		update contactList;

		List<Account> accountList = new List<Account>();
		for(Account acc : [SELECT Id, Additional_Invoice_Recipients__c FROM Account WHERE Additional_Invoice_Recipients__c != null]) 
		{
		    acc.Additional_Invoice_Recipients__c = 'becky@10kview.com';
		    accountList.add(acc);
		}
		update accountList;

		List<Agreement__c> agreementList = new List<Agreement__c>();
		for(Agreement__c agreement : [SELECT Id, Additional_Invoice_Recipients__c FROM Agreement__c WHERE Additional_Invoice_Recipients__c != null]) 
		{
		    agreement.Additional_Invoice_Recipients__c = 'becky@10kview.com';
		    agreementList.add(agreement);
		}
		update agreementList;
	}
}