src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Current_Tier__c</fullName>
        <label>Current Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Base</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Everest</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ascent_Metrics__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Ascent_Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount_Invoiced_YTD__c</fullName>
        <label>Amount Invoiced YTD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Tier__c</fullName>
        <label>Current Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_End_Date__c</fullName>
        <label>Month End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Month_Start_Date__c</fullName>
        <label>Month Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Tier__c</fullName>
        <label>Next Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ascent Metric</label>
    <nameField>
        <label>Ascent Metrics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ascent Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ascent_Tier__mdt.object
<CustomObject>
    <fields>
        <fullName>Spend_Target__c</fullName>
        <label>Spend Target</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ascent Tier</label>
    <pluralLabel>Ascent Tiers</pluralLabel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Period_End_Date__c</fullName>
        <label>Billing Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Period_Start_Date__c</fullName>
        <label>Billing Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Generated_On__c</fullName>
        <label>Billing Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outstanding_Balance__c</fullName>
        <formula>IF(
  ISPICKVAL(Type__c, &quot;Void&quot;),
  0,
  Total_Invoice_Amount__c - Total_Amount_Paid__c
)</formula>
        <label>Outstanding Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Invoice_Amount__c</fullName>
        <label>Total Invoice Amount</label>
        <summarizedField>Invoice_Line_Item__c.Line_Item_Total_Text__c</summarizedField>
        <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Actual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountRelatedInvoicesController.cls
public class AccountRelatedInvoicesController{
    public String accId {get;set;}
    public Integer counter {get;set;}
    public Decimal ytdSpend {get;set;}
    public Decimal amountRemaining {get;set;}
    public Decimal amountPerMonth {get;set;}
    public Boolean statusValue {get;set;}
    public Id ascentRecordId {get;set;}
    public Integer monthsRemaining {get;set;}
    public Decimal data {get;set;}
    public Decimal verticleLinedata {get;set;}
    public Map<String,Decimal> asentTargetMap {get;set;}


    public List<Invoice__c> getInvoiceList(){
        asentTargetMap = new Map<String,Decimal>();
        Ascent_Metrics__c ascentRecord  = [SELECT Id, Month_Start_Date__c,Next_Tier__c, Amount_Invoiced_YTD__c,Account__r.Current_Tier__c, Month_End_Date__c 
                                            FROM Ascent_Metrics__c WHERE Id = :ascentRecordId];
        List<Invoice__c> invoiceList    = [SELECT Id, Billing_Period_Start_Date__c, Billing_Period_End_Date__c, Name, 
                                            Outstanding_Balance__c, Invoice_Generated_On__c, Due_Date__c, 
                                            Total_Invoice_Amount__c 
                                                FROM Invoice__c WHERE Account__c =: accId
                                                And Type__c = 'Actual' 
                                                AND  Outstanding_Balance__c > 0];
        verticleLinedata = 0;
        counter     = 0;
        ytdSpend = ascentRecord.Amount_Invoiced_YTD__c;
        amountRemaining = 0;
        
        for(Ascent_Tier__mdt tier : [SELECT ID, Label, Spend_Target__c FROM Ascent_Tier__mdt]){
            asentTargetMap.put(tier.Label, tier.Spend_Target__c);
        }

		
        if(asentTargetMap.containsKey(ascentRecord.Next_Tier__c))
            amountRemaining     = asentTargetMap.get(ascentRecord.Next_Tier__c) - ascentRecord.Amount_Invoiced_YTD__c;
        monthsRemaining     = (12 - ascentRecord.Month_Start_Date__c.month());
        if(monthsRemaining != 0)
            amountPerMonth  = (amountRemaining / monthsRemaining).setScale(2);
        else
            amountPerMonth  = amountRemaining;

        Integer month = ascentRecord.Month_Start_Date__c.month();
        data = 0;    

        if(ascentRecord.Amount_Invoiced_YTD__c > 0) {
            data = (ascentRecord.Amount_Invoiced_YTD__c / asentTargetMap.get(ascentRecord.Next_Tier__c)) * 100 ;
            data = (data * 700 ) / 100;
        }
        if(asentTargetMap.containsKey(ascentRecord.Next_Tier__c)) {
            verticleLinedata = (asentTargetMap.get(ascentRecord.Next_Tier__c) / 12) * month;
            verticleLinedata = ((verticleLinedata / asentTargetMap.get(ascentRecord.Next_Tier__c)) * 100).setScale(2);
            verticleLinedata = (verticleLinedata * 700 ) / 100;
        }
            
        return invoiceList;

    }

   

}