src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <picklist>
            <picklistValues>
                <fullName>Net 15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 30</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Net 45</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Contact that is associated to this Account</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <infoMessage>Only Contacts that belong to this Account are shown</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Opportunity you selected is not associated with the Account that is selected on this Agreement.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.AccountId</valueField>
            </filterItems>
            <infoMessage>These results have been filtered to show only Opportunities for the Account selected on this Agreement.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <picklist>
            <picklistValues>
                <fullName>Net 15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 45</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <globalPicklist>Account_Tier</globalPicklist>
        <label>Tier</label>
        <type>Picklist</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>MSA</fullName>
        <active>true</active>
        <description>An MSA outlines the terms and hourly rates at which we work with a particular client, but does not define any particular scope of work.</description>
        <label>MSA</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Billable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cost_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Assignments (Cost Rate)</relationshipLabel>
        <relationshipName>Assignments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Do_Not_Send_Feedback_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Send Feedback Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Hours__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Planned Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region used from global value set &apos;Region&apos;</description>
        <globalPicklist>Region</globalPicklist>
        <label>Region</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Number_of_Hours__c</fullName>
        <label>Total Number of Hours</label>
        <summarizedField>Time_Entry__c.Hours__c</summarizedField>
        <summaryForeignKey>Time_Entry__c.Assignment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <recordTypes>
        <fullName>Assignment</fullName>
        <active>true</active>
        <label>Assignment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Budget</relationshipLabel>
        <relationshipName>Budget</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <displayFormat>BUD-{0000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Tier__c</fullName>
        <globalPicklist>Account_Tier</globalPicklist>
        <label>Account Tier</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Agreement_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Agreement Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Closed_Through_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Closed Through Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Opportunity does not belong to the selected Account. Please select another Opportunity.</errorMessage>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <infoMessage>Only Opportunities for the selected Account are shown.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Number_of_Hours__c</fullName>
        <label>Total Number of Hours</label>
        <summarizedField>Assignment__c.Total_Number_of_Hours__c</summarizedField>
        <summaryForeignKey>Assignment__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Agreement</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>PA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <globalPicklist>Region</globalPicklist>
        <label>Region</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate_Card__c.object
<CustomObject>
    <fields>
        <fullName>Account_Tier__c</fullName>
        <globalPicklist>Account_Tier</globalPicklist>
        <label>Account Tier</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Rate Cards</relationshipLabel>
        <relationshipName>Rate_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <globalPicklist>Region</globalPicklist>
        <label>Region</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClosedWonProcessController.cls
global class ClosedWonProcessController {

	@AuraEnabled
	public static OpportunityWrapper getClosedWonOpportunity(Id recId) {
		Opportunity oppRecord 	= [SELECT CloseDate, AccountId, Amount, Type, LeadSource, StageName, Start_Date__c, Account_Tier__c, Account.Payment_Terms__c, 
										Is_Closed_Through_Process__c,RecordTypeId,Agreement_Generated__c, End_Date__c, Account.Primary_Billing_Contact__c 
									FROM Opportunity 
									WHERE Id =:recId];

		List<PickValWrap> opportunityTypePickValues 			= new List<PickValWrap>();
		List<PickValWrap> opportunityLeadSourcePickValues 		= new List<PickValWrap>();
	   	Schema.DescribeFieldResult fieldResult 					= Opportunity.Account_Tier__c.getDescribe();
	   	List<Schema.PicklistEntry> ple 							= fieldResult.getPicklistValues();

	   	for(Schema.PicklistEntry f : ple) {
	   		if(f.getLabel() == oppRecord.Account_Tier__c)
	      		opportunityTypePickValues.add(new PickValWrap(f.getLabel(), f.getValue(), true));
	      	else
	      		opportunityTypePickValues.add(new PickValWrap(f.getLabel(), f.getValue(), false));
	   	}

	   	Schema.DescribeFieldResult fieldResult1 				= Account.Payment_Terms__c.getDescribe();
	   	List<Schema.PicklistEntry> ple1							= fieldResult1.getPicklistValues();

	   	for(Schema.PicklistEntry f1 : ple1) {
	   		if(f1.getLabel() == oppRecord.Account.Payment_Terms__c)
	      		opportunityLeadSourcePickValues.add(new PickValWrap(f1.getLabel(), f1.getValue(), true));
	      	else
	      		opportunityLeadSourcePickValues.add(new PickValWrap(f1.getLabel(), f1.getValue(), false));
	   	}

	   	OpportunityWrapper oppWrapRec 	= new OpportunityWrapper();
	   	oppWrapRec.oppRec 				= oppRecord;
	   	oppWrapRec.oppType 				= opportunityTypePickValues;
	   	oppWrapRec.oppLeadSource 		= opportunityLeadSourcePickValues;

		return oppWrapRec;
	}

	@AuraEnabled
	public static List<AgreementWrapper> getClosedWonOpportunityAggreement(Id recId, Id accId) {
		List<AgreementWrapper> agreementWrapperList = new List<AgreementWrapper>();
		for(Agreement__c agreementRecord : [SELECT Id, Name, Status__c 
												FROM Agreement__c 
												WHERE  Status__c = 'Active' 
												AND Account__c =:accId]) {
			agreementWrapperList.add(new AgreementWrapper(agreementRecord, false));
		}
		return agreementWrapperList;
	}

	@AuraEnabled
	public static List<Project_Agreement__c> retriveProject(Id agreement_Id) {
		List<Project_Agreement__c> projectRecord = [SELECT Id, Name, Project__r.Name 
													FROM Project_Agreement__c 
													WHERE  Agreement__c =:agreement_Id];
		return projectRecord;
	}

	@AuraEnabled
	public static List<AssignmentWrapper> retriveProjectAssigment(String recId, List<Id> agreementIdList, String agreementEffectiveDate, String agreementExpireDate) {
		List<AssignmentWrapper> assignmentRecord 	= new List<AssignmentWrapper>();
		Set<Id> projectIdSet 						= new Set<Id>();
		Set<String> roleSet 						= new Set<String>();
		agreementEffectiveDate 						= agreementEffectiveDate.replace('\"', '');
		agreementExpireDate 						= agreementExpireDate.replace('\"', '');
		Date effectiveDate 							= Date.newInstance(Integer.valueOf(agreementEffectiveDate.split('-')[0]), Integer.valueOf(agreementEffectiveDate.split('-')[1]), Integer.valueOf(agreementEffectiveDate.split('-')[2]));
		Date expireDate 							= Date.newInstance(Integer.valueOf(agreementExpireDate.split('-')[0]), Integer.valueOf(agreementExpireDate.split('-')[1]), Integer.valueOf(agreementExpireDate.split('-')[2]));
		for(Project_Agreement__c projectAgreement : [SELECT Project__c, Project__r.id, Project__r.Name 
														FROM Project_Agreement__c 
														WHERE  Agreement__c IN :agreementIdList]) {
			projectIdSet.add(projectAgreement.Project__c);
		}

        List<String> roleList 						= new List<String>();
        roleList.add('');
        for(Rate_Card__c rateCardRec : [SELECT Id, Role__c, Region__c 
										FROM Rate_Card__c 
										WHERE Opportunity__c =: recId]) {
			roleSet.add(rateCardRec.Role__c + ' - ' + rateCardRec.Region__c);
		}
		roleList.addAll(roleSet);

		Map<Id, Date> projectIdToEndDateMap 		= new Map<Id,Date>();
		for(Project__c projectRec : [SELECT Id, End_Date__c FROM Project__c WHERE Id IN: projectIdSet]) {
			projectIdToEndDateMap.put(projectRec.Id, projectRec.End_Date__c);
		}

		for(Assignment__c assign : [SELECT Id, Name, Role__c, Project__c, Billable__c, Project__r.Name, Status__c, Planned_Hours__c, Total_Number_of_Hours__c, 
										Do_Not_Send_Feedback_Survey__c, Cost_Rate__c, Resource__c, End_Date__c, Start_Date__c, Generate_Budget_Records__c,Region__c 
									FROM Assignment__c 
									WHERE Project__c IN :projectIdSet 
									AND (Status__c = 'Active' OR Status__c = 'Projected') 
									ORDER BY Project__r.Name]) {
			assignmentRecord.add(new AssignmentWrapper(assign, roleList, effectiveDate, (expireDate < projectIdToEndDateMap.get(assign.Project__c) ? expireDate : projectIdToEndDateMap.get(assign.Project__c)), roleSet.contains(assign.Role__c + ' - ' + assign.Region__c) ? assign.Role__c + ' - ' + assign.Region__c : ''));
		}
		assignmentRecord.sort();
		return assignmentRecord;
	}

	@AuraEnabled
	public static String createNewAgreementAndRates(String recId, String agreementEffectiveDate, String agreementExpirationDate, List<Id> agreementIdList, Opportunity oppRec) {
		agreementEffectiveDate 				= agreementEffectiveDate.replace('\"', '');
		agreementExpirationDate 			= agreementExpirationDate.replace('\"', '');
		List<Rate__c> rateList 				= new List<Rate__c>();
		List<Project_Agreement__c> pAgrList = new List<Project_Agreement__c>();
		Set<Id> projectIdSet 				= new Set<Id>();
		List<Opportunity> oppList 			= [SELECT Id, AccountId, Account.Name, Account_Tier__c, Amount FROM Opportunity WHERE Id =: recId];
		List<Account> accountList 			= [SELECT Id, Current_Tier__c FROM Account WHERE Id =: oppList[0].AccountId];
		accountList[0].Current_Tier__c 		= oppList[0].Account_Tier__c;
		Agreement__c agreementRec 			= new Agreement__c();
		
		if(oppRec.RecordTypeId == Constants.RECORDTYPEID_OPPORTUNITY_MSA) {
			agreementRec.RecordTypeId 		= Constants.RECORDTYPEID_AGREEMENT_MSA;
			agreementRec.Name 				= oppList[0].Account.Name + ' - ' + 'MSA' + ' - ';
		}
		else {
			agreementRec.RecordTypeId 		= Constants.RECORDTYPEID_AGREEMENT_DELIVERYPARTER;
			agreementRec.Name 				= oppList[0].Account.Name + ' - ' + 'Time & Materials SOW' + ' - ';
		}
		agreementRec.Name 					+= fetchMonthName(Integer.valueOf(agreementEffectiveDate.split('-')[1])) + ' ' + agreementEffectiveDate.split('-')[0] +
												' to ' + fetchMonthName(Integer.valueOf(agreementExpirationDate.split('-')[1])) + ' ' + agreementExpirationDate.split('-')[0];
		agreementRec.Effective_Date__c 		= Date.newInstance(Integer.valueOf(agreementEffectiveDate.split('-')[0]), Integer.valueOf(agreementEffectiveDate.split('-')[1]), Integer.valueOf(agreementEffectiveDate.split('-')[2]));
		agreementRec.Valid_Through__c 		= Date.newInstance(Integer.valueOf(agreementExpirationDate.split('-')[0]), Integer.valueOf(agreementExpirationDate.split('-')[1]), Integer.valueOf(agreementExpirationDate.split('-')[2]));
		agreementRec.Account__c 			= oppList[0].AccountId;
		agreementRec.Status__c 				= 'Active';
		agreementRec.Tier__c 				= oppList[0].Account_Tier__c;
		agreementRec.Budget__c 				= oppList[0].Amount;
		agreementRec.Opportunity__c 		= oppList[0].Id;
		insert agreementRec;

		for(Rate_Card__c rateCardRec : [SELECT Id, Opportunity__c, Role__c, Assignment_Type__c, Hourly_Rate__c, Region__c   
										FROM Rate_Card__c 
										WHERE Opportunity__c =: recId]) {
			Rate__c rateRec 				= new Rate__c();
			rateRec.Name 					= rateCardRec.Role__c + ' - ' +  (rateCardRec.Region__c != null ? (rateCardRec.Region__c + ' - '):'') +  rateCardRec.Assignment_Type__c + ' - $' + rateCardRec.Hourly_Rate__c;
			rateRec.Role__c 				= rateCardRec.Role__c;
			rateRec.Assignment_Type__c 		= rateCardRec.Assignment_Type__c;
			rateRec.Hourly_Rate__c 			= rateCardRec.Hourly_Rate__c;
			rateRec.Region__c 				= rateCardRec.Region__c;
			rateRec.Agreement__c 			= agreementRec.Id;
			rateList.add(rateRec);
		}
		if(!rateList.isEmpty()) {
			insert rateList;
		}
		oppRec.Is_Closed_Through_Process__c 		= true; 
		oppRec.Agreement_Generated__c 				= true;
		update oppRec;
		update accountList;
		return 'The Agreement has been successfully created.';
	}

	@AuraEnabled
	public static String replaceAgreementsAndAssignments(String recId, String agreementEffectiveDate, String agreementExpirationDate, List<Id> agreementIdList, String wrapperListJSON, Opportunity oppRec) {
		agreementEffectiveDate 				= agreementEffectiveDate.replace('\"', '');
		agreementExpirationDate 			= agreementExpirationDate.replace('\"', '');
		List<AssignmentWrapper> assignWrap 	= (List<AssignmentWrapper>)JSON.deserialize(wrapperListJSON, List<AssignmentWrapper>.class);
		List<Assignment__c> oldAssignList 	= new List<Assignment__c>();
		List<Assignment__c> newAssignList 	= new List<Assignment__c>();
		List<Rate__c> rateList 				= new List<Rate__c>();
		Map<String, Id> newRateRoleToIdMap	= new Map<String, Id>();
		List<Project_Agreement__c> pAgrList = new List<Project_Agreement__c>();
		Set<Id> projectIdSet 				= new Set<Id>();
		List<Opportunity> oppList 			= [SELECT Id, AccountId, Account.Name, Account_Tier__c, Amount FROM Opportunity WHERE Id =: recId];
		List<Account> accountList 			= [SELECT Id, Current_Tier__c FROM Account WHERE Id =: oppList[0].AccountId];
		accountList[0].Current_Tier__c 		= oppList[0].Account_Tier__c;
		Agreement__c agreementRec 			= new Agreement__c();
		
		if(oppRec.RecordTypeId == Constants.RECORDTYPEID_OPPORTUNITY_MSA) {
			agreementRec.RecordTypeId 		= Constants.RECORDTYPEID_AGREEMENT_MSA;
			agreementRec.Name 				= oppList[0].Account.Name + ' - ' + 'MSA' + ' - ';
		}
		else {
			agreementRec.RecordTypeId 		= Constants.RECORDTYPEID_AGREEMENT_DELIVERYPARTER;
			agreementRec.Name 				= oppList[0].Account.Name + ' - ' + 'Time & Materials SOW' + ' - ';
		}
		agreementRec.Name 					+= fetchMonthName(Integer.valueOf(agreementEffectiveDate.split('-')[1])) + ' ' + agreementEffectiveDate.split('-')[0] +
												' to ' + fetchMonthName(Integer.valueOf(agreementExpirationDate.split('-')[1])) + ' ' + agreementExpirationDate.split('-')[0];	
		agreementRec.Effective_Date__c 		= Date.newInstance(Integer.valueOf(agreementEffectiveDate.split('-')[0]), Integer.valueOf(agreementEffectiveDate.split('-')[1]), Integer.valueOf(agreementEffectiveDate.split('-')[2]));
		agreementRec.Valid_Through__c 		= Date.newInstance(Integer.valueOf(agreementExpirationDate.split('-')[0]), Integer.valueOf(agreementExpirationDate.split('-')[1]), Integer.valueOf(agreementExpirationDate.split('-')[2]));
		agreementRec.Account__c 			= oppList[0].AccountId;
		agreementRec.Status__c 				= 'Active';
		agreementRec.Tier__c 				= oppList[0].Account_Tier__c;
		agreementRec.Budget__c 				= oppList[0].Amount;
		agreementRec.Opportunity__c 		= oppList[0].Id;
		insert agreementRec;

		for(Rate_Card__c rateCardRec : [SELECT Id, Opportunity__c, Role__c, Assignment_Type__c, Hourly_Rate__c, Region__c  
										FROM Rate_Card__c 
										WHERE Opportunity__c =: recId]) {
			Rate__c rateRec 				= new Rate__c();
			rateRec.Name 					= rateCardRec.Role__c + ' - ' +  (rateCardRec.Region__c != null ? (rateCardRec.Region__c + ' - '):'') +  rateCardRec.Assignment_Type__c + ' - $' + rateCardRec.Hourly_Rate__c;
			rateRec.Role__c 				= rateCardRec.Role__c;
			rateRec.Assignment_Type__c 		= rateCardRec.Assignment_Type__c;
			rateRec.Hourly_Rate__c 			= rateCardRec.Hourly_Rate__c;
			rateRec.Region__c 				= rateCardRec.Region__c;
			rateRec.Agreement__c 			= agreementRec.Id;
			rateList.add(rateRec);
		}
		if(!rateList.isEmpty()) {
			insert rateList;
		}
		for(Rate__c rate : rateList) {
			newRateRoleToIdMap.put(rate.Role__c + ' - ' + rate.Region__c, rate.Id);
		}
		if(!agreementIdList.isEmpty()) {
			for(Project_Agreement__c projectAgg : [SELECT Id, Project__c 
													FROM Project_Agreement__c 
													WHERE Agreement__c IN : agreementIdList 
													AND Project__r.Status__c = 'Open']) {
				projectIdSet.add(projectAgg.Project__c);
			}
			for(Id projectId : projectIdSet) {
				Project_Agreement__c projAgrRec = new Project_Agreement__c();
				projAgrRec.Agreement__c 		= agreementRec.Id;
				projAgrRec.Project__c 			= projectId;
				pAgrList.add(projAgrRec);
			}
			if(!pAgrList.isEmpty()) {
				insert pAgrList;
			}

			for(AssignmentWrapper assignWrapRec : assignWrap) {
				System.debug(assignWrapRec.endDate);
				Assignment__c assignRec 		= new Assignment__c();
				if(assignWrapRec.assignment.Planned_Hours__c == null)
					assignWrapRec.assignment.Planned_Hours__c = 0;
				if(assignWrapRec.effectiveDate <= Date.today())
					assignRec.Status__c 		= 'Active';
				else
					assignRec.Status__c 		= 'Projected';
				assignRec.Start_Date__c 		= assignWrapRec.effectiveDate;
				assignRec.End_Date__c 			= assignWrapRec.endDate;
				assignRec.Role__c 				= (assignWrapRec.selectedRole).split('-')[0].trim();
				assignRec.Region__c 			= (assignWrapRec.selectedRole).split('-')[1].trim();
				assignRec.Assignment_Type__c 	= 'Time & Materials';
				if(oppRec.RecordTypeId == Constants.RECORDTYPEID_OPPORTUNITY_MSA)
					assignRec.Rate__c 				= newRateRoleToIdMap.get(assignWrapRec.selectedRole);
				assignRec.Project__c 			= assignWrapRec.assignment.Project__c;
				assignRec.Resource__c 			= assignWrapRec.assignment.Resource__c;
				assignRec.Billable__c 			= assignWrapRec.assignment.Billable__c;
				assignRec.Planned_Hours__c 		= assignWrapRec.assignment.Planned_Hours__c - assignWrapRec.assignment.Total_Number_of_Hours__c;
				assignRec.Cost_Rate__c 			= assignWrapRec.assignment.Cost_Rate__c;
				assignRec.Generate_Budget_Records__c = true;
				newAssignList.add(assignRec);

				assignWrapRec.assignment.Do_Not_Send_Feedback_Survey__c = true;
				assignWrapRec.assignment.Planned_Hours__c 				= assignWrapRec.assignment.Total_Number_of_Hours__c;
				assignWrapRec.assignment.Generate_Budget_Records__c 	= true;
				assignWrapRec.assignment.End_Date__c 					= (oppRec.Start_Date__c).addDays(-1);
				assignWrapRec.assignment.Automatically_Close__c 		= true;
				if(assignWrapRec.assignment.End_Date__c < Date.today() || assignWrapRec.assignment.Status__c == 'Projected') {
					assignWrapRec.assignment.Status__c 					= 'Closed';
				} else {
					assignWrapRec.assignment.Status__c 					= 'Active';
				}
				oldAssignList.add(assignWrapRec.assignment);
			}

			if(!oldAssignList.isEmpty())
				update oldAssignList;
			if(!newAssignList.isEmpty())
				insert newAssignList;
		}
		oppRec.Is_Closed_Through_Process__c 	= true;
		oppRec.Agreement_Generated__c 			= true;
		update oppRec;
		update accountList;
		return 'The Agreement has been successfully created.';
	}

	private static String fetchMonthName(Integer month) {
		Map<Integer, String> monthNumberToNameMap = new Map<Integer, String>{1 =>'Jan', 2 =>'Feb', 3 =>'Mar', 4 =>'Apr', 5 =>'May', 6 =>'Jun', 7 =>'Jul', 8 =>'Aug', 9 =>'Sep', 10 =>'Oct', 11 =>'Nov', 12 =>'Dec'};
		return monthNumberToNameMap.get(month);
	}

	global class AssignmentWrapper implements Comparable {
		@AuraEnabled public Assignment__c assignment 		{get;set;}
		@AuraEnabled public List<String> newRole  			{get;set;}
		@AuraEnabled public Date effectiveDate 				{get;set;}
		@AuraEnabled public Date endDate 					{get;set;}
		@AuraEnabled public String selectedRole 			{get;set;}

		global AssignmentWrapper(Assignment__c assignment, List<String> newRole, Date effectiveDate, Date endDate, String selectedRole) {
	    	this.assignment 	= assignment;
	   		this.newRole 		= newRole;
	    	this.effectiveDate 	= effectiveDate;
	    	this.endDate 		= endDate;
	    	this.selectedRole 	= selectedRole;
		}

		global Integer compareTo(Object ObjToCompare) {
            return selectedRole.CompareTo(((AssignmentWrapper)ObjToCompare).selectedRole);
        }
	}

	global class OpportunityWrapper {
		@AuraEnabled public Opportunity oppRec 				{get; set;}
		@AuraEnabled public List<PickValWrap> oppType 		{get; set;}
		@AuraEnabled public List<PickValWrap> oppLeadSource {get; set;}
	}

	global class PickValWrap {
		@AuraEnabled public String text 					{get; set;}
		@AuraEnabled public String val 						{get; set;}
		@AuraEnabled public Boolean isSelected 				{get; set;}

		PickValWrap(String text, String val, Boolean isSelected) {
			this.text 		= text;
			this.val 		= val;
			this.isSelected = isSelected;
		}
	}

	global class AgreementWrapper {
		@AuraEnabled public Agreement__c agreementRec 		{get; set;}
		@AuraEnabled public Boolean isSelected 				{get; set;}

		AgreementWrapper(Agreement__c agreementRec, Boolean isSelected) {
			this.agreementRec 	= agreementRec;
			this.isSelected 	= isSelected;
		}
	}
}