src/objects/Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Trailhead_Logo_Url__c</fullName>
        <label>Trailhead Logo Url</label>
        <type>Url</type>
    </fields>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Trailhead_User_Id__c</fullName>
        <label>Trailhead User Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webassessor_ContactId__c</fullName>
        <label>Webassessor Contact Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expert_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <label>Achievement</label>
        <referenceTo>Achievement__c</referenceTo>
        <relationshipLabel>Expert Achievements</relationshipLabel>
        <relationshipName>Expert_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Certification_Date__c</fullName>
        <label>Certification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Expert Achievements</relationshipLabel>
        <relationshipName>Expert_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expert Achievement</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Expert Achievement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expert Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BadgesDetails_Test.cls
@isTest(SeeAllData=true)
private class BadgesDetails_Test {
  
    static testMethod void test_method_one() {
        
        TestDataFactory factory = new TestDataFactory();   
        List<User>userList = factory.createUsersWith10KCustomerProfile(1);
        Insert userList;
        RecordType trailRecords = [select Id,Name from RecordType where SobjectType='Achievement__c' and Name='Trailhead Badge' Limit 1];
        RecordType certificateRecord = [select Id,Name from RecordType where SobjectType='Achievement__c' and Name='Salesforce Certification' Limit 1];
        List<Achievement__c> achiList = new List<Achievement__c>();
        Achievement__c achi1 = new Achievement__c(Trailhead_Logo_Url__c = '/resource/Salesforce_Certified_Administrator',RecordTypeId = trailRecords.Id);
        Achievement__c achi2 = new Achievement__c(Trailhead_Logo_Url__c = '/resource/Salesforce_Certified_Administrator',RecordTypeId = certificateRecord.Id);
        achiList.add(achi1);
        achiList.add(achi2);
        Insert achiList;
        List<Expert_Achievement__c> expertList = new List<Expert_Achievement__c>();
        Expert_Achievement__c expert1 = new Expert_Achievement__c(Achievement__c = achiList[0].Id,Certification_Date__c = Date.Today(),Contact__c = userList[0].contactId);
        Expert_Achievement__c expert2 = new Expert_Achievement__c(Achievement__c = achiList[1].Id,Certification_Date__c = Date.Today(),Contact__c = userList[0].contactId);
        expertList.add(expert1);
        expertList.add(expert2);
        Insert expertList;
        Contact con = [Select Id,Trailhead_User_Id__c,Webassessor_ContactId__c From Contact Where Id = : userList[0].contactId];
        StaticResource reso = [SELECT Id, Name, ContentType, Body FROM StaticResource Where ContentType = 'image/png' And Name = 'closebutton'  Limit 1];
        System.assertNotEquals(reso, null);
        System.RunAs(userList[0]){
            BadgesDetails.getAchivements(UserInfo.getUserId()); 
            BadgesDetails.getCertifications(UserInfo.getUserId());
            BadgesDetails.getUserDetails(UserInfo.getUserId());
            BadgesDetails.validateCurrentUser(UserInfo.getUserId());
            BadgesDetails.userWrapp wrapp = new BadgesDetails.userWrapp();
            wrapp.userInfo = userList[0];
            wrapp.userStreet = 'Test';
            wrapp.userCity = 'Test';
            wrapp.userState = 'California';
            wrapp.userZip = '333';
            wrapp.userCountry = 'United States';
            wrapp.contactDetail = con;
            String jsonStr = JSON.serialize(wrapp);
            BadgesDetails.saveUserDetails(jsonStr);
            BadgesDetails.saveProfilePicture(EncodingUtil.base64Encode(reso.Body), UserInfo.getUserId());
            BadgesDetails.addFollowUser(UserInfo.getUserId());
            BadgesDetails.removeFollowUser(UserInfo.getUserId());
        }
        
    }
}