src/objects/Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Achievement_Category__c</fullName>
        <label>Achievement Category</label>
        <picklist>
            <picklistValues>
                <fullName>Climb Achievement</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hidden__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hidden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Internal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Internal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_URL__c</fullName>
        <inlineHelpText>Specify a value if you want users to go to this URL when clicking the Achievement Image. This can be used to redirect to a custom page where you manage additional steps before changing the status of the Achievement to &quot;Acquired&quot;.</inlineHelpText>
        <label>Override URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trailhead_Logo_Url__c</fullName>
        <label>Trailhead Logo Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Work_Badge_Image_URL__c</fullName>
        <label>Work Badge Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory_Achievements.cls
public with sharing class TestDataFactory_Achievements {
    
    public static List<Achievement__c> generateAchievements(Id recordTypeId, String achivementName, String achievementCategory, String type, Date expirationDate, boolean isHidden, boolean isInternal, String workBadgeURL, String trailLogoUrl, String overrideUrl, Integer numOfRecords) {
        return generateAchievementsInternal(recordTypeId, achivementName, achievementCategory, type, expirationDate, isHidden, isInternal, workBadgeURL, trailLogoUrl, overrideUrl, numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Achievement__c> generateAchievementsInternal(Id recordTypeId, String achivementName, String achievementCategory, String type, Date expirationDate, boolean isHidden, boolean isInternal, String workBadgeURL, String trailLogoUrl, String overrideUrl, Integer numOfRecords) {
        List<Achievement__c> achievementsList = new List<Achievement__c>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
            Achievement__c ach = new Achievement__c();
            ach.Name = achivementName;
            ach.RecordTypeId = recordTypeId;
            ach.Achievement_Category__c = achievementCategory;
            //ach.Type__c = type;
            ach.Expiration_Date__c = expirationDate;
            ach.Hidden__c = isHidden;
            ach.Is_Internal__c = isInternal;
            ach.Work_Badge_Image_URL__c = workBadgeURL;
            ach.Trailhead_Logo_Url__c = trailLogoUrl;
            ach.Override_URL__c = overrideUrl;
            achievementsList.add(ach);
        }
        
        return achievementsList;
    }
}