src/objects/Achievement__c.object
<CustomObject>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Expert_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <label>Achievement</label>
        <referenceTo>Achievement__c</referenceTo>
        <relationshipLabel>Expert Achievements</relationshipLabel>
        <relationshipName>Expert_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Certification_Date__c</fullName>
        <label>Certification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Expert Achievements</relationshipLabel>
        <relationshipName>Expert_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_From_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created From Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Holder_Name__c</fullName>
        <label>Holder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Expert Achievements</relationshipLabel>
        <relationshipName>Expert_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deprecated</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Expert Achievement</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Expert Achievement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expert Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataFactory_ExpertAchievements.cls
public with sharing class TestDataFactory_ExpertAchievements {
    
    public static List<Expert_Achievement__c> generateExpertAchievements(String status, Id leadId, String holderName, boolean createdFromSync, Id contactId, Date certificationDate, Id achievementId, Integer numOfRecords) {
		return generateExpertAchievementsInternal(status, leadId, holderName, createdFromSync, contactId, certificationDate, achievementId, numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Expert_Achievement__c> generateExpertAchievementsInternal(String status, Id leadId, String holderName, boolean createdFromSync, Id contactId, Date certificationDate, Id achievementId, Integer numOfRecords) {
    	List<Expert_Achievement__c> exAchievementsList = new List<Expert_Achievement__c>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
        	Expert_Achievement__c each = new Expert_Achievement__c();
        	each.Status__c = status;
        	each.Lead__c = leadId;
        	each.Holder_Name__c = holderName;
        	each.Created_From_Sync__c = createdFromSync;
        	each.Contact__c = contactId;
        	each.Certification_Date__c = certificationDate;
        	each.Achievement__c = achievementId;
			exAchievementsList.add(each);
        }
        
        return exAchievementsList;
    }
}