src/objects/Achievement__c.object
<CustomObject>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Achievement_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement</label>
        <referenceTo>Achievement__c</referenceTo>
        <relationshipLabel>Achievement Assignments</relationshipLabel>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Achievement Assignment</label>
    <nameField>
        <displayFormat>AAS-{0000000}</displayFormat>
        <label>Achievement Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestDataFactory_AchievementAssignment.cls
public with sharing class TestDataFactory_AchievementAssignment {
    
    public static List<Achievement_Assignment__c> generateAchievementAssignment(Id achievementId, Integer numOfRecords) {
        return generateAchievementAssignmentInternal(achievementId, numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Achievement_Assignment__c> generateAchievementAssignmentInternal(Id achievementId, Integer numOfRecords) {
        List<Achievement_Assignment__c> achievementAssignmentsList = new List<Achievement_Assignment__c>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
            Achievement_Assignment__c ask = new Achievement_Assignment__c();
            ask.Achievement__c = achievementId;
            achievementAssignmentsList.add(ask);
        }
        
        return achievementAssignmentsList;
    }
}