src/objects/Achievement__c.object
<CustomObject>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Achievement_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <label>Achievement</label>
        <referenceTo>Achievement__c</referenceTo>
        <relationshipLabel>Achievement Skills</relationshipLabel>
        <relationshipName>Achievement_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>ProfileSkill</referenceTo>
        <relationshipLabel>Achievement Skills</relationshipLabel>
        <relationshipName>Achievement_Skills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Achievement Skill</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Achievement Skills Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataFactory_AchievementSkills.cls
public with sharing class TestDataFactory_AchievementSkills {
	
	public static List<Achievement_Skill__c> generateAchievementSkills(Id achievementId, Id skillId, Integer numOfRecords) {
		return generateAchievementSkillsInternal(achievementId, skillId, numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Achievement_Skill__c> generateAchievementSkillsInternal(Id achievementId, Id skillId, Integer numOfRecords) {
    	List<Achievement_Skill__c> achievementSkillsList = new List<Achievement_Skill__c>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
        	Achievement_Skill__c ask = new Achievement_Skill__c();
        	ask.Achievement__c = achievementId;
        	ask.Skill__c = skillId;
			achievementSkillsList.add(ask);
        }
        
        return achievementSkillsList;
    }
}