src/objects/Achievement__c.object
<CustomObject>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Achievement_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <label>Achievement</label>
        <referenceTo>Achievement__c</referenceTo>
        <relationshipLabel>Achievement Skills</relationshipLabel>
        <relationshipName>Achievement_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Achievement Skill</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Achievement Skills Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expert_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <label>Achievement</label>
        <referenceTo>Achievement__c</referenceTo>
        <relationshipLabel>Expert Achievements</relationshipLabel>
        <relationshipName>Expert_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Expert Achievements</relationshipLabel>
        <relationshipName>Expert_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Expert Achievements</relationshipLabel>
        <relationshipName>Expert_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expert Achievement</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Expert Achievement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expert Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AchievementSkillTriggerHandler.cls
public with sharing class AchievementSkillTriggerHandler {
	public static void updateExpertSkills(List<Achievement_Skill__c> achievementSkillList) {
		
		Set<Id> achievementIdset = new Set<Id>();
		for(Achievement_Skill__c achievementSkill : achievementSkillList) {
			achievementIdset.add(achievementSkill.Achievement__c);
		}
		if(achievementIdset.size() > 0) {
			List<Expert_Achievement__c> expertAchievementList = new List<Expert_Achievement__c>();
			List<Expert_Achievement__c> leadExpertAchievementList = new List<Expert_Achievement__c>();
			for(Expert_Achievement__c expertAchievement: [SELECT Id,Contact__c,Lead__c,Achievement__c FROM Expert_Achievement__c WHERE Achievement__c IN: achievementIdset]) {
				if(expertAchievement.Contact__c != null) {
					expertAchievementList.add(expertAchievement);
				}
				if(expertAchievement.Lead__c != null) {
					leadExpertAchievementList.add(expertAchievement);
				}
			}
			if(expertAchievementList.size() > 0) {
				ExpertAchievementTriggerHandler.insertExpertSkillsForExpertAchievements(expertAchievementList,Trigger.newMap.keySet());
			}
			if(leadExpertAchievementList.size() > 0) {
				ExpertAchievementTriggerHandler.insertExpertSkillsForLeadExpertAchievements(leadExpertAchievementList,Trigger.newMap.keySet());
			}
		}
		
	}
}