src/objects/Achievement__c.object
<CustomObject>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Achievement_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <label>Achievement</label>
        <referenceTo>Achievement__c</referenceTo>
        <relationshipLabel>Achievement Skills</relationshipLabel>
        <relationshipName>Achievement_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>ProfileSkill</referenceTo>
        <relationshipLabel>Achievement Skills</relationshipLabel>
        <relationshipName>Achievement_Skills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Achievement Skill</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Achievement Skills Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Endorsement__c.object
<CustomObject>
    <fields>
        <fullName>Expert_Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expert Achievement</label>
        <referenceTo>Expert_Achievement__c</referenceTo>
        <relationshipLabel>Endorsements</relationshipLabel>
        <relationshipName>Endorsements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expert_Skill__c</fullName>
        <label>Expert Skill</label>
        <referenceTo>Expert_Skill__c</referenceTo>
        <relationshipLabel>Endorsements</relationshipLabel>
        <relationshipName>Endorsements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Endorsement</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Endorsement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expert_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <label>Achievement</label>
        <referenceTo>Achievement__c</referenceTo>
        <relationshipLabel>Expert Achievements</relationshipLabel>
        <relationshipName>Expert_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Expert Achievements</relationshipLabel>
        <relationshipName>Expert_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Expert Achievements</relationshipLabel>
        <relationshipName>Expert_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expert Achievement</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Expert Achievement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expert Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expert_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Expert Skills</relationshipLabel>
        <relationshipName>Expert_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Expert Skills</relationshipLabel>
        <relationshipName>Expert_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>ProfileSkill</referenceTo>
        <relationshipLabel>Expert Skills</relationshipLabel>
        <relationshipName>Expert_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expert Skill</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Expert Skill Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expert Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Achievement_Count__c</fullName>
        <label>Achievement Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Expert</fullName>
        <active>true</active>
        <businessProcess>Expert Leads</businessProcess>
        <label>Delivery Partner</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/ProfileSkill.object
<CustomObject>
    <fields>
        <fullName>Skill_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Skill Group</label>
        <referenceTo>Skill_Group__c</referenceTo>
        <relationshipLabel>Skills</relationshipLabel>
        <relationshipName>Skills</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Skill_Group__c.object
<CustomObject>
    <label>Skill Group</label>
    <nameField>
        <label>Skill Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExpertAchievementTriggerHandler_Test.cls
@isTest
private class ExpertAchievementTriggerHandler_Test {
	
	static testMethod void test_usecase_one() {
		
		Id salesforceCertificationRecordTypeId = Schema.SObjectType.Achievement__c.RecordTypeInfosByName.get('Salesforce Certification').RecordTypeId;
        List<Achievement__c> achievementsList = TestDataFactory_Achievements.generateAchievements(salesforceCertificationRecordTypeId, 'Test123', 'Climb Achievement', 'Achievements', Date.today().addDays(365), false, false, '', '', '', 1);
        achievementsList.addAll(TestDataFactory_Achievements.generateAchievements(salesforceCertificationRecordTypeId, 'Test456', 'Climb Achievement', 'Achievements', Date.today().addDays(365), false, false, '', '', '', 1));
        insert achievementsList;
        
		List<Skill_Group__c> skillGroupsList = TestDataFactory_SkillGroups.generateSkillGroups('Test Group', 1);
        insert skillGroupsList;
        
        List<ProfileSkill> profileSkillList = TestDataFactory_Skills.generateSkills('Test Skill', null, skillGroupsList[0].Id, null, 1);
        insert profileSkillList;
        
        List<Achievement_Skill__c> achievementSkillsList = TestDataFactory_AchievementSkills.generateAchievementSkills(achievementsList[0].Id, profileSkillList[0].Id, 1);
        achievementSkillsList.addAll(TestDataFactory_AchievementSkills.generateAchievementSkills(achievementsList[1].Id, profileSkillList[0].Id, 1));
        insert achievementSkillsList;
        
        Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
        List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
                                                            'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
                                                            'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
                                                            null, 'Net 30', 'acc@testemail.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
                                                            1);
        insert accList;
        
        List<Contact> contactList = TestDataFactory_Contacts.generatecontacts(accList, 'Test contact', 'lastName','test2@testemail.com', '', 1);
        insert contactList;
        
        List<Lead> leadList = TestDataFactory_Leads.generateLeads(Constants.RECORDTYPEID_Customer, 'TestCompany', 'LName', 'test@testemail.com', null, null, 'US', 1);
        insert leadList;
        
        List<Expert_Achievement__c> exAchievementsList = TestDataFactory_ExpertAchievements.generateExpertAchievements('Active', null, 'LName', false, contactList[0].id, Date.today().addDays(-30), achievementsList[0].Id, 1);
        exAchievementsList.addAll(TestDataFactory_ExpertAchievements.generateExpertAchievements('Active', leadList[0].Id, 'LName', false, null, Date.today().addDays(-30), achievementsList[0].Id, 1));
        insert exAchievementsList;
        
        List<Expert_Skill__c> expertSkillsList = [SELECT Id FROM Expert_Skill__c WHERE Skill__c =:profileSkillList[0].Id AND (Contact__c=:contactList[0].Id OR Lead__c=:leadList[0].Id)];
        System.assertEquals(2, expertSkillsList.size());
        
        List<Endorsement__c> endorsementList = [SELECt Id, Expert_Skill__c, Expert_Achievement__c FROM Endorsement__c];
        System.assertEquals(2, endorsementList.size());
        
        //In case if contact/lead already have expert skills
        exAchievementsList = TestDataFactory_ExpertAchievements.generateExpertAchievements('Active', null, 'LName', false, contactList[0].id, Date.today().addDays(-30), achievementsList[1].Id, 1);
        exAchievementsList.addAll(TestDataFactory_ExpertAchievements.generateExpertAchievements('Active', leadList[0].Id, 'LName', false, null, Date.today().addDays(-30), achievementsList[1].Id, 1));
        insert exAchievementsList;
        
        endorsementList = [SELECt Id, Expert_Skill__c, Expert_Achievement__c FROM Endorsement__c];
        System.assertEquals(4, endorsementList.size());
        
        System.assertEquals(2, exAchievementsList.size());
        delete exAchievementsList[1];
        
        List<Lead> leadResultList = [SELECT Id,Achievement_Count__c FROM Lead WHERE Id=:leadList[0].Id];
        System.assertEquals(1, leadResultList.size());
        System.assertEquals(1, leadResultList[0].Achievement_Count__c);
	}
	
	static testMethod void test_usecase_two() {
		//Negative Testing
		Id salesforceCertificationRecordTypeId = Schema.SObjectType.Achievement__c.RecordTypeInfosByName.get('Salesforce Certification').RecordTypeId;
        List<Achievement__c> achievementsList = TestDataFactory_Achievements.generateAchievements(salesforceCertificationRecordTypeId, 'Test123', 'Climb Achievement', 'Achievements', Date.today().addDays(365), false, false, '', '', '', 1);
        insert achievementsList;
        
		List<Skill_Group__c> skillGroupsList = TestDataFactory_SkillGroups.generateSkillGroups('Test Group', 1);
        insert skillGroupsList;
        
        List<ProfileSkill> profileSkillList = TestDataFactory_Skills.generateSkills('Test Skill', null, skillGroupsList[0].Id, null, 1);
        insert profileSkillList;
        
        List<Achievement_Skill__c> achievementSkillsList = TestDataFactory_AchievementSkills.generateAchievementSkills(achievementsList[0].Id, profileSkillList[0].Id, 1);
        insert achievementSkillsList;
        
        Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
        List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
                                                            'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
                                                            'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
                                                            null, 'Net 30', 'acc@testemail.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
                                                            1);
        insert accList;
        
        List<Contact> contactList = TestDataFactory_Contacts.generatecontacts(accList, 'Test contact', 'lastName','test2@testemail.com', '', 1);
        insert contactList;
        
        List<Lead> leadList = TestDataFactory_Leads.generateLeads(Constants.RECORDTYPEID_Customer, 'TestCompany', 'LName', 'test@testemail.com', null, null, 'US', 1);
        insert leadList;
        
        List<Expert_Achievement__c> exAchievementsList = TestDataFactory_ExpertAchievements.generateExpertAchievements('Active', null, 'LName', false, contactList[0].id, Date.today().addDays(-30), achievementsList[0].Id, 1);
        exAchievementsList.addAll(TestDataFactory_ExpertAchievements.generateExpertAchievements('Active', leadList[0].Id, 'LName', false, null, Date.today().addDays(-30), achievementsList[0].Id, 1));
        insert exAchievementsList;
        System.assertEquals(2, exAchievementsList.size());
        
        try
        {
        	//validation
        	exAchievementsList = TestDataFactory_ExpertAchievements.generateExpertAchievements('Active', null, 'LName', false, contactList[0].id, Date.today().addDays(-30), achievementsList[0].Id, 1);
        	insert exAchievementsList;
        }
        catch(Exception ex)
        {
        	String errorMessage = ex.getMessage();
        	System.assert(errorMessage.contains('You can\'t select Achievement which already exist.'));
        }
        
        try
        {
        	//validation
        	exAchievementsList = TestDataFactory_ExpertAchievements.generateExpertAchievements('Active', leadList[0].Id, 'LName', false, null, Date.today().addDays(-30), achievementsList[0].Id, 1);
        	insert exAchievementsList;
        }
        catch(Exception ex)
        {
        	String errorMessage = ex.getMessage();
        	System.assert(errorMessage.contains('You can\'t select Achievement which already exist.'));
        }
	}
}