src/objects/Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Achievement_Category__c</fullName>
        <label>Achievement Category</label>
        <picklist>
            <picklistValues>
                <fullName>Climb Achievement</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_Badge_Image_URL__c</fullName>
        <label>Work Badge Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Learning__c.object
<CustomObject>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learnings</pluralLabel>
    <recordTypes>
        <fullName>Resource</fullName>
        <active>true</active>
        <label>Resource</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Learning_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Learning__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Learning</label>
        <referenceTo>Learning__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Progress__c</fullName>
        <description>.</description>
        <label>Progress</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Training_Plan_Section_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Training Plan Section Item</label>
        <referenceTo>Training_Plan_Section_Item__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Plan_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Plan Section</label>
        <referenceTo>Training_Plan_Section__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Plan</label>
        <referenceTo>Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Assignment</label>
    <nameField>
        <displayFormat>LEA-{0000000}</displayFormat>
        <label>Learning Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Training_Plan__c.object
<CustomObject>
    <label>Training Plan</label>
    <nameField>
        <label>Training Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Training_Plan_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>@S-0727 : Replicating the Almond package functionality.</description>
        <label>Achievement</label>
        <referenceTo>Achievement__c</referenceTo>
        <relationshipLabel>Training Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Plan_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Plan Section</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only sections from the parent training plan can be selected</errorMessage>
            <filterItems>
                <field>Training_Plan_Section__c.Training_Plan__c</field>
                <operation>equals</operation>
                <valueField>$Source.Training_Plan__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Training_Plan_Section__c</referenceTo>
        <relationshipLabel>Training Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Plan__c</fullName>
        <label>Training Plan</label>
        <referenceTo>Training_Plan__c</referenceTo>
        <relationshipLabel>Training Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Training Plan Achievement</label>
    <nameField>
        <displayFormat>TPA-{0000000}</displayFormat>
        <label>Training Plan Achievement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Plan Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Plan_Section__c.object
<CustomObject>
    <fields>
        <fullName>Training_Plan__c</fullName>
        <label>Training Plan</label>
        <referenceTo>Training_Plan__c</referenceTo>
        <relationshipLabel>Training Plan Sections</relationshipLabel>
        <relationshipName>Training_Plan_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Training Plan Section</label>
    <nameField>
        <label>Training Plan Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Plan Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Plan_Section_Item__c.object
<CustomObject>
    <fields>
        <fullName>Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only published learnings can be added to a training plan</errorMessage>
            <filterItems>
                <field>Learning__c.Is_Published_Formula__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>NOTE: Only published learnings can be associated to a training plan</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Learning__c</referenceTo>
        <relationshipLabel>Training Plan Section Items</relationshipLabel>
        <relationshipName>Training_Plan_Section_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Plan_Section__c</fullName>
        <label>Training Plan Section</label>
        <referenceTo>Training_Plan_Section__c</referenceTo>
        <relationshipLabel>Training Plan Section Items</relationshipLabel>
        <relationshipName>Training_Plan_Section_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Training Plan Section Item</label>
    <nameField>
        <displayFormat>TPSI-{0000000}</displayFormat>
        <label>Training Plan Section Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Plan Section Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Learning__c</fullName>
        <label>Learning</label>
        <referenceTo>Learning__c</referenceTo>
        <relationshipLabel>Training Resources</relationshipLabel>
        <relationshipName>Training_Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Training Resource</label>
    <nameField>
        <label>Training Resource Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAchievementAssignmentsWorkCom.cls
@isTest
private class TestAchievementAssignmentsWorkCom{

    static testMethod void testCompletingTrainingPlan(){

        //Create admin users
        List<User> adminUsers = TestUtilClass.createUsers(1,'System Administrator');
        List<User> lmsUsers = TestUtilClass.createUsers(1,'Standard User');

        System.runAs(adminUsers.get(0)){
            //Assign corresponding perm sets
            TestUtilClass.addPermissionSet(adminUsers,'LMS_Admin');
            TestUtilClass.addPermissionSet(lmsUsers,'LMS_User');
        }

        Id learningAssignmentId = createSingleItemTrainingPlanWithWorkAchievement(adminUsers,lmsUsers);

        PageReference pageRef = Page.ResourceViewer;
        pageRef.getParameters().put('aid',learningAssignmentId);

        System.assertEquals(0,getWorkBadgeCount(lmsUsers.get(0).Id));

        Test.setCurrentPage(pageRef);
        Test.startTest();
            System.runAs(lmsUsers.get(0)){
                ResourceViewerController cont = new ResourceViewerController();
                String contRef = ResourceViewerController.redirectToResource(learningAssignmentId);
                System.assert(contRef != null);
                List<Learning_Assignment__c> assignments;
                assignments = [select id,Progress__c from Learning_Assignment__c where id = :learningAssignmentId];
                System.assertEquals(LMSConstants.ASSIGNMENT_STATUS_COMPLETED,assignments.get(0).Progress__c);
            }

        Test.stopTest();

        //Assert work badge has been created
        //Commneted By AKshat
        //  System.assertEquals(1,getWorkBadgeCount(lmsUsers.get(0).Id));
        System.assertEquals(0,getWorkBadgeCount(lmsUsers.get(0).Id));
    }

    private static Id createSingleItemTrainingPlanWithWorkAchievement(List<User> adminUsers, List<User> lmsUsers){

        //create resource learnings
        List<Learning__c> resourceLearnings = TestLearningData.createTestLearning(1, 'Resource', false);
        //create training resources
        List<Training_Resource__c> tresources = TestLearningData.createTestTrainingResource(resourceLearnings);

        for(Integer i = 0;i < resourceLearnings.size();i++){
            TestLearningData.publishLearning(resourceLearnings.get(i).Id,'resource',tresources.get(i).Id,false);
        }

        //Create training plans
        List<Training_Plan__c> tplans = TestTrainingPlanData.createTrainingPlans(new List<TestParams.TrainingPlanParam>{new TestParams.TrainingPlanParam()});
        //Create training plan sections
        List<Training_Plan_Section__c> tplanSections1 = TestTrainingPlanData.createTrainingPlanSections(tplans.get(0).Id,1);
        //Create training plan section items for resource
        List<Training_Plan_Section_Item__c> tplan1SectionItems1 = TestTrainingPlanData.createTrainingPlanSectionItems(tplanSections1.get(0).Id,resourceLearnings);
        // Commented By Akshat ---> Adding the new pamaterized to refernce picklist value not Achievement_Category__c.Id
        /*
        List<Achievement_Category__c> lAchieveCat = TestAchievementData.createAchievementCategories(1);
        List<Achievement__c> lAchievements = TestAchievementData.createAchievements(1, lAchieveCat.get(0).Id, 'Achievements');
         */
        List<Achievement__c> lAchievements = TestAchievementData.createAchievements(1, 'Achievements');
        List<Training_Plan_Achievement__c> lTPlanAchievement = TestTrainingPlanData.createTrainingPlanAchievements(tplans, new List<Achievement__c>{lAchievements.get(0)});

        List<WorkBadgeDefinition> lWorkBadges = TestAchievementData.createWorkBadges(1);
        WorkBadgeDefinition wb = lWorkBadges.get(0);

        Achievement__c ach  = new Achievement__c(id = lAchievements.get(0).Id);
        /* ach.Work_Badge_Id__c = wb.Id;
        ach.Work_Badge_Image_URL__c = wb.ImageUrl;
        ach.Work_Badge_Giver__c = adminUsers.get(0).Id; */
        
        update ach;

        List<Training_Plan__c> tplan = [select id from Training_Plan__c];
        System.assertEquals(1,tplan.size());
        Id tplanId = tplan.get(0).Id;

        Set<Id> selectedUserIds = new Set<Id>();

        for(User u : lmsUsers){
            selectedUserIds.add(u.Id);
        }

        System.runAs(adminUsers.get(0)){
            LMSService.upsertAssignments(selectedUserIds,new Set<Id>{tplanId},null);
        }

        List<Learning_Assignment__c> assignments = [select id from Learning_Assignment__c where Training_Plan__c = :tplanId];
        System.assertEquals(1,assignments.size());
        return assignments.get(0).Id;

    }

    private static Integer getWorkBadgeCount(String userId){
        return  [select count() from WorkBadge where RecipientId = :userId];
    }

}