src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Through__c</fullName>
        <label>Valid Through</label>
        <type>Date</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Agreement</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>PA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectAgreementTriggerHandler_Test.cls
@isTest
public class ProjectAgreementTriggerHandler_Test{

    @isTest
    public static void preventOverlappingProjectAgreementsTest() {
    
        TestDataFactory factory = new TestDataFactory();
        
        List<Account> accountList = factory.generateAccounts(1);
        insert accountList;
        
        List<Agreement__c> agreementList = factory.generateRetainerAgreementsForAccounts(accountList, 2);
        agreementList[0].Valid_Through__c = System.Today();
        agreementList[0].Valid_Through__c = System.Today().addDays(10); 
        agreementList[1].Effective_Date__c = System.Today().addDays(2);
        agreementList[1].Valid_Through__c = System.Today().addDays(5); 
        insert agreementList;

        List<Project__c> projectList = factory.generateProjects(accountList[0].Id, 1);
        insert projectList;
        
        List<Project_Agreement__c> projectAgreementList = new List<Project_Agreement__c>();
        projectAgreementList.add(factory.generateProjectAgreements(projectList[0].Id, agreementList[0].Id));
        projectAgreementList.add(factory.generateProjectAgreements(projectList[0].Id, agreementList[0].Id));
        database.insert(projectAgreementList,false);
        
        projectAgreementList.clear();
        projectAgreementList.add(factory.generateProjectAgreements(projectList[0].Id, agreementList[1].Id));
        database.insert(projectAgreementList,false);

        //system.assertEquals([SELECT Id FROM project_agreement__c WHERE project__c =: projectList[0].Id].size(),1);
        
        projectAgreementList.clear();
        projectAgreementList.add(factory.generateProjectAgreements(projectList[0].Id, agreementList[0].Id));
        projectAgreementList.add(factory.generateProjectAgreements(projectList[0].Id, agreementList[1].Id));
        database.insert(projectAgreementList,false);
        
        //system.assertEquals([SELECT Id FROM project_agreement__c WHERE project__c =: projectList[0].Id].size(),1);
    }

}