src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_Through__c</fullName>
        <label>Valid Through</label>
        <type>Date</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <globalPicklist>Assignment_Type</globalPicklist>
        <label>Assignment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Billable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cost_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Assignments (Cost Rate)</relationshipLabel>
        <relationshipName>Assignments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_Hours__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Planned Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billable Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region used from global value set &apos;Region&apos;</description>
        <globalPicklist>Region</globalPicklist>
        <label>Region</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Expert</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <recordTypes>
        <fullName>Assignment</fullName>
        <active>true</active>
        <label>Assignment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Agreement</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>PA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <globalPicklist>Assignment_Type</globalPicklist>
        <label>Assignment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <globalPicklist>Region</globalPicklist>
        <label>Region</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_Through__c</fullName>
        <formula>IF(
  ISBLANK(Rate_Specific_Valid_Through__c),
  Agreement__r.Valid_Through__c,
  Rate_Specific_Valid_Through__c
)</formula>
        <label>Valid Through</label>
        <type>Date</type>
    </fields>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Assignment__r.Project__r.Name</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <formula>TEXT(Assignment__r.Role__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ManageCostRatesController.cls
public with sharing class ManageCostRatesController {

    public List<AssignmentWrapper> assignmentWrapperList {get; set;}
    public List<Agreement__c> agreementsList {get;set;}
    public String projectName {get; set;}
    public String selectedAgreementId {get; set;}
    public Integer selectedIndex {get; set;}
    private Set<Id> agreementIds;
    private List<Assignment__c> deletingAssignments;
    private List<Rate__c> availableRateList;
    private String projectId;
    private Integer indexNo;
    public Boolean isLightningExperience {get; set;}
    
    public ManageCostRatesController(ApexPages.StandardController std) {
        isLightningExperience = false;
        if(ApexPages.CurrentPage().GetParameters().get('sfdcIFrameOrigin') != null) {
            isLightningExperience = true;
        }
        
        assignmentWrapperList = new List<AssignmentWrapper>();
    
        agreementsList  = new List<Agreement__c>();    
        availableRateList = new List<Rate__c>();
        deletingAssignments = new List<Assignment__c>();
        agreementIds = new Set<Id>();

        projectName = '';
        indexNo = 0;
        
        //Fetch the Project Id from the URL, passed in when we arrive from the Manage Assignments button(s) on the Project
        projectId = apexpages.currentpage().getParameters().get('projectId');
        
        if(projectId == null) {
            //Handle the case in which we arrive from the Edit of an Assignment
            String assignmentId = ApexPages.CurrentPage().GetParameters().get('id');
            if(!String.isBlank(assignmentId)) {
                //getting project id
                for(Assignment__c assignmentObj : [SELECT Id, Project__c, Project__r.Name, Region__c 
                                   FROM Assignment__c 
                                   WHERE Id =: assignmentId
                                                   ORDER BY Status__c ASC]) {
                    projectId  = assignmentObj.Project__c;
                    projectName  = assignmentObj.Project__r.Name;
                }
            }
        }
        else {
          List<Project__c> projectList = [SELECT Id, Name FROM Project__c WHERE Id =: projectId];
          if(!projectList.isEmpty()) {
            projectName = projectList[0].Name;
          }
        }

        if(!String.isBlank(projectId)) {
            
            //fetching roles options
            for(Project_Agreement__c projectAgreement : [SELECT Id, Agreement__c 
                                                         FROM Project_Agreement__c 
                                                         WHERE Project__c =: projectId]) {
                agreementIds.add(projectAgreement.Agreement__c);
            }
            
            Set<String> roleSet = new Set<String>(); 
            Set<String> assignmentTypeSet = new Set<String>();
            for(Agreement__c agreement : [SELECT Id, Name, Status__c, RecordType.Id,Account__c,
                                                 (SELECT Id, Name, Agreement__c, Assignment_Type__c, Role__c, Region__c
                                                  FROM Rates__r) 
                                          FROM Agreement__c
                                          WHERE Id IN: agreementIds AND RecordTypeId =: Constants.RECORDTYPEID_AGREEMENT_DELIVERYPARTER
                                          ORDER BY Valid_Through__c DESC]) {
                 
                 //checking if multiple agreements are tied to the project
                 if(agreementIds.size() > 0) {
                    agreementsList.add(agreement);
                     //agreementOptions.add(new SelectOption(agreement.Id, agreement.Name  + ' (' + agreement.Status__c + ')'));
                 }
 
                 //fetching unique roles
                 for(Rate__c rateObj : agreement.Rates__r) {
                     availableRateList.add(rateObj);  
                 }   
            }
            
            if(!agreementIds.isEmpty()) {
            
                for(Assignment__c assignmentObj : [SELECT Id, Status__c, Resource__c, Resource__r.Name,Resource__r.AccountId, Role__c, Assignment_Type__c,
                                                          Planned_Hours__c, Billable__c, Rate__c,Cost_Rate__c,Cost_Rate__r.Agreement__c,
                                                          Cost_Rate__r.Name, Rate__r.Name, Rate__r.Agreement__c, Region__c, 
                                                          (SELECT Id 
                                                           FROM Time_Entries__r
                                                           LIMIT 5)
                                                   FROM Assignment__c
                                                   WHERE Project__c =: projectId]) {
                    
                    String agreementId = (assignmentObj.Cost_Rate__c != null) ? assignmentObj.Cost_Rate__r.Agreement__c : null;

                    assignmentWrapperList.add(new AssignmentWrapper(assignmentObj, ++indexNo, assignmentObj.Role__c, agreementId,this));
                    
                    //populating role according to selected agreement
                    selectedAgreementId = agreementId;
                    
                    selectedIndex = null;
                }
                
                
            }
            else {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Constants.ERROR_NO_PROJECT_AGREEMENTS));
            }   
        }
    }
    
    //populate role options
    public void agreementSelected() {
      //populating roles according to the agreement
      for(AssignmentWrapper wrapperObj : assignmentWrapperList) {
        if(selectedIndex == wrapperObj.index) {
          populateRateValue();
          break; 
        }
      }
    }


    public void populateRateValue() {
        String selectedRole;
        String selectedAssignmentType;
        String selectedRegion;
        if(selectedIndex != null) {
            for(AssignmentWrapper wrapperObj : assignmentWrapperList) {
                if(wrapperObj.index == selectedIndex) {
                    selectedRole = wrapperObj.assignmentObj.Role__c;
                    selectedRegion = wrapperObj.assignmentObj.Region__c;
                    wrapperObj.rateOptions = new List<SelectOption>();
                    wrapperObj.rateOptions.add(new SelectOption('','--None--'));
                    for(Rate__c rateObj : availableRateList) {
                        if(rateObj.Role__c == selectedRole && rateObj.Agreement__c == wrapperObj.selectedAgreementId && rateObj.Region__c == selectedRegion) {
                          wrapperObj.rateOptions.add(new SelectOption(rateObj.Id,rateObj.Name));
                        }
                    }
                    if(wrapperObj.rateOptions.size() == 2){
                      wrapperObj.assignmentObj.Cost_Rate__c = wrapperObj.rateOptions[1].getValue();
                    }
                    break;
                }   
            }
        }
    }

  //to save assignments
  public pagereference save() {

    List<Assignment__c> assignmentList = new List<Assignment__c>();

    for(AssignmentWrapper wrapperObj : assignmentWrapperList) {
      //checking for required fields
      if(wrapperObj.assignmentObj.Resource__c == null || wrapperObj.assignmentObj.Status__c == null || 
        wrapperObj.assignmentObj.Role__c == null ) {

        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,Constants.ERROR_REQUIRED_FIELDS);
        ApexPages.addMessage(myMsg);
        return null; 
      } 
      if( wrapperObj.assignmentObj.Cost_Rate__c == null){
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,Constants.ERROR_REQUIRED_COST_RATE_FIELDS);
        ApexPages.addMessage(myMsg);
        return null; 
      }
      assignmentList.add(wrapperObj.assignmentObj);
    }
       
    try{
      //upserting the assignments
      if(assignmentList.size() > 0) {
        upsert assignmentList;
      }

      //deleting the assignments that were removed FROM UI by user
      if(deletingAssignments.size() > 0) {
        delete deletingAssignments;
      }

    }
    catch(Exception exp) {
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, exp.getMessage()));
      return null; 
    }

    if(projectId != null) {
      if(Apexpages.currentPage().getParameters().get('isdtp') == 'mn') {
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm, 'Assignments have been saved successfully.'));
        return null;
      }
      else {
        return new PageReference('/' + projectId);
      }
    }
    else {
      return new PageReference('/' + Assignment__c.sObjectType.getDescribe().getKeyPrefix());  
    }
  }

    //To cancel and redirect
    public PageReference cancel() {
        if(projectId != null) {
            if(ApexPages.CurrentPage().getParameters().get('isdtp') == 'mn') {
                return new PageReference(ApexPages.CurrentPage().getUrl());
            }
            else {
                return new PageReference('/' + projectId);
            }
        }
        else{
            return new PageReference('/' + Assignment__c.sObjectType.getDescribe().getKeyPrefix());  
        }        
    }

    public class AssignmentWrapper {
        public Assignment__c assignmentObj {get; set;}
        public List<SelectOption> agreementOptions {get; set;}
        public List<SelectOption> rateOptions {get; set;}
        public String selectedAgreementId {get; set;}        
        public String agreementDisplayName {get; set;}
        public Integer index {get; set;}
        public Boolean hasTimeEntry {get; set;}
        
        public AssignmentWrapper(Assignment__c assignmentObj, Integer indx, String role,String agreementId ,ManageCostRatesController outerClass) {

            agreementOptions = new List<SelectOption>();
            agreementOptions.add(new Selectoption('','--None--'));
            selectedAgreementId = agreementId;
            hasTimeEntry = false;
            rateOptions = new List<SelectOption>();
            rateOptions.add(new SelectOption('','--None--'));
            //Check for existing Time Entries, so we know whether or not to render certain things as editable
            if(assignmentObj.Time_Entries__r != null && !assignmentObj.Time_Entries__r.isEmpty()) {
              hasTimeEntry = true;
            }
            this.assignmentObj = assignmentObj;
            index = indx;
            
            Id activeAgrementId;
            Integer count = 0;
            for(Agreement__c agreement: outerClass.agreementsList){
                if(assignmentObj.Resource__r.AccountId  == agreement.Account__c){
                    agreementOptions.add(new SelectOption(agreement.Id, agreement.Name  + ' (' + agreement.Status__c + ')'));
                }
                if(agreement.Status__c == 'Active' && agreementId == null){
                  activeAgrementId = agreement.id;
                  count++;
                }
            }
            
            if(agreementOptions.size() == 2){
                selectedAgreementId = agreementOptions[1].getValue();
            }
            else if(count == 1 && activeAgrementId != null && assignmentObj.Cost_Rate__c == null){
              selectedAgreementId = activeAgrementId;
            }

            for(Rate__c rateObj : outerClass.availableRateList) {
                if(rateObj.Role__c == assignmentObj.Role__c && rateObj.Agreement__c == selectedAgreementId) {
                  rateOptions.add(new SelectOption(rateObj.Id,rateObj.Name));
                }
            }
            
            if(rateOptions.size() == 2 && assignmentObj.Cost_Rate__c == null){
                assignmentObj.Cost_Rate__c= rateOptions[1].getValue();
            }
        }
    }
}