src/objects/Agreement__c.object
<CustomObject>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Agreement</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>PA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataFactory_ProjectAgreements.cls
public with sharing class TestDataFactory_ProjectAgreements {
	
	public static List<Project_Agreement__C> generateProjectAgreements(Id projecId, Id agreementId, Integer numOfRecords) {
		return generateProjectAgreementsInternal(projecId, agreementId, numOfRecords);
	}

	private static List<Project_Agreement__C> generateProjectAgreementsInternal(Id projecId, Id agreementId, Integer numOfRecords) {
		List<Project_Agreement__C> projectAgreementList = new List<Project_Agreement__C>();
		for(Integer i = 0; i < numOfRecords; i++) {
            Project_agreement__c prjAgreement = new Project_agreement__c();
        	prjAgreement.agreement__C = agreementId;
        	prjAgreement.project__C = projecId;
            projectAgreementList.add(prjAgreement); 
        } 
        
        return projectAgreementList;
	}
}