src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Contact you selected is not associated with the Account that is selected on this Agreement.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <infoMessage>These results have been filtered to show only Contacts for the Account selected on this Agreement.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Branding__c</fullName>
        <label>Invoice Branding</label>
        <picklist>
            <picklistValues>
                <fullName>10K Advisors</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Trekbin</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PO_Number__c</fullName>
        <label>PO Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <globalPicklist>Assignment_Type</globalPicklist>
        <label>Assignment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billable Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region used from global value set &apos;Region&apos;</description>
        <globalPicklist>Region</globalPicklist>
        <label>Region</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <recordTypes>
        <fullName>Assignment</fullName>
        <active>true</active>
        <label>Assignment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Agreement you selected is not associated with the Account that is selected on this Invoice.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Agreement__c.Account__c</valueField>
            </filterItems>
            <infoMessage>These results have been filtered to show only Agreements for the Account selected on this Invoice.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Period_End_Date__c</fullName>
        <label>Billing Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Period_Start_Date__c</fullName>
        <label>Billing Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO_Number__c</fullName>
        <label>PO Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sent_To_Customer_On__c</fullName>
        <label>Finalized On</label>
        <type>Date</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Billable_Hours_Total__c</fullName>
        <formula>IF(
  RecordType.DeveloperName != &apos;X10K_Goodwill_Invoice_Line_Item&apos;,
  Rate__r.Hourly_Rate__c * Hours__c,
  0.00
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billable Hours Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credit_Amount__c</fullName>
        <label>Credit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Goodwill_Amount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Goodwill Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate_Text__c</fullName>
        <formula>Rate__r.Hourly_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line_Item_Total__c</fullName>
        <formula>IF(
  RecordType.DeveloperName = &apos;X10K_Product_Invoice_Line_Item&apos;,
  Total_Price__c,
  IF(RecordType.DeveloperName = &apos;X10K_Credit_Invoice_Line_Item&apos;, 
  0  -  Credit_Amount__c , 
  IF(RecordType.DeveloperName = &apos;X10K_Expense_Invoice_Line_Item&apos;, 
   Expense_Amount__c ,
  IF(    
    AND(
      NOT(ISBLANK(Goodwill_Amount__c)),
      Goodwill_Amount__c &gt; 0
    ),
    Goodwill_Amount__c * -1,
    IF(
      OR(
        ISBLANK(Manual_Line_Item_Total_Override__c),
        ISNULL(Manual_Line_Item_Total_Override__c)
      ),
      MAX(
        Minimum_Commitment__c,
        Billable_Hours_Total__c
      ),
      Manual_Line_Item_Total_Override__c
    )
   )
  )
 )
)</formula>
        <label>Line Item Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Rate_Text__c</fullName>
        <formula>Rate__r.Monthly_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Monthly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Named_Resource__c</fullName>
        <formula>CONTAINS(Rate__r.Name, &apos;Named Resource&apos;)</formula>
        <label>Named Resource?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trimmed_Rate_Name__c</fullName>
        <formula>TRIM(LEFT(Rate__r.Name, FIND(&quot;-&quot;, Rate__r.Name))) + &quot; &quot; + 
TRIM(LEFT(RIGHT(Rate__r.Name, LEN(Rate__r.Name)-FIND(&quot;-&quot;, Rate__r.Name)), FIND(&quot;-&quot;, RIGHT(Rate__r.Name, LEN(Rate__r.Name)-FIND(&quot;-&quot;, Rate__r.Name)))-2))</formula>
        <label>Trimmed Rate Name</label>
        <type>Text</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <globalPicklist>Assignment_Type</globalPicklist>
        <label>Assignment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <globalPicklist>Region</globalPicklist>
        <label>Region</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Rate__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <globalPicklist>Assignment_Type</globalPicklist>
        <label>Assignment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Rate__c</fullName>
        <label>Monthly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <globalPicklist>Region</globalPicklist>
        <label>Region</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <formula>Assignment__r.Rate__r.Hourly_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hourly Billable Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <formula>TEXT(Assignment__r.Role__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GenerateInvoicePDFController.cls
public without sharing class GenerateInvoicePDFController {

    public List<Invoice_Line_Item__c> invoiceLineItemList{get;set;} 
    
    public Boolean displaySection {get; set;}
    public Boolean isProductInvoice {get; set;}

    private String invoiceId;
    
    public List<LightningReportGenerationController.ProjectWrapper> allData {get; set;}
    public Map<String,Invoice_Line_Item__c> invoiceLineItemMap {get;set;}

    public String strConcatenatedProjectNames;
    public String strDisplayProjectNames {get;set;}
    public String strBillableStartDate {get;set;}
    public String strBillableEndDate {get;set;}
    
    public String accountName {get;set;} 
    public String addressLine1 {get;set;} 
    public String addressLine2 {get;set;} 
    public String addressLine3 {get;set;} 
    public date billingPeriodForRegion {get;set;}
    
    
    public GenerateInvoicePDFController(ApexPages.StandardController controller) {
        
        system.debug(LoggingLevel.INFO, 'Entering the GenerateInvoicePDFController constructor!');
        billingPeriodForRegion = Date.newInstance(2018,03,01);
        displaySection = false;
        invoiceLineItemMap = new Map<String,Invoice_Line_Item__c>();
        invoiceId = ApexPages.currentPage().getParameters().get('Id');
        String invoiceName = ((Invoice__c)controller.getRecord()).Name; 
        
        strBillableStartDate = String.valueOf(((Invoice__c)controller.getRecord()).Billing_Period_Start_Date__c);
        strBillableEndDate = String.valueOf(((Invoice__c)controller.getRecord()).Billing_Period_End_Date__c);
        
        List<Invoice__c> invoiceList = [SELECT Id, RecordTypeId, Agreement__c, Account__r.BillingStreet, Account__r.BillingCity, Account__r.Name, 
                                               Account__r.BillingState, Account__r.BillingPostalCode, Account__r.BillingCountry, Due_Date__c, 
                                               Sent_To_Customer_On__c, Billing_Period_Start_Date__c, Billing_Period_End_Date__c,
                                               Agreement__r.Invoice_Branding__c
                                        FROM Invoice__c 
                                        WHERE Id =: invoiceId];
        
        isProductInvoice = false;

        if(invoiceList != null && !invoiceList.isEmpty()) {
            
            accountName = invoiceList[0].Account__r.Name;

            addressLine1 = !String.isBlank(invoiceList[0].Account__r.BillingStreet) ? ' ' + invoiceList[0].Account__r.BillingStreet : '';
            
            addressLine2 = !String.isBlank(invoiceList[0].Account__r.BillingCity) ? invoiceList[0].Account__r.BillingCity : '';
            addressLine2 += !String.isBlank(invoiceList[0].Account__r.BillingState) ? '  ' + invoiceList[0].Account__r.BillingState : '';
            addressLine2 +=!String.isBlank(invoiceList[0].Account__r.BillingPostalCode ) ? '  ' + invoiceList[0].Account__r.BillingPostalCode : '';
            
            addressLine3 = !String.isBlank(invoiceList[0].Account__r.BillingCountry) ? invoiceList[0].Account__r.BillingCountry : '';

            if(invoiceList[0].RecordTypeId == Constants.RECORDTYPEID_INVOICE_10KPRODUCTINVOICE) {
                isProductInvoice = true;
            }
        }
        
        strConcatenatedProjectNames = '';
        strDisplayProjectNames = '';
        
        //Extract all non-Goodwill Invoice Line Items.
        invoiceLineItemList = [SELECT Id, Name, Rate__r.Role__c,Rate__r.Assignment_Type__c,Rate__r.Region__c,Rate__r.Hourly_Rate__c, Hours__c, Line_Item_Total__c, Hourly_Rate_Text__c, 
                                      Billable_Hours_Total__c, Rate__r.Name, Rate__r.Monthly_Rate__c, Monthly_Rate_Text__c, Named_Resource__c, 
                                      Trimmed_Rate_Name__c, Goodwill_Amount__c, Invoice__r.Name, Invoice__r.PO_Number__c, Credit_Amount__c, 
                                      Invoice__r.Billing_Period_Start_Date__c, Invoice__r.Billing_Period_End_Date__c, RecordType.Name, 
                                      Invoice__r.Account__r.Name, Invoice__r.Agreement__r.Billing_Contact__r.Name, Product__c,
                                      Invoice__r.Account__r.BillingStreet, Invoice__r.Account__r.BillingCity, Product__r.Name,
                                      Invoice__r.Account__r.BillingPostalCode, Invoice__r.Account__r.BillingCountry, Expense_Amount__c, 
                                      Expert_Names__c, Invoice__r.Invoice_Generated_On__c, Invoice__r.Account__r.BillingState, Description__c, 
                                      Invoice__r.Expert_Names__c, Invoice__r.Sent_To_Customer_On__c, RecordTypeId, Sales_Price__c, Discount__c  
                               FROM Invoice_Line_Item__c
                               WHERE Invoice__c =: invoiceId
                                   AND (Goodwill_Amount__c = null
                                      OR Goodwill_Amount__c = 0) 
                                  AND RecordTypeId != : Constants.RECORDTYPEID_INVOICE_10KCREDITINVOICELINEITEM 
                                  AND RecordTypeId != : Constants.RECORDTYPEID_INVOICE_10KEXPENSEINVOICELINEITEM 
                               ORDER BY Rate__r.Name ASC,
                                        Line_Item_Total__c DESC];

    system.debug(invoiceLineItemList.size());

    //Add the Goodwill Invoice Line Items to the end of the list
    invoiceLineItemList.addAll([SELECT Id, Name, Rate__r.Role__c,Rate__r.Assignment_Type__c,Rate__r.Region__c,Rate__r.Hourly_Rate__c, Hours__c, Line_Item_Total__c, Hourly_Rate_Text__c, 
                                         Billable_Hours_Total__c,  Rate__r.Name, Rate__r.Monthly_Rate__c, Monthly_Rate_Text__c, Named_Resource__c, 
                                         Trimmed_Rate_Name__c, Goodwill_Amount__c, Invoice__r.Name, Invoice__r.PO_Number__c,
                                         Invoice__r.Billing_Period_Start_Date__c, Invoice__r.Billing_Period_End_Date__c, Credit_Amount__c, 
                                         Invoice__r.Account__r.Name, Invoice__r.Agreement__r.Billing_Contact__r.Name, RecordType.Name, 
                                         Invoice__r.Account__r.BillingStreet, Invoice__r.Sent_To_Customer_On__c, Invoice__r.Account__r.BillingCity, 
                                         Invoice__r.Account__r.BillingPostalCode, Invoice__r.Account__r.BillingCountry, Description__c, 
                                         Expert_Names__c, Invoice__r.Invoice_Generated_On__c, Invoice__r.Account__r.BillingState,
                                         Invoice__r.Expert_Names__c,RecordTypeId, Sales_Price__c, Discount__c, Expense_Amount__c 
                                    FROM Invoice_Line_Item__c
                                    WHERE Invoice__c =: invoiceId
                                      AND (Goodwill_Amount__c != null
                                           AND Goodwill_Amount__c != 0) 
                                      AND RecordTypeId != : Constants.RECORDTYPEID_INVOICE_10KCREDITINVOICELINEITEM 
                                      AND RecordTypeId != : Constants.RECORDTYPEID_INVOICE_10KEXPENSEINVOICELINEITEM 
                                  ORDER BY Rate__r.Name ASC,
                                           Line_Item_Total__c DESC]);
      
      system.debug(invoiceLineItemList.size());

      //Add the Expense Invoice Line Items to the end of the list
    invoiceLineItemList.addAll([SELECT Id, Name, Rate__r.Role__c,Rate__r.Assignment_Type__c,Rate__r.Region__c,Rate__r.Hourly_Rate__c, Hours__c, Line_Item_Total__c, Hourly_Rate_Text__c, 
                                         Billable_Hours_Total__c,  Rate__r.Name, Rate__r.Monthly_Rate__c, Monthly_Rate_Text__c, Named_Resource__c, 
                                         Trimmed_Rate_Name__c, Goodwill_Amount__c, Invoice__r.Name, Invoice__r.PO_Number__c,
                                         Invoice__r.Billing_Period_Start_Date__c, Invoice__r.Billing_Period_End_Date__c, Credit_Amount__c, 
                                         Invoice__r.Account__r.Name, Invoice__r.Agreement__r.Billing_Contact__r.Name, RecordType.Name, 
                                         Invoice__r.Account__r.BillingStreet, Invoice__r.Sent_To_Customer_On__c, Invoice__r.Account__r.BillingCity, 
                                         Invoice__r.Account__r.BillingPostalCode, Invoice__r.Account__r.BillingCountry, Description__c, 
                                         Expert_Names__c, Invoice__r.Invoice_Generated_On__c, Invoice__r.Account__r.BillingState,
                                         Invoice__r.Expert_Names__c,RecordTypeId, Sales_Price__c, Discount__c, Expense_Amount__c 
                                    FROM Invoice_Line_Item__c
                                    WHERE Invoice__c =: invoiceId
                                      AND (Expense_Amount__c  != null
                                           AND Expense_Amount__c  != 0) 
                                      AND RecordTypeId != : Constants.RECORDTYPEID_INVOICE_10KCREDITINVOICELINEITEM
                                  ORDER BY Rate__r.Name ASC,
                                           Line_Item_Total__c DESC]);
      
      system.debug(invoiceLineItemList.size());

      //Add the Credit Invoice Line Items to the end of the list
    invoiceLineItemList.addAll([SELECT Id, Name, Rate__r.Role__c,Rate__r.Assignment_Type__c,Rate__r.Region__c,Rate__r.Hourly_Rate__c, Hours__c, Line_Item_Total__c, Hourly_Rate_Text__c, 
                                         Billable_Hours_Total__c,  Rate__r.Name, Rate__r.Monthly_Rate__c, Monthly_Rate_Text__c, Named_Resource__c, 
                                         Trimmed_Rate_Name__c, Goodwill_Amount__c, Invoice__r.Name, Invoice__r.PO_Number__c,
                                         Invoice__r.Billing_Period_Start_Date__c, Invoice__r.Billing_Period_End_Date__c, Credit_Amount__c, 
                                         Invoice__r.Account__r.Name, Invoice__r.Agreement__r.Billing_Contact__r.Name, RecordType.Name, 
                                         Invoice__r.Account__r.BillingStreet, Invoice__r.Sent_To_Customer_On__c, Invoice__r.Account__r.BillingCity, 
                                         Invoice__r.Account__r.BillingPostalCode, Invoice__r.Account__r.BillingCountry, Description__c, 
                                         Expert_Names__c, Invoice__r.Invoice_Generated_On__c, Invoice__r.Account__r.BillingState,
                                         Invoice__r.Expert_Names__c,RecordTypeId, Sales_Price__c, Discount__c, Expense_Amount__c
                                    FROM Invoice_Line_Item__c
                                    WHERE Invoice__c =: invoiceId
                                      AND (Credit_Amount__c  != null
                                           AND Credit_Amount__c  != 0) 
                                      AND RecordTypeId != : Constants.RECORDTYPEID_INVOICE_10KEXPENSEINVOICELINEITEM
                                  ORDER BY Rate__r.Name ASC,
                                           Line_Item_Total__c DESC]);
      
      system.debug(invoiceLineItemList.size());
      System.debug(invoiceId+'==='+strBillableStartDate+'==='+strBillableEndDate);
      
        /* Created by Trekbin on 19-Aug, 2016 as per the requirement on Task T-0006 [R] */
        //Check if the invoiceId, Billable Period Start Date, Billable Period End Date contains some value, if so then proceed  [R]
        if((invoiceId != null && invoiceId != '') && (strBillableStartDate != null && strBillableStartDate != '') && (strBillableEndDate != null && strBillableEndDate != '')){
            
            //Declare a set to hold the Project names of the TimeEntry records  [R]
            set<String> setProjectNamesToDisplay = new set<String>();
            
            //Iterate over all the TimeEntry records pertaining to that Invoice records in order to fetch project details   [R]
            for(Time_Entry__c objTimeEntry : [Select Id, Name, Assignment__c, Assignment__r.Project__c, Assignment__r.Project__r.Name, Invoice__c From Time_Entry__c Where Invoice__c = :invoiceId]) {
                
                //Proceed if the Time_Entry__c record contains any assignment related project   [R]
                if(objTimeEntry.Assignment__r.Project__c != null) { 
                
                    //Add the Project names pertaining to TimeEntry's  Assignment record into a set [R]
                    setProjectNamesToDisplay.add(objTimeEntry.Assignment__r.Project__r.Name);
                }
            }
            
            //If the set formed above contains any value then proceed   [R]
            if(!setProjectNamesToDisplay.isEmpty()) {
                
                //Set the displaySection to true if time entry records persists
                displaySection = true;
                System.debug(setProjectNamesToDisplay);
                //Iterate over all the project Names from the set and prepare a concatenated string [R]
                for(String strProjectName : setProjectNamesToDisplay) {
                    
                    //Hold the project Names in a string    [R]
                    System.debug(strProjectName);
                    strConcatenatedProjectNames += strProjectName+'#';
                }
                
                //Bind the concatenated string to the page after removing last comma    [R]
                strDisplayProjectNames = strConcatenatedProjectNames.removeEnd('#');
                System.debug(strDisplayProjectNames+'=============='+strConcatenatedProjectNames);
                //Check if the strConcatenatedProjectNames contains any value then proceed  [R]
                if(strConcatenatedProjectNames != null && strConcatenatedProjectNames != '') {  
                    LightningReportGenerationController.invoiceId = invoiceId;
                    //Pass the parameteres to 'LightningReportGenerationController' controller  [R]
                    allData = LightningReportGenerationController.getDefaultValues(strBillableStartDate, strBillableEndDate, strDisplayProjectNames,null);  
                }
            }
        }   
            
      if(invoiceName !=null) {
          ApexPages.currentPage().getHeaders().put('content-disposition', 'inline; filename='+invoiceName+'.pdf');
      }
    }
}