src/objects/Agreement__c.object
<CustomObject>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <globalPicklist>Assignment_Type</globalPicklist>
        <label>Assignment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataFactory_Rates.cls
public with sharing class TestDataFactory_Rates {
    
    public static List<Rate__c> generateRateForAgreement(Id agreementId, String assignmentType, String role, Decimal hourlyRate, Integer numOfRecords) {
		return generateRateForAgreementInternal(agreementId, assignmentType, role, hourlyRate, numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Rate__c> generateRateForAgreementInternal(Id agreementId, String assignmentType, String role, Decimal hourlyRate, Integer numOfRecords) {
    	List<Rate__c> rateList = new List<Rate__c>();
        
        for(integer i = 0; i < numOfRecords ; i ++) {
            Rate__c rate = new Rate__c();
            rate.Name = 'Test Rate' + i;
            if(assignmentType == Constants.ASSIGNMENTTYPE_NAMEDRESOURCE) {
                rate.RecordTypeId = Constants.RECORDTYPEID_RATE_NAMED_RESOURCE;
            }
            else if(assignmentType == Constants.ASSIGNMENTTYPE_RETAINEDCAPACITY) {
                rate.RecordTypeId = Constants.RECORDTYPEID_RATE_RETAINED_CAPACITY;
            }
            else if(assignmentType == Constants.ASSIGNMENTTYPE_TIMEANDMATERIALS) {
                rate.RecordTypeId = Constants.RECORDTYPEID_RATE_TIMEANDMATERIALS;
            }
            rate.Agreement__c = agreementId;
            rate.Assignment_Type__c = assignmentType;
            rate.Role__c = role;
            rate.Hourly_Rate__c = hourlyRate;
            rateList.add(rate);
        }
        
        return rateList ;
    }
}