src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Opportunity you selected is not associated with the Account that is selected on this Agreement.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.AccountId</valueField>
            </filterItems>
            <infoMessage>These results have been filtered to show only Opportunities for the Account selected on this Agreement.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid_Through__c</fullName>
        <label>Valid Through</label>
        <type>Date</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>MSA</fullName>
        <active>true</active>
        <description>An MSA outlines the terms and hourly rates at which we work with a particular client, but does not define any particular scope of work.</description>
        <label>MSA</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MSA_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MSA Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>MSA Opportunity</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Opportunity does not belong to the selected Account. Please select another Opportunity.</errorMessage>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <infoMessage>Only Opportunities for the selected Account are shown.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Project_Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Agreement</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>PA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AgreementTriggerHandler_Test.cls
@isTest
public class AgreementTriggerHandler_Test {

    @isTest
    public static void preventOverlappingAgreementsTest() {
    
        TestDataFactory factory = new TestDataFactory();
        
        List<Account> accountList = factory.generateAccounts(1);
        insert accountList;
        
        List<Agreement__c> agreementList = factory.generateRetainerAgreementsForAccounts(accountList, 2);
        agreementList[0].Effective_Date__c = System.Today().addDays(-5);
        agreementList[0].Valid_Through__c = System.Today().addDays(-1); 
        agreementList[1].Effective_Date__c = System.Today();
        agreementList[1].Valid_Through__c = System.Today().addDays(5); 
        insert agreementList;

        List<Opportunity> oppList =TestDataFactory_Opportunity.generateOpportunities(accountList[0].Id, Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('MSA Opportunity').getRecordTypeId(), 'Qualification', Date.today().addDays(6), Date.today(), Date.today().addDays(4), 1);
        insert oppList ;

        List<Opportunity> oppList_two =TestDataFactory_Opportunity.generateOpportunities(accountList[0].Id, Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Services Opportunity').getRecordTypeId(), 'Qualification', Date.today().addDays(6), Date.today(), Date.today().addDays(4), 1);
        oppList_two[0].MSA_Opportunity__c = oppList[0].Id ;
        insert oppList_two ;

        List<Agreement__c> agreementList_two = TestDataFactory_Agreements.generateAgreements('Test Agreement', accountList[0].Id, Schema.SObjectType.Agreement__c.getRecordTypeInfosByName().get('MSA').getRecordTypeId(), 'Active', Date.today(), Date.today().addDays(6), 1);
        agreementList_two[0].Opportunity__c = oppList[0].Id ;
        insert agreementList_two;

        List<Project__c> projectList = factory.generateProjects(accountList[0].Id, 1);
        insert projectList;
        
        List<Project_Agreement__c> projectAgreementList = new List<Project_Agreement__c>();
        projectAgreementList.add(factory.generateProjectAgreements(projectList[0].Id, agreementList[0].Id));
        projectAgreementList.add(factory.generateProjectAgreements(projectList[0].Id, agreementList[1].Id));
        insert projectAgreementList;

        /*Test.startTest();
        agreementList[0].Effective_Date__c = System.Today();
        agreementList[0].Valid_Through__c = System.Today().addDays(10);
        database.update(agreementList, false);
        Test.stopTest();

        system.assert([SELECT Id, Effective_Date__c FROM Agreement__c WHERE Id =: agreementList[0].Id].Effective_Date__c != system.today()); */
    }

}