src/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Resource_Name__c</fullName>
        <formula>Resource__r.FirstName + &apos; &apos; + Resource__r.LastName</formula>
        <label>Expert Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Expert</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <recordTypes>
        <fullName>Assignment</fullName>
        <active>true</active>
        <label>Assignment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Status_Report__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Status Reports</relationshipLabel>
        <relationshipName>Status_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Status Report</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Status Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>Assignment__r.End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Assignment__r.Project__r.Name</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resource_Name__c</fullName>
        <formula>Assignment__r.Resource__r.FirstName + &quot; &quot; + Assignment__r.Resource__r.LastName</formula>
        <label>Expert Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <formula>Assignment__r.Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StatusReportChartController.cls
public with sharing class StatusReportChartController 
{	
	private Id statusReportId;
	private Status_Report__c statusReport;
	private Id projectId;
	public String xAxis {get; Set;}
	private static List<Project__c> projectList;
    private static Date startDate;
    private static Date endDate;
	public StatusReportChartController(ApexPages.StandardController controller)
	{
		statusReportId = (Id)controller.getId();
		statusReport = [SELECT Id, Start_Date__c, End_Date__c, Project__c 
						FROM Status_Report__c 
						WHERE Id =: statusReportId];

        startDate = statusReport.Start_Date__c;
        endDate = statusReport.End_Date__c;

		xAxis = 'From '+statusReport.Start_Date__c.format()+' to '+statusReport.End_Date__c.format();
		projectId = statusReport.Project__c;
		projectList = [SELECT Id,
							(SELECT Id   
							FROM Assignments__r) 
						FROM Project__c 
						WHERE Id =: projectId];
	}
    // Return a list of data points for a chart
    public List<Data> getData() 
    {
        return StatusReportChartController.getChartData();
    }
    
    public static List<Data> getChartData() 
    {
    	Map<String,Decimal> resourceHoursMap = new Map<String,Decimal>();
    	Map<String,String> resourceNameMap = new Map<String,String>();
        List<Data> data = new List<Data>();
        Set<Id> assignmentIdSet = new Set<Id>();

        if(projectList.size() > 0)
        {
        	for(Assignment__c assign : projectList[0].Assignments__r)
        	{
                assignmentIdSet.add(assign.Id);
        	}
        }

        List<Assignment__c> assignmentList = [SELECT Id, Resource__c, Resource_Name__c, 
                                                (SELECT Id, Hours__c 
                                                    FROM Time_Entries__r 
                                                    WHERE Date__c >=: startDate 
                                                    AND Date__c <=: endDate) 
                                                FROM Assignment__c 
                                                WHERE Id 
                                                IN : assignmentIdSet];

        if(!assignmentList.isEmpty())
        {
            for(Assignment__c assignment : assignmentList)
            {
                for(Time_Entry__c timeentry : assignment.Time_Entries__r)
                {
                    if(resourceHoursMap.keySet().contains(assignment.Resource__c)){
                    resourceHoursMap.put(assignment.Resource__c,resourceHoursMap.get(assignment.Resource__c) + timeentry.Hours__c);
                    }
                    else{
                        resourceHoursMap.put(assignment.Resource__c,timeentry.Hours__c);
                        resourceNameMap.put(assignment.Resource__c,assignment.Resource_Name__c);
                    }
                }
            }
        }
        for(String resource: resourceHoursMap.keySet()){
        	data.add(new Data(resourceNameMap.get(resource), resourceHoursMap.get(resource)));
        }
        
        return data;
    }
    
    // Wrapper class
    public class Data 
    {
        public String name { get; set; }
        public Decimal hours { get; set; }
        public Data(String name, Decimal hours) 
        {
            this.name = name;
            this.hours = hours;
        }
    }
}