src/objects/Assignment__c.object
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Availability__c.object
<CustomObject>
    <fields>
        <fullName>Available_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Available Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Forecasted_Hours__c</fullName>
        <label>Forecasted Hours</label>
        <summarizedField>Budget__c.Forecasted_Hours__c</summarizedField>
        <summaryForeignKey>Budget__c.Availability__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Hours_Worked__c</fullName>
        <label>Hours Worked</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Week</label>
        <referenceTo>Week__c</referenceTo>
        <relationshipLabel>Availability</relationshipLabel>
        <relationshipName>Availability</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Availability</label>
    <nameField>
        <displayFormat>AVAIL-{0000}</displayFormat>
        <label>Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Availability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Budget</relationshipLabel>
        <relationshipName>Budget</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Availability__c</fullName>
        <label>Availability</label>
        <referenceTo>Availability__c</referenceTo>
        <relationshipLabel>Budget</relationshipLabel>
        <relationshipName>Budget</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Forecasted_Hours__c</fullName>
        <label>Assigned Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours_Worked__c</fullName>
        <label>Hours Worked</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Week</label>
        <referenceTo>Week__c</referenceTo>
        <relationshipLabel>Budget</relationshipLabel>
        <relationshipName>Budget</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <displayFormat>BUD-{0000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Week__c.object
<CustomObject>
    <fields>
        <fullName>Week_Ends_On__c</fullName>
        <label>Week Ends On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Week_Starts_On__c</fullName>
        <label>Week Starts On</label>
        <type>Date</type>
    </fields>
    <label>Week</label>
    <nameField>
        <label>Week Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weeks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BudgetTriggerHandler.cls
public without sharing class BudgetTriggerHandler {
	
    public static void updateTimeEntries(List<Budget__c> budgetList ) {
        budgetList = [SELECT Id,Assignment__c,Week__c,Week__r.Week_Ends_on__c,Week__r.Week_Starts_on__c 
                        FROM Budget__c WHERE Id IN : budgetList];
        Set<Id> weekIdSet = new Set<Id>();
        Set<Id> assignmentIdSet = new Set<Id>();
        Set<Date> dateSet = new Set<Date>();
        Map<String,Id> assignmentAndBudgetMap = new Map<String,Id>();
        for(Budget__c budget : budgetList) {
            if(budget.Week__c != null && budget.Assignment__c != null) {
                assignmentIdSet.add(budget.Assignment__c);  
                weekIdSet.add(budget.Week__c); 
                for(Date dateVar = budget.Week__r.Week_Starts_on__c ; dateVar <= budget.Week__r.Week_Ends_on__c ; dateVar += 1) {
                    dateSet.add(dateVar);
                    assignmentAndBudgetMap.put(budget.Assignment__c + '' + dateVar,budget.Id);
                }        
            }
        }

        List<Time_Entry__c> timeEntryList = new List<Time_Entry__c>();
        /*Change by A.S remove budget null condition check*/
        /*[SELECT Id, Budget__c,Date__c,Assignment__c FROM Time_Entry__c WHERE Date__c IN: dateSet AND Assignment__c IN : assignmentIdSet AND Budget__c != null]*/
        for(Time_Entry__c timeEntry: [SELECT Id, Budget__c,Date__c,Assignment__c FROM Time_Entry__c WHERE Date__c IN: dateSet AND Assignment__c IN : assignmentIdSet]) {
            if(assignmentAndBudgetMap.containsKey(timeEntry.Assignment__c  + '' +  timeEntry.Date__c)) {
                timeEntry.Budget__c = assignmentAndBudgetMap.get(timeEntry.Assignment__c  + '' +  timeEntry.Date__c);
                timeEntryList.add(timeEntry);
            }
        }
        if(timeEntryList.size() > 0)
            update timeEntryList;
    }

	/*public static void updateAvailabilityHours(List<Budget__c> budgetList , Boolean isNew) {
        Set<Id> weekIdSet = new Set<Id>();
        Set<Id> availabilityIdSet = new Set<Id>();
        for(Budget__c item : budgetList) {
            if(item.Week__c != null && isNew) {
                weekIdSet.add(item.Week__c);        
            }
            else if(item.Week__c != null && !isNew) {
                if(((Budget__c)Trigger.oldMap.get(item.Id)).Week__c != item.Week__c || ((Budget__c)Trigger.oldMap.get(item.Id)).Forecasted_Hours__c != item.Forecasted_Hours__c || ((Budget__c)Trigger.oldMap.get(item.Id)).Hours_Worked__c != item.Hours_Worked__c) 
                    weekIdSet.add(item.Week__c);        
            }
            if(item.Availability__c != null && isNew) {
                availabilityIdSet.add(item.Availability__c);        
            }
            else if(item.Availability__c != null && !isNew) {
                if(((Budget__c)Trigger.oldMap.get(item.Id)).Availability__c != item.Availability__c || ((Budget__c)Trigger.oldMap.get(item.Id)).Forecasted_Hours__c != item.Forecasted_Hours__c || ((Budget__c)Trigger.oldMap.get(item.Id)).Hours_Worked__c != item.Hours_Worked__c) 
                    availabilityIdSet.add(item.Availability__c);        
            }
        }
        if(weekIdSet.size() > 0 && availabilityIdSet.size() > 0) {
        	updateAvailability(weekIdSet ,availabilityIdSet);
        }
    }

    public static void updateAvailability(Set<Id> weekIdSet , Set<Id> availabilityIdSet) {
        
    	List<Availability__c> updateAvailabilityList = new List<Availability__c>();    	
    	Map<String,HoursWrapper> weekHourNewMap = new Map<String,HoursWrapper>();
    	if(weekIdSet.size() > 0 && availabilityIdSet.size() > 0){	
    		for(Budget__c budget : [SELECT Name , Forecasted_Hours__c, Hours_Worked__c ,Week__c,Availability__c FROM Budget__c WHERE Week__c IN : weekIdSet AND Availability__c IN : availabilityIdSet]) {				
					if(!weekHourNewMap.containsKey(budget.Availability__c + '-' + budget.Week__c )) 
						weekHourNewMap.put(budget.Availability__c + '-' + budget.Week__c,new HoursWrapper(0,0));
					
					Decimal hoursWorked = weekHourNewMap.get(budget.Availability__c + '-' + budget.Week__c).hoursWorked + (budget.Hours_Worked__c != null ? budget.Hours_Worked__c > 0 ? budget.Hours_Worked__c : 0 : 0);
					Decimal availableHours = weekHourNewMap.get(budget.Availability__c + '-' + budget.Week__c).availableHours + (budget.Forecasted_Hours__c != null ? budget.Forecasted_Hours__c > 0 ? budget.Forecasted_Hours__c : 0 : 0);
					weekHourNewMap.put(budget.Availability__c + '-' + budget.Week__c,new HoursWrapper(hoursWorked,availableHours));
            } 

			for(Availability__c avalibility : [SELECT Name , Available_Hours__c, Hours_Worked__c ,Week__c FROM Availability__c WHERE Week__c IN : weekIdSet AND Id IN : availabilityIdSet]) {					
				if(weekHourNewMap.containsKey(avalibility.Id + '-' + avalibility.Week__c)) {
					avalibility.Available_Hours__c = weekHourNewMap.get(avalibility.Id + '-' + avalibility.Week__c).availableHours;
					avalibility.Hours_Worked__c = weekHourNewMap.get(avalibility.Id + '-' + avalibility.Week__c).hoursWorked;
					updateAvailabilityList.add(avalibility);	
				}	
			}			
		}
		if(updateAvailabilityList.size() > 0){
			update updateAvailabilityList;
		}
    }

    public class HoursWrapper {
    	public Decimal hoursWorked;
    	public Decimal availableHours;

    	public HoursWrapper(Decimal hoursWorked,Decimal availableHours) {
    		this.hoursWorked = hoursWorked;
    		this.availableHours = availableHours;
    	}
    }*/
}