src/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recalculate_Sharing_on_Save__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recalculate Sharing on Save</label>
        <type>Checkbox</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <recordTypes>
        <fullName>Assignment</fullName>
        <active>true</active>
        <label>Assignment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Recalculate_Sharing_on_Save__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recalculate Sharing on Save</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Request__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recalculate_Sharing_on_Save__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recalculate Sharing on Save</label>
        <type>Checkbox</type>
    </fields>
    <label>Work Request</label>
    <nameField>
        <label>Work Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RecalculateSharingController.cls
public without sharing class RecalculateSharingController implements Queueable{

    set<Id> projectIds;
    set<Id> assignmentIds;
    set<Id> userIds;
    set<Id> setProjectRequestIDs;
    
    public RecalculateSharingController (set<Id> projectids,set<Id> assignmentIds,set<Id> userIds, set<Id> setProjectRequestIDs) {
        this.projectIds =  projectids;
        this.assignmentIds =  assignmentIds;
        this.userIds = userIds;
        this.setProjectRequestIDs = setProjectRequestIDs;
    }

    public void execute(QueueableContext context) {

        if(userIds !=null && userIds.size()>0){
            //queueable to sync portal user to contact
            system.debug('queueing job for contact case---->');
            System.enqueueJob(new SyncPortalUserToContactController (userIds));
        }

        if(projectIds != null && projectIds.size()>0){
        
            List<Project__c> projectList = new List<Project__c>();
            for(Project__c projectObj : [select id,name, Recalculate_Sharing_on_Save__c from project__c where id in :projectIds]){           
                
                projectObj.Recalculate_Sharing_on_Save__c = true;
                projectList.add(projectObj); 
            } 
            if(projectList.size()>0){   
                try{
                    system.debug('---> list to in queue update' + projectList);
                    if(!Test.isRunningTest())
                        update projectList;
                }catch(Exception exp){
                    system.debug('Exception caught qqqqqqq--->' + exp.getMessage());
                }
            }  
        }
        
        if(assignmentIds != null && assignmentIds.size()>0){    
            //setting checkbox to 'True'
            List<Assignment__c> assignmentList = new List<Assignment__c>();
            for(Assignment__c assignmentObj : [select id, Recalculate_Sharing_on_Save__c from assignment__c where id in :assignmentIds]){           
                assignmentObj.Recalculate_Sharing_on_Save__c = true;
                assignmentList.add(assignmentObj); 
            } 
            if(assignmentList.size()>0){   
                try{
                    system.debug('---> assignment list to update' + assignmentList);
                    if(!Test.isRunningTest())
                        update assignmentList;
                }catch(Exception exp){
                    system.debug('Exception caught ---->' + exp.getMessage());
                }
            }  
         }     
         
		if(setProjectRequestIDs != null && setProjectRequestIDs.size() > 0) {
    
			List<Project_Request__c> lstProjectRequestRecordsToUpdate = new List<Project_Request__c>();
	
			for(Project_Request__c objProjectRequest : [Select Id, Recalculate_Sharing_on_Save__c From Project_Request__c where Id IN :setProjectRequestIDs]){           
				
				Project_Request__c objProjectRequestToUpdate = new Project_Request__c(Id = objProjectRequest.Id, Recalculate_Sharing_on_Save__c = true);
				lstProjectRequestRecordsToUpdate.add(objProjectRequestToUpdate); 
			} 
	
			if(!lstProjectRequestRecordsToUpdate.isEmpty()) {  
			
				try {
				
					system.debug('---> list to in queue update' +lstProjectRequestRecordsToUpdate);
					
					if(!Test.isRunningTest()) {
					
						update lstProjectRequestRecordsToUpdate;
					}
				}
				catch(Exception exp){
				
					system.debug('Exception caught qqqqqqq--->' + exp.getMessage());
				}
			}  
		}    
 	}
}