src/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Availability__c.object
<CustomObject>
    <fields>
        <fullName>Available_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Available Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Availability</relationshipLabel>
        <relationshipName>Availability</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Forecasted_Hours__c</fullName>
        <label>Forecasted Hours</label>
        <summarizedField>Budget__c.Forecasted_Hours__c</summarizedField>
        <summaryForeignKey>Budget__c.Availability__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Hours_Worked__c</fullName>
        <label>Hours Worked</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Week</label>
        <referenceTo>Week__c</referenceTo>
        <relationshipLabel>Availability</relationshipLabel>
        <relationshipName>Availability</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Availability</label>
    <nameField>
        <displayFormat>AVAIL-{0000}</displayFormat>
        <label>Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Availability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Budget</relationshipLabel>
        <relationshipName>Budget</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Availability__c</fullName>
        <label>Availability</label>
        <referenceTo>Availability__c</referenceTo>
        <relationshipLabel>Budget</relationshipLabel>
        <relationshipName>Budget</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Forecasted_Hours__c</fullName>
        <label>Assigned Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours_Worked__c</fullName>
        <label>Hours Worked</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Week</label>
        <referenceTo>Week__c</referenceTo>
        <relationshipLabel>Budget</relationshipLabel>
        <relationshipName>Budget</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <displayFormat>BUD-{0000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Availability__c</fullName>
        <label>Availability</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Week__c.object
<CustomObject>
    <label>Week</label>
    <nameField>
        <label>Week Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weeks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AvailabilityTriggerHandler_Test.cls
@isTest
public with sharing class AvailabilityTriggerHandler_Test {
	
	@isTest static void test_method_one() {
        Test.startTest();
        //Crating Instance of TestDataFactory
        TestDataFactory obj = new TestDataFactory();

        //Inserting Accounts Records By using TestDataFactory
        List<Account> accList = obj.generateAccounts(5);
        insert accList;

        //Inserting Contacts Records By using TestDataFactory
        List<Contact> conList = obj.generateContactsForAccounts(accList,5);
        insert conList;

        //Inserting Week__c Records 
        List<Week__c> weekList = new List<Week__c>();
            for(Integer i = 0; i < 5 ; i++) {
                weekList.add(new Week__c(Name = 'Week ' + i));
            }
        insert weekList;

        //Inserting Availability__c Records 
        List<Availability__c> availabilityList = new List<Availability__c>();
            for(Integer i = 0; i < 5 ; i++) {
                availabilityList.add(new Availability__c( Available_Hours__c = 0, Week__c = weekList[0].Id , Contact__c = conList[0].Id));
            }
        insert availabilityList;

        //Inserting Project__c Records
        List<Project__c> projectList = new List<Project__c>();
            for(Integer i = 0; i < 5 ; i++) {
                projectList.add(new Project__c(Name = 'TestProject ' + i));           
            }
        insert projectList;
        //Inserting Assignment__c Records By using TestDataFactory 
        List<Assignment__c> assignmentList = obj.generateAssignment(projectList[0].Id, 'Time & Materials', 5);
        insert assignmentList;

        //Inserting Budget__c Records
        List<Budget__c> budgetList = new List<Budget__c>();
            for(Integer i = 0; i < 5 ; i++) {
                budgetList.add(new Budget__c(Forecasted_Hours__c = 5 , Hours_Worked__c = 5, Availability__c = availabilityList[1].Id ,Assignment__c = assignmentList[0].Id,  Week__c = weekList[0].Id ));           
            }
        insert budgetList;
        if(availabilityList.size() > 0) {
            availabilityList[0].Available_Hours__c = 10;
            availabilityList[0].Week__c = null ;
        }    
        update availabilityList;
        if(availabilityList.size() > 0) {
            availabilityList[0].Available_Hours__c = 10;
            availabilityList[0].Week__c = weekList[2].Id ;
        }    
        update availabilityList;
        Test.stopTest();

    }
}