src/objects/Assignment__c.object
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataFactory_TimeEntries.cls
public with sharing class TestDataFactory_TimeEntries {
    
    public static List<Time_Entry__c> generateTimeEntries(Id assignmentId, String description, Date dateValue, Decimal hour, Integer numOfRecords) {
		return generateRateForTimeEntriesInternal(assignmentId, description, dateValue, hour, numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Time_Entry__c> generateRateForTimeEntriesInternal(Id assignmentId, String description, Date dateValue, Decimal hour, Integer numOfRecords) {
    	List<Time_Entry__c> timeEntriesList = new List<Time_Entry__c>();
        
        for(integer i = 0; i < numOfRecords ; i ++) {
            Time_Entry__c timeEntry = new Time_Entry__c();
            timeEntry.assignment__C = assignmentId;
            timeEntry.description__c = description;
            timeEntry.date__C = dateValue;
            timeEntry.Hours__c = hour;
            timeEntriesList.add(timeEntry);
        }
        
        return timeEntriesList ;
    }
}