src/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story_LOE_Required_Starting_At__c</fullName>
        <globalPicklist>Story_Status</globalPicklist>
        <label>Story LOE Required Starting At</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_LOE_Required_Starting_At__c</fullName>
        <globalPicklist>Task_Status</globalPicklist>
        <label>Task LOE Required Starting At</label>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Level_of_Effort__c</fullName>
        <label>Level of Effort</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <globalPicklist>Priority</globalPicklist>
        <label>Priority</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Story_Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story_Name__c</fullName>
        <label>Story Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Story</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Estimated_Level_of_Effort__c</fullName>
        <label>Estimated Level of Effort</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <globalPicklist>Priority</globalPicklist>
        <label>Priority</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Task_Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story__c</fullName>
        <label>Story</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Task_Name__c</fullName>
        <label>Task Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Assignment__r.Project__r.Name</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Story</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TaskTriggerHandler_Test.cls
@isTest
private class TaskTriggerHandler_Test {
    
    @isTest 
    static void test_method_one() {
        Test.startTest();

            List<Task__c> taskList = createData();
            List<Story__c> storyList ;
            System.assertNotEquals(null,taskList);
            taskList[0].Status__c = 'Ready For Work';
            update taskList;

            storyList = [SELECT Id,Status__c FROM Story__c Limit 1];
            system.assertEquals(storyList[0].Status__c ,'Draft');
        	storyList[0].Level_of_Effort__c = 5;
        	update storyList;

            taskList[0].Status__c = 'In Progress';
            update taskList;

            storyList = [SELECT Id,Status__c FROM Story__c Limit 1];
            system.assertEquals(storyList[0].Status__c ,'In Progress');

          

            /*
            taskList[0].Status__c = 'Blocked';
            update taskList;

            storyList = [SELECT Id,Status__c FROM Story__c Limit 1];
            system.assertEquals(storyList[0].Status__c ,'Blocked');

            taskList[0].Status__c = 'Completed';
            update taskList;

            storyList = [SELECT Id,Status__c FROM Story__c Limit 1];
            system.assertEquals(storyList[0].Status__c ,'Ready for Review');
            */
        Test.stopTest();
    }

    public static List<Task__c> createData() {
        TestDataFactory dataFactory = new TestDataFactory();
        List<Account> accountsList = dataFactory.generateAccounts(1);
        insert accountsList;

        List<Project__c> projectList = dataFactory.generateProjects(accountsList[0].Id, 1);
        projectList[0].Story_LOE_Required_Starting_At__c = 'Ready for Review';
        projectList[0].Task_LOE_Required_Starting_At__c = 'Ready for Review';
        insert projectList;
        
       

        List<Story__c> storyList = new List<Story__c>();
        storyList.add(new Story__c(Story_Name__c = 'Test Story', Project__c = projectList[0].Id, Status__c = 'Draft', Priority__c = 'Medium'));
        insert storyList;
        
        List<Contact> contactList = dataFactory.generateContactsForAccounts(accountsList, 1);
        contactList[0].Email='Test@gmail.com';
        insert contactList ;

         List<Assignment__c> assignmentList = TestDataFactory_Assignments.generateAssignments(projectList[0].Id, contactList[0].Id, null, 'Active', 'Developer', 'Named Resource', true, 250, 1);
        insert assignmentList;
        
        List<Task__c> taskList = new List<Task__c>();
        taskList.add(new Task__c(Task_Name__c = 'Task 1',Story__c = storyList[0].Id, Status__c = 'Draft',Priority__c = 'Medium' ));
        taskList[0].Estimated_Level_of_Effort__c = 5;
        insert taskList;

          List<Time_Entry__c> timeEntriesList = TestDataFactory_TimeEntries.generateTimeEntries(assignmentList[0].Id, 'Test', system.today().addDays(10), 8, 2);
            timeEntriesList[0].Story__c = storyList[0].Id;
            timeEntriesList[0].Task__c = taskList[0].Id;

            insert timeEntriesList;

        return taskList;
    }
}