src/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Assignments (Cost Rate)</relationshipLabel>
        <relationshipName>Assignments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billable Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource_Name__c</fullName>
        <formula>Resource__r.FirstName + &apos; &apos; + Resource__r.LastName</formula>
        <label>Expert Name</label>
        <type>Text</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goodwill_Amount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Goodwill Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate_Text__c</fullName>
        <formula>Rate__r.Hourly_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate__c.object
<CustomObject>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Partner_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Partner Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expert_Goodwill_Hours__c</fullName>
        <label>Expert Goodwill Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Goodwill_Hours__c</fullName>
        <label>Goodwill Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource_Name__c</fullName>
        <formula>Assignment__r.Resource__r.FirstName + &quot; &quot; + Assignment__r.Resource__r.LastName</formula>
        <label>Expert Name</label>
        <type>Text</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ApplyGoodwillController.cls
public with sharing class ApplyGoodwillController 
{
	private String invoiceId;
	public List<Time_Entry__c> timeEntryList {get; set;}
	public Boolean isLightningExperience {get; set;}
	private Set<Id> rateIdSet;
	private Set<Id> costRateIdSet;
	private Set<Id> deliveryInvoiceIdSet;
	private List<Invoice_Line_Item__c> goodwillLineItemsToBeInserted;
	private List<Invoice_Line_Item__c> expertGoodwillLineItemsToBeInserted;
	public List<Invoice_Line_Item__c> invoiceLineItemList;

	public ApplyGoodwillController(ApexPages.StandardController controller) 
	{
		rateIdSet = new Set<Id>();
		costRateIdSet = new Set<Id>();
		deliveryInvoiceIdSet = new Set<Id>();
		goodwillLineItemsToBeInserted = new List<Invoice_Line_Item__c>();
		expertGoodwillLineItemsToBeInserted = new List<Invoice_Line_Item__c>();
		isLightningExperience = false;
        if(ApexPages.CurrentPage().GetParameters().get('sfdcIFrameOrigin') != null) 
        {
            isLightningExperience = true;
        }

		invoiceId = ApexPages.currentPage().getParameters().get('Id');
		timeEntryList = [SELECT Id, Resource_Name__c, Date__c, Hours__c, Description__c, Goodwill_Hours__c, Delivery_Partner_Invoice__c, 
							Assignment__r.Rate__r.Name, Assignment__r.Rate__r.Id, Assignment__r.Cost_Rate__r.Id, Expert_Goodwill_Hours__c 
						FROM Time_Entry__c
						WHERE Invoice__c =: invoiceId 
						ORDER BY Date__c DESC];

		invoiceLineItemList = [SELECT Id, Rate__c, RecordTypeId, Invoice__c, Hours__c, Hourly_Rate_Text__c, Goodwill_Amount__c 
								FROM Invoice_Line_Item__c 
								WHERE Invoice__c =: invoiceId 
								ORDER BY Rate__c];
	}
	public PageReference saveTimeEntries()
	{
		if(timeEntryList != null && !timeEntryList.isEmpty())
		{
			System.debug(timeEntryList[0].Goodwill_Hours__c);
			System.debug(timeEntryList[0].Expert_Goodwill_Hours__c);
			update timeEntryList;

			for(Time_Entry__c timeEntry : timeEntryList)
			{
				rateIdSet.add(timeEntry.Assignment__r.Rate__r.Id);
				costRateIdSet.add(timeEntry.Assignment__r.Cost_Rate__r.Id);
				deliveryInvoiceIdSet.add(timeEntry.Delivery_Partner_Invoice__c);
			}
			if(rateIdSet.size() > 0 && rateIdSet != null)
			{
				for(Id rateId : rateIdSet)
				{
					Decimal hours = 0.00;
					for(Time_Entry__c timeEntry : timeEntryList)
					{
						if(rateId == timeEntry.Assignment__r.Rate__r.Id)
						{
							if(timeEntry.Goodwill_Hours__c != null )
								hours = hours + timeEntry.Goodwill_Hours__c;
						}
					}
					if(hours != 0.00 || hours > 0.00)
					{
						if(invoiceLineItemList != null && !invoiceLineItemList.isEmpty())
						{
							for(Invoice_Line_Item__c lineItem : invoiceLineItemList)
							{
								if(lineItem.RecordTypeId == Constants.RECORDTYPEID_INVOICE_10KGOODWILLNVOICELINEITEM && lineItem.Rate__c == rateId)
								{
									if(goodwillLineItemsToBeInserted != null && !goodwillLineItemsToBeInserted.isEmpty() && goodwillLineItemsToBeInserted.get(goodwillLineItemsToBeInserted.size()-1).Rate__c == lineItem.Rate__c)
									{
										goodwillLineItemsToBeInserted.remove(goodwillLineItemsToBeInserted.size()-1);
									}
									lineItem.Rate__c 			= rateId;
									lineItem.RecordTypeId 		= Constants.RECORDTYPEID_INVOICE_10KGOODWILLNVOICELINEITEM;
									lineItem.Hours__c 			= hours;
									lineItem.Goodwill_Amount__c = hours * lineItem.Hourly_Rate_Text__c;
									goodwillLineItemsToBeInserted.add(lineItem);
								}
								else if(lineItem.RecordTypeId != Constants.RECORDTYPEID_INVOICE_10KGOODWILLNVOICELINEITEM && lineItem.Rate__c == rateId)
								{
									if(goodwillLineItemsToBeInserted != null && !goodwillLineItemsToBeInserted.isEmpty() && goodwillLineItemsToBeInserted.get(goodwillLineItemsToBeInserted.size()-1).Rate__c == lineItem.Rate__c){}
									else if(goodwillLineItemsToBeInserted == null || goodwillLineItemsToBeInserted.isEmpty())
									{
										Invoice_Line_Item__c invoiceLineItem = new Invoice_Line_Item__c(Rate__c 			= rateId,
																										RecordTypeId 		= Constants.RECORDTYPEID_INVOICE_10KGOODWILLNVOICELINEITEM,
																										Hours__c 			= hours,
																										Goodwill_Amount__c 	= hours * lineItem.Hourly_Rate_Text__c,
																										Invoice__c 			= invoiceId
																										);
										goodwillLineItemsToBeInserted.add(invoiceLineItem);
									}
									else if(goodwillLineItemsToBeInserted != null && !goodwillLineItemsToBeInserted.isEmpty() && goodwillLineItemsToBeInserted.get(goodwillLineItemsToBeInserted.size()-1).Rate__c != lineItem.Rate__c)
									{
										Invoice_Line_Item__c invoiceLineItem = new Invoice_Line_Item__c(Rate__c 			= rateId,
																										RecordTypeId 		= Constants.RECORDTYPEID_INVOICE_10KGOODWILLNVOICELINEITEM,
																										Hours__c 			= hours,
																										Goodwill_Amount__c 	= hours * lineItem.Hourly_Rate_Text__c,
																										Invoice__c 			= invoiceId
																										);
										goodwillLineItemsToBeInserted.add(invoiceLineItem);
									}
								}
							}
						}
					}
				}
				if(goodwillLineItemsToBeInserted.size() > 0)
					upsert goodwillLineItemsToBeInserted;
			}

			invoiceLineItemList = [SELECT Id, Rate__c, RecordTypeId, Invoice__c, Hours__c, Hourly_Rate_Text__c, Goodwill_Amount__c 
									FROM Invoice_Line_Item__c 
									WHERE Invoice__c IN : deliveryInvoiceIdSet  
									ORDER BY Rate__c];

			if(costRateIdSet.size() > 0 && costRateIdSet != null)
			{
				for(Id rateId : costRateIdSet)
				{
					Decimal hours = 0.00;
					for(Id deliveryInvoiceId : deliveryInvoiceIdSet)
					{
						for(Time_Entry__c timeEntry : timeEntryList)
						{
							if(rateId == timeEntry.Assignment__r.Cost_Rate__r.Id && deliveryInvoiceId == timeEntry.Delivery_Partner_Invoice__c)
							{
								if(timeEntry.Expert_Goodwill_Hours__c != null )
									hours = hours + timeEntry.Expert_Goodwill_Hours__c;
							}
						}
						if(hours != 0.00 || hours > 0.00)
						{
							if(invoiceLineItemList != null && !invoiceLineItemList.isEmpty())
							{
								for(Invoice_Line_Item__c lineItem : invoiceLineItemList)
								{
									if(lineItem.RecordTypeId == Constants.RECORDTYPEID_INVOICE_10KGOODWILLNVOICELINEITEM && lineItem.Rate__c == rateId && lineItem.Invoice__c == deliveryInvoiceId)
									{
										if(expertGoodwillLineItemsToBeInserted != null && !expertGoodwillLineItemsToBeInserted.isEmpty() && expertGoodwillLineItemsToBeInserted.get(expertGoodwillLineItemsToBeInserted.size()-1).Rate__c == lineItem.Rate__c)
										{
											expertGoodwillLineItemsToBeInserted.remove(expertGoodwillLineItemsToBeInserted.size()-1);
										}
										lineItem.Rate__c 			= rateId;
										lineItem.RecordTypeId 		= Constants.RECORDTYPEID_INVOICE_10KGOODWILLNVOICELINEITEM;
										lineItem.Hours__c 			= hours;
										lineItem.Goodwill_Amount__c = hours * lineItem.Hourly_Rate_Text__c;
										expertGoodwillLineItemsToBeInserted.add(lineItem);
									}
									else if(lineItem.RecordTypeId != Constants.RECORDTYPEID_INVOICE_10KGOODWILLNVOICELINEITEM && lineItem.Rate__c == rateId && lineItem.Invoice__c == deliveryInvoiceId)
									{
										if(expertGoodwillLineItemsToBeInserted != null && !expertGoodwillLineItemsToBeInserted.isEmpty() && expertGoodwillLineItemsToBeInserted.get(expertGoodwillLineItemsToBeInserted.size()-1).Rate__c == lineItem.Rate__c){}
										else if(expertGoodwillLineItemsToBeInserted == null || expertGoodwillLineItemsToBeInserted.isEmpty())
										{
											Invoice_Line_Item__c invoiceLineItem = new Invoice_Line_Item__c(Rate__c 			= rateId,
																											RecordTypeId 		= Constants.RECORDTYPEID_INVOICE_10KGOODWILLNVOICELINEITEM,
																											Hours__c 			= hours,
																											Goodwill_Amount__c 	= hours * lineItem.Hourly_Rate_Text__c,
																											Invoice__c 			= deliveryInvoiceId
																											);
											expertGoodwillLineItemsToBeInserted.add(invoiceLineItem);
										}
										else if(expertGoodwillLineItemsToBeInserted != null && !expertGoodwillLineItemsToBeInserted.isEmpty() && expertGoodwillLineItemsToBeInserted.get(expertGoodwillLineItemsToBeInserted.size()-1).Rate__c != lineItem.Rate__c)
										{
											Invoice_Line_Item__c invoiceLineItem = new Invoice_Line_Item__c(Rate__c 			= rateId,
																											RecordTypeId 		= Constants.RECORDTYPEID_INVOICE_10KGOODWILLNVOICELINEITEM,
																											Hours__c 			= hours,
																											Goodwill_Amount__c 	= hours * lineItem.Hourly_Rate_Text__c,
																											Invoice__c 			= deliveryInvoiceId
																											);
											expertGoodwillLineItemsToBeInserted.add(invoiceLineItem);
										}
									}
								}
							}
						}
					}
				}
				if(expertGoodwillLineItemsToBeInserted.size() > 0)
					upsert expertGoodwillLineItemsToBeInserted;
			}
		}
		return new PageReference('/' + invoiceId);
	}
}