src/objects/Availability__c.object
<CustomObject>
    <fields>
        <fullName>Available_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Available Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Week</label>
        <referenceTo>Week__c</referenceTo>
        <relationshipLabel>Availability</relationshipLabel>
        <relationshipName>Availability</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Availability</label>
    <nameField>
        <displayFormat>AVAIL-{0000}</displayFormat>
        <label>Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Availability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Week__c.object
<CustomObject>
    <label>Week</label>
    <nameField>
        <label>Week Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weeks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AvailabilityTriggerHandler.cls
public without sharing class AvailabilityTriggerHandler {

	public static void weekHourRollupUpdate(List<Availability__c> availabilityList,Map<Id,Availability__c> oldAvailabilityMap) {
		Set<Id> weekIds = new Set<Id>();
		List<Availability__c> availabilityListToUpdate = new List<Availability__c>();
    	for(Availability__c item : availabilityList){
    		if(item.Week__c != null && ((Availability__c)oldAvailabilityMap.get(item.Id)).Week__c != item.Week__c)
				weekIds.add(item.Week__c);				
			if(item.Week__c == null && item.Available_Hours__c != null ) {
				Availability__c availability 		= new Availability__c();
				availability.Id 					= item.Id;
				availability.Available_Hours__c 	= null;
				availabilityListToUpdate.add(availability);
			}
		}
		if (availabilityListToUpdate.size() > 0)
			update availabilityListToUpdate;
		//if (weekIds.size() > 0 )
			//BudgetTriggerHandler.updateAvailability(weekIds , Trigger.newMap.keySet());
    }   
}