src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Additional_Case_Contact_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Case Contact 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Additional_Case_Contact_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Case Contact 2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Additional Case Contact 2)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Additional_Case_Contact_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Case Contact 3</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Additional Case Contact 3)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Additional_Case_Contact_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Case Contact 4</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Additional Case Contact 4)</relationshipLabel>
        <relationshipName>Cases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Additional_Case_Contact_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Case Contact 5</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Additional Case Contact 5)</relationshipLabel>
        <relationshipName>Cases4</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/AdditionalCaseContactController.cls
public with sharing class AdditionalCaseContactController 
{
	@AuraEnabled
    public static Case retriveCase(String caseIdValue)
    {
        String caseId = caseIdValue;
        return [SELECT Id, AccountId, Additional_Case_Contact_1__c, Additional_Case_Contact_1__r.Name, Additional_Case_Contact_2__c, Additional_Case_Contact_2__r.Name, 
        		Additional_Case_Contact_3__c, Additional_Case_Contact_3__r.Name, Additional_Case_Contact_4__c, Additional_Case_Contact_4__r.Name, Additional_Case_Contact_5__c, Additional_Case_Contact_5__r.Name 
        			FROM Case 
        			WHERE Id =: caseId];
        
    }

	@AuraEnabled
    public static Case updateAdditionalCaseContacts(Case caseRec)
    {
        Case caseObj = new Case();
        System.debug(caseObj);
        caseObj = (Case)caseRec;
        update caseObj;
        return [SELECT Id, AccountId, Additional_Case_Contact_1__c, Additional_Case_Contact_1__r.Name, Additional_Case_Contact_2__c, Additional_Case_Contact_2__r.Name, 
        		Additional_Case_Contact_3__c, Additional_Case_Contact_3__r.Name, Additional_Case_Contact_4__c, Additional_Case_Contact_4__r.Name, Additional_Case_Contact_5__c, Additional_Case_Contact_5__r.Name 
        			FROM Case 
        			WHERE Id =: caseObj.Id];
    }
}