src/objects/Code_Scan_Rule_Set__mdt.object
<CustomObject>
    <description>Code Scan Rule Set</description>
    <fields>
        <fullName>Rule_Description__c</fullName>
        <label>Rule Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Code Scan Rule Set</label>
    <pluralLabel>Code Scan Rule Sets</pluralLabel>
</CustomObject>

src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Scan_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scan Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Manage_Artifacts_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Manage Artifacts Setting</label>
    <pluralLabel>Manage Artifacts Settings</pluralLabel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Scan_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scan Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Connection__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Connection__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Connection__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Connection__c</referenceTo>
        <relationshipLabel>Releases (Target)</relationshipLabel>
        <relationshipName>Releases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Scan_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scan Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Story_Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CodeReviewLightning.cls
// Code Review Lightning Controller for Story

public with sharing class CodeReviewLightning {
    @AuraEnabled
    public static String getCodeReviewFunctionality(String recId) {
        LogResponse mainLogResponse = new LogResponse();
        String storyKeyPrifix       = Schema.getGlobalDescribe().get('Story__c').getDescribe().getKeyPrefix();
        String releaseKeyPrifix     = Schema.getGlobalDescribe().get('Release__c').getDescribe().getKeyPrefix();
        String connectionKeyPrifix  = Schema.getGlobalDescribe().get('Connection__c').getDescribe().getKeyPrefix();
        String objectName           = '';
        String message              = '';
        if(recId.substring(0, 3) == storyKeyPrifix) {
            objectName  = 'Story__c';
            message     = 'There are no artifacts attached to this Story. Please add some Apex classes and/or triggers before running a code scan.';
        }
        else if (recId.substring(0, 3) == releaseKeyPrifix) {
            objectName  = 'Release__c';
            message     = 'There are no artifacts attached to this Release. Please add some Apex classes and/or triggers before running a code scan.';
        }
        else if (recId.substring(0, 3) == connectionKeyPrifix) {
            objectName  = 'Connection__c';
            message     = 'This connection is not authorized. Please authorize the connection before running a code scan.';
        }

        SObject record                  = retrieveStory(recId,objectName);
        List<Log> logsList              = new List<Log>();
        mainLogResponse.objctAPIName    = objectName;
        mainLogResponse.objctLabel      = objectName.replace('__c','');

        if((Boolean)record.get('Created_On_Heroku__c') != true) {
            mainLogResponse.activeStatus = message;
            return JSON.serialize(mainLogResponse);
        }
        else {
            if(objectName == 'Connection__c') {
                Connection__c connection = [SELECT Id, Status__c FROM Connection__c WHERE Id =: recId];
                if(connection.Status__c != 'Active') {
                    mainLogResponse.activeStatus = 'This connection is not active. Please authorize the connection before running a code scan.';
                    return JSON.serialize(mainLogResponse);
                }
            }
            if(objectName == 'Release__c') {
                List<Release__c> release = [SELECT Id, Source__c, Source__r.Status__c, Source__r.Created_On_Heroku__c, Target__c FROM Release__c WHERE Id =:recId];
                if(release[0].Source__c == null || release[0].Source__r.Status__c != 'Active' || !release[0].Source__r.Created_On_Heroku__c) {
                    mainLogResponse.activeStatus = 'There is no active source connection for this release.';
                    return JSON.serialize(mainLogResponse);
                }
            }
            logsList                            = retriveReviewLogs(record,objectName);
            mainLogResponse.logList             = logsList;
            mainLogResponse.isRefreshRunning    = (Boolean)record.get('Scan_Running__c');
            return JSON.serialize(mainLogResponse);
        }
    }
    
    @AuraEnabled
    public static Sobject retrieveStory(String recId,String objectName) {
        String querystring = 'SELECT Id, Scan_Running__c, Created_On_Heroku__c, Project__c, Project__r.Name FROM ' + objectName + ' WHERE Id =: recId';
        return Database.query(querystring);
    }

    @AuraEnabled
    public Static void manageRelease(String recId) {
        String releaseKeyPrifix = Schema.getGlobalDescribe().get('Release__c').getDescribe().getKeyPrefix();
        if (recId.substring(0, 3) == releaseKeyPrifix)
            ManageReleaseArtifactsLightning.manageRelease(recId);
    }
    
    public Static List<Log> retriveReviewLogs(Sobject record,String objectName) {
        List<Log> logsList = new List<Log>();
        String reqEndpoint = '';
        if(objectName == 'Story__c')
            reqEndpoint = 'Story_ReviewLogs';
        else if(objectName == 'Connection__c')
            reqEndpoint = 'Connection_ReviewLogs';
        else 
            reqEndpoint = 'Release_ReviewLogs';


        HttpResponse res = RestRequestHandlerForHeroku.sendRequest('POST',reqEndpoint,'',(String)record.Id,(String)record.get('Project__c'),(String)record.getSobject('Project__r').get('Name'));
        if(res.getStatusCode() == 200 ) {
            ReviewLog dlog = (ReviewLog) JSON.deserialize(res.getBody(), ReviewLog.class);
            if(dlog.Status == 'Success' && dlog.Log != null)
              logsList = dlog.Log;
        }
        return logsList;
    }
    
    @AuraEnabled
    public static List<LogIssue> retriveScanLogIssues(String logId,String objectName, String recordsLimit,String recId) {
        Sobject record                              = retrieveStory(recId,objectName);
        Manage_Artifacts_Setting__mdt defaultLimit  = [SELECT ID, QualifiedApiName, Limit__c  FROM Manage_Artifacts_Setting__mdt LIMIT 1];
        Integer recCount                            = Integer.valueOf(recordsLimit) + Integer.valueOf(defaultLimit.Limit__c);
        String reqEndpoint = '';
        if(objectName == 'Story__c')
            reqEndpoint = 'Story_ScanResult';
        else if(objectName == 'Connection__c')
            reqEndpoint = 'Connection_ScanResult';
        else 
            reqEndpoint = 'Release_ScanResult';

        List<RuleSetWrapper> ruleSetWrapperList = new List<RuleSetWrapper>();
        for(Code_Scan_Rule_Set__mdt rule : [SELECT Id, QualifiedApiName, Severity__c, State__c, Rule_Description__c FROM Code_Scan_Rule_Set__mdt]){
            RuleSetWrapper ruleInfo = new RuleSetWrapper();
            ruleInfo.ruleName       = rule.QualifiedApiName;
            ruleInfo.ruleSeverity  = rule.Severity__c;
            ruleSetWrapperList.add(ruleInfo);
        }

        String requestJSONBody = '"limit":"' + recCount + '",' +
                                 '"ruleList":' + JSON.serialize(ruleSetWrapperList);
        HttpResponse res = RestRequestHandlerForHeroku.sendRequest('POST',reqEndpoint,requestJSONBody,logId,(String)record.get('Project__c'),(String)record.getSobject('Project__r').get('Name'));
        List<LogIssue> logIssueList = new List<LogIssue>();
        if(res.getStatusCode() == 200 ){
            ReviewIssue scanLogIssue = (ReviewIssue) JSON.deserialize(res.getBody(), ReviewIssue.class);
            if(scanLogIssue.Status == 'Success' && scanLogIssue.LogIssue != null)
              logIssueList = scanLogIssue.LogIssue; 
        }
        return logIssueList;
    }
    
    @AuraEnabled
    public static CodeScan scanCode(Id recId,String objectName) {
        Sobject record = retrieveStory((String)recId,objectName);
        String reqEndpoint = '';
        if(objectName == 'Story__c')
            reqEndpoint = 'Story_CodeReview';
        else if(objectName == 'Connection__c')
            reqEndpoint = 'Connection_CodeReview';
        else 
            reqEndpoint = 'Release_CodeReview';
        List<RuleSetWrapper> ruleSetWrapperList = new List<RuleSetWrapper>();
        for(Code_Scan_Rule_Set__mdt rule : [SELECT Id, QualifiedApiName, Severity__c, State__c, Rule_Description__c FROM Code_Scan_Rule_Set__mdt]){
            RuleSetWrapper ruleInfo = new RuleSetWrapper();
            ruleInfo.ruleName   = rule.QualifiedApiName;
            ruleInfo.ruleState = rule.State__c;
            ruleSetWrapperList.add(ruleInfo);
        }

        String requestJSONBody = '"ruleList":' + JSON.serialize(ruleSetWrapperList);
        
        HttpResponse res = RestRequestHandlerForHeroku.sendRequest('POST',reqEndpoint,requestJSONBody,(String)recId,(String)record.get('Project__c'),(String)record.getSobject('Project__r').get('Name'));
        CodeScan dlog;
        if(res.getStatusCode() == 200 ) {
            dlog = (CodeScan) JSON.deserialize(res.getBody(), CodeScan.class);
            if(dlog.status == 'Success' )
                record.put('Scan_Running__c',true);
        }
        update record;
        return dlog;
    }

    public class RuleSetWrapper {
        @AuraEnabled public string ruleName         {get;set;}
        @AuraEnabled public string ruleState       {get;set;}
        @AuraEnabled public string ruleSeverity    {get;set;}
    }
    
    public class ReviewLog {
        @AuraEnabled public String Status {get;set;}
        @AuraEnabled public List<Log> Log {get;set;}
    }
    public class Log {
        @AuraEnabled public String logId    {get;set;}
        @AuraEnabled public String status   {get;set;}
        @AuraEnabled public String logTime  {get;set{
                logTime = value.replace(' ','T') + 'Z';
            }
        }
        @AuraEnabled public String communityUrl { get {
                return  Site.getPathPrefix().split('/s')[0];
            } set;
        }
    }
    public class ReviewIssue {
        @AuraEnabled public String Status;
        @AuraEnabled public List<LogIssue> LogIssue;
    }
    public class LogIssue {
        @AuraEnabled public String artifactType  {get;set;}
        @AuraEnabled public String artifactName  {get;set;}
        @AuraEnabled public String lineNo        {get;set;}
        @AuraEnabled public String severity      {get;set;}
        @AuraEnabled public String violation     {get;set;}  
    }
    public class CodeScan {
        @AuraEnabled public String status;
        @AuraEnabled public String message;
    }
    public class LogResponse {
        @AuraEnabled public List<Log> logList           {get;set;} 
        @AuraEnabled public Boolean isRefreshRunning    {get;set;}
        @AuraEnabled public String activeStatus         {get;set;} 
        @AuraEnabled public String objctAPIName         {get;set;} 
        @AuraEnabled public String objctLabel           {get;set;} 
    }
}