src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Organization_URL__c</fullName>
        <label>Organization URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestDataFactory_Connections.cls
public with sharing class TestDataFactory_Connections {
    
    public static List<Connection__c> generateConnections(Id recordTypeId, Id projectId, String status, String orgUrl, Integer numOfRecords) {
		return generateConnectionsInternal(recordTypeId, projectId, status, orgUrl, numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Connection__c> generateConnectionsInternal(Id recordTypeId, Id projectId, String status, String orgUrl, Integer numOfRecords) {
    	List<Connection__c> connectionList = new List<Connection__c>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
			Connection__c con = new Connection__c();
			con.Project__c = projectId;
			con.Status__c = status;
			if(orgUrl != null)
				con.Organization_URL__c = orgUrl;
			if(recordTypeId != null)
				con.RecordTypeId = recordTypeId;
            connectionList.add(con);
        }
        
        return connectionList;
    }
}