src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Heroku_Endpoint__mdt.object
<CustomObject>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Heroku Endpoint</label>
    <pluralLabel>Heroku Endpoints</pluralLabel>
</CustomObject>

src/objects/Heroku_oAuth_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Call_back_Url_Community__c</fullName>
        <label>Call back Url Community</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Callback_URL__c</fullName>
        <label>Callback URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Heroku_URL__c</fullName>
        <label>Heroku URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>IsSandbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSandbox</label>
        <type>Checkbox</type>
    </fields>
    <label>Heroku oAuth Setting</label>
    <pluralLabel>Heroku oAuth Settings</pluralLabel>
</CustomObject>

src/objects/Manage_Artifacts_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Manage Artifacts Setting</label>
    <pluralLabel>Manage Artifacts Settings</pluralLabel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Release_Date__c</fullName>
        <label>Actual Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Connection__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Connection__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Release_Date__c</fullName>
        <label>Target Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Connection__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Connection__c</referenceTo>
        <relationshipLabel>Releases (Target)</relationshipLabel>
        <relationshipName>Releases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Validation_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validation Running</label>
        <type>Checkbox</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ValidateDeploymentController.cls
public with sharing class ValidateDeploymentController {
	public Release__c release 		{get;set;}
	public List<Log> logsList 		{get;set;}
	public String baseUrl			{get;set;}
	public boolean releaseExists    {get;set;}
	
	@TestVisible private Heroku_oAuth_Setting__mdt credentials;
    @TestVisible private Map<String, String> herokuEndpointsMap;
    @TestVisible private Manage_Artifacts_Setting__mdt defaultLimit;

	public ValidateDeploymentController(ApexPages.StandardController std) {
		
		Organization orgz = [SELECT IsSandbox FROM Organization LIMIT 1];
		credentials = [SELECT ID, QualifiedApiName, Callback_URL__c, Call_back_Url_Community__c, Consumer_Key__c, Consumer_Secret__c,
					  Heroku_URL__c  FROM Heroku_oAuth_Setting__mdt WHERE IsSandbox__c =: orgz.IsSandbox LIMIT 1];
		
		defaultLimit = [SELECT ID, QualifiedApiName, Limit__c  FROM Manage_Artifacts_Setting__mdt LIMIT 1];
										
		herokuEndpointsMap = new Map<String, String>();
		
		for(Heroku_Endpoint__mdt endpoint : [SELECT ID, QualifiedApiName, Endpoint__c FROM Heroku_Endpoint__mdt]){
			herokuEndpointsMap.put(endpoint.QualifiedApiName, endpoint.Endpoint__c);
		}
		
        release = [SELECT Id, Name, Project__c, Status__c, Source__c, Source__r.Status__c, Target__c, Actual_Release_Date__c,Target_Release_Date__c, 
        				Created_On_Heroku__c ,Target__r.Status__c,Validation_Running__c
        			FROM Release__c 
        			WHERE Id =: std.getRecord().Id];
        
        releaseExists = true;
        if(release.Created_On_Heroku__c == false) {
            releaseExists = false;
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'Release is not created on Heroku.'));
        }
        if(release.Source__c == null || release.Source__r.Status__c != 'Active') {
        	releaseExists = false;
        	ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'There is no active source connection for this release.'));
        }
        if(release.Target__c == null || release.Target__r.Status__c != 'Active') {
        	releaseExists = false;
        	ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'There is no active target connection for this release.'));
        }
        retriveDeploymentLogs();
        baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
    }

	public void retriveDeploymentLogs(){
		
		String token = HerokuToken.headerToken();
		
		Http h = new Http();

		HttpRequest req = new HttpRequest();
		req.setEndpoint(credentials.Heroku_URL__c + herokuEndpointsMap.get('Deployment_Logs') + release.Id);
		req.setMethod('GET');
		req.setHeader('token',token);
		req.setHeader('Content-Type', 'application/json');
		req.setTimeOut(120000); 
		
		HttpResponse res = h.send(req);
		
		System.debug(res);
		System.debug(res.getBody());
		logsList = new List<Log>();
		if(res.getStatusCode() == 200 ) 
        {
            DeploymentLog dlog = (DeploymentLog) JSON.deserialize(EncodingUtil.urlDecode(res.getBody(), 'UTF-8'), DeploymentLog.class);
            //System.debug(dlog);
            
            if(dlog.Status == 'Success' && dlog.Log != null)
            {
            	logsList = dlog.Log;
            }
        }
	}
	
    public void validateDeployment() {
    	deploy(true);
    }

    public void deployMetadata() {
    	deploy(false);
    }

    public void deploy(Boolean checkOnly) {
    	String token = HerokuToken.headerToken();
    	
		Http h = new Http();

		HttpRequest req = new HttpRequest();
		req.setEndpoint(credentials.Heroku_URL__c + herokuEndpointsMap.get('Validate_Deployment') + release.Id);
		req.setMethod('POST');
		req.setHeader('Content-Type', 'application/json');
		req.setHeader('token',token);

		String requestJSONBody = '{"Source_Connection":"'+ release.Source__c +'",'+ 
		    					 '"Target_Connection":"'+ release.Target__c +'",'+
		    					 '"Check_Only":"' + checkOnly + '"}';

		req.setBody(requestJSONBody );
		req.setTimeOut(120000);

		HttpResponse res = h.send(req);

		//System.debug(res);
		//System.debug(res.getBody());
		
		if(res.getStatusCode() == 200 ) 
        {
            DeploymentLog dlog = (DeploymentLog) JSON.deserialize(EncodingUtil.urlDecode(res.getBody(), 'UTF-8'), DeploymentLog.class);
            //System.debug(dlog);
            
            if(dlog.Status == 'Success' )
            {
            	release.Validation_Running__c = true;
            }
        }
        update release; 
    }
    
    @remoteAction
    public static List<Log_Issue> retriveDeploymentLogIssues(String log_Id){

    	Organization orgz = [SELECT IsSandbox FROM Organization LIMIT 1];
		Heroku_oAuth_Setting__mdt credentials = [SELECT ID, QualifiedApiName, Callback_URL__c, Call_back_Url_Community__c, Consumer_Key__c, Consumer_Secret__c,
					  Heroku_URL__c  FROM Heroku_oAuth_Setting__mdt WHERE IsSandbox__c =: orgz.IsSandbox LIMIT 1];
		
		Map<String, String> herokuEndpointsMap = new Map<String, String>();
		
		for(Heroku_Endpoint__mdt endpoint : [SELECT ID, QualifiedApiName, Endpoint__c FROM Heroku_Endpoint__mdt]){
			herokuEndpointsMap.put(endpoint.QualifiedApiName, endpoint.Endpoint__c);
		}

		String token = HerokuToken.headerToken(); 
		
		Http h = new Http();
		
		HttpRequest req = new HttpRequest();
		req.setEndpoint(credentials.Heroku_URL__c + herokuEndpointsMap.get('Deployment_Issues') + log_Id);
		req.setMethod('GET');
		req.setHeader('token',token);
		req.setTimeOut(120000); 
		
		HttpResponse res = h.send(req);
		System.debug(res);
		System.debug(res.getBody()); 

		List<Log_Issue> logIssueList = new List<Log_Issue>();
		if(res.getStatusCode() == 200 ) 
        {
            DeploymentIssue dlogIssue = (DeploymentIssue) JSON.deserialize(EncodingUtil.urlDecode(res.getBody(), 'UTF-8'), DeploymentIssue.class);
            //System.debug(dlogIssue);
            
            if(dlogIssue.Status == 'Success' && dlogIssue.LogIssue != null)
            {
            	logIssueList = dlogIssue.LogIssue; 
            }
        }
        return logIssueList; 
	}
	
	public void releaseValidationStatus() {
        release = [SELECT Id, Name, Project__c, Status__c, Source__c, Source__r.Status__c, Target__c, Actual_Release_Date__c,Target_Release_Date__c, 
        			Created_On_Heroku__c ,Target__r.Status__c,Validation_Running__c
        			FROM Release__c 
        			WHERE Id =: release.Id];
    }
	
    public class DeploymentLog {
		public String Status {get;set;} 
		public List<Log> Log {get;set;} 
	}
	public class Log {
		//public List<Log_Issue> log_Issue {get;set;} 
		public String logId 	{get;set;} 
		public String status 	{get;set;} 
		public String logTime 	{get;set;}
		public String action 	{get;set;} 
	}
	
	public class DeploymentIssue {
		public String Status 			{get;set;} 
		public List<Log_Issue> LogIssue {get;set;} 
	}
	public class Log_Issue {
		public String description 	{get;set;} 
		public String type 			{get;set;} 
	}
}