src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Deletion__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow Deletion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Code_Scan_Describe_Message__c</fullName>
        <label>Code Scan Describe Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Scan_Status__c</fullName>
        <label>Code Scan Status</label>
        <picklist>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Violation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comparing_Connections__c</fullName>
        <label>Comparing Connections</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Connection_Compare_Describe_Message__c</fullName>
        <label>Connection Compare Describe Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Metadata_Describe_Error__c</fullName>
        <label>Metadata Describe Error</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Metadata_Last_Described__c</fullName>
        <label>Metadata Last Described</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Refresh_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Refresh Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Scan_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scan Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SyncConnection.cls
@RestResource(urlMapping='/syncConnection/')
global with sharing class SyncConnection {
    @HttpPost
    global static String syncConnectionRecord() {
        RestRequest req = RestContext.request;
        try {
            List<Connection__c> connectionList = [SELECT Metadata_Last_Described__c, Allow_Deletion__c, Metadata_Describe_Error__c, 
                                                      Scan_Running__c, Code_Scan_Status__c, Code_Scan_Describe_Message__c, Status__c,
              										  Connection_Compare_Describe_Message__c, Comparing_Connections__c 
          										  FROM Connection__c
                                                  WHERE ID =: req.params.get('Connection_Id')];
            if(connectionList.size() > 0) {
                for( Connection__c connectionToUpdate :connectionList) {
                	if(req.params.get('Task') == 'MetadataDescribe') {
    	            	if(req.params.get('refreshStstus') == 'true') {
    	            		connectionToUpdate.Refresh_Running__c = true;
    	            	}
    	            	else {
    						connectionToUpdate.Metadata_Last_Described__c = Datetime.now(); 
    						connectionToUpdate.Refresh_Running__c         = false; 
    						connectionToUpdate.Status__c                  = req.params.get('Status'); 
    						connectionToUpdate.Metadata_Describe_Error__c = req.params.get('Error_Message'); 
                            //connectionToUpdate.Allow_Deletion__c          = false;
    	            	}
                	}
                	if(req.params.get('Task') == 'CodeReview') {
                		connectionToUpdate.Code_Scan_Status__c            = req.params.get('Status');
                		connectionToUpdate.Scan_Running__c                = false; 
                		connectionToUpdate.Code_Scan_Describe_Message__c  = req.params.get('Describe_Error'); 
                        connectionToUpdate.Allow_Deletion__c              = false;
                	}
                	if(req.params.get('Task') == 'ConnectionCompare') {
                		connectionToUpdate.Connection_Compare_Describe_Message__c = req.params.get('Describe_Error'); 
                        connectionToUpdate.Allow_Deletion__c                      = false;
                        String connectionIdString = '';
                        connectionToUpdate.Comparing_Connections__c = connectionToUpdate.Comparing_Connections__c == null ? '' : connectionToUpdate.Comparing_Connections__c;
                        for(String connectionId : connectionToUpdate.Comparing_Connections__c.split(','))
                            if(connectionId != req.params.get('targetConnection') && connectionId.trim() != '')
                                connectionIdString += connectionIdString == '' ? connectionId : ',' + connectionId;
                        connectionToUpdate.Comparing_Connections__c = connectionIdString;
                	}
                } 
                if(req.params.get('Task') == 'ConnectionCompare' && req.params.get('targetConnection') != req.params.get('Connection_Id')) {
                    for(Connection__c connection : [SELECT Id, Comparing_Connections__c FROM Connection__c WHERE Id =: req.params.get('targetConnection')]) {
                        String connectionIdString = '';
                        connection.Comparing_Connections__c = connection.Comparing_Connections__c == null ? '' : connection.Comparing_Connections__c;
                        for(String connectionId : connection.Comparing_Connections__c.split(','))
                            if(connectionId != req.params.get('Connection_Id')  && connectionId.trim() != '')
                                connectionIdString += connectionIdString == '' ? connectionId : ',' + connectionId;
                        connection.Comparing_Connections__c = connectionIdString;
                        connectionList.add(connection);
                    }
                }
                update connectionList; 

                return 'Success';
            }
        }
        catch(Exception ex) {
            return 'Failure : '+ ex.getMessage();
        }  
        return 'Success';
   }
}