src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Development_Environment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Development Environment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Story_Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CodeReviewStoriesController_Test.cls
@isTest
private class CodeReviewStoriesController_Test {
   
   @testSetup static void setupData() {
        
        Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
    List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
                                'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
                                'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
                                null, 'Net 30', 'test@test.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
                                1);
        insert accList;
        
        List<Project__c> projectList = TestDataFactory_Projects.generateProjects(accList[0].Id, 'Test Project', 1);
        insert projectList;
        
        List<Connection__c> connectionList = TestDataFactory_Connections.generateConnections(Constants.RECORDTYPEID_CONNECTION_PRODICTION, projectList[0].Id, 'Active', null, 2);
        connectionList[0].Status__c = 'Active';
        connectionList[0].Primary_Development_Environment__c = true;
        insert connectionList;
        
        List<Story__c> storyList = TestDataFactory_Stories.generateStories('testStory', projectList[0].id,'','',1);
        insert storyList;
        
        /*List<Release__c> releaseList = TestDataFactory_Releases.generateReleases(projectList[0].Id, connectionList[0].Id, connectionList[0].Id, 'TestRelease', 'Planned', System.today(), System.today().addDays(2), 1);
        releaseList[0].Created_On_Heroku__c = true;
        insert releaseList;*/
    }
    
    @isTest static void test_usecase_one() {
        List<Story__c> storyList = [Select Id From Story__c];
        
        Test.setMock(HttpCalloutMock.class, new MockResponse_HerokuConnection());
        Test.startTest();
          ApexPages.StandardController standardController = new ApexPages.StandardController(storyList[0]);
          CodeReviewStoriesController review = new CodeReviewStoriesController(standardController);
          System.assertEquals(storyList[0].Id, review.story.Id);
          
          CodeReviewStoriesController.scanCodeResult('Test123ATOZ');
          review.scanCode();
          review.releaseScanStatusStory();          
        Test.stopTest();
    }
    
    @isTest static void test_usecase_two() {
        List<Story__c> storyList = [Select Id From Story__c];
        System.assertEquals(1, storyList.size());
        
        List<Connection__c> connectionList = [Select Id,Status__c From Connection__c];
        System.assertEquals(2, connectionList.size());
        connectionList[0].Status__c = 'Inactive';
        connectionList[1].Status__c = 'Inactive';
        update connectionList;
        
        Test.setMock(HttpCalloutMock.class, new MockResponse_HerokuConnection());
        Test.startTest();
            ApexPages.StandardController standardController = new ApexPages.StandardController(storyList[0]);
            CodeReviewStoriesController review = new CodeReviewStoriesController(standardController);
            review.retriveReviewLogs();
            System.assertEquals(storyList[0].Id, review.story.Id);
        Test.stopTest();
    }
}