src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Development_Environment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Development Environment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Scan_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scan Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Heroku_Endpoint__mdt.object
<CustomObject>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Heroku Endpoint</label>
    <pluralLabel>Heroku Endpoints</pluralLabel>
</CustomObject>

src/objects/Heroku_oAuth_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Heroku_URL__c</fullName>
        <label>Heroku URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>IsSandbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSandbox</label>
        <type>Checkbox</type>
    </fields>
    <label>Heroku oAuth Setting</label>
    <pluralLabel>Heroku oAuth Settings</pluralLabel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Scan_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scan Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Story_Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CodeReviewStoriesController.cls
// Code Review COntroller for Story

public with sharing class CodeReviewStoriesController {
    public Story__c story                   {get;set;}
    public List<Log> logsList               {get;set;}
    public String baseUrl                   {get;set;}
    public boolean connectionExist          {get;set;}
    public boolean herokuExist              {get;set;}
    
    public CodeReviewStoriesController(ApexPages.StandardController std) {
    	logsList = new List<Log>();
        story   = [SELECT Id, Name, Scan_Running__c, Created_On_Heroku__c,Project__c 
                    FROM Story__c 
                    WHERE Id =: std.getRecord().Id];
        
        
        for(Project__c project : [SELECT Id,
                                    (SELECT Id, Name, Status__c, Primary_Development_Environment__c 
                                    FROM Connections__r 
                                    WHERE Status__c = 'Active' 
                                    ORDER BY CreatedDate ASC) 
                                FROM Project__c 
                                WHERE Id =: story.Project__c ]) {
            if(project.Connections__r != null && project.Connections__r.size() > 0) {
                connectionExist = true;
            }
            else {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'No active connection found for the Project of this Story.'));
            }
        }
        
        If(story.Created_On_Heroku__c != true) {
            herokuExist = false;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'This story does not exist on Heroku'));
        }
        else {
            herokuExist = true;
            retriveReviewLogs();
        }
        baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
    }
    
    public void retriveReviewLogs() {

        Map<String, String> herokuEndpointsMap  = new Map<String, String>();
        Organization orgz                       = [SELECT IsSandbox FROM Organization LIMIT 1];
        Heroku_oAuth_Setting__mdt credentials   = [SELECT ID, QualifiedApiName, Heroku_URL__c  
                                                    FROM Heroku_oAuth_Setting__mdt 
                                                    WHERE IsSandbox__c =: orgz.IsSandbox LIMIT 1];
        
        for(Heroku_Endpoint__mdt endpoint : [SELECT ID, QualifiedApiName, Endpoint__c FROM Heroku_Endpoint__mdt]) {
            herokuEndpointsMap.put(endpoint.QualifiedApiName, endpoint.Endpoint__c);
        }
    
        String token    = HerokuToken.headerToken();
        Http h          = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint(credentials.Heroku_URL__c + herokuEndpointsMap.get('Story_ReviewLogs') + story.Id);
        req.setMethod('GET');
        req.setHeader('token',token); 
        req.setTimeOut(120000);
        HttpResponse res = h.send(req); 
        
        if(res.getStatusCode() == 200 ) {
            ReviewLog dlog = (ReviewLog) JSON.deserialize(EncodingUtil.urlDecode(res.getBody(), 'UTF-8'), ReviewLog.class);
            //System.debug(dlog);
            if(dlog.Status == 'Success' && dlog.Log != null)
              logsList = dlog.Log;
        }
        
    }
    
    @remoteAction
    public static List<LogIssue> scanCodeResult(String scan_Id) {

        Map<String, String> herokuEndpointsMap  = new Map<String, String>();
        Organization orgz                       = [SELECT IsSandbox FROM Organization LIMIT 1];
        Heroku_oAuth_Setting__mdt credentials   = [SELECT ID, QualifiedApiName, Heroku_URL__c  
                                                    FROM Heroku_oAuth_Setting__mdt 
                                                    WHERE IsSandbox__c =: orgz.IsSandbox LIMIT 1];
        
        for(Heroku_Endpoint__mdt endpoint : [SELECT ID, QualifiedApiName, Endpoint__c FROM Heroku_Endpoint__mdt]) {
            herokuEndpointsMap.put(endpoint.QualifiedApiName, endpoint.Endpoint__c);
        }

        String token    = HerokuToken.headerToken();
        Http h          = new Http();
        HttpRequest req = new HttpRequest();
         req.setEndpoint(credentials.Heroku_URL__c + herokuEndpointsMap.get('Story_ScanResult') + scan_Id);
        req.setMethod('GET');
        req.setHeader('token',token); 
        req.setTimeOut(120000);
        
        HttpResponse res = h.send(req);
        System.debug(res);
        System.debug(res.getBody());
                
        List<LogIssue> logIssueList = new List<LogIssue>();
        if(res.getStatusCode() == 200 ){
            ReviewIssue scanLogIssue = (ReviewIssue) JSON.deserialize(EncodingUtil.urlDecode(res.getBody(), 'UTF-8'), ReviewIssue.class);
            //System.debug(scanLogIssue);
            if(scanLogIssue.Status == 'Success' && scanLogIssue.LogIssue != null)
              logIssueList = scanLogIssue.LogIssue; 
        }
          return logIssueList;
    }
    
    public void scanCode() {

        Map<String, String> herokuEndpointsMap  = new Map<String, String>();
        Organization orgz                       = [SELECT IsSandbox FROM Organization LIMIT 1];
        Heroku_oAuth_Setting__mdt credentials   = [SELECT ID, QualifiedApiName, Heroku_URL__c  
                                                    FROM Heroku_oAuth_Setting__mdt 
                                                    WHERE IsSandbox__c =: orgz.IsSandbox LIMIT 1];
        
        for(Heroku_Endpoint__mdt endpoint : [SELECT ID, QualifiedApiName, Endpoint__c FROM Heroku_Endpoint__mdt]) {
            herokuEndpointsMap.put(endpoint.QualifiedApiName, endpoint.Endpoint__c);
        }

        String token    = HerokuToken.headerToken();
        Http h          = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint(credentials.Heroku_URL__c + herokuEndpointsMap.get('Story_CodeReview') + story.Id);
        req.setMethod('GET');
        req.setHeader('token',token); 
        req.setTimeOut(120000);
        
        HttpResponse res = h.send(req);
        System.debug(res);
        System.debug(res.getBody());
        
        if(res.getStatusCode() == 200 ) 
        {
            CodeScan dlog = (CodeScan) JSON.deserialize(EncodingUtil.urlDecode(res.getBody(), 'UTF-8'), CodeScan.class);
            //System.debug(dlog);
            if(dlog.Status == 'Success' )
              story.Scan_Running__c = true;
        }
        update story;
    }
    
    
    public void releaseScanStatusStory() {      
        story = [SELECT Id, Name, Scan_Running__c, Created_On_Heroku__c,Project__c  FROM Story__c WHERE Id =: story.Id];
    }
    
    
    public class ReviewLog {
        public String Status {get;set;}
        public List<Log> Log {get;set;}
    }
    public class Log {
        public String logId     {get;set;}
        public String status    {get;set;}
        public String logTime   {get;set;}
    }
    public class ReviewIssue {
        public String Status;
        public List<LogIssue> LogIssue;
    }
    public class LogIssue {
        public String artifactType  {get;set;}
        public String artifactName  {get;set;}
        public String lineNo        {get;set;}
        public String violation     {get;set;}  
    }
    public class CodeScan {
        public String Status;
    }
}