src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Deletion__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow Deletion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Metadata_Describe_Error__c</fullName>
        <label>Metadata Describe Error</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Metadata_Last_Described__c</fullName>
        <label>Metadata Last Described</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Organization_URL__c</fullName>
        <label>Organization URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Development_Environment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Development Environment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Refresh_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Refresh Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Manage_Artifacts_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Manage Artifacts Setting</label>
    <pluralLabel>Manage Artifacts Settings</pluralLabel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Deletion__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow Deletion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Story_Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ManageArtifactsLightning.cls
public without sharing class ManageArtifactsLightning {
    
    @AuraEnabled
    public static MetadataLightningWrapper getMetadataFunctionality(Id recId,string selectedConnection,String recordsLimit,String searchText,String selectedMetadataType,String selectedMetadaListJson ) {
        selectedConnection              = selectedConnection == '' ? null : selectedConnection;
        Boolean alreagyHasConnection    = false;
        if(selectedConnection != null && selectedConnection.trim() != '')
            alreagyHasConnection = true;
        List<MetadataWrapper> wrapperListSelected = new List<MetadataWrapper>();
        if(selectedMetadaListJson != null && selectedMetadaListJson != '' && selectedMetadaListJson != '[]')
            wrapperListSelected = (List<MetadataWrapper>)JSON.deserialize(selectedMetadaListJson,List<MetadataWrapper>.class);
        else 
            wrapperListSelected = retrieveStoryArtifacts(recId);

        //--Retrieving existing story Artifacts.
        Map<String,Set<String>> storyArtifactsMap = new Map<String,Set<String>>(); 

        for(MetadataWrapper wrapperObj : wrapperListSelected) {
            if(wrapperObj.metadataType != null && wrapperObj.metadataType != '') {
                if(!storyArtifactsMap.containsKey(wrapperObj.metadataType))
                    storyArtifactsMap.put(wrapperObj.metadataType,new Set<String>());
                Set<String> artifactsSet = new Set<String>();
                if(wrapperObj.metadataName != null) {
                    for(MetadataName nameWrap : wrapperObj.metadataName)
                        artifactsSet.add(wrapperObj.metadataType + '##' +nameWrap.name);
                    storyArtifactsMap.get(wrapperObj.metadataType).addAll(artifactsSet);
                }
            }
        }

        Story__c story = new Story__c(); 
        List<SelectOptionCustom> connectionOption = new List<SelectOptionCustom>();
        List<SelectOptionCustom> metadataOption = new List<SelectOptionCustom>();
        
        //string selectedConnection ;
        
        for(Story__c tempStory : [SELECT Id, Name, Project__c  FROM Story__c  WHERE Id =: recId])
            story = tempStory ;
        if(!alreagyHasConnection) {
            for(Project__c project : [SELECT Id,(SELECT Id, Name, Status__c, Primary_Development_Environment__c FROM Connections__r WHERE Status__c = 'Active' ORDER BY CreatedDate ASC) FROM Project__c WHERE Id =: story.Project__c ]) {
                if(project.Connections__r != null && project.Connections__r.size() > 0) {
                    for(Connection__c con : project.Connections__r) {
                        connectionOption.add(new SelectOptionCustom(con.Id, con.Name));
                        if(con.Primary_Development_Environment__c == true)
                            selectedConnection = con.Id;
                    }
                    if(selectedConnection == null)
                        selectedConnection = project.Connections__r[0].Id;
                }
            } 
        } 

        Connection__c isRefresh = new Connection__c();
        if(selectedConnection != null && selectedConnection.trim() != '')
            isRefresh = [SELECT Id, Refresh_Running__c, Metadata_Last_Described__c, Project__c, Project__r.Name  
                        FROM Connection__c 
                        WHERE Id =: selectedConnection ];
        
        Manage_Artifacts_Setting__mdt defaultLimit  = [SELECT ID, QualifiedApiName, Limit__c  FROM Manage_Artifacts_Setting__mdt LIMIT 1];
        Integer recCount                            = Integer.valueOf(recordsLimit) + Integer.valueOf(defaultLimit.Limit__c);
        String requestJSONBody  = '"type":"'  + (selectedMetadataType == 'All' ? '' : selectedMetadataType) +'",'+ 
                                  '"name":"'  + (searchText == null ? '' : searchText) +'",'+
                                  '"limit":"' + recCount +'"';
        HttpResponse res = RestRequestHandlerForHeroku.sendRequest('POST','Connection_Metadata',requestJSONBody,selectedConnection,isRefresh.Project__c,isRefresh.Project__r.Name);
        
        List<MetadataWrapper> wrapperList = new List<MetadataWrapper>(); 
        if(res.getStatusCode() == 200) {
            
            MetadataResponse response = (MetadataResponse) JSON.deserialize(res.getBody(), MetadataResponse.class);
            if(response.Status == 'Success' && response.metadataList != null)
                wrapperList = response.metadataList;
        }
        wrapperList.sort();
        If(selectedConnection != null && selectedConnection != '')
            metadataOption.add(new SelectOptionCustom('All','All'));
        for(Integer index = 0;index < wrapperList.size() ;index++) {
            //--Setting metadata options.
            if(wrapperList[index].metadataType != null)
                metadataOption.add(new SelectOptionCustom(wrapperList[index].metadataType,wrapperList[index].metadataType));

            if(wrapperList[index].metadataName.size() > 0 && wrapperList[index].metadataName[0].name == '') {
                wrapperList.remove(index);
                index--;
                continue;
            }
            
            if(storyArtifactsMap.containsKey(wrapperList[index].metadataType)) {
                Set<MetadataName> metadataNameSet = new Set<MetadataName>(wrapperList[index].metadataName);
                for(MetadataName metadataName: wrapperList[index].metadataName) {
                    if(storyArtifactsMap.get(wrapperList[index].metadataType).contains(wrapperList[index].metadataType + '##' + metadataName.name))
                        metadataNameSet.remove(metadataName);
                }
                wrapperList[index].metadataName = new List<MetadataName>(metadataNameSet);
            }
        }  
        
        wrapperListSelected.sort();
        wrapperList.sort();
        return new MetadataLightningWrapper(isRefresh,recCount,story,connectionOption,metadataOption,selectedConnection, wrapperListSelected,wrapperList);
    }
    
    //---------------------------New 04 Oct 2017-----------------------------
    @AuraEnabled
    public static void createStoryArtifacts(Id recId,String mainMetadataWrapperStr) {
        List<MetadataWrapper> metadataBundleWrapper = (MetadataWrapper[])JSON.deserialize(mainMetadataWrapperStr, list<MetadataWrapper>.class);

        List<ArtifactWrapper> artifactsIdList = new List<ArtifactWrapper>();
        for(MetadataWrapper metadataWrapper : metadataBundleWrapper)
            for(MetadataName nameWrapp : metadataWrapper.metadataName)
                artifactsIdList.add(new ArtifactWrapper(nameWrapp.artifactId,nameWrapp.action));

        Story__c story = [SELECT Id, Project__c, Project__r.Name, Created_On_Heroku__c FROM Story__c WHERE Id =: recId];
        String Heroku_existence;
        if(story.Created_On_Heroku__c == true)
            Heroku_existence = 'true';
        else
            Heroku_existence = 'false'; 
        
        String requestJSONBody  = '"Heroku_existence":"' + Heroku_existence +'",'+ 
                                  '"Story_Artifacts":'   + JSON.serialize(artifactsIdList);
        
        HttpResponse res = RestRequestHandlerForHeroku.sendRequest('POST','Story_Artifacts_Create',requestJSONBody,recId,story.Project__c,story.Project__r.Name);
        if(res.getStatusCode() == 200) {
            ArtifactResponsetJSON response = (ArtifactResponsetJSON) JSON.deserialize(res.getBody(), ArtifactResponsetJSON.class);
            if(response.status == 'Success' ) {
                if(story.Created_On_Heroku__c == false) {
                    story.Created_On_Heroku__c = true;
                    update story;
                }
                List<Connection__c> connectionlist = [SELECT Id, Allow_Deletion__c FROM Connection__c WHERE Id IN: response.connectionIdList];
                if(connectionlist.size() > 0) {
                    for(Connection__c connection :connectionlist) {
                        connection.Allow_Deletion__c = false;
                    }
                    update connectionlist;
                }
            }
        }
    }
    
    public static List<MetadataWrapper> retrieveStoryArtifacts(Id recId) {
        Story__c story = [SELECT Id, Project__c, Project__r.Name, Created_On_Heroku__c FROM Story__c WHERE Id =: recId];
        HttpResponse res = RestRequestHandlerForHeroku.sendRequest('POST','Story_Artifacts_Retrieve','',recId,story.Project__c,story.Project__r.Name);
        List<MetadataWrapper> wrapperList = new List<MetadataWrapper>(); 
        if(res.getStatusCode() == 200) {
            MetadataResponse response = (MetadataResponse) JSON.deserialize(res.getBody(), MetadataResponse.class);
            //--Getting artifacts list from response.
            if(response.Status == 'Success' && response.metadataList != null && response.metadataList.size() > 0 && response.metadataList[0].metadataType != '')
                wrapperList = response.metadataList;
        }
        wrapperList.sort();
        return wrapperList;
    }
    //---------------------------New 04 Oct 2017-----------------------------

    @AuraEnabled
    public static Connection__c connectionRefreshStatus(String currentConnection) {
        Connection__c conn = [SELECT Id, Name, Project__c, Project__r.Name, Refresh_Running__c, Metadata_Last_Described__c 
                                FROM Connection__c 
                                WHERE Id =: currentConnection];
        return conn;
    }
    
    @AuraEnabled
    public static string refreshArtifacts(String selectedConnection) {
        Connection__c connection  = [SELECT Id, Name, RecordTypeId, Refresh_Running__c, Created_On_Heroku__c, 
                                        Metadata_Describe_Error__c, Organization_URL__c, Project__c, Project__r.Name 
                                    FROM Connection__c 
                                    WHERE Id =: selectedConnection];
        String connectionType;
        if(connection.RecordTypeId != Constants.RECORDTYPEID_CONNECTION_GITHUB) 
            connectionType = 'Salesforce';
        else 
            connectionType = 'Github';
        String requestJSONBody =  '"Action":"Refresh",'+
                                  '"Connection_Type":"' + connectionType + '"';
        HttpResponse res = RestRequestHandlerForHeroku.sendRequest('PUT','Connection_Update',requestJSONBody,selectedConnection,connection.Project__c,connection.Project__r.Name);
        String returnResopnse;
        if(res.getStatusCode() == 200 ) {
            ConnectionResponseWrapper response = (ConnectionResponseWrapper) JSON.deserialize(res.getBody(), ConnectionResponseWrapper.class);
            if(response.status == 'Success') {
                connection.Refresh_Running__c = true;
                connection.Metadata_Describe_Error__c = '';
                returnResopnse = 'Success';
            }
            else {
                connection.Metadata_Describe_Error__c = response.message;
                connection.Refresh_Running__c = false;
                returnResopnse = response.message;
            }
            update connection;
        }
        return returnResopnse ;
    }
    
    public Class MetadataLightningWrapper {
        @AuraEnabled public Story__c story                              {get;set;}
        @AuraEnabled public Connection__c isRefresh                     {get;set;}
        @AuraEnabled public Integer recCount                            {get;set;}
        @AuraEnabled public List<SelectOptionCustom> connectionOption   {get;set;}
        @AuraEnabled public List<SelectOptionCustom> metadataOption     {get;set;}
        @AuraEnabled public string selectedConnection                   {get;set;}
        @AuraEnabled public List<MetadataWrapper> wrapperListSelected   {get;set;}
        @AuraEnabled public List<MetadataWrapper> wrapperList           {get;set;}
        
        public MetadataLightningWrapper (Connection__c isRefresh,Integer recCount,Story__c story,List<SelectOptionCustom> connectionOption,List<SelectOptionCustom> metadataOption,string selectedConnection,List<MetadataWrapper> wrapperListSelected,List<MetadataWrapper> wrapperList ) {
            this.story                  = story;
            this.recCount               = recCount;
            this.connectionOption       = connectionOption;
            this.metadataOption         = metadataOption;
            this.selectedConnection     = selectedConnection;
            this.wrapperListSelected    = wrapperListSelected;
            this.wrapperList            = wrapperList;
            this.isRefresh              = isRefresh;
        }
    }

    public class SelectOptionCustom {
        @AuraEnabled public String label{get;set;}
        @AuraEnabled public String value{get;set;}
        
        public SelectOptionCustom(String value,String label){
            this.value = value;
            this.label = label;
        }
    }
    
    public class MetadataWrapper implements Comparable {
        @AuraEnabled public List<MetadataName> metadataName   {get;set;}
        @AuraEnabled public String metadataType               {get;set;}

        public Integer compareTo(Object compareTo) {
            MetadataWrapper other = (MetadataWrapper) compareTo;
            if (this.metadataType > other.metadataType)
              return 1;
            else if (this.metadataType == other.metadataType)
              return 0;
            return -1;
        }
    }

    public class MetadataName implements Comparable {
        @AuraEnabled public String name         {get;set;}
        @AuraEnabled public String action       {get;set;}
        @AuraEnabled public String artifactId   {get;set;}

        public MetadataName(String name,String action,String artifactId) {
            this.name       = name;
            this.action     = action;
            this.artifactId = artifactId;

        }

        public Integer compareTo(Object compareTo) {
            MetadataName other = (MetadataName) compareTo;
            if (this.name > other.name)
              return 1;
            else if (this.name == other.name)
              return 0;
            return -1;
        }
    }
    
    public class MetadataResponse {
        @AuraEnabled public String Status;
        @AuraEnabled public List<MetadataWrapper> metadataList;
    }
    
    public class ConnectionResponseWrapper {
        @AuraEnabled public String message;
        @AuraEnabled public String status;
    }

    //---------------------------New 04 Oct 2017-----------------------------
    class ArtifactWrapper {
        @AuraEnabled public String artifact_Id;
        @AuraEnabled public String action;

        public ArtifactWrapper(String artifact_Id, String action) {
            this.artifact_Id = artifact_Id;
            this.action = action;
        }
    }
    
    public class ArtifactResponsetJSON {
        @AuraEnabled public String message;  //Story Artifact updated successfully.
        @AuraEnabled public String status;   //Success
        @AuraEnabled public List<String> connectionIdList;   //[111aXXX, 222aYYY, 333aZZZ]
    }
}