src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Development_Environment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Development Environment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>AsyncResultId__c</fullName>
        <label>Async Result Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Connection__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Connection__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Connection__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Connection__c</referenceTo>
        <relationshipLabel>Releases (Target)</relationshipLabel>
        <relationshipName>Releases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Validation_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validation Running</label>
        <type>Checkbox</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ValidateDeploymentLightning_Test.cls
@isTest
private class ValidateDeploymentLightning_Test {
    
    @testSetup static void setupData() {
    	
    	Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
		List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
    														'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
    														'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
    														null, 'Net 30', 'test@test.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
    														1);
        insert accList;
        
        List<Project__c> projectList = TestDataFactory_Projects.generateProjects(accList[0].Id, 'Test Project', 1);
        insert projectList;
        
      	List<Connection__c> connectionList = TestDataFactory_Connections.generateConnections(Constants.RECORDTYPEID_CONNECTION_PRODICTION, projectList[0].Id, 'Active', null, 1);
      	connectionList[0].Status__c = 'Active';
        connectionList[0].Primary_Development_Environment__c = true;
        connectionList[0].Created_On_Heroku__c = true;
      	insert connectionList;
      	
      	List<Release__c> releaseList = TestDataFactory_Releases.generateReleases(projectList[0].Id, connectionList[0].Id, connectionList[0].Id, 'TestRelease', 'Planned', System.today(), System.today().addDays(2), 2);
        releaseList[0].Created_On_Heroku__c = true;
        releaseList[1].Created_On_Heroku__c = false;
        insert releaseList;
    }
      
    @isTest static void use_testcase_one() {
        
        List<Release__c> releaseList = [Select Id From Release__c];
        System.assertEquals(2, releaseList.size());
       
        Test.setMock(HttpCalloutMock.class, new MockResponse_HerokuConnection());
        
        Test.startTest();
	    	String JSNStr = ValidateDeploymentLightning.init(releaseList[0].Id);
	    	
	    	ValidateDeploymentLightning.retriveDeploymentLogIssues('Test123ATOZ',releaseList[0].Id);
            //String checkOnly, Id releaseId,Boolean runAllTests,String testClassNames,String recentValidationId
	     	ValidateDeploymentLightning.deployMetadata('true',releaseList[0].Id,'','','');
	     	
	     	
	        
	        ValidateDeploymentLightning.LogResponse dlog = (ValidateDeploymentLightning.LogResponse) JSON.deserialize(JSNStr, ValidateDeploymentLightning.LogResponse.class);
	    	System.assert(dlog.logList.size() > 0);
        Test.stopTest();
    }
    
    @isTest static void use_testcase_two() {
        
        List<Release__c> releaseList = [Select Id,Created_On_Heroku__c From Release__c];
        releaseList[0].Created_On_Heroku__c = false;
        releaseList[0].Source__c = null;
        releaseList[0].Target__c = null;
        update releaseList;
        System.assertEquals(2, releaseList.size());
       
        Test.setMock(HttpCalloutMock.class, new MockResponse_HerokuConnection());
        
        Test.startTest();
	    	String JSNStr = ValidateDeploymentLightning.init(releaseList[0].Id);
	    	
	    	ValidateDeploymentLightning.retriveDeploymentLogIssues('Test123ATOZ',releaseList[0].Id);
            //String checkOnly, Id releaseId,Boolean runAllTests,String testClassNames,String recentValidationId
	     	ValidateDeploymentLightning.deployMetadata('true',releaseList[0].Id,'','','');
	        
	        ValidateDeploymentLightning.LogResponse dlog = (ValidateDeploymentLightning.LogResponse) JSON.deserialize(JSNStr, ValidateDeploymentLightning.LogResponse.class);
        Test.stopTest();
    }
    
    @isTest static void use_testcase_three() {
        
        List<Release__c> releaseList = [Select Id,Created_On_Heroku__c,Validation_Running__c,AsyncResultId__c From Release__c];
        releaseList[0].Validation_Running__c = true;
        releaseList[0].AsyncResultId__c = 'a0X2C000000E9zIUAS';
        update releaseList;
        System.assertEquals(2, releaseList.size());
       
        Test.setMock(HttpCalloutMock.class, new MockResponse_HerokuConnection());
        
        Test.startTest();
	     	ValidateDeploymentLightning.ValidationResponseWrapper wrap = ValidateDeploymentLightning.retrieveRelease(releaseList[0].Id);
	     	System.assertEquals(releaseList[0].Id,wrap.release.Id);
        Test.stopTest();
    }

    @isTest static void use_testcase_four() {
        
        List<Release__c> releaseList = [Select Id,Source__c,Target__c From Release__c];
        releaseList[0].Source__c = null;
        update releaseList;
        System.assertEquals(2, releaseList.size());
       
        Test.setMock(HttpCalloutMock.class, new MockResponse_HerokuConnection());
        
        Test.startTest();
            String JSNStr = ValidateDeploymentLightning.init(releaseList[0].Id);
            System.assertNotEquals(JSNStr,null);
        Test.stopTest();
    }

    @isTest static void use_testcase_five() {
        
        List<Release__c> releaseList = [Select Id,Source__c,Target__c From Release__c];
        releaseList[0].Target__c = null;
        update releaseList;
        System.assertEquals(2, releaseList.size());
       
        Test.setMock(HttpCalloutMock.class, new MockResponse_HerokuConnection());
        
        Test.startTest();
            String JSNStr = ValidateDeploymentLightning.init(releaseList[0].Id);
            System.assertNotEquals(JSNStr,null);
        Test.stopTest();
    }
    @isTest static void test_usecase_six() {
        
        List<Release__c> releaseList = [Select Id From Release__c];
        System.assertEquals(2, releaseList.size());
       
        Test.setMock(HttpCalloutMock.class, new MockResponse_HerokuConnection());
        Test.startTest();
            ValidateDeploymentLightning.manageRelease(releaseList[0].Id);
            ValidateDeploymentLightning.manageRelease(releaseList[1].Id);
            
            releaseList = [Select Id From Release__c WHERE Id=:releaseList[1].Id AND Created_On_Heroku__c=true];
            System.assertEquals(1, releaseList.size());
        Test.stopTest();
    }
}