src/objects/ConnectedApp__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Connected App Settings</description>
    <fields>
        <fullName>Callback_URL__c</fullName>
        <label>Callback URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ConnectedApp</label>
</CustomObject>

src/objects/Countries_Regions_Continents_ISO_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Countries, Regions, Continents and ISO Codes</description>
    <fields>
        <fullName>Continent__c</fullName>
        <label>Continent</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_2__c</fullName>
        <label>ISO (2)</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_3__c</fullName>
        <label>ISO (3)</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Countries Regions Continents ISO Codes</label>
</CustomObject>

src/objects/Endpoint_URIs__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ContactId_URI_Salesforce_Certificate__c</fullName>
        <label>ContactId URI Salesforce Certificate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesforceCertificates_URI__c</fullName>
        <label>SalesforceCertificates URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrailheadBadges_URI_Trailhead__c</fullName>
        <label>TrailheadBadges URI Trailhead</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Endpoint URIs</label>
</CustomObject>

src/objects/GoogleAuthSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to store Access Token &amp; Refresh Token that would be generated at the first time with other details</description>
    <fields>
        <fullName>API_Key__c</fullName>
        <label>API Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GoogleClientID__c</fullName>
        <label>GoogleClientID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GoogleClientSecret__c</fullName>
        <label>GoogleClientSecret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X10K_Domain__c</fullName>
        <label>10K Domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Google Auth Settings</label>
</CustomObject>

src/classes/TestDataFactory_CustomSettings.cls
public with sharing class TestDataFactory_CustomSettings {
    
    public static List<Countries_Regions_Continents_ISO_Codes__c> generateCountriesRegionsContinentsISOCodes(String continent, String country, String ISO2, String ISO3, String Region, Integer numOfRecords) {
        return generateCountriesRegionsContinentsISOCodesInternal(continent, country, ISO2, ISO3, Region, numOfRecords);
    }
    
    private static List<Countries_Regions_Continents_ISO_Codes__c> generateCountriesRegionsContinentsISOCodesInternal(String continent, String country, String ISO2, String ISO3, String Region, Integer numOfRecords) {
        
        List<Countries_Regions_Continents_ISO_Codes__c> countriesRegionsContinentsISOCodesList = new List<Countries_Regions_Continents_ISO_Codes__c>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
            Countries_Regions_Continents_ISO_Codes__c crcISOcode = new Countries_Regions_Continents_ISO_Codes__c();
            crcISOcode.Name          = country;
            crcISOcode.Continent__c  = continent;
            crcISOcode.Country__c    = country;
            crcISOcode.ISO_2__c      = ISO2;
            crcISOcode.ISO_3__c      = ISO3;
            crcISOcode.Region__c     = Region;
            countriesRegionsContinentsISOCodesList.add(crcISOcode);
        }
        
        return countriesRegionsContinentsISOCodesList;
    }
    
    public static void initializeEndpointURIsCustomSetting() {
        try {
            Endpoint_URIs__c customSetting                          = Endpoint_URIs__c.getOrgDefaults();
            customSetting.TrailheadBadges_URI_Trailhead__c          = 'https://trailhead.salesforce.com/me/';
            customSetting.ContactId_URI_Salesforce_Certificate__c   = 'http://certification.salesforce.com/verification-email?init=1&email=';
            customSetting.SalesforceCertificates_URI__c             = 'http://certification.salesforce.com/certification-detail?conId=';
            update customSetting;
        }
        catch (Exception ex) {
            Endpoint_URIs__c customSetting                          = new Endpoint_URIs__c();
            customSetting.TrailheadBadges_URI_Trailhead__c          = 'https://trailhead.salesforce.com/me/';
            customSetting.ContactId_URI_Salesforce_Certificate__c   = 'http://certification.salesforce.com/verification-email?init=1&email=';
            customSetting.SalesforceCertificates_URI__c             = 'http://certification.salesforce.com/certification-detail?conId=';
            insert customSetting;
        }
    }
    
    public static List<GoogleAuthSettings__c> generateGoogleAuthSettings(String name, String googleClientId, String googleclientSecret, String APIKey, String domain10k) {
        return generateGoogleAuthSettingsInternal(name, googleClientId, googleclientSecret, APIKey, domain10k);
    }
    
    private static List<GoogleAuthSettings__c> generateGoogleAuthSettingsInternal(String name, String googleClientId, String googleclientSecret, String APIKey, String domain10k) {
        
        List<GoogleAuthSettings__c> googleAuthLi    = new List<GoogleAuthSettings__c>();
                                                        
        GoogleAuthSettings__c objCustomSetting      = new GoogleAuthSettings__c();
        objCustomSetting.Name                       = name;
        objCustomSetting.GoogleClientID__c          = googleClientId;
        objCustomSetting.GoogleClientSecret__c      = googleclientSecret;
        objCustomSetting.API_Key__c                 = APIKey;
        objCustomSetting.X10K_Domain__c             = domain10k;
        googleAuthLi.add(objCustomSetting);
        
        return googleAuthLi;
    }
    
    public static ConnectedApp__c createConnectedAppCustomSetting() {
        /*ConnectedApp__c credentials = new ConnectedApp__c( Callback_URL__c = URL.getSalesforceBaseUrl().toExternalForm() + '/apex/AuthorizeSalesforceOrg', 
                                                            Consumer_Key__c = '3MVG9hq7jmfCuKfcGjlDxJufcTij8DYinl.ioRbU7QNTrZC8q67ySP3hrO.hcTzWYMk8AjBySMwCqkNlYA1jI', 
                                                            Consumer_Secret__c = '3922199713804899562' ); */
        ConnectedApp__c credentials = new ConnectedApp__c( Callback_URL__c = URL.getSalesforceBaseUrl().toExternalForm() + '/apex/AuthorizeSalesforceOrg', 
                                                            Consumer_Key__c = '3MVG9uudbyLbNPZNRb0Klk8MWh1YXLQzh8Pg9FaT3rn.K7NUg3GJtltUqeHl2sD8AujLMvuHYhRxrTJfg2Nni', 
                                                            Consumer_Secret__c = '8679647137275828905' );                                                    
                                                            
        insert credentials;
        return credentials;
    }
}