src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Release_Date__c</fullName>
        <label>Actual Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Connection__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Connection__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Release_Date__c</fullName>
        <label>Target Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Connection__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Connection__c</referenceTo>
        <relationshipLabel>Releases (Target)</relationshipLabel>
        <relationshipName>Releases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Created_On_Heroku__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created On Heroku</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Story_Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ViewReleaseMetadataLightning.cls
public class ViewReleaseMetadataLightning {
    
    @AuraEnabled
    public Static String getInit(String releaseId)
    {
        Release__c release = [SELECT Id, Name, Project__c, Project__r.Name, Status__c, Source__c, Source__r.Status__c, Target__c, Actual_Release_Date__c,
                                    Target_Release_Date__c, Created_On_Heroku__c 
                                FROM Release__c 
                   			    WHERE Id =: releaseId]; 

        ReleaseStuff obj = searchStory(release);
        //System.debug(obj);
        return JSON.serialize(obj);
    }
    
    public static ReleaseStuff searchStory(Release__c release) {
        Map<String, String> storyMap            = new Map<String, String>();         
        List<ReleaseStories> releaseStoryList   = new List<ReleaseStories>();
        List<Artifacts> releaseArtifactList     = new List<Artifacts>();
        List<Stories> storyList                 = new List<Stories>();
        Set<String> selectedStory               = new Set<String>();

        HttpResponse res = RestRequestHandlerForHeroku.sendRequest('POST','Release_StoriesArtifacts_Retrieve','',release.Id,release.Project__c,release.Project__r.Name);
       
        if(res.getStatusCode() == 200 ) {
            ReleaseArtifactResponseJSON searchStory = (ReleaseArtifactResponseJSON) JSON.deserialize(res.getBody(), ReleaseArtifactResponseJSON.class);
            if(searchStory.Status == 'Success') {
                for(ReleaseStories record : searchStory.ReleaseStories) {
					if(record.storyId != '') {
						if(record.artifacts[0].metadataType != '')
							releaseStoryList.add(record);
						else {
							record.artifacts = new List<Artifacts>();
							releaseStoryList.add(record);
						}
					}
					else {
						if(record.artifacts[0].metadataType != '')
							releaseArtifactList = record.artifacts;
					}
				}
            }
        }
        
        if(releaseStoryList.size() > 0) {
        	List<String> storyIdList = new List<String>();
        	for(ReleaseStories story : releaseStoryList)
        		storyIdList.add(story.storyId);
        	List<Story__c> releaseStory = [SELECT Id, Name FROM Story__c WHERE Id IN:storyIdList];
	        if(releaseStory != null) {
	        	for(Story__c story : releaseStory)
	        		storyMap.put(story.Id, Story.Name);
	        	for(ReleaseStories story : releaseStoryList) {
                    story.artifacts.sort();
                    Stories newStory     = new Stories();
                    newStory.storyId     = story.storyId;
                    newStory.storyName   = storyMap.get(story.storyId);
	        		newStory.artifacts   = story.artifacts;
	        		storyList.add(newStory);
	        	}
	        }
        }

        releaseArtifactList.sort();
        ReleaseStuff obj        = new ReleaseStuff();
        obj.releaseArtifactList = releaseArtifactList;
        obj.releaseStoryList    = storyList;
        return obj;
    }
	
	public class ReleaseArtifactResponseJSON {
        public String Status;
        public List<ReleaseStories> ReleaseStories;
    }

    public class ReleaseStories {
        public String storyId				{get;Set;}
        public List<Artifacts> artifacts	{get;Set;}
    }

    public class Artifacts implements Comparable {
        @AuraEnabled public String metadataType              {get;Set;}
        @AuraEnabled public List<MetadataName> metadataName  {get;set;} 

        public Integer compareTo(Object compareTo) {
            Artifacts other = (Artifacts) compareTo;
            if (this.metadataType > other.metadataType)
              return 1;
            else if (this.metadataType == other.metadataType)
              return 0;
            return -1;
        }
    }

    public class MetadataName {
        @AuraEnabled public String name          {get;set;}
        @AuraEnabled public String action        {get;set;}
        @AuraEnabled public String artifactId    {get;set;}
    }
    
    public class ReleaseStuff {
    	@AuraEnabled public String baseUrl                          {get{return  Site.getPathPrefix().split('/s')[0];} set;}
        @AuraEnabled public List<Artifacts> releaseArtifactList		{get;set;}
        @AuraEnabled public List<Stories>  releaseStoryList  	    {get;set;}
    }
    
    public class Stories {
        @AuraEnabled public String storyId				{get;Set;}
        @AuraEnabled public String storyName			{get;Set;}
        @AuraEnabled public List<Artifacts> artifacts	{get;Set;}
    }
}