src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disabled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RemoveAuthConnectionController_Test.cls
@isTest
private class RemoveAuthConnectionController_Test {
  
	@testSetup static void setupData() {
		
	    Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
		List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
    														'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
    														'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
    														null, 'Net 30', 'test@test.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
    														1);
        insert accList;
        
        List<Project__c> projectList = TestDataFactory_Projects.generateProjects(accList[0].Id, 'Test Project', 1);
        insert projectList;
        
      	List<Connection__c> connectionList = TestDataFactory_Connections.generateConnections(Constants.RECORDTYPEID_CONNECTION_PRODICTION, projectList[0].Id, 'Inactive', null, 1);
      	insert connectionList;
  	}
  	
  	static testMethod void test_usecase_one() {
  		
  		List<Connection__c> connectionList = [Select Id From Connection__c];
  		System.assertEquals(1, connectionList.size());
  		
	    ApexPages.StandardController sc = new ApexPages.StandardController(connectionList[0]);
	    RemoveAuthConnectionController cntrlr = new RemoveAuthConnectionController(sc);
	    
	    Test.startTest();
			cntrlr.returnBack();
	    	System.assertEquals(connectionList[0].Id,cntrlr.connection.Id);
	    Test.stopTest();
  	}
  	
  	static testMethod void test_usecase_two() {
  		
  		List<Connection__c> connectionList = [Select Id From Connection__c];
	    ApexPages.StandardController sc = new ApexPages.StandardController(connectionList[0]);
	    RemoveAuthConnectionController cntrlr = new RemoveAuthConnectionController(sc);
	    
	    Test.setMock(HttpCalloutMock.class, new MockResponse_HerokuConnection());
	    
	    Test.startTest();
	      	RemoveAuthConnectionController.removeAuth(connectionList[0].Id);
	      	Connection__c con = [SELECT Id, Status__c FROM Connection__c WHERE Id =:connectionList[0].Id];
	      	System.assertEquals(con.Status__c,'Disabled');
	    Test.stopTest();
  	}
}