src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Lifetime_Points_Earned__c</fullName>
        <label>Lifetime Points Earned</label>
        <summarizedField>Points__c.Number_of_Points__c</summarizedField>
        <summaryForeignKey>Points__c.Contact__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Lifetime_Points_Redeemed__c</fullName>
        <label>Lifetime Points Redeemed</label>
        <summarizedField>Order__c.Total_Points_Redeemed__c</summarizedField>
        <summaryForeignKey>Order__c.Contact__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Points__c.object
<CustomObject>
    <fields>
        <fullName>Points_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Points Rule</label>
        <referenceTo>Points_Rule__c</referenceTo>
        <relationshipLabel>Points</relationshipLabel>
        <relationshipName>Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Points</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Points Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Points_Rule__c.object
<CustomObject>
    <fields>
        <fullName>My_Points_Display_Name__c</fullName>
        <label>My Points Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Points Rule</label>
    <nameField>
        <label>Points Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Points_Rule_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Points_Rule__c</fullName>
        <label>Points Rule</label>
        <referenceTo>Points_Rule__c</referenceTo>
        <relationshipLabel>Points Rule Criteria</relationshipLabel>
        <relationshipName>Points_Rule_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Points Rule Criteria</label>
    <nameField>
        <label>Points Rule Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points Rule Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Stories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Story_Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PointDetailController_Test.cls
@isTest
private class PointDetailController_Test {
	
	@isTest static void test_PointDetailController() {
		
		Test.startTest();
			List<User> userList = TestDataFactory_Users.generateUsersWith10KDeliveryPartnerProfile(true, 1);
			insert userList;
		Test.stopTest();
		
		Id partnerClientrecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('Partner Client').RecordTypeId;
		List<Account> accList = TestDataFactory_Accounts.generateAccounts(partnerClientrecordTypeId, 'Test1', 'Prospect', 15, 'code coverage', 'internal',
    														'App Cloud;Sales Cloud', 'Enterprise', 'ISV', 'Sensitive Information', 'JIRA', 'GotoMeeting', 'Use 10k portal', 
    														'code quality with code coverage above 75%', 'NDA aggrement', 'United States', '501 test street', 'test city', 'Florida', '90001', null,
    														null, 'Net 30', 'test@test.com', 'Test-6', 'HELLO WORLD', 'invoicingNotes', 'Partner Client',
    														1);
        insert accList;
        
        List<Contact> contactList = TestDataFactory_Contacts.generatecontacts(accList, 'Test contact', 'lastName', '', '', 1);
        insert contactList;
        
        List<Project__c> projectList = TestDataFactory_Projects.generateProjects(accList[0].Id, 'Test Project', 1);
        insert projectList;
        
        List<Story__c> storiesList = TestDataFactory_Stories.generateStories('Test Story', projectList[0].Id, 'Completed', 'Medium', 2);
        storiesList[0].Delivery_Owner__c = userList[0].Id;
        storiesList[1].Delivery_Owner__c = userList[0].Id;
        insert storiesList;
        
        Id systemRecordTypeId = Schema.SObjectType.Points_Rule__c.RecordTypeInfosByName.get('System Generated').RecordTypeId;
        
        List<Points_Rule__c> pointRuleRecList = TestDataFactory_PointRules.generatePointRules(true, 'AND', 'Delivery_Owner__r.ContactId', 'Story__c', 10, systemRecordTypeId, 2);
        System.debug('pointRuleRecList'+pointRuleRecList);
        pointRuleRecList[0].My_Points_Display_Name__c = 'Project__r.Name';
        insert pointRuleRecList;
        
        List<Points_Rule_Criteria__c> pointRuleCriteriaList = TestDataFactory_PointsRuleCriteria.generatePointRuleCriteria('Status__c', 'Completed', '=', pointRuleRecList[0].Id, 1);
        insert pointRuleCriteriaList;
        
        List<Points__c> pointList = TestDataFactory_Points.generatePoints(storiesList[0].Id, userList[0].ContactId, 20, pointRuleRecList[0].Id, 1);
        pointList.addAll(TestDataFactory_Points.generatePoints(storiesList[1].Id, userList[0].ContactId, 20, pointRuleRecList[0].Id, 1));
        insert pointList;

		System.runAs(userList[0]) {
			//Test.startTest();
				PointDetailController.retPoints();
                pointRuleRecList[0].My_Points_Display_Name__c = 'Test Name';
                update pointRuleRecList;
                PointDetailController.retPoints();
                pointRuleRecList[0].My_Points_Display_Name__c = 'Project__c';
                update pointRuleRecList;
                PointDetailController.retPoints();
				Contact con = [SELECT Id, Lifetime_Points_Earned__c, Lifetime_Points_Redeemed__c FROM Contact WHERE Id =: userList[0].ContactId];
				System.assertEquals(con.Lifetime_Points_Earned__c, 40);
			//Test.stopTest();
		}
	}
}