src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Lifetime_Points_Earned__c</fullName>
        <label>Lifetime Points Earned</label>
        <summarizedField>Points__c.Number_of_Points__c</summarizedField>
        <summaryForeignKey>Points__c.Contact__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Lifetime_Points_Redeemed__c</fullName>
        <label>Lifetime Points Redeemed</label>
        <summarizedField>Order__c.Total_Points_Redeemed__c</summarizedField>
        <summaryForeignKey>Order__c.Contact__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Merchandise__c</fullName>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity_On_Hand__c</fullName>
        <formula>Total_Quantity__c - Quantity_Redeemed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity On Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Redeemed__c</fullName>
        <label>Quantity Redeemed</label>
        <summarizedField>Order_Line_Item__c.Quantity_Ordered__c</summarizedField>
        <summaryForeignKey>Order_Line_Item__c.Item__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <picklist>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XXXL</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Quantity__c</fullName>
        <label>Total Quantity</label>
        <summarizedField>Inventory__c.Quantity_Purchased_Value__c</summarizedField>
        <summaryForeignKey>Inventory__c.Item__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Item</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Orders_for_Sold_Out_Items__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Orders for Sold Out Items</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Display_Sizes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display Sizes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Estimated_Shipping_Cost__c</fullName>
        <label>Estimated Shipping Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Free_Merchandise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Free Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Merchandise</relationshipLabel>
        <relationshipName>Merchandise</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Omit_from_Store__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Omit from Store</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Point_Value__c</fullName>
        <label>Point Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>Zip Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Free_Order_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Free Order Line Item</label>
        <referenceTo>Order_Line_Item__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity_Ordered__c</fullName>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Points_Redeemed_Text__c</fullName>
        <label>Total Points Redeemed Text</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{0000}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MerchandiseStoreController.cls
public with sharing class MerchandiseStoreController 
{
	@AuraEnabled
	public static List<Merchandise__c> getMerchandise()
	{
		List<Merchandise__c> merchandiseList = [SELECT Id, Free_Merchandise__c,Name, Cost__c, Description__c, Estimated_Shipping_Cost__c, Picture__c, Point_Value__c, 
													Allow_Orders_for_Sold_Out_Items__c, Display_Sizes__c, 
														(SELECT Id, Name, Merchandise__r.Name, Merchandise__r.Display_Sizes__c, Merchandise__r.Point_Value__c, Quantity_On_Hand__c, Quantity_Redeemed__c, Total_Quantity__c, Size__c 
														FROM Items__r)
													FROM Merchandise__c 
													WHERE Point_Value__c != null 
													AND Omit_from_Store__c != True];

		List<Merchandise__c> merchandiseWrapperList = new List<Merchandise__c>();
		for(Merchandise__c merchant : merchandiseList)
		{
			if((merchant.Items__r).size() > 0)
			{
				Boolean merchandiseValidForDisplay = false;
				for(Item__c item : merchant.Items__r)
				{
					if((merchant.Allow_Orders_for_Sold_Out_Items__c && merchant.Display_Sizes__c) || item.Quantity_On_Hand__c > 0)
					{
						merchandiseValidForDisplay = true;
					}
				}
				if(merchandiseValidForDisplay)
					merchandiseWrapperList.add(merchant);
			}
		}
		return merchandiseWrapperList;
	}

	@AuraEnabled
	public static UserContactWrapp getPoints()
	{
		String contactId;
		List<User> userList = [SELECT Id, ContactId FROM USER WHERE Id=: UserInfo.getUserId()];
		List<Contact> contactList = [SELECT Id, MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry, Email, Phone, FirstName, LastName, Lifetime_Points_Earned__c, Lifetime_Points_Redeemed__c, AccountId FROM Contact WHERE Id =:userList[0].ContactId];
		if(!contactList.isEmpty()){
			List<Account> accountList = [SELECT ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, ShippingCountry FROM Account WHERE Id =: contactList[0].AccountId];
			contactList[0].MailingStreet 		= accountList[0].ShippingStreet;
			contactList[0].MailingCity 			= accountList[0].ShippingCity;
			contactList[0].MailingState 		= accountList[0].ShippingState;
			contactList[0].MailingPostalCode 	= accountList[0].ShippingPostalCode;
			contactList[0].MailingCountry 		= accountList[0].ShippingCountry;
			UserContactWrapp contactWrap = new UserContactWrapp();
			contactWrap.contactDetail = contactList[0];
			contactId = contactList[0].Id;

			List<CartQuantityWrap> oldCartItemsList = new List<CartQuantityWrap>();
			Map<String,Integer> merchantIdToQuantityMap = new Map<String,Integer>();
			Map<Id,Order_Line_Item__c> itemIdtoOliMap = new Map<Id,Order_Line_Item__c>();
			Map<Id,Order_Line_Item__c> freeoliIdtoOliMap = new Map<Id,Order_Line_Item__c>();
			List<Order_Line_Item__c> oliListToBeDeleted = new List<Order_Line_Item__c>();
			Set<Id> merchandiseIdSet = new Set<Id>();
			List<Order__c> orderList = [SELECT Id, Status__c,
										(SELECT Free_Order_Line_Item__c, Id, Order__c, Item__c, Item__r.Merchandise__c, Quantity_Ordered__c 
											FROM Order_Line_Items__r) 
										FROM Order__c 
										WHERE Status__c = 'Draft' 
										AND Contact__c =: contactId];
            
			if(!orderList.isEmpty())
			{
                for(Order_Line_Item__c oli : orderList[0].Order_Line_Items__r)
				{	
					if(oli.Quantity_Ordered__c != null && oli.Free_Order_Line_Item__c == null){
						merchantIdToQuantityMap.put(oli.Item__c, Integer.valueOf(String.valueOf(oli.Quantity_Ordered__c)));
						itemIdtoOliMap.put(oli.Item__c,oli);
						merchandiseIdSet.add(oli.Item__r.Merchandise__c);
					}
					
					

					if(oli.Free_Order_Line_Item__c != null){
						freeoliIdtoOliMap.put(oli.Free_Order_Line_Item__c ,oli);
					}
					
				}
			}

			List<Merchandise__c> oldCartMerchantList = new List<Merchandise__c>();
			List<Order_Line_Item__c> orderLineItemFreeList = new List<Order_Line_Item__c>();
			if(!merchantIdToQuantityMap.isEmpty())
			{
				List<Merchandise__c> oldCartItemsLst = [SELECT Id,Free_Merchandise__c, Name, Cost__c, Description__c, Estimated_Shipping_Cost__c, Picture__c, Point_Value__c, 
														Allow_Orders_for_Sold_Out_Items__c, Display_Sizes__c, 
															(SELECT Id, Name, Quantity_On_Hand__c, Quantity_Redeemed__c, Total_Quantity__c, Size__c 
															FROM Items__r) 
														FROM Merchandise__c 
														WHERE Id IN : merchandiseIdSet];
														//
				Map<Id,List<Item__c>> freeMerchandiseIdToItemsMap = new Map<Id,List<Item__c>>();										
				for(Merchandise__c oldCartMerchandise : [SELECT Id,Free_Merchandise__c, Name, Cost__c, Description__c, Estimated_Shipping_Cost__c, Picture__c, Point_Value__c, 
														Allow_Orders_for_Sold_Out_Items__c, Display_Sizes__c, 
															(SELECT Id, Name, Quantity_On_Hand__c, Quantity_Redeemed__c, Total_Quantity__c, Size__c 
															FROM Items__r) 
														FROM Merchandise__c ]) {
					freeMerchandiseIdToItemsMap.put(oldCartMerchandise.Id, oldCartMerchandise.Items__r);
				}
				for(Merchandise__c oldCartMerchandise : oldCartItemsLst)
				{
					oldCartMerchantList.add(oldCartMerchandise);
					for(Item__c oldCartItem : oldCartMerchandise.Items__r)
					{
						if(merchantIdToQuantityMap.containsKey(oldCartItem.Id))
						{
							CartQuantityWrap cartQuantity = new CartQuantityWrap();
							cartQuantity.oldCartItem = oldCartItem;
							cartQuantity.relatedMerchandisePointValue = Integer.valueOf(oldCartMerchandise.Point_Value__c);
							cartQuantity.quantityOrdered = merchantIdToQuantityMap.get(oldCartItem.Id);
							oldCartItemsList.add(cartQuantity);
						}

						if(itemIdtoOliMap.containskey(oldCartItem.Id)){
							if(oldCartMerchandise.Free_Merchandise__c == null && freeoliIdtoOliMap.containsKey(itemIdtoOliMap.get(oldCartItem.Id).Id)){
								oliListToBeDeleted.add(freeoliIdtoOliMap.get(itemIdtoOliMap.get(oldCartItem.Id).Id));
							}
							if(oldCartMerchandise.Free_Merchandise__c != null && !freeoliIdtoOliMap.containsKey(itemIdtoOliMap.get(oldCartItem.Id).Id)){
								Order_Line_Item__c orderLineItemFree = new Order_Line_Item__c();
								for(Item__c item : freeMerchandiseIdToItemsMap.get(oldCartMerchandise.Free_Merchandise__c)){
									if(item.Quantity_On_Hand__c > 0){
										orderLineItemFree.Item__c = item.Id;
										break;
									}
								}
								orderLineItemFree.Order__c = itemIdtoOliMap.get(oldCartItem.Id).Order__c;
								orderLineItemFree.Free_Order_Line_Item__c =  itemIdtoOliMap.get(oldCartItem.Id).Id;
								orderLineItemFree.Quantity_Ordered__c = itemIdtoOliMap.get(oldCartItem.Id).Quantity_Ordered__c;
								orderLineItemFree.Total_Points_Redeemed_Text__c = 0;
								orderLineItemFreeList.add(orderLineItemFree);
							}
						}
					}
				}
			}
			if(!oliListToBeDeleted.isEmpty()){
				Delete oliListToBeDeleted;
			}
			if(!orderLineItemFreeList.isEmpty())
				insert orderLineItemFreeList;

			contactWrap.oldCartItems = oldCartItemsList;
			contactWrap.cartMerchandise = oldCartMerchantList;
			contactWrap.allMerchandise  = getMerchandise();
			return contactWrap;
		}
		else{
			return null;
		}
	}

	@AuraEnabled
	public static String createOrder(Item__c[] cartItemsList, String contactRec) 
	{
		upsertDraftOrder(cartItemsList, 'Submitted', contactRec,'orderSubmited');
		return 'Success';
	}

	@AuraEnabled
	public static List<Merchandise__c> upsertDraftOrder(Item__c[] cartItemsList, String isSubmitted, String contactRecJSON,String freeGiftItemWrapper)
	{
		List<Order_Line_Item__c> orderLineItemFreeList = new List<Order_Line_Item__c>();
		ItemGiftWrapper freeGiftItemWrapperRec ;
		if(freeGiftItemWrapper != 'orderSubmited' && freeGiftItemWrapper != 'No Free Item' && freeGiftItemWrapper != 'removeOrder')
			 freeGiftItemWrapperRec = (ItemGiftWrapper)JSON.deserialize(freeGiftItemWrapper, ItemGiftWrapper.class);
		
		String contactId;
		String orderId;
		List<User> userList = [SELECT Id, ContactId FROM USER WHERE Id=: UserInfo.getUserId()];
		List<Contact> contactList = [SELECT Id, Lifetime_Points_Earned__c, Lifetime_Points_Redeemed__c FROM Contact WHERE Id =:userList[0].ContactId];
		if(contactList.size() > 0){
			contactId = contactList[0].Id;
		}
		List<Item__c> cartItems = new List<Item__c>();
		Map<String,Item__c> merchantItemsMap = new Map<String,Item__c>();
        
		for(object obj : cartItemsList)
		{
			cartItems.add((Item__c)obj);
			merchantItemsMap.put(((Item__c)obj).Id, (Item__c)obj);
		}
		List<Order__c> orderList = [SELECT Id, Status__c,
										(SELECT Id, Item__c,Free_Order_Line_Item__c, Quantity_Ordered__c 
											FROM Order_Line_Items__r) 
										FROM Order__c 
										WHERE Status__c = 'Draft' 
										AND Contact__c =: contactId LIMIT 1];

		Map<Id, Order_Line_Item__c> idToOrderLineItemMap = new Map<Id, Order_Line_Item__c>();
        Map<Id, Order_Line_Item__c> idToOrderLineItemMapParent = new Map<Id, Order_Line_Item__c>();
		if(!orderList.isEmpty())
		{
			for(Order_Line_Item__c oli : orderList[0].Order_Line_Items__r){
				if(oli.Free_Order_Line_Item__c != null)
					idToOrderLineItemMap.put(oli.Free_Order_Line_Item__c,oli);
			}
            for(Order_Line_Item__c oli : orderList[0].Order_Line_Items__r){
                idToOrderLineItemMapParent.put(oli.Id,oli);
            }
		}

		List<Order_Line_Item__c> oliListToBeDeleted = new List<Order_Line_Item__c>();
		List<Order_Line_Item__c> oliListToBeUpserted = new List<Order_Line_Item__c>();
		List<Order_Line_Item__c> oliListToBeInsert = new List<Order_Line_Item__c>();
		Map<String, Order_Line_Item__c> oliMap = new Map<String, Order_Line_Item__c>();

		if(!orderList.isEmpty())
		{
			orderId = orderList[0].Id;
			for(Order_Line_Item__c oli : orderList[0].Order_Line_Items__r)
			{
				if(!merchantItemsMap.containsKey(oli.Item__c) && oli.Free_Order_Line_Item__c == null && freeGiftItemWrapper == 'removeOrder')
				{
					oliListToBeDeleted.add(oli);
				}
				else if(idToOrderLineItemMap.containsKey(oli.Free_Order_Line_Item__c) && oli.Free_Order_Line_Item__c != null && !merchantItemsMap.containsKey(idToOrderLineItemMapParent.get(oli.Free_Order_Line_Item__c).Item__c) && freeGiftItemWrapper == 'removeOrder')
				{	
					oliListToBeDeleted.add(idToOrderLineItemMap.get(oli.Free_Order_Line_Item__c));
				}
				else
				{
					if(!idToOrderLineItemMap.containsKey(oli.Free_Order_Line_Item__c))
						oliMap.put(oli.Item__c, oli);
				}
			}

			for(Item__c merchant : cartItems)
			{
				if(oliMap.containsKey(merchant.Id))
				{
					oliMap.get(merchant.Id).Quantity_Ordered__c  = merchant.Quantity_Redeemed__c;
					if(idToOrderLineItemMap.containsKey(oliMap.get(merchant.Id).Id)){
						idToOrderLineItemMap.get(oliMap.get(merchant.Id).Id).Quantity_Ordered__c = merchant.Quantity_Redeemed__c;
						oliListToBeUpserted.add(idToOrderLineItemMap.get(oliMap.get(merchant.Id).Id));
					}
					oliListToBeUpserted.add(oliMap.get(merchant.Id));
				}
				else
				{
					if(freeGiftItemWrapper != 'orderSubmited'){
						oliListToBeInsert.clear();
						Order_Line_Item__c orderLineItem = new Order_Line_Item__c();
						orderLineItem.Item__c = merchant.Id;
						orderLineItem.Order__c = orderId;
						orderLineItem.Quantity_Ordered__c = merchant.Quantity_Redeemed__c;
						oliListToBeInsert.add(orderLineItem);
						if(!oliListToBeInsert.isEmpty())
							insert oliListToBeInsert;

						if(freeGiftItemWrapper != 'No Free Item'){
							Order_Line_Item__c orderLineItemFree = new Order_Line_Item__c();
							orderLineItemFree.Item__c = freeGiftItemWrapperRec.freeMerchandiseItem.Id;
							orderLineItemFree.Order__c = orderId;
							orderLineItemFree.Free_Order_Line_Item__c =  oliListToBeInsert[0].Id;
							orderLineItemFree.Quantity_Ordered__c = oliListToBeInsert[0].Quantity_Ordered__c;
							orderLineItemFree.Total_Points_Redeemed_Text__c = 0;
							orderLineItemFreeList.add(orderLineItemFree);
						}

						if(!orderLineItemFreeList.isEmpty())
							upsert orderLineItemFreeList;
					}

				}
			}
			if(isSubmitted == 'Submitted'){
				Contact updatedCon = (Contact)JSON.deserialize(contactRecJSON,Contact.class);
				orderList[0].Status__c 		= 'Submitted';
				orderList[0].First_Name__c 	= updatedCon.FirstName;
				orderList[0].Last_Name__c 	= updatedCon.LastName;
				orderList[0].Email__c 		= updatedCon.Email;
				orderList[0].Phone__c 		= updatedCon.Phone;
				orderList[0].Street__c 		= updatedCon.MailingStreet;
				orderList[0].City__c 		= updatedCon.MailingCity;
				orderList[0].State__c 		= updatedCon.MailingState;
				orderList[0].Country__c 	= updatedCon.MailingCountry;
				orderList[0].ZipCode__c 	= updatedCon.MailingPostalCode;
				upsert orderList;
			}
			if(!oliListToBeDeleted.isEmpty()) 
				delete oliListToBeDeleted;
			if(!oliListToBeUpserted.isEmpty()) 
				upsert oliListToBeUpserted;
		}
		else
		{
			Order__c order = new Order__c(Contact__c = contactId, Status__c = 'Draft');
			insert order;
			List<Order_Line_Item__c> orderLineItemList = new List<Order_Line_Item__c>();
			
			for(Item__c merchant : cartItems) {
				Order_Line_Item__c orderLineItem = new Order_Line_Item__c();
				orderLineItem.Item__c = merchant.Id;
				orderLineItem.Order__c = order.Id;
				orderLineItem.Quantity_Ordered__c = merchant.Quantity_Redeemed__c;
				orderLineItemList.add(orderLineItem);
			}
			if(!orderLineItemList.isEmpty()) 
				insert orderLineItemList;

			
			if(freeGiftItemWrapper != 'No Free Item'){
				Order_Line_Item__c orderLineItemFree = new Order_Line_Item__c();
				orderLineItemFree.Item__c = freeGiftItemWrapperRec.freeMerchandiseItem.Id;
				orderLineItemFree.Order__c = order.Id;
				orderLineItemFree.Free_Order_Line_Item__c =  orderLineItemList[0].Id;
				orderLineItemFree.Quantity_Ordered__c = orderLineItemList[0].Quantity_Ordered__c;
				orderLineItemFree.Total_Points_Redeemed_Text__c = 0;
				orderLineItemFreeList.add(orderLineItemFree);
			}
			if(!orderLineItemFreeList.isEmpty()) 
				insert orderLineItemFreeList;
		}
		
		List<Merchandise__c> merchandiseList = getMerchandise();
		return merchandiseList;
	}

	@AuraEnabled
	public static Merchandise__c getFreeItem(Merchandise__c currentMerchandise) {
		Merchandise__c merchandise = [SELECT Id, Name, Cost__c, Description__c,Free_Merchandise__c, Estimated_Shipping_Cost__c, Picture__c, Point_Value__c, 
													Allow_Orders_for_Sold_Out_Items__c, Display_Sizes__c 
													FROM Merchandise__c 
													WHERE Point_Value__c != null 
													AND Id = :currentMerchandise.Id];
        
        
        Merchandise__c freeMerchandise	= [SELECT Id, Name,Cost__c, Description__c,Free_Merchandise__c, Estimated_Shipping_Cost__c, Picture__c, Point_Value__c, 
													Allow_Orders_for_Sold_Out_Items__c, Display_Sizes__c, 
														(SELECT Id, Name, Quantity_On_Hand__c, Quantity_Redeemed__c, Total_Quantity__c, Size__c 
														FROM Items__r)
													FROM Merchandise__c 
													WHERE Point_Value__c != null 
													AND Id = :merchandise.Free_Merchandise__c];
        
		return freeMerchandise; 		
	}
    
    @AuraEnabled
    public static ItemGiftWrapper getItemWrapper(Merchandise__c currentMerchandise,Item__c currentMerchandiseItem,Merchandise__c FreeMerchandise,Item__c FreeMerchandiseItem){
        ItemGiftWrapper itemgiftWrapper = new ItemGiftWrapper(currentMerchandiseItem,freeMerchandiseItem);
        return itemgiftWrapper;
    }

    @AuraEnabled 
    public static List<FreeMerchandiseLineItemWrapper> getFreeMerchandiseWrapper(Merchandise__c[] cartMerchandise, String contactRecJson) {
    	List<FreeMerchandiseLineItemWrapper> freeMerchantLineItemList	= new List<FreeMerchandiseLineItemWrapper>();
    	Map<Id,Item__c> itemMap 										= new Map<Id,Item__c>();
    	Map<Id,Order_Line_Item__c> oliMap 								= new Map<Id,Order_Line_Item__c>();
    	Contact contactRec 												= (Contact)JSON.deserialize(contactRecJSON,Contact.class);
    	List<Order__c> orderList = [SELECT Id, Status__c,
										(SELECT Id, Item__c,Free_Order_Line_Item__c, Quantity_Ordered__c 
											FROM Order_Line_Items__r) 
										FROM Order__c 
										WHERE Status__c = 'Draft' 
										AND Contact__c =: contactRec.Id LIMIT 1];

		List<Merchandise__c> allMerchandise =  getMerchandise();

		for(Merchandise__c merchant : allMerchandise){
			for(Item__c item : merchant.Items__r){
				itemMap.put(item.Id,item);
			}
		}

		for(Order_Line_Item__c oli : orderList[0].Order_Line_Items__r)
			oliMap.put(oli.Id,oli);

		for(Order_Line_Item__c oliItem : orderList[0].Order_Line_Items__r) {
			if(oliItem.Free_Order_Line_Item__c != null)
				freeMerchantLineItemList.add(new FreeMerchandiseLineItemWrapper(itemMap.get(oliMap.get(oliItem.Free_Order_Line_Item__c).Item__c),oliItem,itemMap.get(oliItem.Item__c)));
		}

		return freeMerchantLineItemList;
	}

	public class UserContactWrapp{
        @AuraEnabled public Contact contactDetail{get;set;}
        @AuraEnabled public List<CartQuantityWrap> oldCartItems {get; set;}
        @AuraEnabled public List<Merchandise__c> cartMerchandise {get; set;}
        @AuraEnabled public List<Merchandise__c> allMerchandise {get; set;}
    }
    public class CartQuantityWrap{
    	@AuraEnabled public Item__c oldCartItem {get; set;}
    	@AuraEnabled public Integer relatedMerchandisePointValue {get; set;}
        @AuraEnabled public Integer quantityOrdered {get; set;}
    }

    public class ItemGiftWrapper{
    	@AuraEnabled public Item__c currentMerchandiseItem 			{get;set;}
		@AuraEnabled public Item__c freeMerchandiseItem 				{get;set;}
		public ItemGiftWrapper(Item__c currentMerchandiseItem,Item__c freeMerchandiseItem) {
	    	this.currentMerchandiseItem 	= currentMerchandiseItem;
	    	this.freeMerchandiseItem 	= freeMerchandiseItem;
	    }
    }

    public class FreeMerchandiseLineItemWrapper{
    	@AuraEnabled public Item__c merchantItem 									{get;set;}
    	@AuraEnabled public Order_Line_Item__c freeMerchantLineItem 				{get;set;}
		@AuraEnabled public Item__c freeMerchantItem 								{get;set;}
		public FreeMerchandiseLineItemWrapper(Item__c merchantItem,Order_Line_Item__c freeMerchantLineItem,Item__c freeMerchantItem) {
	    	this.merchantItem 			= merchantItem; 
	    	this.freeMerchantLineItem 	= freeMerchantLineItem;
	    	this.freeMerchantItem 		= freeMerchantItem;

	    }
    } 
}