src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Request_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Skills Required</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requested_End_Date__c</fullName>
        <label>Requested End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requested_Hours__c</fullName>
        <label>Requested Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Requested_Rate__c</fullName>
        <label>Requested Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Requested_Start_Date__c</fullName>
        <label>Requested Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Requested Expert</label>
    <nameField>
        <displayFormat>RE-{0000}</displayFormat>
        <label>Requested Expert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requested Experts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectRequestOverrideController_Test.cls
@isTest
private class ProjectRequestOverrideController_Test {

    private static testMethod void testStaticMethods() {
                
        TestDataFactory objTestDataFactory = new TestDataFactory();
        
        List<Account> accountList = objTestDataFactory.generateAccounts(1);
        insert accountList;
        
        List<Contact> contactList = objTestDataFactory.generateContactsForAccounts(accountList, 1);
        contactList[0].Email = 'testEmail@test.com';
        insert contactList;
        
        List<User> userList = objTestDataFactory.createUsersWith10KCustProfileRecords(1, accountList, contactList);
        insert userList;
        //Testing as community User
        system.runas(userList[0]){
            
            List<Project__c> projectList = objTestDataFactory.generateProjects(accountList[0].Id, 2);
            projectList[0].Account__c = accountList[0].Id;
            projectList[0].Name = 'Test Project';
            projectList[0].Start_Date__c = date.today();
            projectList[0].End_Date__c = date.today().addDays(3);      
            projectList[0].Status__c = 'Open';  
            projectList[1].Status__c = 'Open';  
            projectList[1].Name = 'Test Project';
            projectList[1].Account__c = accountList[0].Id;
            projectList[1].Start_Date__c = date.today();
            projectList[1].End_Date__c = date.today().addDays(7); 
            insert projectList;
            
            User objUser = [Select Id, ContactId, Contact.AccountId From User Where Id = :userList[0].Id];
            
            ProjectRequestOverrideController.onloadWrapperController objonloadWrapperController = ProjectRequestOverrideController.Intialise();
            system.assertNotEquals(objonloadWrapperController, null);
            String picklistValue = objonloadWrapperController.RolePickValues[0];
            system.assertEquals('None', picklistValue);
           
            Project__c proj = ProjectRequestOverrideController.ProjectRecord(projectList[1].Id);
            system.assertEquals(proj.Id, projectList[1].Id);
            
            Project_Request_Detail__c prD = ProjectRequestOverrideController.incrementPRDRow(projectList[1]);
            system.assertEquals(prD.Requested_Hours__c, 0);
            
            List<Project_Request_Detail__c> lstPrd = new List<Project_Request_Detail__c>();
            lstprd.add(new Project_Request_Detail__c(Role__c = '', Requested_Start_Date__c = date.today(), Requested_End_Date__c = date.today(), Description__c='', Requested_Hours__c= 1, Requested_Rate__c = 0.00));
            lstprd.add(new Project_Request_Detail__c(Role__c = '', Requested_Start_Date__c = date.today(), Requested_End_Date__c = date.today(), Description__c='', Requested_Hours__c= 1, Requested_Rate__c = 0.00));
            
            ProjectRequestOverrideController.insertprojectRecord(projectList[1],JSON.serialize(lstprd),'Project Request Description');
            
            List<Project__c> project = objTestDataFactory.generateProjects(accountList[0].Id, 1);
            project[0].Account__c = accountList[0].Id;
            project[0].Start_Date__c = date.today();
            project[0].End_Date__c = date.today().addDays(3);      
            project[0].Status__c = 'Open';  
            project[0].Name = 'Test Project';
            
            ProjectRequestOverrideController.insertprojectRecord(project[0],JSON.serialize(lstprd),'Project Request Description');
            
            
            
        }
        
        
    }

}