src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_Achievement_Sync__c</fullName>
        <label>Last Achievement Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Trailhead_User_Id__c</fullName>
        <label>Trailhead User Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webassessor_Email__c</fullName>
        <label>Webassessor Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Endpoint_URIs__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Limit_of_Records_Sync__c</fullName>
        <label>Limit of Records Sync</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Endpoint URIs</label>
</CustomObject>

src/classes/AchievementContactSyncSchedule.cls
global class AchievementContactSyncSchedule implements Schedulable 
{
    global void execute(SchedulableContext sc) 
    {
        Map<Id,String> contactIdMap = new Map<Id,String>();
        Integer recordLimit = Endpoint_URIs__c.getOrgDefaults().Limit_of_Records_Sync__c != null ? (Integer) Endpoint_URIs__c.getOrgDefaults().Limit_of_Records_Sync__c : 5;
        for(Contact selectedContact : [SELECT Id,Last_Achievement_Sync__c FROM Contact WHERE (Webassessor_Email__c != null OR Trailhead_User_Id__c != null)  AND (Last_Achievement_Sync__c = null OR Last_Achievement_Sync__c <= : Datetime.now() - 6)  ORDER BY Last_Achievement_Sync__c LIMIT: recordLimit])
        {
            contactIdMap.put(selectedContact.id,'both');
        }
        Id batchInstanceId = Database.executeBatch(new AchievementSyncBatch(contactIdMap,false,'Contact'), 1); 
    }
}