src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Project_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Contact does not belong to the selected Account. Please select another Contact.</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <infoMessage>Only Contacts for the selected Account are shown.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Resource Plan Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Staffing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Work Request</label>
    <nameField>
        <label>Work Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Request_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Skills Required</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_Request__c</fullName>
        <label>Work Request</label>
        <referenceTo>Project_Request__c</referenceTo>
        <relationshipLabel>Requested Experts</relationshipLabel>
        <relationshipName>Project_Request_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requested_Allocation__c</fullName>
        <label>Requested Allocation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Requested_End_Date__c</fullName>
        <label>Requested End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requested_Hours__c</fullName>
        <label>Requested Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Requested_Rate__c</fullName>
        <label>Requested Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Requested_Start_Date__c</fullName>
        <label>Requested Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Requested Expert</label>
    <nameField>
        <displayFormat>RE-{0000}</displayFormat>
        <label>Requested Expert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requested Experts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectRequestOverrideController.cls
public without sharing class ProjectRequestOverrideController {
    
    //Wrapper Class used to fetch the all the required things on load.
    public class onloadWrapperController{
        @AuraEnabled
        public List<String> RolePickValues {get;set;}
        @AuraEnabled
        public List<Project__c> ActiveProjects {get;set;}
        @AuraEnabled
        public Project_Request_Detail__c PRD {get;set;}
        
        public onloadWrapperController(List<Project__C> Active,List<String> lstStr,Project_Request_Detail__c objPrd ){
            this.RolePickValues = lstStr;
            this.ActiveProjects = Active;
            this.PRD = objPrd;
        }
    }
    
    @AuraEnabled
    public static onloadWrapperController Intialise(){
        List<String> lstRoleValues = ProjectRequestOverrideController.pickListValues();
        List<Project__c> ActiveProjects = ProjectRequestOverrideController.ActiveProjectsOfLoggedInUser();
        Project_Request_Detail__c ObjPrd = ProjectRequestOverrideController.incrementPRDRow(new Project__c());
        onloadWrapperController objWrapper = new onloadWrapperController(ActiveProjects,lstRoleValues,ObjPrd);
        return objWrapper;
    }
    
    @AuraEnabled
    public static List<String> pickListValues(){
        List<String> lstoptions = new List<string>();
        Schema.DescribeFieldResult fieldResult = Project_Request_Detail__c.Role__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        lstoptions.add('None');
        for( Schema.PicklistEntry f : ple)
        {
           lstoptions.add(f.getValue());
        }       
        return lstoptions;
    }
    
    @AuraEnabled
    public static List<project__c> ActiveProjectsOfLoggedInUser(){
        User objCurrentLoggedInUser = [Select Id, ContactId, Contact.AccountId From User Where Id = :userInfo.getUserId()];
        return [Select Id, Name, Account__c, Status__c, OwnerId From Project__c Where Account__c = :objCurrentLoggedInUser.Contact.AccountId AND Status__c = 'Open'];
    }
    
    @AuraEnabled
    public static Project__C ProjectRecord(Id selectedProjectRecordID){
        return [Select Id, Name,Start_Date__c,End_Date__c From Project__c Where Id =: selectedProjectRecordID];
    }
    
    @AuraEnabled
    public static Project_Request_Detail__c incrementPRDRow(Project__c project){
        if(project != null &&(project.Start_Date__c != null && project.End_Date__c != null))
        {
            return new Project_Request_Detail__c(Role__c = '', Requested_Start_Date__c = project.Start_Date__c, Requested_End_Date__c = project.End_Date__c, Requested_Allocation__c=10, Description__c='', Requested_Hours__c= 0, Requested_Rate__c = 0.00);
        }
        else{
            return new Project_Request_Detail__c(Role__c = '', Requested_Start_Date__c = Date.today(), Requested_End_Date__c = Date.today(), Requested_Allocation__c=10, Description__c='', Requested_Hours__c= 0, Requested_Rate__c = 0.00);
        }
    }
    
    @AuraEnabled
    public static saveResponse insertprojectRecord(Project__c objProjectToInsert, String strProjectReqDetailToInsert,string pRDescription){
        
        Savepoint sp1 = Database.setSavepoint();
        
        Project_Request__c objProjectRequestToInsert = new Project_Request__c();
		List<Project_Request_Detail__c> listToInsertPRD = new List<Project_Request_Detail__c>();
        system.debug('Project-------------:'+objProjectToInsert);
        system.debug('Prd--------:'+strProjectReqDetailToInsert);
        User objCurrentLoggedInUser = [Select Id, ContactId, Contact.AccountId,contact.Account.ownerId From User Where Id = :userInfo.getUserId()];
        objProjectToInsert.Account__c =  objCurrentLoggedInUser.Contact.AccountId;
        objProjectToInsert.Status__c = 'Open';
        //deserialise the string
        List<Project_Request_Detail__c> lstProjectReqDetailToInsert = (List<Project_Request_Detail__c>)JSON.deserializeStrict(strProjectReqDetailToInsert, List<Project_Request_Detail__c>.class);    
        system.debug('----------------------'+lstProjectReqDetailToInsert);
        try{
            //commenting this as project record is being created by S-0081. we are not creating the project Record
            /*if(objProjectToInsert.id == null){
                insert objProjectToInsert;
            }*/
            
            
            if(objCurrentLoggedInUser.ContactId != null) {
                            
                //objProjectRequestToInsert.Project__c = objProjectToInsert.Id;
                objProjectRequestToInsert.Project_Name__c = objProjectToInsert.Name;
                objProjectRequestToInsert.Account__c = objCurrentLoggedInUser.Contact.AccountId;
                objProjectRequestToInsert.Request_Contact__c = objCurrentLoggedInUser.ContactId;
                objProjectRequestToInsert.Start_Date__c = objProjectToInsert.Start_Date__c;
                objProjectRequestToInsert.End_Date__c = objProjectToInsert.End_Date__c;
            }
            else
            {
                //objProjectRequestToInsert.Project__c = objProjectToInsert.Id;
                objProjectRequestToInsert.Project_Name__c = objProjectToInsert.Name;
            }
            objProjectRequestToInsert.Description__c = pRDescription;
            objProjectRequestToInsert.OwnerId = objCurrentLoggedInUser.Contact.Account.ownerId;
            
            insert objProjectRequestToInsert;
                
            if(objProjectRequestToInsert != null) {
                            
                for(Project_Request_Detail__c objProjectRequestDetail : lstProjectReqDetailToInsert){                                                                                
                               
                    objProjectRequestDetail.Project_Request__c = objProjectRequestToInsert.Id;
                    
                    listToInsertPRD.add(objProjectRequestDetail);
                }
                listToInsertPRD.remove(listToInsertPRD.size()-1);
                system.debug('PRD Inserted--------------------:'+ listToInsertPRD);
                    
                if(!listToInsertPRD.isEmpty()) {
                    insert listToInsertPRD;
                    system.debug('PRD Inserted:'+ listToInsertPRD);
                    return new saveResponse(false,'Request Successfuly Submitted',objProjectRequestToInsert.Id);
                
                    //return performRedirectionToDetailViewPage(objProjectRequestToInsert.Id);
                }
            }
            
        }
        catch(Exception e)
        {
            System.debug('Project Request Detail Records not Created:');
            Database.RollBack(sp1);
            return new saveResponse(true,e.getMessage(),null);
        }
        if(objProjectRequestToInsert.Id != null)
        	return new saveResponse(false,'Project Request Created',objProjectRequestToInsert.Id);
        else 
            return null;
            
    }
    
    public class saveResponse {
        @AuraEnabled
        public Boolean isError {get;set;}
        @AuraEnabled
        public String Error_SuccessMsg {get;set;}
        @AuraEnabled 
        public Id ProjectRequestId {get;set;}
        
        public saveResponse(Boolean isError, String msg, Id prId){
            this.isError = isError;
            this.Error_SuccessMsg = msg;
            this.ProjectRequestId = prId;
        }
    }
    
}