src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_Achievement_Sync__c</fullName>
        <label>Last Achievement Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Trailhead_User_Id__c</fullName>
        <label>Trailhead User Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webassessor_Email__c</fullName>
        <label>Webassessor Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AchievementContactSyncSchedule_Test.cls
@isTest
private class AchievementContactSyncSchedule_Test {

    @isTest static void test_method_one() {
        TestDataFactory_CustomSettings.initializeEndpointURIsCustomSetting();

        Test.startTest();
            List<Contact> contactList = new List<Contact>();
            contactList.add(new Contact(LastName = 'Test', Webassessor_Email__c = 'test@test.test', Trailhead_User_Id__c = 'testtesttest',Last_Achievement_Sync__c = Datetime.now() - 7));
            insert contactList;
            String CRON_EXP = '0 30 * * * ?';
            Test.setMock(HttpCalloutMock.class, new MockResponseCallout());
            AchievementContactSyncSchedule conSch = new AchievementContactSyncSchedule();
            system.schedule('Hourly Contact Sync Batch Schedule job', CRON_EXP, conSch);
        Test.stopTest();
    }
}