src/objects/Endpoint_URIs__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Limit_of_Records_Sync__c</fullName>
        <label>Limit of Records Sync</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Endpoint URIs</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Last_Achievement_Sync__c</fullName>
        <label>Last Achievement Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Trailhead_User_Id__c</fullName>
        <label>Trailhead User Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webassessor_Email__c</fullName>
        <label>Webassessor Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/AchievementLeadSyncSchedule.cls
global class AchievementLeadSyncSchedule implements Schedulable 
{
    global void execute(SchedulableContext sc) 
    {
        Map<Id,String> leadIdMap = new Map<Id,String>();
        //Datetime 
        Integer recordLimit = Endpoint_URIs__c.getOrgDefaults().Limit_of_Records_Sync__c != null ? (Integer) Endpoint_URIs__c.getOrgDefaults().Limit_of_Records_Sync__c : 5;
        for(Lead selectedLead : [SELECT Id,Last_Achievement_Sync__c 
                                FROM Lead 
                                WHERE IsConverted = false AND ( Webassessor_Email__c != null OR Trailhead_User_Id__c != null ) AND (Last_Achievement_Sync__c = null OR Last_Achievement_Sync__c <= : Datetime.now() - 1) 
                                ORDER BY Last_Achievement_Sync__c LIMIT: recordLimit])
        {
            leadIdMap.put(selectedLead.id,'both');
        }
        Id batchInstanceId = Database.executeBatch(new AchievementSyncBatch(leadIdMap,false,'Lead'), 1); 
    }
}