src/objects/Epic__c.object
<CustomObject>
    <fields>
        <fullName>Epic_Name__c</fullName>
        <label>Epic Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Epics</relationshipLabel>
        <relationshipName>Epics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Epic</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Epic Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Projected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Epic__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Epic</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Story and the Epic must be associated to the same Project</errorMessage>
            <filterItems>
                <field>Epic__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Epic__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sprint</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Story and the Sprint must be associated to the same Project</errorMessage>
            <filterItems>
                <field>Sprint__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Story_Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <label>Story</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StoriesListViewController_Test.cls
/**
@Name          : StoriesListViewController_Test
@Dated         : 15 oct, 2016
@Author        :
@Description   : This is used to test StoriesListViewController. 
*/

@IsTest
public class StoriesListViewController_Test{
    
    @IsTest
    public static void unitTest(){
        TestDataFactory dataFactory   = new TestDataFactory();
        List<Account> accountsList     = dataFactory.generateAccounts(1);
        insert accountsList;
        List<Project__c> projectList   = dataFactory.generateProjects(accountsList[0].Id, 1);
        insert projectList;
        List<Sprint__c> sprintList     = new List<Sprint__c>();
        sprintList.add(new Sprint__c(Name = 'Test Sprint',Project__c = projectList[0].Id,Status__c = 'Planned'));
        insert sprintList;
        List<Epic__c> epicList = new List<Epic__c>();
        epicList.add(new Epic__c(Epic_Name__c = 'Epic Test', Project__c = projectList[0].id));
        insert epicList;
        List<User> u = dataFactory.createUsersWith10KDeliveryPartnerProfile(1);
        insert u;

        List<Story__c> storyList = dataFactory.generateStories(projectList[0].id, 1);
        storyList[0].Functional_Owner__c = u[0].id;
        insert storyList;
        List<String> status = new List<String>();
        status.add('Draft');
        system.debug(storyList[0].id);
        //testing static methods
        StoriesListViewController.getAllStories();
        StoriesListViewController.getProjects();
        StoriesListViewController.getSprints();
        StoriesListViewController.getStatusPickList();
        StoriesListViewController.getCurrUserId();
        StoriesListViewController.getcurrentStory(storyList[0].id);
        StoriesListViewController.getfilteredStory(projectList[0].id, sprintList[0].id, epicList[0].id, status, u[0].id, 'My Stories - Functional Owner');
        List<Story__c> storyList1 = dataFactory.generateStories(projectList[0].id, 1);
        
        StoriesListViewController.submitCreate(storyList1[0]);
        Story__c story = [SELECT id from story__c limit 1];
        StoriesListViewController.submitDelete(story);
    }

}