src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Order__c</fullName>
        <label>Inventory Order</label>
        <referenceTo>Inventory_Order__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity_Purchased_Value__c</fullName>
        <label>Quantity Purchased</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Inventory Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Inventory_Order__c.object
<CustomObject>
    <label>Inventory Order</label>
    <nameField>
        <displayFormat>INO-{0000}</displayFormat>
        <label>Inventory Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <label>Item</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataFactory_Inventory.cls
public with sharing class TestDataFactory_Inventory {
   
	public static List<Inventory__c> generateInventory(Id merchantItemId,Integer quantityPurchasedValue,Id inventoryOrderId, Integer numOfRecords) {
		return generateInventoryInternal(merchantItemId, quantityPurchasedValue,inventoryOrderId ,numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Inventory__c> generateInventoryInternal(Id merchantItemId,Integer quantityPurchasedValue,Id inventoryOrderId, Integer numOfRecords) {
    	List<Inventory__c> inventoryRecList = new List<Inventory__c>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
			Inventory__c inventoryRec = new Inventory__c();
			inventoryRec.Item__c = merchantItemId;
			inventoryRec.Quantity_Purchased_value__c = quantityPurchasedValue;
			inventoryRec.Inventory_Order__c = inventoryOrderId;
			inventoryRecList.add(inventoryRec);
        }
        
        return inventoryRecList;
    }
}