src/objects/Inventory_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Placed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Inventory Order</label>
    <nameField>
        <displayFormat>INO-{0000}</displayFormat>
        <label>Inventory Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory_InventoryOrder.cls
public with sharing class TestDataFactory_InventoryOrder {
   
	public static List<Inventory_Order__c> generateInventoryOrder(Date orderDate,String status, Integer numOfRecords) {
		return generateInventoryOrderInternal(orderDate, status, numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Inventory_Order__c> generateInventoryOrderInternal(Date orderDate, String status, Integer numOfRecords) {
    	List<Inventory_Order__c> orderList = new List<Inventory_Order__c>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
			Inventory_Order__c order = new Inventory_Order__c();
			order.Order_Date__c = orderDate;
			order.Status__c = status;
			orderList.add(order);
        }
        
        return orderList;
    }
}