src/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataFactory_Payments.cls
public with sharing class TestDataFactory_Payments {
	
	public static List<Payment__c> generatePayments(Id invoiceId, Decimal ammount, Date paymentDate, Integer numOfRecords) {
		return generatePaymentsInternal(invoiceId, ammount, paymentDate, numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Payment__c> generatePaymentsInternal(Id invoiceId, Decimal ammount, Date paymentDate, Integer numOfRecords) {
    	List<Payment__c> paymentList = new List<Payment__c>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
			Payment__c payment = new Payment__c();
			payment.Amount__c = ammount;
			payment.Payment_Date__c = paymentDate;
			payment.Invoice__c = invoiceId;
            paymentList.add(payment);
        }
        
        return paymentList;
    }
}