src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Generated_On__c</fullName>
        <label>Billing Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outstanding_Balance__c</fullName>
        <formula>IF(
  ISPICKVAL(Type__c, &quot;Void&quot;),
  0,
  Total_Invoice_Amount__c - Total_Amount_Paid__c
)</formula>
        <label>Outstanding Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Profit_Margin__c</fullName>
        <label>Profit Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sent_To_Customer_On__c</fullName>
        <label>Finalized On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Invoice_Amount__c</fullName>
        <label>Total Invoice Amount</label>
        <summarizedField>Invoice_Line_Item__c.Line_Item_Total_Text__c</summarizedField>
        <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataFactory_Invoices.cls
public with sharing class TestDataFactory_Invoices {
    
    public static List<Invoice__c> generateInvoices(Id accountId, Date dueDate, Date sentToCustomerOn, Date invoiceGeneratedOn, Decimal profitMargin, Integer numOfRecords) {
		return generateInvoicesInternal(accountId, dueDate, sentToCustomerOn, invoiceGeneratedOn, profitMargin, numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Invoice__c> generateInvoicesInternal(Id accountId, Date dueDate, Date sentToCustomerOn, Date invoiceGeneratedOn, Decimal profitMargin, Integer numOfRecords) {
    	List<Invoice__c> invoiceList = new List<Invoice__c>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
			Invoice__c invoice = new Invoice__c();
			invoice.Account__c = accountId;
			invoice.Due_Date__c =  dueDate;
			//invoice.Outstanding_Balance__c =  
			invoice.Sent_To_Customer_On__c = sentToCustomerOn;
			invoice.Invoice_Generated_On__c = invoiceGeneratedOn;
			invoice.Profit_Margin__c = profitMargin;
            //invoice.Total_Invoice_Amount__c = 
            invoiceList.add(invoice);
        }
        
        return invoiceList;
    }
}