src/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate__c.object
<CustomObject>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataFactory_InvoiceLineItems.cls
public with sharing class TestDataFactory_InvoiceLineItems {
    
    public static List<Invoice_Line_Item__c> generateInvoiceLineItems(Id invoiceId, Id recordTypeId, Id rateId, Decimal discount, Decimal salesPrice, Integer numOfRecords) {
		return generateInvoiceLineItemsInternal(invoiceId, recordTypeId, rateId, discount, salesPrice, numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Invoice_Line_Item__c> generateInvoiceLineItemsInternal(Id invoiceId, Id recordTypeId, Id rateId, Decimal discount, Decimal salesPrice, Integer numOfRecords) {
    	List<Invoice_Line_Item__c> InvoiceLineItemsList = new List<Invoice_Line_Item__c>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
            Invoice_Line_Item__c invoiceLineItem = new Invoice_Line_Item__c();
            invoiceLineItem.invoice__c = invoiceId;
            invoiceLineItem.rate__c = rateId;
            invoiceLineItem.Discount__c = discount;
            invoiceLineItem.Sales_Price__c = salesPrice;
            invoiceLineItem.RecordTypeId = recordTypeId;
            InvoiceLineItemsList .add(invoiceLineItem);
        }
        
        return InvoiceLineItemsList;
    }
}