src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Merchandise__c</fullName>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity_On_Hand__c</fullName>
        <formula>Total_Quantity__c - Quantity_Redeemed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity On Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Redeemed__c</fullName>
        <label>Quantity Redeemed</label>
        <summarizedField>Order_Line_Item__c.Quantity_Ordered__c</summarizedField>
        <summaryForeignKey>Order_Line_Item__c.Item__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <picklist>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XXXL</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Quantity__c</fullName>
        <label>Total Quantity</label>
        <summarizedField>Inventory__c.Quantity_Purchased_Value__c</summarizedField>
        <summaryForeignKey>Inventory__c.Item__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Item</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Orders_for_Sold_Out_Items__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Orders for Sold Out Items</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Display_Sizes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display Sizes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Estimated_Shipping_Cost__c</fullName>
        <label>Estimated Shipping Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Free_Merchandise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Free Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Merchandise</relationshipLabel>
        <relationshipName>Merchandise</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Point_Value__c</fullName>
        <label>Point Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FreeMerchandiseItemController.cls
public class FreeMerchandiseItemController {
	@AuraEnabled
	public static Merchandise__c getFreeItem(Merchandise__c currentMerchandise) {
		Merchandise__c merchandise = [SELECT Id, Name, Cost__c, Description__c,Free_Merchandise__c, Estimated_Shipping_Cost__c, Picture__c, Point_Value__c, 
													Allow_Orders_for_Sold_Out_Items__c, Display_Sizes__c 
													FROM Merchandise__c 
													WHERE Point_Value__c != null 
													AND Id = :currentMerchandise.Id];
        
        
        Merchandise__c freeMerchandise	= [SELECT Id, Name,Cost__c, Description__c,Free_Merchandise__c, Estimated_Shipping_Cost__c, Picture__c, Point_Value__c, 
													Allow_Orders_for_Sold_Out_Items__c, Display_Sizes__c, 
														(SELECT Id, Name, Quantity_On_Hand__c, Quantity_Redeemed__c, Total_Quantity__c, Size__c 
														FROM Items__r)
													FROM Merchandise__c 
													WHERE Point_Value__c != null 
													AND Id = :merchandise.Free_Merchandise__c];
        
		return freeMerchandise; 		
	}
    
    @AuraEnabled
    public static ItemGiftWrapper getItemWrapper(Merchandise__c currentMerchandise,Item__c currentMerchandiseItem,Merchandise__c FreeMerchandise,Item__c FreeMerchandiseItem){
        
        ItemGiftWrapper itemgiftWrapper = new ItemGiftWrapper(currentMerchandiseItem,freeMerchandiseItem);
        return itemgiftWrapper;
    }


    public class ItemGiftWrapper{
    	@AuraEnabled public Item__c currentMerchandiseItem 			{get;set;}
		@AuraEnabled public Item__c freeMerchandiseItem 				{get;set;}
		public ItemGiftWrapper(Item__c currentMerchandiseItem,Item__c freeMerchandiseItem) {
	    	this.currentMerchandiseItem 	= currentMerchandiseItem;
	    	this.freeMerchandiseItem 	= freeMerchandiseItem;
	    }
    } 
}