src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <globalPicklist>Region</globalPicklist>
        <label>Region</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Project_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closed_Date__c</fullName>
        <label>Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Opportunity does not belong to the selected Account. Please select another Opportunity.</errorMessage>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <infoMessage>Only Opportunities for the selected Account are shown.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Resource Plan Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Staffing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Work Request</label>
    <nameField>
        <label>Work Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Request_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Project_Request__c</fullName>
        <label>Work Request</label>
        <referenceTo>Project_Request__c</referenceTo>
        <relationshipLabel>Requested Experts</relationshipLabel>
        <relationshipName>Project_Request_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <globalPicklist>Region</globalPicklist>
        <label>Region</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requested_Hours__c</fullName>
        <label>Requested Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Requested_Rate__c</fullName>
        <label>Requested Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Requested Expert</label>
    <nameField>
        <displayFormat>RE-{0000}</displayFormat>
        <label>Requested Expert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requested Experts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectRequestDetailTriggerHandler_Test.cls
@isTest
private class ProjectRequestDetailTriggerHandler_Test {
   
   @testSetup static void setup() {
       Account ac = new Account(
        Name = 'TestAc'
     );
     Database.insert( ac );
    Test.startTest();
     Project_Request__c pRequest = new Project_Request__c(
        Closed_Date__c = Date.today(),
        Start_Date__c = Date.today(),
        End_Date__c  =  Date.today().addDays(1),
        Status__c = 'New',
        Account__c =  ac.Id
     );
     Database.insert( pRequest );
     
     List<Project_Request__c > pReq = [SELECT Id,Opportunity__c,Opportunity__r.PriceBook2Id FROM Project_Request__c WHERE ID = :pRequest.Id ];
     System.assertNotEquals( pReq[0].Opportunity__c, NULL );
     
     List<Product2> prod =  TestDataFactory_Products.generateProducts('Developer - India - Time & Materials', 'Developer');
     prod[0].Region__c = 'India';
     insert prod;
     List<Product2> prod1 =  TestDataFactory_Products.generateProducts('Technical Lead - India - Time & Materials', 'Technical Lead');
     prod1[0].Region__c = 'India';
     insert prod1;

     Id standardPriceBookId = Test.getStandardPricebookId();

     List<PricebookEntry> standardPrice = TestDataFactory_PriceBookEntries.generatePriceBookEntries(standardPriceBookId, prod[0].Id, 10000, true);
     insert standardPrice;
     
     List<PricebookEntry> standardPrice1 = TestDataFactory_PriceBookEntries.generatePriceBookEntries(standardPriceBookId, prod1[0].Id, 10000, true);
     insert standardPrice1;
        
     Id servicesRecordTypeId = Schema.SObjectType.Pricebook2.getRecordTypeInfosByName().get('Services Price Book').getRecordTypeId();
     List<PriceBook2> pb = TestDataFactory_PriceBooks.generatePriceBooks('Custom Test PriceBook', true, 'Base', 'Testing', 1);
     pb[0].RecordTypeId = servicesRecordTypeId;
     insert pb;
        
     List<PricebookEntry> customPrice = TestDataFactory_PriceBookEntries.generatePriceBookEntries(pb[0].Id, prod[0].Id, 12000, true);
     insert customPrice;
     
     List<PricebookEntry> customPrice2 = TestDataFactory_PriceBookEntries.generatePriceBookEntries(pb[0].Id, prod1[0].Id, 12000, true);
     insert customPrice2;
        
      List<opportunity> opp = [SELECT PriceBook2Id FROM opportunity WHERE Id =: pReq[0].Opportunity__c];
      opp[0].PriceBook2Id = pb[0].Id;  
      Database.update( opp );
      System.assertNotEquals( opp[0].PriceBook2Id , NULL );
      List<Project_Request_Detail__c> lstProjectRequestDetails = new List<Project_Request_Detail__c>();
      Project_Request_Detail__c objProjectRequestDetail1 = new Project_Request_Detail__c (
        Requested_Rate__c = 6,
        Requested_Hours__c = 5,
        Region__c = 'India',
        Project_Request__c = pRequest.Id,
        Role__c = 'Developer'
     );
     lstProjectRequestDetails.add(objProjectRequestDetail1);
     Database.insert( lstProjectRequestDetails );
     
     //lstProjectRequestDetails[0].Requested_Hours__c  = 10;   where id =:lstProjectRequestDetails[0].id
      Test.stopTest();
        
    }
   
   
   static testMethod void test_method_one() {
        Test.startTest();
      List<Project_Request_Detail__c> pdetail = [Select Requested_Hours__c  from Project_Request_Detail__c];
      pdetail[0].Requested_Hours__c  = 10;
      Database.update( pdetail[0] );
      
       Delete pdetail[0];
        Test.stopTest();
       List<Project_Request__c> projectRequets = [Select Opportunity__c  from Project_Request__c];
       System.assertNotEquals(projectRequets[0].Opportunity__c, null);
   } 
        
}