src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Last_Achievement_Sync__c</fullName>
        <label>Last Achievement Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Trailhead_User_Id__c</fullName>
        <label>Trailhead User Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webassessor_Email__c</fullName>
        <label>Webassessor Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/AchievementLeadSyncSchedule_Test.cls
@isTest
private class AchievementLeadSyncSchedule_Test {
    @isTest static void test_method_one() {
        
        TestDataFactory_CustomSettings.initializeEndpointURIsCustomSetting();

        Test.startTest();
            List<Lead> leadsList = new List<Lead>();
            leadsList.add(new Lead(LastName = 'Test', Company = 'test' ,Webassessor_Email__c = 'test@test.test', Trailhead_User_Id__c = 'testtesttest',Last_Achievement_Sync__c = Datetime.now() - 1));
            insert leadsList;
            String CRON_EXP = '0 0 * * * ?';
            Test.setMock(HttpCalloutMock.class, new MockResponseCallout());
            AchievementLeadSyncSchedule leadSch = new AchievementLeadSyncSchedule();
            system.schedule('Hourly Lead Sync Batch Schedule job for testing', CRON_EXP, leadSch);
        Test.stopTest();
    }
}