src/objects/Points__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Points</relationshipLabel>
        <relationshipName>Points</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Points__c</fullName>
        <label>Number of Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Points Rule</label>
        <referenceTo>Points_Rule__c</referenceTo>
        <relationshipLabel>Points</relationshipLabel>
        <relationshipName>Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Record_Id__c</fullName>
        <label>Source Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Points</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Points Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Points_Rule__c.object
<CustomObject>
    <label>Points Rule</label>
    <nameField>
        <label>Points Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory_Points.cls
public with sharing class TestDataFactory_Points {
    
    public static List<Points__c> generatePoints(Id storyId, Id contactId, Integer numberOfPoints, Id pointRuleId, Integer numOfRecords) {
		return generatePointsInternal(storyId, contactId, numberOfPoints, pointRuleId, numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Points__c> generatePointsInternal(Id storyId, Id contactId, Integer numberOfPoints, Id pointRuleId, Integer numOfRecords) {
    	List<Points__c> pointList = new List<Points__c>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
            
            Points__c pointRec = new Points__c();
            pointRec.Source_Record_Id__c = storyId;
            pointRec.Contact__c = contactId;
            pointRec.Number_of_Points__c = numberOfPoints;
            pointRec.Points_Rule__c = pointRuleId;
            
            pointList.add(pointRec);
        }
        
        return pointList;
    }  
}