src/objects/Points_Rule__c.object
<CustomObject>
    <label>Points Rule</label>
    <nameField>
        <label>Points Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Points_Rule_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Value__c</fullName>
        <inlineHelpText>For Date fields use the format dd/MM/yyyy
For Date/Time fields use the format dd/MM/yyyy hh:mm:ss, with 24 hour military time</inlineHelpText>
        <label>Field Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>=</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>!=</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt;=</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;=</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Points_Rule__c</fullName>
        <label>Points Rule</label>
        <referenceTo>Points_Rule__c</referenceTo>
        <relationshipLabel>Points Rule Criteria</relationshipLabel>
        <relationshipName>Points_Rule_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Points Rule Criteria</label>
    <nameField>
        <label>Points Rule Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points Rule Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataFactory_PointsRuleCriteria.cls
public with sharing class TestDataFactory_PointsRuleCriteria {
    
    public static List<Points_Rule_Criteria__c> generatePointRuleCriteria(String fieldAPIName, String fieldValue, String operator, Id pointRuleId, Integer numOfRecords) {
		return generatePointRuleCriteriaInternal(fieldAPIName, fieldValue, operator, pointRuleId, numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<Points_Rule_Criteria__c> generatePointRuleCriteriaInternal(String fieldAPIName, String fieldValue, String operator, Id pointRuleId, Integer numOfRecords) {
    	List<Points_Rule_Criteria__c> pointRuleRecList = new List<Points_Rule_Criteria__c>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
            
            Points_Rule_Criteria__c pointRuleCriteriaRec = new Points_Rule_Criteria__c();
	        pointRuleCriteriaRec.Field_API_Name__c = fieldAPIName;
	        pointRuleCriteriaRec.Field_Value__c = fieldValue;
	        pointRuleCriteriaRec.Operator__c = operator;
	        pointRuleCriteriaRec.Points_Rule__c = pointRuleId;
            
            pointRuleRecList.add(pointRuleCriteriaRec);
        }
        
        return pointRuleRecList;
    }   
}