src/objects/ProfileSkill.object
<CustomObject>
    <fields>
        <fullName>Skill_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Skill Category</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Skill Category that is related to the selected Skill Group</errorMessage>
            <filterItems>
                <field>$Source.Skill_Group__c</field>
                <operation>equals</operation>
                <valueField>Skill_Category__c.Skill_Group__c</valueField>
            </filterItems>
            <infoMessage>This list of Skill Categories has been filtered based on the selected Skill Group</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Skill_Category__c</referenceTo>
        <relationshipLabel>Skills</relationshipLabel>
        <relationshipName>Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skill_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Skill Group</label>
        <referenceTo>Skill_Group__c</referenceTo>
        <relationshipLabel>Skills</relationshipLabel>
        <relationshipName>Skills</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skill_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Skill Type</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Skill Type that is related to the selected Skill Category</errorMessage>
            <filterItems>
                <field>$Source.Skill_Category__c</field>
                <operation>equals</operation>
                <valueField>Skill_Type__c.Skill_Category__c</valueField>
            </filterItems>
            <infoMessage>This list of Skill Types has been filtered based on the selected Skill Category</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Skill_Type__c</referenceTo>
        <relationshipLabel>Skills</relationshipLabel>
        <relationshipName>Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Skill_Category__c.object
<CustomObject>
    <fields>
        <fullName>Skill_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Skill Group</label>
        <referenceTo>Skill_Group__c</referenceTo>
        <relationshipLabel>Skill Categories</relationshipLabel>
        <relationshipName>Skill_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Skill Category</label>
    <nameField>
        <label>Skill Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Skill_Group__c.object
<CustomObject>
    <label>Skill Group</label>
    <nameField>
        <label>Skill Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Skill_Type__c.object
<CustomObject>
    <fields>
        <fullName>Skill_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Skill Category</label>
        <referenceTo>Skill_Category__c</referenceTo>
        <relationshipLabel>Skill Types</relationshipLabel>
        <relationshipName>Skill_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Skill Type</label>
    <nameField>
        <label>Skill Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory_Skills.cls
public with sharing class TestDataFactory_Skills {
    
    public static List<ProfileSkill> generateSkills(String skillName, Id skillCategoryId, Id skillGroupId, Id skillTypeId, Integer numOfRecords) {
		return generateProfileSkillsInternal(skillName, skillCategoryId, skillGroupId, skillTypeId, numOfRecords);
    }

    //DO NOT call this method from other methods not inside this class. This will build a dependency that will make changes difficult. Instead, build
    //another public method within this class that can be called from other test classes, then call this internal master method from within your method.
    private static List<ProfileSkill> generateProfileSkillsInternal(String skillName, Id skillCategoryId, Id skillGroupId, Id skillTypeId, Integer numOfRecords) {
    	List<ProfileSkill> profileSkillList = new List<ProfileSkill>();
        
        for(Integer i = 0; i < numOfRecords; i++) {
        	ProfileSkill psk = new ProfileSkill();
        	psk.Name = skillName;
        	psk.Skill_Category__c = skillCategoryId;
        	psk.Skill_Group__c = skillGroupId;
        	psk.Skill_Type__c = skillTypeId;
			profileSkillList.add(psk);
        }
        
        return profileSkillList;
    }
}