src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Client_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Contact does not belong to the selected Account. Please select another Contact.</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <infoMessage>Only Contacts for the selected Account are shown.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Health__c</fullName>
        <label>Project Health</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Status_Report__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Issues_Risks__c</fullName>
        <label>Issues / Risks</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project_Health__c</fullName>
        <label>Project Health</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Status Reports</relationshipLabel>
        <relationshipName>Status_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sent_to_Client_On__c</fullName>
        <label>Sent to Client On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Status Report</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Status Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SendStatusReportController.cls
public class SendStatusReportController {

    public static final String MISSING_CONTACT_EMAIL                = 'The Contact on the Status Report has no Email Address';
    public static final String STATUS_REPORT_SENT_SUCCESSFULLY      = 'Status Report sent successfully';

    @TestVisible private Status_Report__c statusReport ;

    public String returnURL {Get;set;}
    public Boolean isLightningExperience {get; set;}


    public SendStatusReportController(ApexPages.StandardController std) {
        statusReport = (Status_Report__c) std.getRecord();
        isLightningExperience = false;
        if(Apexpages.currentPage().getParameters().get('sfdcIFrameOrigin') != null)
            isLightningExperience = true;
    }

    @RemoteAction
    public static String sendStatusReport(Id statusReportId){
        Status_Report__c selectedStatusReport;
        for(Status_Report__c statusReport : [SELECT Id, Name, Start_Date__c, End_Date__c, Project__r.Account__r.Name, Project__r.Name, CreatedDate,
                                                Project__r.Primary_Client_Contact__r.Email, Project__r.Project_Health__c, Issues_Risks__c,
                                                Project__r.Primary_Client_Contact__c, Sent_to_Client_On__c
                                            FROM Status_Report__c
                                            WHERE Id =: statusReportId ]){
            selectedStatusReport = statusReport;
        }

        Map<String,EmailTemplate> emailTemplateMap = new Map<String,EmailTemplate>();
        
        for(EmailTemplate selectedEmailTemplate : [SELECT Id, DeveloperName FROM EmailTemplate LIMIT 500]) {
            emailTemplateMap.put(selectedEmailTemplate.DeveloperName, selectedEmailTemplate);
        }
        if(selectedStatusReport.Project__r.Primary_Client_Contact__r.Email == null) {
            return MISSING_CONTACT_EMAIL;
        }
        else {
            List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId(selectedStatusReport.Project__r.Primary_Client_Contact__c);
            mail.setWhatId(selectedStatusReport.Id);
            mail.setSaveAsActivity(true);
            mail.setTemplateId(emailTemplateMap.get(Label.Status_Report_Email_Template).Id);
            mail.setCcAddresses(new List<String>{Userinfo.getUserEmail(),Label.Project_Status_Email});
            
            List<Messaging.EmailFileAttachment> fileAttachments = new List<Messaging.EmailFileAttachment>();
            PageReference selectedStatusReportPDFPageRef = new PageReference('/apex/GenerateStatusReportPDF?id=' + selectedStatusReport.Id);
           
            Messaging.EmailFileAttachment selectedStatusReportPDFAttachment = new Messaging.EmailFileAttachment(); 

            Blob pdfData = Test.isRunningTest() ? Blob.valueOf('UNIT.TEST') : selectedStatusReportPDFPageRef.getcontentAsPDF();

            selectedStatusReportPDFAttachment.setFileName(selectedStatusReport.Name+'.pdf');
            selectedStatusReportPDFAttachment.setBody(pdfdata);  
            fileAttachments.add(selectedStatusReportPDFAttachment);

            mail.setFileAttachments(fileAttachments);
            mailList.add(mail);

            List<Messaging.SendEmailResult> results = Messaging.sendEmail(mailList);

            if(!results.get(0).isSuccess()) {
                System.StatusCode statusCode = results.get(0).getErrors()[0].getStatusCode();
                return results.get(0).getErrors()[0].getMessage();
            }
        }
        if(selectedStatusReport.Sent_to_Client_On__c == null) {
            selectedStatusReport.Sent_to_Client_On__c = Date.today();
        }
        update selectedStatusReport;
        return STATUS_REPORT_SENT_SUCCESSFULLY;
    }

    public PageReference returnBack() {
        Status_Report__c currentStatusReport = [SELECT ID, Sent_to_Client_On__c FROM Status_Report__c WHERE Id =: statusReport.Id ];
        PageReference statusReportPage = new ApexPages.StandardController(currentStatusReport ).view();
        returnURL = System.URL.getSalesforceBaseUrl().toExternalForm() + '/' + statusReportPage.getUrl();
        return null;
    }
}