src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>IF(
  $User.Is_Portal_User__c,
  Account__r.Name,
  HYPERLINK(&apos;/&apos; + Account__c, Account__r.Name, &apos;_top&apos;) 
)</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Client_Contact_Name__c</fullName>
        <formula>IF(
  $User.Is_Portal_User__c,
  Primary_Client_Contact__r.FirstName + &apos; &apos; + Primary_Client_Contact__r.LastName,
  HYPERLINK(&apos;/&apos; + Primary_Client_Contact__c, Primary_Client_Contact__r.FirstName + &apos; &apos; + Primary_Client_Contact__r.LastName, &apos;_top&apos;) 
)</formula>
        <label>Primary Client Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Health__c</fullName>
        <label>Project Health</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Status_Report__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key_Items_Completed_Last_Week__c</fullName>
        <label>Key Items Completed Last Week</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Key_Items_Scheduled_for_This_Week__c</fullName>
        <label>Key Items Scheduled for This Week</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project_Health__c</fullName>
        <label>Project Health</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <formula>Project__r.Project_Lead__r.FirstName + &apos; &apos; +  Project__r.Project_Lead__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Lead</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Status Reports</relationshipLabel>
        <relationshipName>Status_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Questions_Concerns__c</fullName>
        <label>Questions / Concerns</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Upcoming_Holidays_PTO__c</fullName>
        <label>Upcoming Holidays / PTO</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Status Report</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Status Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GenerateStatusReportPDFController.cls
public with sharing class GenerateStatusReportPDFController {

    public Status_Report__c selectedStatusReport {get;set;}
    public String projectDetailUrl {get;set;}

    public GenerateStatusReportPDFController(ApexPages.StandardController stdController) {
        //this.mysObject = (sObject)stdController.getRecord();
        for(Status_Report__c statusReport : [SELECT Id, Start_Date__c, End_Date__c,Project__c, Project__r.Account_Name__c, Project__r.Name, CreatedDate,
                                                Project__r.Primary_Client_Contact_Name__c, Project__r.Project_Health__c, Questions_Concerns__c,
                                                Key_Items_Completed_Last_Week__c, Key_Items_Scheduled_for_This_Week__c, Upcoming_Holidays_PTO__c, 
                                                Project_Lead__c,Project_Health__c
                                            FROM Status_Report__c
                                            WHERE Id =: stdController.getRecord().Id ]){
            selectedStatusReport    = statusReport;
            

        }
        List<Project__c> projectList = [SELECT Id FROM Project__c WHERE Id =: selectedStatusReport.Project__c];
        if(projectList.size() > 0) {
            PageReference statusReportPage = new ApexPages.StandardController(projectList[0]).view();
            projectDetailUrl = System.URL.getSalesforceBaseUrl().toExternalForm() + '/' + statusReportPage.getUrl();
        }
        else {
            projectDetailUrl = '';
        }
            
    }
}