src/objects/Project_Request__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Work Request</label>
    <nameField>
        <label>Work Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreateOpportunityFromWorkRequest_Test.cls
@isTest
private class CreateOpportunityFromWorkRequest_Test 
{
    
    @isTest static void test_method_one() 
    {
        TestDataFactory fact = new TestDataFactory();

        Test.startTest();
            List<Account> acc = fact.generateAccounts(2);
            insert acc;
            List<Contact> con = fact.generateContactsForAccounts(acc, 1);
            insert con;
            Project_Request__c projectReq = fact.generateProjectRequestRecord(acc[0].Id, 'New', con[0].Id, 'Test', Date.today());
            projectReq.Start_Date__c = system.today();
            insert projectReq;
            System.assertEquals(acc.size(), 2);
            CreateOpportunityFromWorkRequest.createOpportunity((String)projectReq.Id);
        Test.stopTest();
    }
}