src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Status_Report__c.object
<CustomObject>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <formula>Project__r.Project_Lead__r.FirstName + &apos; &apos; +  Project__r.Project_Lead__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Lead</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Status Reports</relationshipLabel>
        <relationshipName>Status_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Status Report</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Status Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DeleteStatusReportController.cls
public with sharing class DeleteStatusReportController 
{
	@AuraEnabled
	public static DataWrapper deleteStatusReportRecord(String recId)
	{
		String currentUserId = UserInfo.getUserId();
		DataWrapper dataWarp = new DataWrapper();
		Status_Report__c statusReport = [SELECT Id, Project__c, Project__r.Project_Lead__c FROM Status_Report__c WHERE Id =: recId];
		if(currentUserId == statusReport.Project__r.Project_Lead__c)
		{
			Delete statusReport;
			dataWarp.projectId = statusReport.Project__c;
			dataWarp.isProjectLead = true;
		}
		else
		{
			dataWarp.projectId = statusReport.Project__c;
			dataWarp.isProjectLead = false;
		}
		return dataWarp;
	}

	public class DataWrapper
	{
		@AuraEnabled public String projectId;
		@AuraEnabled public Boolean isProjectLead;
	}
}