src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Health__c</fullName>
        <label>Project Health</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Status_Report__c.object
<CustomObject>
    <fields>
        <fullName>Project_Health__c</fullName>
        <label>Project Health</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Status Reports</relationshipLabel>
        <relationshipName>Status_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Status Report</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Status Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StatusReportTriggerHandlerTest.cls
@isTest
private class StatusReportTriggerHandlerTest {

    static testMethod void myUnitTest() {
    	
      Test.startTest();
      
	    TestDataFactory dataFactory = new TestDataFactory();
	    List<Account> accounts = dataFactory.generateAccounts(1);
	    insert accounts;
	
	    List<Project__c> projects = dataFactory.generateProjects(accounts[0].Id, 1);
	    insert projects; 
	  
	    List<Status_Report__c> statusReports = dataFactory.generateStatusReports(1, projects[0]);
	    insert statusReports;
	  
	    statusReports[0].Project_Health__c = 'Red';
	    update statusReports[0];
	    System.assertEquals('Red', statusReports[0].Project_Health__c);
      
      Test.stopTest();
    }
}