src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Client_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Contact does not belong to the selected Account. Please select another Contact.</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <infoMessage>Only Contacts for the selected Account are shown.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Status_Report__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Status Reports</relationshipLabel>
        <relationshipName>Status_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Status Report</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Status Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SendStatusReportController_Test.cls
@isTest
private class SendStatusReportController_Test {
	
        @isTest static void test_method_one() {

                Test.startTest();
                	// Implement test code.
                	TestDataFactory factory = new TestDataFactory();

                	List<Account> accList = factory.generateAccounts(1);
                        insert accList;

                        List<Contact> contactList = factory.generateContactsForAccounts(accList, 1);
                        contactList[0].Email = 'nowhere@nowhere.com';
                        insert contactList;

                        List<Project__c> projectList = factory.generateProjects(accList[0].Id,1);
                        projectList[0].Primary_Client_Contact__c = contactList[0].Id;
                        insert projectList;

                        List<Status_Report__c> statusReportList = factory.generateStatusReports(1,projectList[0]);
                        insert statusReportList;

                        SendStatusReportController.sendStatusReport(statusReportList[0].Id);


                        ApexPages.StandardController stdController = new ApexPages.StandardController(statusReportList[0]);
                        SendStatusReportController sendStatusReportCtrl = new SendStatusReportController(stdController);
                        System.assertNotEquals(sendStatusReportCtrl.statusReport,null);
                        sendStatusReportCtrl.returnBack();


                Test.stopTest();

        }
	
}