src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreatePackageXMLController.cls
public with sharing class CreatePackageXMLController {

	public String artifactPackageXMLString     {get;set;}
    public String artifactDestructiveXMLString {get;set;}
	public String errorMessage                 {get;set;}
	private Release__c release;
	public CreatePackageXMLController(ApexPages.StandardController stdController) {
        errorMessage = '';
        release      = [SELECT Id, Project__c, Project__r.Name FROM Release__c WHERE Id =: stdController.getId()];

		HttpResponse res = RestRequestHandlerForHeroku.sendRequest('POST','Release_Artifacts_Retrieve','',release.Id,release.Project__c,release.Project__r.Name);

		if(res.getStatusCode() == 200 ) {
            ResponseWrapper response = (ResponseWrapper) JSON.deserialize(res.getBody(), ResponseWrapper.class);
            if(response.Status == 'Success' && response.artifact != null) {
            	if(response.artifact.artifactPackageXML != null) {
            		artifactPackageXMLString = '{';

            		for(ArtifactList artifact : response.artifact.artifactPackageXML) {
            			if(artifact.metadataName != null && artifact.metadataName.size() > 0 && artifact.metadataName[0].trim() != '') {
            				artifactPackageXMLString += artifactPackageXMLString == '{' ? '' : ',';
            				artifactPackageXMLString += '"' + artifact.metadataType + '":' + JSON.serialize(artifact.metadataName);
            			}
            		}
            		artifactPackageXMLString += '}';
            		
            	}
            	if(response.artifact.artifactDestructiveXML != null) {
            		artifactDestructiveXMLString = '{';

            		for(ArtifactList artifact : response.artifact.artifactDestructiveXML) {
            			if(artifact.metadataName != null && artifact.metadataName.size() > 0 && artifact.metadataName[0].trim() != '') {
            				artifactDestructiveXMLString += artifactDestructiveXMLString == '{' ? '' : ',';
            				artifactDestructiveXMLString += '"' + artifact.metadataType + '":' + JSON.serialize(artifact.metadataName);
            			}
            		}
            		artifactDestructiveXMLString += '}';
            		
            	}
            }
            if((artifactPackageXMLString == null || artifactPackageXMLString == '{}' ) && (artifactDestructiveXMLString == null || artifactDestructiveXMLString == '{}')) 
                errorMessage = 'There are no artifacts attached to this Release. Please add some artifacts before downloading package.xml.';
        }
	}

	public PageReference redirectBackToRelease() {
        PageReference releaseDetail = new ApexPages.StandardController(release).view();
        releaseDetail.setRedirect(true);
        return releaseDetail;
    }

    public class ResponseWrapper {
	 	public Artifact artifact;
	 	public String status;
	}
	public class Artifact {
	 	public List<ArtifactList> artifactPackageXML;
	 	public List<ArtifactList> artifactDestructiveXML;
	}
	public class ArtifactList {
	 	public List<String> metadataName;
	 	public String metadataType;
	}
}