src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Health__c</fullName>
        <label>Project Health</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Status_Report__c.object
<CustomObject>
    <fields>
        <fullName>Project_Health__c</fullName>
        <label>Project Health</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Status Reports</relationshipLabel>
        <relationshipName>Status_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Status Report</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Status Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StatusReportTriggerHandler.cls
public without sharing class StatusReportTriggerHandler {
    
    //Update the Project's Project Health according to Status Report's Project Health
    public static void updateProjectHealth(List<Status_Report__c> oldRecords, List<Status_Report__c> newRecords){
      Map<Id, Status_Report__c> projectStatusReportMap = new Map<Id, Status_Report__c>();
      for (Integer i=0; i<newRecords.size(); i++){
      	if (oldRecords != null && oldRecords[i].Project_Health__c != newRecords[i].Project_Health__c) {
      	  projectStatusReportMap.put(newRecords[i].Project__c, newRecords[i]);
      	} else if (oldRecords == null) {
  		  projectStatusReportMap.put(newRecords[i].Project__c, newRecords[i]);
      	}
      }
      
      if (projectStatusReportMap.size() > 0) {
      	List<Project__c> updationProjects = new List<Project__c>();
      	for (Project__c project : [select Id,Project_Health__c FROM Project__c WHERE Id IN :projectStatusReportMap.keyset() ]) {
      	  project.Project_Health__c = (projectStatusReportMap.get(project.Id)).Project_Health__c;
      	  updationProjects.add(project);
      	}
      	
      	if (updationProjects.size() > 0) {
      		update updationProjects;
      	}
      }
    }
}