src/objects/Rate_Card__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Rate Cards</relationshipLabel>
        <relationshipName>Rate_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <globalPicklist>Region</globalPicklist>
        <label>Region</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <globalPicklist>Role</globalPicklist>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataFactory_RateCard.cls
public with sharing class TestDataFactory_RateCard {
	public static List<Rate_Card__c> generateRateCard(String rateCardName, Id opportunityId, String region, String role, Integer numberOfRateCard) {
		return generateRateCardInternal(rateCardName,opportunityId,region,role,numberOfRateCard);
	}

	private static List<Rate_Card__c> generateRateCardInternal(String rateCardName, Id opportunityId, String region, String role, Integer numberOfRateCard) {
		List<Rate_Card__c> rateCardList = new List<Rate_Card__c>();
        
        for(Integer i = 0; i < numberOfRateCard; i++) {
        	Rate_Card__c rateCard = new Rate_Card__c();
        	rateCard.Region__c = region ;
        	rateCard.Role__c = role ;
        	rateCard.Opportunity__c = opportunityId;
        	rateCard.Name = rateCardName ;
        	rateCardList.add(rateCard);
        }

        return rateCardList ;
	}
}