src/objects/Referral__c.object
<CustomObject>
    <fields>
        <fullName>Referred_By_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referred By Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{0000}</displayFormat>
        <label>Referral Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PersonReferralProfileController_Test.cls
@isTest
private class PersonReferralProfileController_Test {
	
	@isTest static void test_method_one() 
	{
		TestDataFactory factory = new TestDataFactory();   
        List<User>userList = factory.createUsersWith10KCustomerProfile(1);
        Insert userList;

        Referral__c referralRec = new Referral__c();
        referralRec.Referred_By_Contact__c = userList[0].ContactId;
        insert referralRec;

        System.RunAs(userList[0]){
        	PersonReferralProfileController.getReferralCount(UserInfo.getUserId());
        	Boolean isCurrentUser = PersonReferralProfileController.validateCurrentUser(UserInfo.getUserId());
        	System.assertEquals(isCurrentUser, true);
        }
	}
}