src/objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Deletion__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow Deletion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AsyncResultId__c</fullName>
        <label>Async Result Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodeScan_Describe_Error__c</fullName>
        <label>Code Scan Describe Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodeScan_Status__c</fullName>
        <label>Code Scan Status</label>
        <picklist>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Violation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warning</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scan_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scan Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Validation_Describe_Error__c</fullName>
        <label>Validation Describe Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validation_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validation Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Validation_Status__c</fullName>
        <label>Validation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Succeeded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warning</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SyncRelease.cls
@RestResource(urlMapping='/SyncRelease/')
global with sharing class SyncRelease {
    @HttpPost
    global static String SyncReleaseRecord() {
        RestRequest req = RestContext.request;
        try {
            List<Release__c> releaseList = [SELECT Validation_Status__c, Allow_Deletion__c, CodeScan_Status__c, Scan_Running__c, 
                                                Validation_Running__c, CodeScan_Describe_Error__c, Validation_Describe_Error__c,AsyncResultId__c  
                                            FROM Release__c 
                                            WHERE ID =: req.params.get('Release_Id')];
            if(releaseList.size() > 0) {
                for( Release__c release :releaseList) {
                	if(req.params.get('Task') == 'CodeReview') {
                		release.CodeScan_Status__c            = req.params.get('Status');
                		release.Scan_Running__c               = false; 
                		release.CodeScan_Describe_Error__c    = req.params.get('Describe_Error'); 
                        release.Allow_Deletion__c             = false;
                		
                	}
                	if(req.params.get('Task') == 'DeploymentValidation') {
                		release.Validation_Status__c          = req.params.get('Status');
                		release.Validation_Running__c         = false; 
                        release.Allow_Deletion__c             = false;
                		release.Validation_Describe_Error__c  = req.params.get('Describe_Error'); 
                	}
                	if(req.params.get('Task') == 'ValidationProgress') {
                		release.AsyncResultId__c = req.params.get('asyncResultId'); 
                	}
                } 
                update releaseList;  
                return 'Success';
            }
        }
        catch(Exception ex) {
          return 'Failure : '+ ex.getMessage();
        }  
        return 'Success';
   }
}