src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Deletion__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow Deletion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CodeScan_Describe_Error__c</fullName>
        <label>Code Scan Describe Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodeScan_Status__c</fullName>
        <label>Code Scan Status</label>
        <picklist>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Violation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warning</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scan_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scan Running</label>
        <type>Checkbox</type>
    </fields>
    <label>Story</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SyncStory.cls
@RestResource(urlMapping='/SyncStory/')
global with sharing class SyncStory {
    @HttpPost
    global static String SyncStoryRecord() {
        RestRequest req = RestContext.request;
        try {
            List<Story__c> storyList = [SELECT Scan_Running__c, Allow_Deletion__c, CodeScan_Status__c, CodeScan_Describe_Error__c FROM Story__c WHERE ID =: req.params.get('Story_Id')];
            if(storyList != null && storyList.size() > 0) {
                for(Story__c story : storyList) {
                    story.Scan_Running__c               = false; 
                    story.CodeScan_Status__c            = req.params.get('Status');  
                    story.CodeScan_Describe_Error__c    = req.params.get('Describe_Error'); 
                    story.Allow_Deletion__c             = false;
                } 
                update storyList ; 
                return 'Success';
            }
        }
        catch(Exception ex) {
          return 'Failure : '+ ex.getMessage();
        }  
        return 'Success';
   }
}