src/objects/X10K_Launch_Episode__c.object
<CustomObject>
    <fields>
        <fullName>Episode_Description__c</fullName>
        <label>Episode Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Episode_Id__c</fullName>
        <label>Episode Id</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Episode_Number__c</fullName>
        <label>Episode Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>10K Launch Episode</label>
    <nameField>
        <label>10K Launch Episode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>10K Launch Episodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Launch10KPodcastController.cls
public without sharing class Launch10KPodcastController{
    public List<X10K_Launch_Episode__c> launchEpisodeList{get;set;}
    
    public Launch10KPodcastController() {
        launchEpisodeList = new List<X10K_Launch_Episode__c>();
        launchEpisodeList = [Select Id,Name,Episode_Id__c,Episode_Description__c,Episode_Number__c From X10K_Launch_Episode__c ORDER BY Episode_Number__c DESC LIMIT 10000];
    }
}