src/objects/X10K_Launch_Episode__c.object
<CustomObject>
    <fields>
        <fullName>Episode_Description__c</fullName>
        <label>Episode Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Episode_Id__c</fullName>
        <label>Episode Id</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Episode_Number__c</fullName>
        <label>Episode Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>10K Launch Episode</label>
    <nameField>
        <label>10K Launch Episode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>10K Launch Episodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Launch10KPodcastController_Test.cls
/**
    @Name           : Launch10KPodcastController_Test
    @Dated          : 14 Sept, 2017
    @Author         :
    @Description    : This class is used to test Launch10KPodcastController.   
*/

@isTest
public class Launch10KPodcastController_Test{
    
    @isTest
    public static void Launch10KPodcastControllerTest_one(){
        List<X10K_Launch_Episode__c> launchEpisodeList = new List<X10K_Launch_Episode__c>();
        for(Integer i = 0; i < 2; i++) {
            launchEpisodeList.add(new X10K_Launch_Episode__c(Name = 'Ep1' ,Episode_Number__c = i + 1,Episode_Id__c = '5468631', Episode_Description__c= 'On this episode, we talk about the origin story for 10Ks VP of Client Services, Diane Shotton. Her story cover'));
        }
        insert launchEpisodeList;
        Launch10KPodcastController cont = new Launch10KPodcastController();
        //system.assert(cont.launchEpisodeList .size()>0);
    }
}